### ISSUE TITLE
Can we get `1.17.1` version release  at `ppa:strukturag/libheif`

### ISSUE THREAD

**Issue by bigcat88** [strukturag/libheif#1005]
Subj. Will be good if release will appear. )

**Comment by fancycode** [comment]
Sure, this is on my (already long) list of things to do ;-)

**Comment by fancycode** [comment]
The packages are currently building in the PPA.

**Comment by bigcat88** [comment]
@fancycode any chance to see `1.17.3` in the PPA when you have free time? )

**Comment by fancycode** [comment]
> @fancycode any chance to see `1.17.3` in the PPA when you have free time? )

Sure, just uploaded latest 1.17.4. Btw, no need to ping me for every release :wink: I'll update the PPA as soon as time permits...

**Comment by bigcat88** [comment]
> > @fancycode any chance to see `1.17.3` in the PPA when you have free time? )
> 
> Sure, just uploaded latest 1.17.4. Btw, no need to ping me for every release 😉 I'll update the PPA as soon as time permits...

Okay, I won't, sorry.
Thanks for the releases)
