### ISSUE TITLE
Incorrect result from `heif_get_version_number_minor` 

### ISSUE THREAD

**Issue by 0xC0000054** [strukturag/libheif#1023]
https://github.com/strukturag/libheif/blob/c469dcbd8b70c32a51c393ecfc5c591c681868e1/libheif/heif.cc#L96C1-L99C1

This method (along with its `_major` and `_maintenance` counterparts) assume that the version number parts use a packed BCD encoding, when it actually does not.
In practice, `LIBHEIF_NUMERIC_VERSION` packs the decimal version numbers into a 32-bit integer without BCD encoding, e.g. `#define LIBHEIF_NUMERIC_VERSION ((1<<24) | (17<<16) | (1<<8) | 0)`

This bug can be reproduced with the following program:
```c++
#include <stdio.h>
#include "libheif/heif.h"

int main()
{
    printf("%s\n", heif_get_version());
    printf("0x%08x\n", heif_get_version_number());
    printf("%d.%d.%d\n", heif_get_version_number_major(), heif_get_version_number_minor(), heif_get_version_number_maintenance());
}
```

It produces the following output:

```
1.17.1
0x01110100
1.11.1
```

I think the fix would be to remove the `bcd2dec` method call, and update the API documentation to remove the references to BCD encoding.

**Comment by farindk** [comment]
Thank you. The commit above should correct this.
I think this re-interpretation happened during the autoconf to cmake transition.
