### ISSUE TITLE
Provide method to obtain width/height of image without transforms.

### ISSUE THREAD

**Issue by GregoryJWolfe** [strukturag/libheif#106]
Functions heif_image_handle_get_width() and heif_image_handle_get_height() provide the width and height of the image without having to decode the compressed data.  However, the width and height provided reflect the transformations specified in the image file.

If one disables transformations (using heif_decoding_options::ignore_transformations = 1), and then decodes the image, functions heif_image_get_width() and heif_image_get_height() provide the untransformed width and height.  However, I would like to be able to get this information without actually decoding the image.  Is there, or can you add, functions that would do this?  Thanks.

**Comment by GregoryJWolfe** [comment]
Using the debugger I discovered that the file parsing code already has the metadata rotation information, it just isn't saved anywhere.  A relatively simple set of changes enabled me to be able to access this information from my client code.  I'm "officially" requesting that these changes be added to the software repository. 

Other than changing the size of the HeifContext class, theses modifications are quite benign and do not modify the current behavior of libheif.

- In heif_context.h, class HeifContext, add the following:
```
  public:
      void set_rotation(int rot) { m_rotation=rot; }
      int get_rotation() const { return m_rotation; }
  private:
      int m_rotation;
```
- in heif_context.cc, add lines marked as ***** NEW ****:

- --- in function function HeifContext::interpret_heif_file():
```
        auto irot = std::dynamic_pointer_cast<Box_irot>(prop.property);
        if (irot) {
          image->set_rotation(irot->get_rotation());	// ***** NEW *****
          if (irot->get_rotation()==90 ||
              irot->get_rotation()==270) {
            // swap width and height
            image->set_resolution( image->get_height(),
                                   image->get_width() );
          }
```
- --- in constructor HeifContext::Image::Image():
```
HeifContext::Image::Image(HeifContext* context, heif_item_id id)
  : m_heif_context(context),
    m_id(id),
    m_rotation(0)	// ***** NEW *****
```
- In heif.h, add the following to the "heif_image_handle" section:
```
// Get the rotation of an image.
LIBHEIF_API
int heif_image_handle_get_rotation(const struct heif_image_handle* handle);
```
- in heif.cc, add the following:
```
int heif_image_handle_get_rotation(const struct heif_image_handle* handle)
{
  if (handle && handle->image) {
    return handle->image->get_rotation();
  }
  else {
    return 0;
  }
}
```

**Comment by farindk** [comment]
Thanks for your contribution, but unfortunately it is a bit more complicated...
There can be a list of transformations, and hence, it will not generally work to just return a rotation that could be anywhere in this list.

My proposal would be to query the original image size directly from the 'ispe' box.
I can easily add that, but before I do this, could you please tell me why anyone would be interested in the dimensions of the raw original image?

**Comment by GregoryJWolfe** [comment]
Dirk:

I understand your reply, and agree that in the general case what you say is true.

Our application is the generation of photo products for the consumer.  The overwhelming majority of HEIC images we see come directly from an iPhone, and the only transformation needed is a reorientation of the image from storage in the file to the intended portrait or landscape viewing  orientation.

The IJG JPEG toolkit, which we use for reading JPEG images, delivers the image in the orientation in which it I stored.  The client can then query the EXIF tags to determine how to rotate/flip the image to the proper viewing orientation.  All of our downstream software assumes this is the case, so we want our HEIC reader to operate the same way:  turn off automatically reorienting the image, and then use the EXIF metadata to apply the needed transformations.

Any new interface you provide that allows us to do what I described above is OK with me.  We use a number of open source libraries (jpeg, tiff, exif, ffmpeg, libopenh264, GraphicsMagick, OpenCV, and now libheif/libde265), and our corporate management fully supports supplying bug fixes and other modifications back to the open source organizations with no strings attached.  The changes I suggested were provided in that spirit, but feel free to ignore them if you have a better solution.

Thanks for your speedy reply and interest in this matter.

Greg W.


Gregory J. Wolfe | Software Engineer
Kodak Moments Division, Kodak Alaris Inc., 336 Initiative Drive, Rochester, NY 14624
gregory.wolfe@kodakmoments.com | Office: 585.441.7735 | Mobile: N/A | Fax 585.722.6324
www.kodakmoments.com<http://www.kodakmoments.com/>

View The Kodak Moments Project<https://www.kodakmoments.com/kodak-moments-project>, celebrating the magical moments in everyday life.
[cid:image003.jpg@01D4BA17.7879F660]
Information contained in this e-mail transmission may be privileged, confidential and covered by the Electronic Communications Privacy Act, 18 U.S.C. Sections 2510-2521.

If you have received this e-mail transmission in error, please treat it as you would like your own email sent in error to be treated and

  *   notify us immediately by return email of the error and
  *   delete the message from your system without reading, forwarding or copying it.

Thank you in advance for your courtesy!

**Comment by farindk** [comment]
Hi Gregory,

have a look into the latest commit in the master branch. I've added the functions
heif_image_handle_get_ispe_width() and heif_image_handle_get_ispe_height(), which return the original, untransformed image size.

Does that solve your problem?

Dirk

**Comment by GregoryJWolfe** [comment]
Dirk:

Thanks for the added functions.  For testing purposes I pulled just the affected files, and they provide the functionality we need.  When I get a chance I will be upgrading our libheif software to use the full master branch.

Greg W.

Gregory J. Wolfe | Software Engineer
Kodak Moments Division, Kodak Alaris Inc., 336 Initiative Drive, Rochester, NY 14624
gregory.wolfe@kodakmoments.com | Office: 585.441.7735 | Mobile: N/A | Fax 585.722.6324
www.kodakmoments.com<http://www.kodakmoments.com/>

View The Kodak Moments Project<https://www.kodakmoments.com/kodak-moments-project>, celebrating the magical moments in everyday life.
[cid:image003.jpg@01D4BD38.9DF367E0]
Information contained in this e-mail transmission may be privileged, confidential and covered by the Electronic Communications Privacy Act, 18 U.S.C. Sections 2510-2521.

If you have received this e-mail transmission in error, please treat it as you would like your own email sent in error to be treated and

  *   notify us immediately by return email of the error and
  *   delete the message from your system without reading, forwarding or copying it.

Thank you in advance for your courtesy!
