### ISSUE TITLE
libheif don't import files PNG {libpng 1.6.37}

### ISSUE THREAD

**Issue by Jamaika1** [strukturag/libheif#108]
Why does the HDR function not allow you to import PNG files?

**Comment by farindk** [comment]
I don't understand the question. Now, with the `hdr` branched merged, I can convert 16bit PNGs to HEIF. That should work fine. If you have a PNG that does not work, please attach it here so that I can check it.

**Comment by Jamaika1** [comment]
I don't mean 16 bit PNG files. Before adding the HDR function can be added 24bit PNG files. After adding the function codec will not work. Adds my latest compiled libheif plus test PNG.
http://forum.doom9.org/showthread.php?p=1864517#post1864517
https://www.sendspace.com/file/ul7toj

**Comment by farindk** [comment]
I tried your image and your command line (except "tune=vmaf", which my x265 does not understand) and got no problem at all. Could it be a problem with your x265 version?

**Comment by farindk** [comment]
Thank you. Can you please confirm that the following patch this fixes it?
18a37f6e41fff253ab29573f10d0fb4075903c70

**Comment by Jamaika1** [comment]
Thank you for your help. I understand that it can not be better.
I have reservations about the quality of 48bit files.
_heifenc_08bit_hdr.exe -v -b 8 -p preset=placebo --no-alpha -o output1.heic image_21447_64.png_
https://www.sendspace.com/file/wc6l04
