### ISSUE TITLE
32-bit compile fails

### ISSUE THREAD

**Issue by freakout42** [strukturag/libheif#1086]
libheif-1.17.6/libheif/plugins/encoder_jpeg.cc:366:37: error: invalid conversion from 'long unsigned 
        int*' to 'size_t*' {aka 'unsigned int*'} [-Werror=permissive]
    366 |   jpeg_mem_dest(&cinfo, &outbuffer, &outlength);
        |                                     ^~~~~~~~~~
        |                                     |
        |                                     long unsigned int*

**Comment by bradh** [comment]
Same as #1008. Can you follow up with the question on that issue?
