### ISSUE TITLE
Newbie help compiling with local libde265

### ISSUE THREAD

**Issue by bitwombat** [strukturag/libheif#109]
libde265 is on my Ubuntu 16.04 system, but ./configure wasn't detecting it (and, for some reason pkg-config isn't either), so I thought I'd compile it from scratch. I want to compile it, and libheif, locally.

    $ git clone libde265
    $ ./configure --prefix=/tmp/root
    $ make -j8 && make install

Happy outputs are now in /tmp/root/lib and /temp/root/include/libde265

Now libheif needs to find it, so my, probably wrong, guesses:

    $ export LD_LIBRARY_PATH=/tmp/root/lib
    $ export LDFLAGS="-L/tmp/root/lib"
    $ export libde265_CFLAGS="-I/tmp/root/include/"
    $ export libde265_LIBS="-L/tmp/root/lib"

I'm sure one of those is wrong, but I don't know gcc well. If I set CFLAGS to /tmp/root/include/libde265 I don't get as far as below.

So now:

    $ ./configure --prefix=/tmp/root
    checking for libde265... yes
    configure: libde265 decoder: yes

So that looks good. But then:

    $ make -j8

    '/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..
    -fvisibility=hidden -I/tmp/root/include/libde265  -DLIBHEIF_EXPORTS -I..
    -DHAVE_VISIBILITY -g -O2 -std=gnu++11 -Wall -Werror -Wsign-compare -Wconversion
    -Wno-sign-conversion -Wno-error=conversion -Wno-error=unused-parameter -MT
    libheif_la-heif_decoder_libde265.lo -MD -MP -MF
    .deps/libheif_la-heif_decoder_libde265.Tpo -c -o
    libheif_la-heif_decoder_libde265.lo 'test -f 'heif_decoder_libde265.cc' || echo
    './''heif_decoder_libde265.cc libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I..
    -fvisibility=hidden -I/tmp/root/include/libde265 -DLIBHEIF_EXPORTS -I..
    -DHAVE_VISIBILITY -g -O2 -std=gnu++11 -Wall -Werror -Wsign-compare -Wconversion
    -Wno-sign-conversion -Wno-error=conversion -Wno-error=unused-parameter -MT
    libheif_la-heif_decoder_libde265.lo -MD -MP -MF
    .deps/libheif_la-heif_decoder_libde265.Tpo -c heif_decoder_libde265.cc  -fPIC
    -DPIC -o .libs/libheif_la-heif_decoder_libde265.o
    heif_decoder_libde265.cc:31:28: fatal error: libde265/de265.h: No such file or
    directory '

What configure flag or environment variable do I need so it finds the libde265 include files? I don't see my libde265_CFLAGS value getting used...

**Comment by fancycode** [comment]
> libde265 is on my Ubuntu 16.04 system, but ./configure wasn't detecting it [...]

Did you also install the `libde265-dev` package? This contains the header files and is required so `pkg-config` can detect it.

> If I set CFLAGS to /tmp/root/include/libde265 I don't get as far as below.

Instead of `/tmp/root/include/libde265` you should use just `/tmp/root/include` (i.e. the root of your include path).

In all cases, the contents of `config.log` show what is being tested by `configure` and where it failed.

**Comment by bitwombat** [comment]
OK, thanks, that gets me further.

Now it's not linking the examples:

    $ ../libtool  --tag=CXX   --mode=link g++ -I.. -I.. -I/usr/include/libpng12 -g -O2 -std=gnu++11 -Wall -Werror -Wsign-compare -Wconversion -Wno-sign-conversion -Wno-error=conversion -Wno-error=unused-parameter -lpng12 -L/tmp/root/lib -o heif-thumbnailer heif_thumbnailer-encoder.o heif_thumbnailer-heif_thumbnailer.o heif_thumbnailer-encoder_png.o ../libheif/libheif.la -lpthread -I/tmp/root/include/libde265
    libtool: link: g++ -I.. -I.. -I/usr/include/libpng12 -g -O2 -std=gnu++11 -Wall -Werror -Wsign-compare -Wconversion -Wno-sign-conversion -Wno-error=conversion -Wno-error=unused-parameter -o .libs/heif-thumbnailer heif_thumbnailer-encoder.o heif_thumbnailer-heif_thumbnailer.o heif_thumbnailer-encoder_png.o -I/tmp/root/include/libde265  -lpng12 -L/tmp/root/lib ../libheif/.libs/libheif.so -lpthread -Wl,-rpath -Wl,/tmp/root/lib
    ../libheif/.libs/libheif.so: undefined reference to `de265_flush_data'
    ../libheif/.libs/libheif.so: undefined reference to `de265_get_chroma_format'
    ../libheif/.libs/libheif.so: undefined reference to `de265_release_next_picture'
    ../libheif/.libs/libheif.so: undefined reference to `de265_get_image_plane'
    ../libheif/.libs/libheif.so: undefined reference to `de265_init'
    ../libheif/.libs/libheif.so: undefined reference to `de265_new_decoder'
    ../libheif/.libs/libheif.so: undefined reference to `de265_get_image_height'
    ../libheif/.libs/libheif.so: undefined reference to `de265_free'
    ../libheif/.libs/libheif.so: undefined reference to `de265_get_version'
    ../libheif/.libs/libheif.so: undefined reference to `de265_decode'
    ../libheif/.libs/libheif.so: undefined reference to `de265_push_NAL'
    ../libheif/.libs/libheif.so: undefined reference to `de265_start_worker_threads'
    ../libheif/.libs/libheif.so: undefined reference to `de265_free_decoder'
    ../libheif/.libs/libheif.so: undefined reference to `de265_get_image_width'
    ../libheif/.libs/libheif.so: undefined reference to `de265_get_bits_per_pixel'
    ../libheif/.libs/libheif.so: undefined reference to `de265_get_next_picture'
    collect2: error: ld returned 1 exit status

Which is weird since -L/tmp/root/lib is in there, and:

    $ nm -g /tmp/root/lib/libde265.so | grep de265_flush_data
    00000000000351d0 T de265_flush_data

**Comment by bitwombat** [comment]
Solution is to re-run that linker command line with /root/tmp/lib/libde265.la included. Don't understand why the -I path isn't working to get it picked up.

But then I get a runtime error, and same with the official libde265-dev package's header files... so I'll try a release instead of master. Thanks for the help!
