### ISSUE TITLE
Could not decode image Unsupported feature: Unsupported codec

### ISSUE THREAD

**Issue by freakout42** [strukturag/libheif#1094]
$ /opt/heif/bin/heif-info --version
    1.17.6
    libheif: 1.17.6
    plugin path: /opt/heif/lib/libheif

    $ /opt/heif/bin/heif-info /save/axel/alr3/y23/m2306/d2306_wldkrc/IMG_1539.HEIC
    MIME type: image/heic
    main brand: heic
    compatible brands: mif1, MiPr, miaf, MiHB, heic

    image: 4032x3024 (id=49), primary
      colorspace: YCbCr, 4:2:0
      bit depth: 8
      thumbnail: 320x240
      color profile: prof
      alpha channel: no
      depth channel: no
    metadata:
      Exif: 2370 bytes
    transformations:
      angle (ccw): 0
    region annotations:
      none
    properties:
    Could not decode image Unsupported feature: Unsupported codec

**Comment by bradh** [comment]
It worked fine for me (shows a couple of kids). 

What does `/opt/heif/bin/heif-convert --list-decoders` show?

On my build, it contains
```
HEIC decoders:
- libde265 = libde265 HEVC decoder, version 1.0.12
```

(and some other stuff, but that is the key item).

**Comment by freakout42** [comment]
/opt/heif/bin/heif-convert --list-decoders
    HEIC decoders:
    AVIF decoders:
    JPEG decoders:
    JPEG 2000 decoders:
    uncompressed: yes

i have removed the image for privacy reasons

**Comment by bradh** [comment]
Its clearly not going to be able to decode the image without a decoder, and you don't have one for HEIC. The image isn't going to matter.

Without deeper understanding of what you did to build, its going to be hard to guess the issue. Candidate options:

- you don't have de265 for some reason (e.g. disabled in configuration)
- you have it as a plugin, but its not installed in the configured directory (`/opt/heif/lib/libheif` from your initial report)
- you have it, but there is another dependency problem (e.g. a system lockdown of some kind, maybe SELinux not configured correctly)
- some other mismatch in versioning

Can you try to debug the configuration? Maybe strace it?

**Comment by farindk** [comment]
I changed the error text to `Error while loading plugin: No decoding plugin installed for this compression format" as this is a FAQ.

**Comment by freakout42** [comment]
did install x265 and libde265 and it works now thanks
