### ISSUE TITLE
heif-convert reports "Input file is not an HEIF file" on iOS-generated file

### ISSUE THREAD

**Issue by bitwombat** [strukturag/libheif#111]
This [file](http://bitwombat.com.au/IMG_3630.HEIC) causes heif-convert to report:

    Input file is not an HEIF file

The file was generated by the camera on iOS 12.

**Comment by fancycode** [comment]
Error reported by `heif-info`:
```
Could not read HEIF file: Invalid input: No 'ftyp' box
```
@farindk is this supposed to work or is the file broken/unsupported?

**Comment by farindk** [comment]
This is a JPEG file with a wrong filename suffix.

**Comment by bitwombat** [comment]
Well, good times... Apple's doing this. Be prepared for a FAQ.

    $ file *
    IMG_3560.HEIC: ISO Media
    IMG_3564.HEIC: JPEG image data, JFIF standard 1.01, aspect ratio, density 72x72, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=11, manufacturer=Apple, model=iPhone 7, xresolution=162, yresolution=170, resolutionunit=2, software=12.1.2, datetime=2019:01:16 12:44:19], baseline, precision 8, 1554x1562, frames 3
    IMG_3568.HEIC: ISO Media
    IMG_3570.HEIC: ISO Media
    IMG_3572.HEIC: JPEG image data, JFIF standard 1.01, aspect ratio, density 72x72, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=11, manufacturer=Apple, model=iPhone 7, xresolution=162, yresolution=170, resolutionunit=2, software=12.1.2, datetime=2019:01:17 10:29:00], baseline, precision 8, 1629x1201, frames 3
