### ISSUE TITLE
ctuSize in heif_compression_HEVC encoder

### ISSUE THREAD

**Issue by keni7385** [strukturag/libheif#1138]
Hello,

How can I set the `ctuSize` when using `heif_compression_HEVC` as `heif::Encoder`?

Is the parameter already exposed to libheif users? Or does the codebase require changes?

Thank you!

**Comment by silverbacknet** [comment]
For x265, you're looking for `set_parameter_integer("ctu",x);`. (`set_parameter_string` for string parameters)

**Comment by keni7385** [comment]
Thank you to both of you.

String parameter solved my issue:
```c++
encoder.set_string_parameter("x265:ctu", "16");
```

I was trying `encoder.set_integer_parameter("x265:ctu", 16)`, which didn't work. Indeed, only `x265_set_parameter_string` has the logic to handle parameters prefixed by "x265":

https://github.com/strukturag/libheif/blob/33e00a4ec54e6fffca3febe3054017b1b81a0c49/libheif/plugins/encoder_x265.cc#L513-L515
