### ISSUE TITLE
whether heif supports images with alpha, such as webp?

### ISSUE THREAD

**Issue by IphoneCoder** [strukturag/libheif#1142]

**Comment by farindk** [comment]
Yes, it does.

**Comment by IphoneCoder** [comment]
> Yes, it does.

Thanks. I used the demo in the latest libheif version to convert the apng GIF to heif, but only the first frame，What is the right way？

**Comment by farindk** [comment]
libheif does not support encoding image sequences yet. Only still images.

**Comment by bigcat88** [comment]
_But you still can encode multiple images into one "heic" with libheif_

**Comment by IphoneCoder** [comment]
> _But you still can encode multiple images into one "heic" with libheif_

I have looked at the ISO/IEC STANDARD 23008-12, but I am not sure what format should be if there is an alpha map per frame. Now we want to replace all webps with heif, any samples ?

**Comment by bradh** [comment]
You should be able to make such samples with `heif-enc` utility. It should handle alpha correctly by default.

**Comment by shixuemei** [comment]
Has this issue been resolved? I’m facing the same problem😭

**Comment by bradh** [comment]
> Has this issue been resolved? I’m facing the same problem😭

It should work.

If it doesn't, please open an issue with a specific reproduceable sample showing exactly what steps you took, what you expected to happen, and what happened instead.

**Comment by IphoneCoder** [comment]
> > Has this issue been resolved? I’m facing the same problem😭
> 
> It should work.
> 
> If it doesn't, please open an issue with a specific reproduceable sample showing exactly what steps you took, what you expected to happen, and what happened instead.

Such as this apng sample, I want to convert it to heif, but I don't know how to store the yuv and alpha data of each frame in heif.
![animated](https://github.com/strukturag/libheif/assets/8368850/63406d69-032b-4f0a-9266-e05f442b8101)
