### ISSUE TITLE
Build without PPA ? 

### ISSUE THREAD

**Issue by rgarrigue** [strukturag/libheif#115]
Hi

In your build script you're relying exclusively on a PPA, here https://github.com/strukturag/libheif/blob/master/scripts/install-ci-linux.sh#L53

Is it possible to have the same as the previous lib, a non-PPA alternative, for debian packaging ? I'm trying to get libheif for imagemagick on our debian stretch servers.

Best regards,

**Comment by fancycode** [comment]
The CI servers are running Ubuntu Trusty which doesn't provide `libx265-dev` or `libde265-dev`, so we are using the PPA to provide these packages for Trusty.

If you are building for Debian Stretch or a newer version of Ubuntu, you don't need the PPA but can use the packages provided by your distribution:
https://packages.debian.org/stretch/libx265-dev
https://packages.debian.org/stretch/libde265-dev

**Comment by fancycode** [comment]
Btw, we are also maintaining packages for Debian:
https://salsa.debian.org/multimedia-team/libheif
https://packages.debian.org/search?keywords=libheif

You should be able to simply backport this to Stretch.

**Comment by rgarrigue** [comment]
I sent an email to the Debian ML for ImageMagick to ask for a backport from buster to stretch  this morning.

And indeed, I'm currently backporting this. But since I'm not an expert in Debian packaging, which is a rater obscure technology at best, I'm a bit struggling, hence the questions.
