### ISSUE TITLE
How to Compile libheif with  openjpeg ?

### ISSUE THREAD

**Issue by Mech0n** [strukturag/libheif#1152]
How to compile libheif with  openjpeg ?

I use `PKG_CONFIG_PATH` but failed, I do not want install this library:

```
-- The imported target "opj_decompress" references the file
   "/usr/bin/opj_decompress"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/x86_64-linux-gnu/openjpeg-2.1/OpenJPEGTargets.cmake"
but not all the files it references.
```

**Comment by bradh** [comment]
Its coming from the CMake configuration that Ubuntu ships for OpenJPEG.

Are you saying you do want to use OpenJPEG, but you do not want to install the command line tools?

**Comment by kmilos** [comment]
Install `libopenjp2-tools` as well?

Btw, this version (and your system?) seems very old, there might be quite a bit of other things not working as expected.

**Comment by kmilos** [comment]
> Its coming from the CMake configuration that Ubuntu ships for OpenJPEG.

Btw, it's not only Ubuntu, it's in my most recent MSYS2 package as well. A bit unusual to have those binaries as imported targets...

**Comment by Mech0n** [comment]
thank you.  I find I miss `PLUGIN_DIRECTORY`
