### ISSUE TITLE
Essential item properties should be checked

### ISSUE THREAD

**Issue by bradh** [strukturag/libheif#1153]
There is a flag on item property references if it is "essential" that it be understood. Right now, it looks like we're ignoring that, and potentially trying to handle images that require functionality we don't provide.

I hit this experimenting with the ISO 23001-17 Amd 2 CDAM generically compressed image support, where there are some extra properties to say "zlib inflate the data before decoding".

**Comment by farindk** [comment]
It is a bit tricky to see whether a box will be used during the decoding process.
My idea would be that we maintain a flag for each box that tells whether it has been considered during the decoding.
Then, at the end of decoding, we can check whether there is any box without that flag set and output an error in that case.

However, it will be impossible to prevent e.g. the "uncompressed codec" to try reading zlib compressed data when it doesn't know the compressed metadata. Thus all of those codecs have to be robust against reading past the end of the data, for example.

**Comment by farindk** [comment]
@bradh Right. Now that we have `Box_other`, this could indeed be a simple check.

It will not indicate an error when we can parse the box but don't use it's content correctly in the codec, but detecting software errors is out of scope of the 'essential' flag.

**Comment by farindk** [comment]
I've added the check.

One undesired side-effect is that when we read such a file with an unsupported essential property, also `heif-info` does not work because it will output the same error.

**Comment by bradh** [comment]
> I've added the check.
Thanks.

> One undesired side-effect is that when we read such a file with an unsupported essential property, also `heif-info` does not work because it will output the same error.

Maybe an option or flag for strict vs tolerant parsing could be useful. Not usually a good thing but perhaps useful in this case.

**Comment by farindk** [comment]
The culprit is the `interpret_heif_file()` function which organizes the whole content when reading the file. I think this should be much more on-demand so that it will not bail out with an error when a completely unrelated detail fails, and it would also help reading speed when it's only processing the items when they are actually accessed.

**Comment by bradh** [comment]
> The culprit is the `interpret_heif_file()` function which organizes the whole content when reading the file. I think this should be much more on-demand so that it will not bail out with an error when a completely unrelated detail fails, and it would also improve the reading speed when it's only processing the items when they are actually accessed.

So right now we'd fail on a whole file if any image item has an unsupported property?

**Comment by farindk** [comment]
Yes. But that is for all kinds of parse errors, not only the `essential` flags.

In `libde265`, I was assigning decoding errors to the respective images instead of having a global error response. That might be an option.
