### ISSUE TITLE
How to change the compatible brands of heic image

### ISSUE THREAD

**Issue by zx310** [strukturag/libheif#1160]
I am learning libheif, I want to change the compatible brands,, pls help me.

**Comment by bradh** [comment]
I don't believe there is any public API to do that. You'd need to be making internal changes to libheif.

I note your comment on #1159 that:

> I just want to convert HEVC to HEIC images, and I already have the HEVC data, so I don't want to use any plugin modules from libheif, just to serve as a container, like MP4.

That isn't going to be possible without changing libheif either. Remember discussion at https://github.com/strukturag/libheif/issues/534

**Comment by zx310** [comment]
> I don't believe there is any public API to do that. You'd need to be making internal changes to libheif.
> 
> I note your comment on #1159 that:
> 
> > I just want to convert HEVC to HEIC images, and I already have the HEVC data, so I don't want to use any plugin modules from libheif, just to serve as a container, like MP4.
> 
> That isn't going to be possible without changing libheif either. Remember discussion at #534

Thank you very much
