### ISSUE TITLE
possible bug: inconsistent reporting of width/height of rotated images

### ISSUE THREAD

**Issue by jcupitt** [strukturag/libheif#117]
Hello, thank you for this nice library! I've used it to [add heic support to libvips](https://github.com/libvips/libvips/issues/671).

I've been having problems trying to disable the autorotate feature. libheif does not seem to report the width and height of transformed images consistently.

For example, with this test program:

```C
/* compile with
 *
 *   gcc -g -Wall heif.c `pkg-config libheif --cflags --libs`
 *
 */

#include <stdio.h>
#include <libheif/heif.h>

int
main( int argc, char **argv )
{       
        struct heif_context *context;
        struct heif_image_handle *handle;
        struct heif_error error;

        context = heif_context_alloc();

        error = heif_context_read_from_file( context, argv[1], NULL );
        if( error.code ) {
                fprintf( stderr, "%s", error.message );
                return( -1 );
        }

        error = heif_context_get_primary_image_handle( context, &handle );
        if( error.code ) {
                fprintf( stderr, "%s", error.message );
                return( -1 );
        }

        printf( "%s: width = %d\n",
                argv[1], heif_image_handle_get_width( handle ) );
        printf( "%s: height = %d\n",
                argv[1], heif_image_handle_get_height( handle ) );

        heif_image_handle_release( handle );
        heif_context_free( context );

        return( 0 );
}  
```

And these two sample images:

https://trac.ffmpeg.org/attachment/ticket/6521/IMG_4479.HEIC

https://github.com/libvips/libvips/blob/master/test/test-suite/images/Example1.heic

I see:

```
$ ./a.out ~/pics/IMG_4479.HEIC 
/home/john/pics/IMG_4479.HEIC: width = 3024
/home/john/pics/IMG_4479.HEIC: height = 4032
$ ./a.out ~/pics/Example1.heic 
/home/john/pics/Example1.heic: width = 4032
/home/john/pics/Example1.heic: height = 3024
```

Both images are EXIF orientation 6 and both (obviously) are 4032 across and 3024 down when untransformed, but only the first seems to report the rotated width/height in libheif.

**Comment by farindk** [comment]
Hello John,

I looked at the two images and this is what I found.
Both raw images are stored as 4032x3024. However, the first (IMG_4479) has an additional 'irot' box in the HEIF file that tells libheif to rotate the image by 90 degrees. Hence, in that sense, libheif is correct for both images.

Now, the really interesting question is how the HEIF rotation should interact with the rotation stored in the Exif data. The HEIF standard says this:

"Metadata specified in Annex A or according to the item type and MIME type values is descriptive and
does not normatively affect the presentation. In particular, an image item can be rotated by 90°, 180°,
or 270° using the 'irot' transformative item property. Rotation metadata, e.g. according to Annex A,
is ignored in the displaying process." (Annex A refers to Exif, XMP, and MPEG-7 metadata.)

That means that the second image "Example1.heic" is stored incorrectly, as the 'irot' rotation box is missing and rotation is only specified in the Exif data. I am not sure how image viewers generally handle this situation, i.e. whether they will ignore the transformation in the Exif or whether they will apply it.

Do you know how the "Example1.heic" file was generated?

**Comment by jcupitt** [comment]
Hi Dirk, thanks for the quick reply!

I believe `Example1.heic` is just a shot from an iphone. The exif says July 2017, so a few versions of ios ago. Someone sent it to me when I asked for an example with XMP metadata.

This is very confusing. I'll swap my `Example1.heic` for `IMG_4479.HEIC`, and people with old iphone shots will have to suffer inconsistent behaviour. 

The new `heif_image_handle_get_ispe_width()` should let me add something to disable transforms too. Nice!

**Comment by farindk** [comment]
Both seem to be coming from iPhones, because they both use 512x512 tiles internally. However, the HEVC encoding parameters are different.

> The new heif_image_handle_get_ispe_width() should let me add something to disable transforms too.

Either that, or one might look at the Exif data to see what the desired output should be and apply the rotation if necessary. I.e. compare the HEIF image's width/height with the Exif data, see whether it matches, and rotate if necessary.

Of course that would be exactly the opposite as written in the standard, i.e. using the Exif data for the final decision. But it might be the only way to work around those wrong files.

Please let me know if you find a solution that seems to work reliably in all cases.

**Comment by jcupitt** [comment]
I had tried reading orientation, but I hadn't considered checking the exif dimensions as well. That's a good idea. Yes, I'll let you know.
