### ISSUE TITLE
heic image decode color incorrect 

### ISSUE THREAD

**Issue by lam2003** [strukturag/libheif#1189]
Hi, I use heif_convert command(from libheif example) to convert below heif image to jpg/png. The output image color incorrect which seems too green

[1040g008313u8g0qp1m4g5nkalku094d2qla98k0 2.heic.zip](https://github.com/user-attachments/files/15837489/1040g008313u8g0qp1m4g5nkalku094d2qla98k0.2.heic.zip)

**Comment by lam2003** [comment]
![1](https://github.com/strukturag/libheif/assets/22312935/eaad3a2b-7055-4373-9f38-0af3b77e3e1e)

**Comment by farindk** [comment]
I had a look at the file structure. It seems that there is no color-space information in that file (no nclx, no ICC). Also the file structure is different than what I have seen before. The EXIF data says that it was captured by a Xiaomi camera. Is that correct, or was it post-processed in some other software?

**Comment by lam2003** [comment]
Is there something wrong on the color conversion?

**Comment by lam2003** [comment]
I have confirm the rgb matrix take from decoder already has color incorrection

**Comment by farindk** [comment]
It's strange that your tool says RGB colorspace, but Chroma 4:2:0.
I'll need to have a closer look into the h265 stream.

**Comment by lam2003** [comment]
> > It's strange that your tool says RGB colorspace, but Chroma 4:2:0.
> 
> ... and matrix coeffs identity? exiftool indeed does not see any nclx or ICC either, but only chroma 4:2:0 as well - no matrix coeffs, no transfer curve...
> 
> The white comes out as (128, 255, 128) in RGB, which looks to me like some (U, Y, V) values?
> 
> FWIW, Windows 11 photo app shows it correctly as well.

The matrix coeffs value is 0;
<img width="688" alt="image" src="https://github.com/strukturag/libheif/assets/22312935/e9af4980-9ac1-43f7-a59c-a0560072d67e">

**Comment by silverbacknet** [comment]
My assumption is that these other libraries have sanity checks to change RGB 4:2:0 to Unspecified (and just treat that as 709), because shoddy developers assuming 0 is default or just not caring is definitely A Thing. This isn't an *illegal* configuration, if someone decided to subsample red & blue, it's just a weird and slightly crazy one.

I haven't checked whether flipping that bit to 1 will fix it, I can try when I get home tonight, but I suspect it will.

**Comment by lam2003** [comment]
> My assumption is that these other libraries have sanity checks to change RGB 4:2:0 to Unspecified (and just treat that as 709), because shoddy developers assuming 0 is default or just not caring is definitely A Thing. This isn't an _illegal_ configuration, if someone decided to subsample red & blue, it's just a weird and slightly crazy one.
> 
> I haven't checked whether flipping that bit to 1 will fix it, I can try when I get home tonight, but I suspect it will.

<img width="1413" alt="image" src="https://github.com/strukturag/libheif/assets/22312935/d83a1ca6-f163-4874-bab8-c6af5eb3e541">

I set matrix_coefficients to heif_matrix_coefficients_unspecified and output image can show correctly.  Thank you!

[2.png.zip](https://github.com/user-attachments/files/15845256/2.png.zip)
