### ISSUE TITLE
"cmin" box header flags meaning

### ISSUE THREAD

**Issue by TimYao18** [strukturag/libheif#1191]
cmin box is a fullbox that owns its flags definitions, but I don't find the spec from ISO 23008-12 or 14496-12.

I got a heic image that its version-flags bytes are: 00 00 1D 00 
but when I set_intrinsic_matrix(), the flags are always 00 00 13 00
I don't know how to manage it. Is there a hint for me?

**Comment by farindk** [comment]
The standard defining `cmin` is not published yet. I implemented the draft from w22940, mpeg143.
The flags you are referring to are the precision that is used for storing the values. See here:

https://github.com/strukturag/libheif/blob/7cdda11ac100a0d62f1323436dd0c7369f77c135/libheif/box.cc#L3421

**Comment by TimYao18** [comment]
I found the w22940 draft from [MPEG](https://www.mpeg.org/wp-content/uploads/mpeg_meetings/143_Geneva/w22940.zip) but it seems not the same as Apple spatial photo generated by newly public [sample code](https://developer.apple.com/documentation/imageio/writing-spatial-photos) on WWDC24.

My spatial photo is generated from a 1280x720 image by Apple Vision Pro visionOS 2.0 spatial button. The Intrinsics is 
[2920.76, 0, 640,
  0, 2920.76, 360,
  0, 0, 1]
In HEX editor, the cmin value after fourCC is 00 00 1C 00, 24 92 6E 7E, 08 00 00 00, 08 00 00 00

When I converted another images from 3840x2160 into spatial photo by sample code, the intrinsics is 
[2288.167, 0, 1920,
0, 2288.167, 1080,
0, 0, 1]
In HEX editor, the cmin value after fourCC is 00 00 1D 00, 13 11 6C 37, 10 00 00 00, 10 00 00 00

The principal point x and y value is not mapping into the document on w22940:

aligned(8) class CameraIntrinsicMatrixProperty
extends ItemFullProperty('cmin', version = 0, flags) {
	signed int(32) focal_length_x;
	signed int(32) principal_point_x;
	signed int(32) principal_point_y;
	if (flags & 1) {
		signed int(32) focal_length_y;
		signed int(32) skew_factor;
	}
}

Maybe there is another spec to check how the intrinsic defined.

**Comment by farindk** [comment]
@TimYao18 I didn't understand your last comment. Do you have an image that you can share where the values reported by `heif-info` (without option `-d`) do not match the values that the Apple API gives you?

**Comment by TimYao18** [comment]
Sorry, what I mean is:
If I take the Apple spatial photo's cmin box as sample, then the spatial photo's cmin box does not match the w22940 spec.
Maybe Apple has its own definition on 'cmin' box?

For example, Apple spatial photo cmin box value after fourCC('cmin') is:
`00 00 1C 00, 24 92 6E 7E, 08 00 00 00, 08 00 00 00`
By spec,
Focal Length x should be the value: `24 92 6E 7E`
Principal Point x should be the value: `08 00 00 00`
Principal Point y should be the value: `08 00 00 00`
But the ppx and ppy should set at the center of the image (1280, 720) that is (640, 360), does not match the value: (`08 00 00 00`, `08 00 00 00`)

Attached a spatial photo, it is 3840x2160 and its Intrinsics: [2,288.167, 0, 1,920, 0, 2,288.167, 1,080, 0, 0, 1], its values paste as below, that `10 00 00 00 10 00 00 00` should be ppx and ppy.
<img width="595" alt="Screenshot 2024-06-20 at 8 30 43 PM" src="https://github.com/strukturag/libheif/assets/15173100/69ebb5d9-aa19-40a8-919c-eda19839c868">

[spatial photo](https://drive.google.com/file/d/1GXfyu89F0ygzwHd7NtTrIdTppuiF29lh/view?usp=drive_link)

**Comment by farindk** [comment]
The principal point is normalized to the image size. The 0x80000000 is a fixed point number, shifted by 0x1c, which should decode to 0.5. Then the width 1280 * 0.5 = 640 gives the principal point.
