### ISSUE TITLE
Build libheif with Visual Studio 2013.

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libheif#12]
We create binaries for the @ImageMagick project with Visual Studio 2013 but that fails to build at the moment. This is failing because `constexpr` is not supported. The main issue is `fourcc` and the switch in `Box::read` because that actually requires a constant value. This is what they use in webp:

```#define MKFOURCC(a, b, c, d) ((a) | (b) << 8 | (c) << 16 | (uint32_t)(d) << 24)```

I don't mind sending and testing a PR if you tell me what kind of solution you want for this.

**Comment by farindk** [comment]
Ok, I replaced with a simple #define.

**Comment by dlemstra** [comment]
I had to do a bit more to make it work: https://github.com/ImageMagick/libheif/commit/c4f4ecc7da8c16adbf9f9b6712fb127f0d565159

**Comment by sati32** [comment]
I downloaded your project, because I want to build libheif with Visual Studio, too.
But there is no Visual Studio project in the package.

**Comment by silverbacknet** [comment]
@sati32 Like most modern open source, this uses CMake to generate the compiler-specific projects. Look up the CMake-GUI to do that on Windows.
