### ISSUE TITLE
AVIF experimental branch `avif` seems not working, the image color turned green and cropped

### ISSUE THREAD

**Issue by dreampiggy** [strukturag/libheif#120]
## Env:
OS: macOS 10.14
Version: Using branch `avif` (cid: 0edf8a3), with the both aom v1.0.0 and aom v1.0.0-errata1

## Usage
Using a simple image viewer app, which based on libheif and can sucessfuly decoding all HEIC images.
Trying to switch to `avif` branch, set the `USE_AOM` and build libheif to support AVIF.

## Test Image:
Using both the image sample from http://download.opencontent.netflix.com/?prefix=AV1/Chimera/AVIF/.

## Result

The color showing green overlay for AVIF images. See the screenshot:

![image](https://user-images.githubusercontent.com/6919743/55649747-6182d600-5816-11e9-9034-7ccf705e6ed3.png)

The image viewer code, using the exact same for HEIF and AVIF. I think from the user side, there don't need any code update (using the `heif_decode_image` API).

The left one is one HEIC image from nokia sample, looks great: http://nokiatech.github.io/heif/content/images/ski_jump_1440x960.heic

The right one is one AVIF image from netflix sample, looks green and cropped: http://download.opencontent.netflix.com.s3.amazonaws.com/AV1/Chimera/AVIF/Chimera-AV1-8bit-1280x720-3363kbps-100.avif

The correct render result should be like this (using a online view page, which based on Chrome's built-in AV1 codec polyfill, here: https://kagami.github.io/avif.js/)

![9c432007-ea11-4985-bd26-cbb6a45af6d0](https://user-images.githubusercontent.com/6919743/55649991-0f8e8000-5817-11e9-8bc8-9c3d307e63de.jpg)

**Comment by dreampiggy** [comment]
Solved. This is because of the out-of-date aom built myself.

It seems after upgradting to the latest aom git commit and rebuild, solve this issue.

**Comment by mholt** [comment]
5 years later, I know, but I just encountered this issue today. My decoded images look like this:

![image](https://github.com/user-attachments/assets/9f0c302e-0edb-4c04-b4e6-668f6090b78b)

Cropped and a bit distorted... and green. Do you think it's the same problem? (I'm not sure what aom is or how to update it, so that's why I'm asking.)

**Comment by bradh** [comment]
It would be easier to check if you provided a sample image and the exact decode process on a new topic ticket.

**Comment by farindk** [comment]
> Do you think it's the same problem?

@mholt It looks like the decoded image is >8bit (2 bytes per pixel) while the part that saves the images treats this like a 1 byte/pixel image.

Check with the `heif-dec` tool whether it decodes correctly (use PNG output for >8 bit: `heif-dec testimage.avif output.png`). If you still get the problem, please provide the source image and the output of `heif-dec --list-decoders`.

**Comment by mholt** [comment]
Yes, sorry; for now, I actually don't think that this is a bug or problem with libheif, so I hesitated to open a new issue...

`heif-dec` works properly, so I suspect it has to do with a version mismatch between the Go bindings in this repo and maybe some dependencies on my system (aom? still looking into that). I run arch so it uses the latest on everything.

Thank you for the insights! I'll open a new issue if I can pin anything down.

**Comment by farindk** [comment]
Even though I don't use it myself, I had a quick look into the Go wrapper. The function `GetImage` seems to handle >8 bpp images correctly when it is decoded to RGB, but when the output colorspace is YCbCr, it appears to me that it assumes that it is 8 bpp only. Maybe that helps in the search (cc @fancycode).

**Comment by mholt** [comment]
@farindk Ah, interesting -- thank you for the tip!
