### ISSUE TITLE
Api example failed

### ISSUE THREAD

**Issue by Arthur111** [strukturag/libheif#121]
Your example :

// decode the image and convert colorspace to RGB, saved as 24bit interleaved
heif_image* img;
heif_decode_image(handle, &img, heif_colorspace_RGB, heif_chroma_interleaved_24bit, nullptr);

failed 

Even after being fixed :
    // decode the image and convert colorspace to RGB, saved as 24bit interleaved
struct heif_image *img;

struct heif_error err = heif_decode_image(handle, &img, heif_colorspace_RGB, heif_chroma_interleaved_RGB, NULL);

i got the message : "Unsupported feature: Unsupported codec"

Why ?

**Comment by farindk** [comment]
How did you compile libheif? You probably compiled it without support for h.265.
You first have to install libde265. Then, when running ./configure for libheif, it should detect this and enable h.265 support.

**Comment by Arthur111** [comment]
Yes, it was compiled without libde265.
Now its ok, thanks.
