### ISSUE TITLE
Loading, writing an image then loading it give differents pixels randomly

### ISSUE THREAD

**Issue by Arthur111** [strukturag/libheif#122]
Hello,

Loading and writing an image with heif_encoder_set_lossless(encoder, 1); then loading it  give differents pixels.

Simplified code : 

`heif_context_read_from_file ( https://github.com/nokiatech/heif_conformance/blob/master/conformance_files/C004.heic )
heif_context_get_primary_image_handle
heif_image_handle_has_alpha_channel (for rgb or rgba in decode_image)
heif_decode_image
heif_image_get_bits_per_pixel
heif_image_get_width
heif_image_get_height
heif_image_get_plane_readonly

    for (i = 0; i < height; ++i)
    {
        plane = data + i * stride;
        for (j = 0; j < width; ++j)
        {
            from = j * bytes_per_pixel;
            for (x = from; x < from + bytes_per_pixel; ++x)
            {
               printf"%d:",plane[x]);
             }
          }
     }

heif_context_get_encoder_for_format (heif_compression_HEVC)
heif_encoder_set_lossless 1
heif_context_encode_image
heif_context_write_to_file (new file)`

First 32 bytes
80:98:114:86:104:120:92:110:126:83:101:117:84:102:118:84:102:118:91:109:125:87:105:121:88:106:122:91:109:125:85:103

and 

`heif_context_read_from_file (new file)
heif_context_get_primary_image_handle
heif_image_handle_has_alpha_channel (for rgb or rgba in decode_image)
heif_decode_image
heif_image_get_bits_per_pixel
heif_image_get_width
heif_image_get_height
heif_image_get_plane_readonly

    for (i = 0; i < height; ++i)
    {
        plane = data1 + i * planeNo;
        for (j = 0; j < width; ++j)
        {
            from = j * bytes_per_pixel;
            for (x = from; x < from + bytes_per_pixel; ++x)
            {
                 printf"%d:",plane[x]);
             }
         }
     }`

First 32 bytes
78:98:113:84:104:119:90:110:125:81:101:116:82:102:117:82:102:117:89:109:124:85:105:120:86:106:121:89:109:124:83:103

We can see bytes 1, 3, 4, 6, 7, 9, 10, 12, 13, 15, 16, 18, 19, 21, 22, 24, 25, 27, 28, 30, 31
are differents.

Why these differences ?
Thank you

**Comment by farindk** [comment]
You're probably reading the image in RGB. Then colorspace transformations to/from YUV are used. These are not lossless. You have to process the data in the native YUV colorspace

**Comment by Arthur111** [comment]
Yes i use RGB  ( heif_colorspace_RGB )

But in

 enum heif_colorspace {
  heif_colorspace_undefined=99,
  heif_colorspace_YCbCr=0,
  heif_colorspace_RGB  =1,
  heif_colorspace_monochrome=2
};
There is no YUV

Which value should i use in enum heif_colorspace and enum heif_chroma chroma ?

**Comment by farindk** [comment]
Sorry, I mean YCbCr. YUV is not strictly correct.
Chroma: it really depends on what you are doing and where the data comes from. If you are loading existing HEIF files, take the same chroma. Otherwise, take the one fitting to your input data.

**Comment by Arthur111** [comment]
Ok, thank you.
