### ISSUE TITLE
memory leak in openjpeg_decode_image

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#1251]
Hello,

https://github.com/strukturag/libheif/blob/master/libheif/plugins/decoder_openjpeg.cc

I observed that `opj_stream_destroy(stream);` is called only in case success but not in case of some previous errors.

I think that `opj_stream_destroy` should be used in the error handlers too.

When I look at example usage of openjpeg in https://github.com/uclouvain/openjpeg/blob/master/tests/test_tile_decoder.c

I have impression that `opj_destroy_codec` and `opj_image_destroy` should be used in the code too.

**Comment by bradh** [comment]
Could well be the case. Do you want to prepare changes?

**Comment by farindk** [comment]
Thanks for reporting this. Should be handled correctly now.
