### ISSUE TITLE
encode_jpeg2000 test failures

### ISSUE THREAD

**Issue by Lastique** [strukturag/libheif#1254]
When building libheif Debian packages under pbuilder/cowbuilder, I'm seeing the following test failures:

```
test 3
    Start 3: encode_jpeg2000

3: Test command: /build/libheif/libheif/obj-x86_64-linux-gnu/tests/encode_jpeg2000
3: Test timeout computed to be: 1500
3:
3: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3: encode_jpeg2000 is a Catch v2.13.9 host application.
3: Run with -? for options
3:
3: -------------------------------------------------------------------------------
3: Encode JPEG2000 lossy
3: -------------------------------------------------------------------------------
3: ./tests/encode_jpeg2000.cc:76
3: ...............................................................................
3:
3: ./tests/encode_jpeg2000.cc:53: FAILED:
3:   REQUIRE( err.code == heif_error_Ok )
3: with expansion:
3:   3 == 0
3:
3: -------------------------------------------------------------------------------
3: Encode JPEG2000 lossless
3: -------------------------------------------------------------------------------
3: ./tests/encode_jpeg2000.cc:82
3: ...............................................................................
3:
3: ./tests/encode_jpeg2000.cc:53: FAILED:
3:   REQUIRE( err.code == heif_error_Ok )
3: with expansion:
3:   3 == 0
3:
3: ===============================================================================
3: test cases:  2 | 2 failed
3: assertions: 10 | 8 passed | 2 failed
3:
1/3 Test #3: encode_jpeg2000 ..................***Failed    0.06 sec

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
encode_jpeg2000 is a Catch v2.13.9 host application.
Run with -? for options

-------------------------------------------------------------------------------
Encode JPEG2000 lossy
-------------------------------------------------------------------------------
./tests/encode_jpeg2000.cc:76
...............................................................................

./tests/encode_jpeg2000.cc:53: FAILED:
  REQUIRE( err.code == heif_error_Ok )
with expansion:
  3 == 0

-------------------------------------------------------------------------------
Encode JPEG2000 lossless
-------------------------------------------------------------------------------
./tests/encode_jpeg2000.cc:82
...............................................................................

./tests/encode_jpeg2000.cc:53: FAILED:
  REQUIRE( err.code == heif_error_Ok )
with expansion:
  3 == 0

===============================================================================
test cases:  2 | 2 failed
assertions: 10 | 8 passed | 2 failed
```

Full build log: 
[libheif_jpeg2000_errors.txt](https://github.com/user-attachments/files/16431383/libheif_jpeg2000_errors.txt)

This happens when building packages for Ubuntu 22.04, Debian 11 and Debian 12.

This is with libheif 1.18.1. This problem did not appear on libheif 1.17.6.

**Comment by silverbacknet** [comment]
Here's the relevant lines of the log:
```
CMake Warning at CMakeLists.txt:214 (find_package):
  Could not find a configuration file for package "OpenJPEG" that is
  compatible with requested version "2".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/openjpeg-2.4/OpenJPEGConfig.cmake, version: unknown
    /usr/lib/x86_64-linux-gnu/openjpeg-2.1/OpenJPEGConfig.cmake, version: unknown
    /lib/x86_64-linux-gnu/openjpeg-2.4/OpenJPEGConfig.cmake, version: unknown
    /lib/x86_64-linux-gnu/openjpeg-2.1/OpenJPEGConfig.cmake, version: unknown
```

So there simply is no jpeg2000 to test. I'm not sure why cmake would say version is unknown. Have you built cmake yourself? The version in the repo should be current and compatible with everything; if you built it yourself or obtained it elsewhere, that's a wildcard.

**Comment by Lastique** [comment]
> Have you built cmake yourself?

No, CMake is stock from the respective distro's repository. Both when building libheif 1.18.1 and 1.17.6. In fact, in both cases the build environment is the same.

The `libopenjp2-7-dev` package is installed before building libheif. On Ubuntu 22.04 it is version 2.4.0-6, on Debian 11 - 2.4.0-3, on Debian 12 - 2.5.0-2. Those are also stock versions from the respective distros, and I believe the CMake modules that are mentioned in the quoted message belong to `libopenjp2-7-dev`, not CMake.

If CMake doesn't find a suitable OpenJPEG library (which is a bug of its own), then why OpenJPEG tests are run and fail? I would expect the tests to be skipped.

**Comment by Lastique** [comment]
If I'm reading CMake [docs](https://cmake.org/cmake/help/v3.22/command/find_package.html#version-selection) correctly, it expects a version file next to the config file, but there is no such file provided by `libopenjp2-7-dev`. E.g. see [here](https://packages.ubuntu.com/jammy/amd64/libopenjp2-7-dev/filelist). This is probably why the version is "unknown" and the version check is not satisfied. libheif 1.17.6 did not contain the version requirement, which is why it succeeded to build with OpenJPEG.

**Comment by farindk** [comment]
This is where this change comes from:
https://github.com/strukturag/libheif/pull/1135
https://github.com/strukturag/libheif/issues/1134

**Comment by Lastique** [comment]
I see, thanks for the links. So this is a packaging bug in Debian/Ubuntu. BTW, I can confirm that removing the version requirement from CMakeLists.txt lets the tests succeed.

The remaining issue then is whether the tests should be skipped rather than fail when OpenJPEG is not detected.

**Comment by farindk** [comment]
Above patch switches off the test when the JPEG2000 encoder was not found.
