### ISSUE TITLE
libheif libheif/libheif/api/libheif/heif_properties.cc fails to compile (as part of GraphicsMagick oss-fuzz build)

### ISSUE THREAD

**Issue by bobfriesenhahn** [strukturag/libheif#1260]
The GraphicsMagick oss-fuzz build also builds libheif. There is a failure while building libheif in the 8/8/2024 build viewable at [OSS-Fuzz Build Status](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#graphicsmagick).

The error message coming out is "merror: muse of undeclared identifier 'properties'".

**Comment by bradh** [comment]
Have add a fix at https://github.com/strukturag/libheif/pull/1261

**Comment by farindk** [comment]
Should be fixed now (34fd2acd1d25fe8f395e2a20142034c4b66c5170).
