### ISSUE TITLE
heif-convert command not found

### ISSUE THREAD

**Issue by OPRESEK** [strukturag/libheif#1265]
Hi, when I try to use the heif-convert command it appears that it doesn't exist
`zsh: command not found: heif-convert`  

I have libheif-1.18.1-1 on Arch Linux

**Comment by bradh** [comment]
It was renamed to `heif-dec`. There is supposed to be a symbolic link from `heif-convert` but the initial 
implementation didn't work correctly for some installations.  That has since been resolved, so consider upgrading if this is important to you.

**Comment by denizsincar29** [comment]
heif-dec is also dont work.

**Comment by bradh** [comment]
@denizsincar29 This is a closed ticket. If you have having problems, please raise a new ticket.

Try to explain exactly what you did, what you expected to happen, what happened instead, and what debugging you have done.

**Comment by denizsincar29** [comment]
No warries, i installed libheif examples package and all worked.
