### ISSUE TITLE
heif-enc 1.18.2 regression: grayscale with alpha channel is not being read correctly

### ISSUE THREAD

**Issue by homm** [strukturag/libheif#1274]
## Source image

![dices LA](https://github.com/user-attachments/assets/2dbebd19-a867-4dc9-b7dd-f8b60d0f4125)

## Reproduce

```bash
# heif-enc dices.LA.png -o dices.LA.avif
# heif-enc dices.LA.png -o dices.LA.heif
```

### 1.16.2

Works as expected

### 1.18.2

[Archive.zip](https://github.com/user-attachments/files/16657312/Archive.zip)

![dices LA avif](https://github.com/user-attachments/assets/e471f7d4-0710-4a36-a96f-ed877641d245)

**Comment by farindk** [comment]
Thank you for the report and example image.

The PNG reader did not support mono + alpha. I have added this in the commit above. (also cherry-picked to master and v1.18.x branches).
