### ISSUE TITLE
libvips 8.8 now has heic support via libheif

### ISSUE THREAD

**Issue by jcupitt** [strukturag/libheif#129]
Hello, I thought you might be interested in the new libvips 8.8 release. It has fairly complete HEIC support via libheif, including support for XMP and EXIF metadata, colour profiles, animated and many-page images, heif thumbnails and lossy and lossless compression.

libvips is widely used on the web as an image resize library. It's popular on node, so this should get libheif some more exposure. 

There are some notes here:

https://libvips.github.io/libvips/2019/04/22/What's-new-in-8.8.html

For example:

```
$ vips thumbnail dancing_banana2.lossless.webp[n=-1] x.heic[Q=30] 128
$ vips copy x.heic[n=-1] x.gif
```

The `n=-1` means process all pages.  It makes this GIF:

![x](https://user-images.githubusercontent.com/580843/57847712-11147600-77cf-11e9-8aaf-94e8e6b6a54a.gif)

It doesn't support save alpha to HEIC, unfortunately. 

You can download libvips rc3 here:

https://github.com/libvips/libvips/releases/tag/v8.8.0-rc3

It should be released formally in about a week.

**Comment by farindk** [comment]
Thanks for the note, John. This is great, I'll have a look at your new release.

Curious to see how the banana is stored in the HEIF even though we do not have image-sequence support in libheif (.heics) yet.

**Comment by jcupitt** [comment]
It just writes a set of pages, with (I think?) the first page as the

**Comment by jcupitt** [comment]
libvips 8.8 is out now. I'll close.
