### ISSUE TITLE
errors with small images

### ISSUE THREAD

**Issue by jcupitt** [strukturag/libheif#130]
Hello, I've noticed some problems with small images (less than 128 x 128 pixels).

For example, this seems fine:

```shell
john@yingna ~/pics $ vips crop k2.png x.png 0 0 128 128
john@yingna ~/pics $ heif-enc x.png -o x.heic
john@yingna ~/pics $ heif-info x.heic 
image: 128x128 (id=1), primary
  color profile: no
  alpha channel: no
  depth channel: no
```

But this mysteriously drops a pixel:

```shell
john@yingna ~/pics $ vips crop k2.png x.png 0 0 127 127
john@yingna ~/pics $ heif-enc x.png -o x.heic
john@yingna ~/pics $ heif-info x.heic 
image: 126x126 (id=1), primary
  color profile: no
  alpha channel: no
  depth channel: no
```

And this doesn't work at all:

```shell
john@yingna ~/pics $ vips crop k2.png x.png 0 0 128 58
john@yingna ~/pics $ heif-enc x.png -o x.heic
Could not encode HEIF file: Encoder plugin generated an error: Invalid parameter value: Images smaller than 16 pixels are not supported
```

**Comment by farindk** [comment]
Hi John,

yes, h265 can only encode at image sizes that are a multiple of the color subsampling factor. I.e. at 4:2:0, we can only encode even sizes. One solution to that problem could be to encode the image at a larger resolution and use a HEIF cropping transformation to get the desired resolution. That is an open point for libheif.

At very small image sizes, we hit a bug in x265, i.e. that the minimum image size has to be at least one CU. We reported this to x265, but they did not react yet. Here, we might need a similar workaround with storing at a larger size and cropping to the final resolution.

**Comment by jcupitt** [comment]
Ah gotcha. Thank you very much for the quick response, I'll close.

**Comment by farindk** [comment]
I'll keep this open as a reminder...

**Comment by Jehan** [comment]
> At very small image sizes, we hit a bug in x265, i.e. that the minimum image size has to be at least one CU. We reported this to x265, but they did not react yet.

Could you give the report URL please? So that we can follow the advancement.

**Comment by farindk** [comment]
Link to x265 issue about image size < CTU size:
https://bitbucket.org/multicoreware/x265/issues/475/x265-does-not-allow-image-sizes-smaller

**Comment by farindk** [comment]
2f91ec1 now implements odd HEIF image sizes and sizes < 16 pixels.
