### ISSUE TITLE
HEIF Decoding Image Failed

### ISSUE THREAD

**Issue by pramath-pancholi** [strukturag/libheif#1303]
I'm using the heic2any library which uses this library under the hood to convert heif images to jpeg, and I'm getting a decoding error on some images but not others. All the images I'm trying to convert are in heif format, and while some successfully get converted to jpeg, others all fail with the exact same error:

<img width="1443" alt="image" src="https://github.com/user-attachments/assets/13b2de44-1b66-49b5-bf33-e884ba4d2d8e">

Since everything is minified I really can't tell what the problem could be.

**Comment by farindk** [comment]
Probably, it's because `heic2any` uses an old libheif version. You should try the image with the `heif-dec` program (or `heif-convert` if you have an older version installed). You should try with a v1.18.x version because current images from iOS may need that version.

**Comment by farindk** [comment]
Can I close this?
