### ISSUE TITLE
'pixi' of version 1 should be ignored rather than cause parsing to fail

### ISSUE THREAD

**Issue by leo-barnes** [strukturag/libheif#1306]
Per email discussion with @farindk and @wantehchang, libheif will currently return an error if a 'pixi' with version 1 is encountered.
Ideally a v1 'pixi' would be ignored (unless marked as essential).

(Per discussion we will propose to not bump the version but rather just append the new data to the box since it should be backwards compatible.)

**Comment by leo-barnes** [comment]
Related: https://github.com/AOMediaCodec/libavif/issues/2428

**Comment by wantehchang** [comment]
Note that this issue also applies to other FullBoxes (which have a version). The 'pixi' box is just the one that led us to investigate this issue in libavif and libheif.

**Comment by farindk** [comment]
Implemented. Parse errors in 'informal' boxes will not stop the decoding process anymore, but instead output warnings:
````
$ heif-dec pixi-unknown-version.heic out.jpg
Warning: Unsupported feature: Unsupported data version: pixi box data version 153 is not implemented yet
Written to out.jpg
````

and show the parse error in the box dump:
````
| | | index: 5
| | | Box: irot -----
| | | size: 9   (header size: 8)
| | | rotation: 270 degrees (CCW)
| | | 
| | | index: 6
| | | 'pixi' parse error: pixi box data version 153 is not implemented yet
| | | fatality: optional
| | | 
| | | index: 7
| | | Box: colr -----
````
