### ISSUE TITLE
Use-of-uninitialized-memory in `convert_colorspace()`

### ISSUE THREAD

**Issue by skorpion98** [strukturag/libheif#1308]
### Summary
We found a use-of-uninitialized-memory error while testing the `encoder_heic_fuzzer` fuzzing harness for ImageMagick. Upon further inspection, this issue seems to be related to an external dependency (libheif) rather than to ImageMagick itself. For this reason, we decided to report it directly here, instead of reporting it to ImageMagick. It is still possible that this error is caused by an incorrect use of libheif; if you believe this is the case, we will report it to ImageMagick as well.

We found the bug in function [Op_YCbCr_to_RGB<unsignedshort>::convert_colorspace()](https://github.com/strukturag/libheif/blob/8cc6c796ac706bdf99c1f6f82f32b7873bbbf19d/libheif/color-conversion/yuv2rgb.cc#L86), more specifically in lines 246, 247, and 248. 
Upon further inspection, we believe that access to the `out_x` buffers is happening on uninitialized data, perhaps due to buffer overruns caused by unchecked boundaries. We found two inputs that trigger the bug in slightly different ways, you may find them both attached to this report.

### Steps to reproduce
In the [following archive](https://github.com/user-attachments/files/16995883/libheif_msan.zip) you will find a directory `bugs` containing the two inputs that triggered the aforementioned bug and their respective Valgrind log. Additionally, you will find [at this link](https://drive.google.com/file/d/1BK1eqg6FmseIAsF3BiSNWAdd_9BxpuaE/view?usp=drive_link) the compiled fuzzing harness we used to perform our tests (we had to share it from outside github as its size exceeds the size limit for this issue).

To reproduce the errors, a memory safety tool is required to expose the bug. Run the given binary with the testcase files inside Valgrind with a command like `valgrind ./encoder_heic_fuzzer /path_to_testcases/input`

The program has been tested on the standard Docker image provided on OSS-Fuzz using Ubuntu 20.04, providing AFL++ as fuzzing engine and build flag `--sanitizer=none`.

The libheif hash commit used to perform the tests is `3a043d9`, the latest at the time of testing.
The ImageMagick hash commit used to perform the tests is `6299383`.

**Environment**
- OS: Linux
- Version/Distribution: Ubuntu 20.04
- Architecture: x86_64

**Comment by farindk** [comment]
The h265 data in the file is incomplete, it does not cover the whole image. This can be seen as the green stripe at the bottom of the image.
The `libde265` decoder returns uninitialized memory for this area.

Initializing the whole memory with `0` fixes the uninitialized memory access:
  https://github.com/strukturag/libde265/commit/89c841109743ef6b30f546982529a17400273f5b
A faster way to only initialize undecoded image areas would be nice, but is much harder to implement.

In any case, the issue is non-critical.
