### ISSUE TITLE
Add and Use this Library in a C# project.

### ISSUE THREAD

**Issue by moutasem1989** [strukturag/libheif#131]
Can I use this library in a C# app to extract an Image Collection contained in this [HEIC Sample](https://github.com/strukturag/libheif/files/3232354/HEIC.Sample.zip) ?
How can I do it? How can add the library to my project ?

**Comment by farindk** [comment]
We do not provide a C# interface at this point of time, but you should be able to almost automatically get a C# interface wrapper by using SWIG: http://www.swig.org/Doc3.0/CSharp.html

**Comment by moutasem1989** [comment]
Unfortunately, I am not familiar with SWIG. Perhaps there is a totorial you can recomend or an example you can provide?
I have been reading about calling a DLL (in C++) file function from a C# Project, but it is definitely a new territory for me. Another solution would be to rewrite the HEIC Conversion function in C# which is a lot of work for a beginner like me.

**Comment by farindk** [comment]
Swig is quite easy to use. There are tutorials on their web site.
In the end, it is probably not much more than writing a simple configuration file like below (completely untested), and running Swig on it.

-------------------

%module libheif
%{
#include "libheif/heif.h"
%}

%include "libheif/heif.h"

**Comment by moutasem1989** [comment]
I am sorry to bother you but i am hopping you can help me bring this issue to an end.

I created a file in the Project directory named "libheif_Swig.i" containing this :

%module libheif
%{
        #include "libheif/heif.h"
%}

%include <windows.i>
%include "libheif/heif.h"

Changed the properties of this file (Custom Build tools/ Command Line: c:\swigwin-4.0.0\swig -csharp -c++ -outdir C:\dump\swig\Generated libheif_Swig.i

Then just right-click libheif_Swig.i and select ‘Compile’. This will generate those files in the Generated folder.
cpp.cs
cpp_file.cs
cppPINVOKE.cs

and this file in the libheif folder
cpp_file_wrap.cxx

It is a very simple process that shouldnt take more than 5 min. My old PC however cant seem to handle it for some reason. it keeps on freezing halfway with no response only to fail hours later.
I have tried to compile it with Visual Studio but I got to a dead end. Perhaps if you have to time you could compile it for me?
