### ISSUE TITLE
Assertion `sps->SubWidthC == SubWidthC' failed.

### ISSUE THREAD

**Issue by naoto0804** [strukturag/libheif#132]
I'm trying to get a depth channel from .heic file taken by recent iPhone. 
When I try converting it by `heif-convert`, the following error happened. It seems something is wrong when the program tries to process the depth channel (because the RGB image is written [here](https://github.com/strukturag/libheif/blob/master/examples/heif_convert.cc#L234)), but I have no idea how to fix it. I would really appreciate it if someone could give me some suggestions.

$ ./libheif/examples/heif-convert IMG_8262.HEIC foo.png
File contains 1 images
Written to foo.png
lt-heif-convert: image.cc:315: de265_error de265_image::alloc_image(int, int, de265_chroma, std::shared_ptr<const seq_parameter_set>, bool, decoder_context*, encoder_context*, de265_PTS, void*, bool): Assertion `sps->SubWidthC == SubWidthC' failed.
Aborted (core dumped)

Just in case, `heif-info` is working and the result is like the following (at least there is a depth channel in the input image):
$ ./libheif/examples/heif-info IMG_8262.HEIC
image: 4032x3024 (id=49), primary
  thumbnail: 320x240
  color profile: prof
  alpha channel: no
  depth channel: yes
 (768x576)
    z-near: undefined
    z-far:  undefined
    d-min:  1.172852
    d-max:  1.936523
    representation: uniform disparity
    disparity_reference_view: 0

Environment
- Ubuntu 16.04

**Comment by hyunjun529** [comment]
+1, I had same problem in CentOS 7.

lt-heif-convert: image.cc:316: de265_error de265_image::alloc_image(int, int, de265_chroma, std::shared_ptr<const seq_parameter_set>, bool, decoder_context*, de265_PTS, void*, bool): Assertion `sps->SubWidthC == SubWidthC' failed.

**Comment by farindk** [comment]
Does this problem still exist? I've tried all my images with depth channels on the latest version (1.6.0) and cannot reproduce it.

If you still get the error, can you please share the image?
You can upload it to
https://nextcloud.struktur.de/s/cwrZ41qozrPFaAg
if you can't attach it here.

**Comment by hyunjun529** [comment]
Hi, i just checked again. yes, it still exist in CentOS 7 with `libde265-1.0.3` and `libheif-1.4.0`.
also I didn't check on `libheif-1.6.0`.

I uploaded image `IMG_2188.HEIC` taken on the iPhone.
but sorry for that image cleaned up with `magick mogrify -strip IMG_2188.HEIC`.
if you need original image then please comment again.

and there are more information
```bash
$ ./heif-info ~/resource/heic/IMG_2188.HEIC
image: 4032x3024 (id=49), primary
  thumbnail: 320x240
  color profile: prof
  alpha channel: no
  depth channel: yes
 (768x576)
    z-near: undefined
    z-far:  undefined
    d-min:  1.134766
    d-max:  2.523438
    representation: uniform disparity
    disparity_reference_view: 0

$ ./heif-convert ~/resource/heic/IMG_2188.HEIC ~/results/hi.png
File contains 1 images
Written to ~/results/hi.png
lt-heif-convert: image.cc:316: de265_error de265_image::alloc_image(int, int, de265_chroma, std::shared_ptr<const seq_parameter_set>, bool, decoder_context*, de265_PTS, void*, bool): Assertion `sps->SubWidthC == SubWidthC' failed.
```

**Comment by farindk** [comment]
The image you uploaded has the depth channel removed. Thus, it does not crash.
I would need the image including the depth channel to reproduce the problem.

    $ ./examples/heif-info ~/data/images/heif/issue-reports/IMG_2188.HEIC 
    MIME type: image/heic
    image: 4032x3024 (id=1), primary
      color profile: no
      alpha channel: no
      depth channel: no

    $ ./examples/heif-convert ~/data/images/heif/issue-reports/IMG_2188.HEIC out.png
    File contains 1 images
    Written to out.png

**Comment by hyunjun529** [comment]
original image upload again. please test `IMG_2188-org.HEIC` file.

Sorry for your inconvenience :pray:

**Comment by farindk** [comment]
Thank you for the example image.

I have fixed the problem in libde265 with commit 
https://github.com/strukturag/libde265/commit/c109180d47352802092b269dad8b512dae140941
It's on the `v1-branch` branch.
