### ISSUE TITLE
High CPU Usage During HEIF Format Conversion

### ISSUE THREAD

**Issue by Axin647** [strukturag/libheif#1327]
I tried to implement the conversion to HEIF format using a simple example, and it was successful. However, the CPU usage is very high. My encoders and decoders are libde265 and libx265. When running this code, the CPU usage spikes significantly:
error = heif_context_encode_image(ctx, image, encoder, nullptr, nullptr);
if (error.code != heif_error_Ok) {
	std::cerr << "编码图像失败: " << error.message << std::endl;
	heif_encoder_release(encoder);
	heif_image_release(image);
	heif_context_free(ctx);
	return false;
}

**Comment by Axin647** [comment]
Is it possible to add an entry to set the x265 thread pool size in libheif?

**Comment by farindk** [comment]
Why would that be useful? It will make the encoding much slower.

**Comment by Axin647** [comment]
Thank you for your reply. What I mean is, are there any alternative solutions to address the issue of high CPU usage?

**Comment by farindk** [comment]
> are there any alternative solutions to address the issue of high CPU usage?

Not much, actually. Encoding to HEIC/AVIF is simply much more computation intensive than JPEG.
Only hardware acceleration support might help.
