### ISSUE TITLE
Some tiled images cannot be decoded with example applications

### ISSUE THREAD

**Issue by bradh** [strukturag/libheif#1328]
When using the new tiled image approaches, the example apps may fail to decode.

```
bradh@micrantha:~/libheif/build$ ./examples/heif-info ~/Downloads/rio-tild.avif 
MIME type: image/avif
main brand: avif
compatible brands: avif, mif1, miaf

image: 64768x41216 (id=1), primary
  tiles: 253x161, tile size: 256x256
  colorspace: YCbCr, 4:2:0
  bit depth: 8
  color profile: no
  alpha channel: no 
  depth channel: no
metadata:
  none
transformations:
  none
region annotations:
  none
properties:
Could not decode image Memory allocation error: Security limit exceeded: Image size 64768x41216 exceeds the maximum image size 1073741824
```

and

```
bradh@micrantha:~/libheif/build$ ./examples/heif-info ~/Downloads/rotterdam.avif 
MIME type: image/avif
main brand: avif
compatible brands: avif, mif1, miaf

image: 6656x7936 (id=1), primary
  tiles: 26x31, tile size: 256x256
  colorspace: YCbCr, 4:2:0
  bit depth: 8
  color profile: no
  alpha channel: no 
  depth channel: no
metadata:
  none
transformations:
  none
region annotations:
  none
properties:
Could not decode image Unsupported feature: Unspecified: 'tild' images can only be access per tile
```

**Comment by farindk** [comment]
With the above change, `heif-info` does not need to decode the image anymore.

> "Security limit exceeded: Image size 64768x41216 exceeds the maximum image size"

I think that error is reasonable. There is a new API to change the security limit, but I guess that converting that image to a single JPEG will fail anyway because of the memory needs.
But potentially, there could be a TIFF writer that converts it to tiled TIFFs, or we could at least output a set of image tile JPEGs.

**Comment by bradh** [comment]
Agree it is 

> I think that error is reasonable. There is a new API to change the security limit, but I guess that converting that image to a single JPEG will fail anyway because of the memory needs.

Concur its reasonable in this kind of example app.

**Comment by farindk** [comment]
I changed `heif-dec`. When you give it the new option `--tiles`, it will write all tiles to separate output images.
