### ISSUE TITLE
Images without ispe property cannot be read by libheif

### ISSUE THREAD

**Issue by YakoYakoYokuYoku** [strukturag/libheif#1349]
With 0b23606 images that have a missing `ispe` cannot be read with libheif. What's peculiar about this is that those images could be produced by libheif with versions previous to `v1.12.0`. As opposed to this FFmpeg can read these without issue. I open this to ask if `ispe` is really needed per what's in that commit or it isn't. Stemming from libgd/libgd#889, see [this example](https://github.com/libgd/libgd/blob/39c4644fa01f6b9f002119e4109e252bc665b8f1/tests/heif/label.heic).

**Comment by bradh** [comment]
This is an interesting case in that whether `ispe` is needed depends on the codec in use.

**Comment by farindk** [comment]
By specification, every image needs an `ispe` item, but it is true that in early versions of libheif, this was not always written because it is often not required for decoding.
I think, we should throw the error only if the `strict_decoding` flag is set in the `decoding_options`.

**Comment by YakoYakoYokuYoku** [comment]
> I think, we should throw the error only if the `strict_decoding` flag is set in the `decoding_options`.

That or a compatibility flag could be added in case issues like this one arise in the future.

**Comment by farindk** [comment]
Ok, my `strict_decoding` idea does not work because this is checked before any image is decoded.

I've changed it such that when there is no `ispe`, a decoding warning is attached to the image.
In cases where an `ispe` is required for decoding (camera matrices, tiling information), it will still output an error.
