### ISSUE TITLE
Configure doesn't create Makefile in Windows

### ISSUE THREAD

**Issue by eumel19900** [strukturag/libheif#1356]
I tried Building following the instructions on windows 11 x64 in msys-environment. It didn't create an makefile, so I can't compile.

I know I am missing all codex, but I think that is not important right know.

`Robert@Roberts-PC /c/tmp/libheif/build
$ ls -la
total 12
drwxr-xr-x  2 Robert Administratoren 8192 Oct 29 19:57 .
drwxr-xr-x 18 Robert Administratoren 4096 Oct 29 19:57 ..

Robert@Roberts-PC /c/tmp/libheif/build
$ cmake --preset=release ..
Preset CMake variables:

  BUILD_SHARED_LIBS="ON"
  BUILD_TESTING="OFF"
  CMAKE_BUILD_TYPE="Release"
  ENABLE_PLUGIN_LOADING="ON"
  WITH_AOM_DECODER="ON"
  WITH_AOM_DECODER_PLUGIN="ON"
  WITH_AOM_ENCODER="ON"
  WITH_AOM_ENCODER_PLUGIN="ON"
  WITH_DAV1D="ON"
  WITH_DAV1D_PLUGIN="ON"
  WITH_EXAMPLES="ON"
  WITH_FFMPEG_DECODER="ON"
  WITH_FFMPEG_DECODER_PLUGIN="ON"
  WITH_FUZZERS="OFF"
  WITH_HEADER_COMPRESSION="ON"
  WITH_JPEG_DECODER="ON"
  WITH_JPEG_DECODER_PLUGIN="ON"
  WITH_JPEG_ENCODER="ON"
  WITH_JPEG_ENCODER_PLUGIN="ON"
  WITH_KVAZAAR="ON"
  WITH_KVAZAAR_PLUGIN="ON"
  WITH_LIBDE265="ON"
  WITH_LIBDE265_PLUGIN="ON"
  WITH_LIBSHARPYUV="ON"
  WITH_OPENJPH_ENCODER="ON"
  WITH_OpenJPEG_DECODER="ON"
  WITH_OpenJPEG_DECODER_PLUGIN="ON"
  WITH_OpenJPEG_ENCODER="ON"
  WITH_OpenJPEG_ENCODER_PLUGIN="ON"
  WITH_RAV1E="ON"
  WITH_RAV1E_PLUGIN="ON"
  WITH_REDUCED_VISIBILITY="ON"
  WITH_SvtEnc="ON"
  WITH_SvtEnc_PLUGIN="ON"
  WITH_UNCOMPRESSED_CODEC="ON"
  WITH_X265="ON"
  WITH_X265_PLUGIN="ON"

-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.26100.0 to target Windows 10.0.22631.
-- The C compiler identification is MSVC 19.41.34123.0
-- The CXX compiler identification is MSVC 19.41.34123.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Performing Test has_potentially_evaluated_expression
-- Performing Test has_potentially_evaluated_expression - Failed
CMake Warning at cmake/modules/LibFindMacros.cmake:267 (message):
  WARNING: MISSING PACKAGE

  We could not find development headers for LIBDE265.  Do you have the
  necessary dev package installed? This package is NOT REQUIRED and you may
  ignore this warning but by doing so you may miss some functionality of
  libheif.

  Relevant CMake configuration variables:

    LIBDE265_INCLUDE_DIR-NOTFOUND=
    LIBDE265_INCLUDE_DIR=<not found>
    LIBDE265_LIBRARY-NOTFOUND=
    LIBDE265_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/modules/FindLIBDE265.cmake:17 (libfind_process)
  CMakeLists.txt:123 (find_package)

-- Could NOT find LIBDE265 (missing: LIBDE265_INCLUDE_DIRS LIBDE265_LIBRARIES)
CMake Warning at cmake/modules/LibFindMacros.cmake:267 (message):
  WARNING: MISSING PACKAGE

  We could not find development headers for X265.  Do you have the necessary
  dev package installed? This package is NOT REQUIRED and you may ignore this
  warning but by doing so you may miss some functionality of libheif.

  Relevant CMake configuration variables:

    X265_INCLUDE_DIR=<not found>
    X265_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/modules/FindX265.cmake:17 (libfind_process)
  CMakeLists.txt:130 (find_package)

-- Could NOT find X265 (missing: X265_INCLUDE_DIR X265_LIBRARIES)
CMake Warning at cmake/modules/LibFindMacros.cmake:267 (message):
  WARNING: MISSING PACKAGE

  We could not find development headers for KVAZAAR.  Do you have the
  necessary dev package installed? This package is NOT REQUIRED and you may
  ignore this warning but by doing so you may miss some functionality of
  libheif.

  Relevant CMake configuration variables:

    KVAZAAR_INCLUDE_DIR=<not found>
    KVAZAAR_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/modules/Findkvazaar.cmake:19 (libfind_process)
  CMakeLists.txt:137 (find_package)

-- Performing Test HAVE_KVAZAAR_ENABLE_LOGGING
-- Performing Test HAVE_KVAZAAR_ENABLE_LOGGING - Failed
-- Could NOT find kvazaar (missing: KVAZAAR_INCLUDE_DIR KVAZAAR_LIBRARIES)
CMake Warning at cmake/modules/LibFindMacros.cmake:267 (message):
  WARNING: MISSING PACKAGE

  We could not find development headers for OpenH264.  Do you have the
  necessary dev package installed? This package is NOT REQUIRED and you may
  ignore this warning but by doing so you may miss some functionality of
  libheif.

  Relevant CMake configuration variables:

    OpenH264_INCLUDE_DIR=<not found>
    OpenH264_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/modules/FindOpenH264.cmake:19 (libfind_process)
  CMakeLists.txt:186 (find_package)

-- Could NOT find OpenH264 (missing: OpenH264_INCLUDE_DIR OpenH264_LIBRARIES)
CMake Warning at cmake/modules/LibFindMacros.cmake:267 (message):
  WARNING: MISSING PACKAGE

  We could not find development headers for DAV1D.  Do you have the necessary
  dev package installed? This package is NOT REQUIRED and you may ignore this
  warning but by doing so you may miss some functionality of libheif.

  Relevant CMake configuration variables:

    DAV1D_INCLUDE_DIR=<not found>
    DAV1D_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/modules/FindDAV1D.cmake:17 (libfind_process)
  CMakeLists.txt:204 (find_package)

-- Could NOT find DAV1D (missing: DAV1D_INCLUDE_DIR DAV1D_LIBRARIES)
-- Looking for AOM_USAGE_GOOD_QUALITY
-- Looking for AOM_USAGE_GOOD_QUALITY - not found
CMake Warning at cmake/modules/LibFindMacros.cmake:267 (message):
  WARNING: MISSING PACKAGE

  We could not find development headers for AOM.  Do you have the necessary
  dev package installed? This package is NOT REQUIRED and you may ignore this
  warning but by doing so you may miss some functionality of libheif.

  Relevant CMake configuration variables:

    AOM_INCLUDE_DIR=<not found>
    AOM_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/modules/FindAOM.cmake:35 (libfind_process)
  CMakeLists.txt:212 (find_package)

-- Could NOT find AOM (missing: AOM_INCLUDE_DIR AOM_LIBRARIES)
CMake Warning at cmake/modules/LibFindMacros.cmake:267 (message):
  WARNING: MISSING PACKAGE

  We could not find development headers for SvtEnc.  Do you have the
  necessary dev package installed? This package is NOT REQUIRED and you may
  ignore this warning but by doing so you may miss some functionality of
  libheif.

  Relevant CMake configuration variables:

    SvtEnc_INCLUDE_DIR=<not found>
    SvtEnc_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/modules/FindSvtEnc.cmake:17 (libfind_process)
  CMakeLists.txt:227 (find_package)

-- Could NOT find SvtEnc (missing: SvtEnc_INCLUDE_DIR SvtEnc_LIBRARIES)
CMake Warning at cmake/modules/LibFindMacros.cmake:267 (message):
  WARNING: MISSING PACKAGE

  We could not find development headers for RAV1E.  Do you have the necessary
  dev package installed? This package is NOT REQUIRED and you may ignore this
  warning but by doing so you may miss some functionality of libheif.

  Relevant CMake configuration variables:

    RAV1E_INCLUDE_DIR=<not found>
    RAV1E_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/modules/FindRAV1E.cmake:17 (libfind_process)
  CMakeLists.txt:234 (find_package)

-- Could NOT find RAV1E (missing: RAV1E_INCLUDE_DIR RAV1E_LIBRARIES)
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
CMake Warning at CMakeLists.txt:250 (find_package):
  By not providing "FindOpenJPEG.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenJPEG",
  but CMake did not find one.

  Could not find a package configuration file provided by "OpenJPEG"
  (requested version 2) with any of the following names:

    OpenJPEGConfig.cmake
    openjpeg-config.cmake

  Add the installation prefix of "OpenJPEG" to CMAKE_PREFIX_PATH or set
  "OpenJPEG_DIR" to a directory containing one of the above files.  If
  "OpenJPEG" provides a separate development package or SDK, be sure it has
  been installed.

-- Could NOT find FFMPEG (missing: FFMPEG_INCLUDE_DIRS FFMPEG_LIBRARIES avcodec avutil)
CMake Warning at cmake/modules/LibFindMacros.cmake:267 (message):
  WARNING: MISSING PACKAGE

  We could not find development headers for OPENJPH.  Do you have the
  necessary dev package installed? This package is NOT REQUIRED and you may
  ignore this warning but by doing so you may miss some functionality of
  libheif.

  Relevant CMake configuration variables:

    OPENJPH_INCLUDE_DIR=<not found>
    OPENJPH_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/modules/FindOPENJPH.cmake:17 (libfind_process)
  CMakeLists.txt:265 (find_package)

-- Could NOT find OPENJPH (missing: OPENJPH_INCLUDE_DIR OPENJPH_LIBRARY)

=== Summary of compiled codecs ===
libde265 HEVC decoder           : - not found
FFMPEG HEVC decoder (HW acc)    : - not found
x265 HEVC encoder               : - not found
Kvazaar HEVC encoder            : - not found
AOM AV1 decoder                 : - not found
AOM AV1 encoder                 : - not found
Dav1d AV1 decoder               : - not found
SVT AV1 encoder                 : - not found
Rav1e AV1 encoder               : - not found
JPEG decoder                    : - not found
JPEG encoder                    : - not found
OpenH264 decoder                : - not found
OpenJPEG J2K decoder            : - not found
OpenJPEG J2K encoder            : - not found
OpenJPH HT-J2K encoder          : - not found
uvg266 VVC enc. (experimental)  : - disabled
vvenc VVC enc. (experimental)   : - disabled
vvdec VVC dec. (experimental)   : - disabled

=== Supported formats ===
format        decoding   encoding
AVC             NO         NO
AVIF            NO         NO
HEIC            NO         NO
JPEG            NO         NO
JPEG2000        NO         NO
JPEG2000-HT     NO         NO
Uncompressed    YES        YES
VVC             NO         NO

CMake Warning at cmake/modules/LibFindMacros.cmake:267 (message):
  WARNING: MISSING PACKAGE

  We could not find development headers for LIBSHARPYUV.  Do you have the
  necessary dev package installed? This package is NOT REQUIRED and you may
  ignore this warning but by doing so you may miss some functionality of
  libheif.

  Relevant CMake configuration variables:

    LIBSHARPYUV_INCLUDE_DIR=<not found>
    LIBSHARPYUV_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/modules/Findlibsharpyuv.cmake:18 (libfind_process)
  CMakeLists.txt:386 (find_package)

-- Could NOT find libsharpyuv (missing: LIBSHARPYUV_INCLUDE_DIR LIBSHARPYUV_LIBRARIES)
libsharpyuv: disabled
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
zlib not found
-- Did not find Brotli (missing: BROTLI_COMMON_LIB BROTLI_DEC_INCLUDE_DIR BROTLI_DEC_LIB BROTLI_ENC_INCLUDE_DIR BROTLI_ENC_LIB)
Brotli not found
-- Looking for _LIBCPP_VERSION
-- Looking for _LIBCPP_VERSION - not found
-- Could NOT find TIFF (missing: TIFF_LIBRARY TIFF_INCLUDE_DIR)
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR)

=== Active input formats for heif-enc ===
JPEG: ------ (libjpeg not found)
PNG:  ------ (libpng not found)
TIFF: ------ (libtiff not found)

-- Found Doxygen: C:/Program Files/doxygen/bin/doxygen.exe (found version "1.12.0") found components: doxygen missing components: dot

Doxygen build started
Not compiling 'x265' backend
Not compiling 'libde265' backend
Not compiling 'dav1d' backend
Not compiling 'aomdec' backend
Not compiling 'aomenc' backend
Not compiling 'svtenc' backend
Not compiling 'rav1e' backend
Not compiling 'jpegdec' backend
Not compiling 'jpegenc' backend
Not compiling 'j2kdec' backend
Not compiling 'j2kenc' backend
Not compiling 'kvazaar' backend
Not compiling 'ffmpegdec' backend
Not compiling 'jphenc' backend
Not compiling 'uvg266' backend
Not compiling 'vvdec' backend
Not compiling 'vvenc' backend
Not compiling 'openh264dec' backend
Not compiling 'libsharpyuv'
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Configuring done (7.9s)
-- Generating done (0.1s)
-- Build files have been written to: C:/tmp/libheif/build

Robert@Roberts-PC /c/tmp/libheif/build
$ make
make: *** No targets specified and no makefile found.  Stop.

Robert@Roberts-PC /c/tmp/libheif/build
$ ls -la
total 446
drwxr-xr-x  8 Robert Administratoren   8192 Oct 29 19:58 .
drwxr-xr-x 18 Robert Administratoren   4096 Oct 29 19:57 ..
-rw-r--r--  1 Robert Administratoren  56574 Oct 29 19:58 ALL_BUILD.vcxproj
-rw-r--r--  1 Robert Administratoren    269 Oct 29 19:58 ALL_BUILD.vcxproj.filters
-rw-r--r--  1 Robert Administratoren  33107 Oct 29 19:58 CMakeCache.txt
-rw-r--r--  1 Robert Administratoren  15874 Oct 29 19:58 CMakeDoxyfile.in
-rw-r--r--  1 Robert Administratoren  22081 Oct 29 19:58 CMakeDoxygenDefaults.cmake
drwxr-xr-x 12 Robert Administratoren   4096 Oct 29 19:58 CMakeFiles
-rw-r--r--  1 Robert Administratoren   3540 Oct 29 19:58 CPackConfig.cmake
-rw-r--r--  1 Robert Administratoren   3928 Oct 29 19:58 CPackSourceConfig.cmake
-rw-r--r--  1 Robert Administratoren 114901 Oct 29 19:58 Doxyfile
-rw-r--r--  1 Robert Administratoren  10462 Oct 29 19:58 INSTALL.vcxproj
-rw-r--r--  1 Robert Administratoren    511 Oct 29 19:58 INSTALL.vcxproj.filters
-rw-r--r--  1 Robert Administratoren  10741 Oct 29 19:58 PACKAGE.vcxproj
-rw-r--r--  1 Robert Administratoren    511 Oct 29 19:58 PACKAGE.vcxproj.filters
-rw-r--r--  1 Robert Administratoren  59953 Oct 29 19:58 ZERO_CHECK.vcxproj
-rw-r--r--  1 Robert Administratoren    512 Oct 29 19:58 ZERO_CHECK.vcxproj.filters
-rw-r--r--  1 Robert Administratoren   3480 Oct 29 19:58 cmake_install.cmake
-rw-r--r--  1 Robert Administratoren  59464 Oct 29 19:58 doc_doxygen.vcxproj
-rw-r--r--  1 Robert Administratoren    669 Oct 29 19:58 doc_doxygen.vcxproj.filters
drwxr-xr-x  3 Robert Administratoren   4096 Oct 29 19:58 examples
drwxr-xr-x  3 Robert Administratoren   4096 Oct 29 19:58 gdk-pixbuf
drwxr-xr-x  3 Robert Administratoren   4096 Oct 29 19:58 gnome
drwxr-xr-x  3 Robert Administratoren   4096 Oct 29 19:58 heifio
drwxr-xr-x  4 Robert Administratoren   4096 Oct 29 19:58 libheif
-rw-r--r--  1 Robert Administratoren    335 Oct 29 19:58 libheif.pc
-rw-r--r--  1 Robert Administratoren  11614 Oct 29 19:58 libheif.sln

Robert@Roberts-PC /c/tmp/libheif/build`

This worked on my macbook => so how is the build supposed to work on windows?

Any help would be appreciated.
Thanks in advance.

Greetings
Robert

**Comment by farindk** [comment]
Your cmake seems to be configured to output VisualStudio Project files (vcxproj).
You can set the generator to use on the cmake command line:
  https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html

You probably want something like
`cmake -G "NMake Makefiles"`

I'm closing this because it is not related to libheif. Please read the cmake documentation for further details.
