### ISSUE TITLE
In the encoding result, the offset of iloc is 0 but the display effect is not affected. Why?

### ISSUE THREAD

**Issue by yqbgq** [strukturag/libheif#1368]
![image](https://github.com/user-attachments/assets/c174c4aa-9d17-4395-8da1-63096ddb2e8f)

I would like to ask why the offset in the iloc of my encoding result is 0, which does not affect the display result. 

Thanks!

**Comment by farindk** [comment]
Please attach the file.

**Comment by bradh** [comment]
As @farindk  says, we would need to see the file, but there are at least two possibilities - the dumping is wrong, or there is a `base_offset` value that is not shown.

**Comment by yqbgq** [comment]
Sorry, the cause of the problem is that I do not understand the heif format. In the heif file obtained from a third party, base_offset is incorrectly set to 0 and extend_offset is set to writer_pos. Therefore, offset is not displayed as 0 during software parsing.

Thanks to farindk and bradh for their help.
