### ISSUE TITLE
Missing symbols when building tests on Windows

### ISSUE THREAD

**Issue by kmilos** [strukturag/libheif#1374]
Building 1.19.2 now gives:
```
 FAILED: tests/encode.exe 
  C:\Windows\system32\cmd.exe /C "cd . && D:\M\msys64\ucrt64\bin\g++.exe -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wp,-D__USE_MINGW_ANSI_STDIO=1 -O3 -DNDEBUG  tests/CMakeFiles/encode.dir/encode.cc.obj -o tests\encode.exe -Wl,--out-implib,tests\libencode.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libheif/libheif.dll.a  tests/libtestframework.a  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
  D:/M/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: tests/libtestframework.a(test_utils.cc.obj):test_utils.cc:(.text+0x6b): undefined reference to `__imp_heif_context_get_number_of_top_level_images'
```
[1.19.1 patched for symbol export](https://github.com/msys2/MINGW-packages/commit/144defc6ac63718732d7e1b453d531f02e42667f) was building ok.

I guess one could just turn off building the tests, but looks like Windows CI should be generally improved...

**Comment by farindk** [comment]
That is because of the switch to the new catch2 testing framework.
Does it work when you add this line:
````
diff --git a/tests/CMakeLists.txt b/tests/CMakeLists.txt
index 0dbae17..c69debb 100644
--- a/tests/CMakeLists.txt
+++ b/tests/CMakeLists.txt
@@ -12,6 +12,7 @@ if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "GN
 endif()
 
 add_library(testframework STATIC ${CMAKE_BINARY_DIR}/generated/test-config.cc test_utils.cc catch_amalgamated.cpp)
+target_link_libraries(testframework PRIVATE heif)
 
 macro(add_libheif_test TEST_FILE)
     set(TEST_NAME ${TEST_FILE})
````

**Comment by farindk** [comment]
> but perhaps you really want more formally:

I have the feeling that we have to link `heif` into all targets that use functions from `heif`. Duplicates will be removed by the linker, but if we only link it into the `testframework`, we might get errors like the one because of which you opened this issue.

> Also, maybe have `BUILD_TESTING` off by default?

That is what the cmake presets are for. When building for a release package, use the `release` preset, which has testing switched off.

**Comment by farindk** [comment]
Thanks for the report.
