### ISSUE TITLE
std::mutex in grid.cc outside #if ENABLE_PARALLEL_TILE_DECODING

### ISSUE THREAD

**Issue by jerstlouis** [strukturag/libheif#1377]
@farindk Could these (2) be inside such an `#if` to facilitate building on MinGW-w64 compilers that do not have `std::mutex`? There are some potential solutions to that (https://github.com/meganz/mingw-std-threads or a different MinGW-w64 POSIX g++ package), but that would require a lot more efforts on our end to get that going.

The use of C++17 have made things quite tricky for our cross-platform builds, and this tweak was the last thing standing in the way.

It should be possible to invoke the encoder / decoder from a single thread without any additional threading involved (#635).

Or does this mutex serve to protect global things from concurrency when invoking the encoder/decoder from two separate threads?

Thanks!

**Comment by farindk** [comment]
I've now disabled the mutexes when `ENABLE_PARALLEL_TILE_DECODING` is not enabled.
Thanks for reporting this.
