### ISSUE TITLE
Upgrade PPA build to 1.19.3

### ISSUE THREAD

**Issue by earlbread** [strukturag/libheif#1383]
Hi team,
Could you please add 1.19.3 version to [Ubuntu PPA](https://launchpad.net/~strukturag/+archive/ubuntu/libheif/+packages)?
Currently the latest version is 1.19.1.

Thank you.

**Comment by earlbread** [comment]
@fancycode Thanks for the reply.
I asked because 1.19.3 seems to fix a major issue, but I fully understand it takes time to update the PPA.
Thank you.

**Comment by andrey18106** [comment]
> There is no need to immediately open new issues to update the PPA after a new version has been released. We will update the PPA as soon as possible, but usually this takes a couple of days - depending on the current work load.

@fancycode Hello, is there any timeline when to expect an update for 1.19.5 version? Thank you.

**Comment by fancycode** [comment]
I'm planning to update packages after winter holidays around mid January.

**Comment by fancycode** [comment]
Uploaded, sorry for the delay.
