### ISSUE TITLE
Kvazaar - 10 bit and 4:2:2 and 4:4:4 YUV sampling details

### ISSUE THREAD

**Issue by PetrMinar** [strukturag/libheif#1384]
Just a quick information that might be useful for anyone trying to use kvazaar encoder to write heif files:

- 10 bit support is compile time option for the codec. Single binary cannot produce both 8bit and 10bit h265 bitstream.
- kvazaar only supports 4:2:0 and 4:0:0 yuv samplings. When you try to configure and use the encoder to produce 4:2:2 / 4:4:4, it generates garbage. See [link](https://github.com/ultravideo/kvazaar/issues/418).

Hope this saves some time to anyone trying to make it run.

**Comment by farindk** [comment]
Thank you for the information. The above commit forces the colorspace to 4:2:0 when kvazaar is used.

**Comment by farindk** [comment]
libheif now checks whether the image bit depth matches the bit depth kvazaar was compiled for.
