### ISSUE TITLE
For monochrome image `heif_image_handle_get_preferred_decoding_colorspace` return YCbCr ?

### ISSUE THREAD

**Issue by bigcat88** [strukturag/libheif#1390]
I'm trying the new libheif version 1.19.3 and I noticed that on image with one channel it tells me that Colorspace=0(`YCBCR`) and Chroma=1(`420`)

In version 1.18 - for this image results was: Colorspace=2(`MONOCHROME`), Chroma=0(`MONOCHROME`) (AFAIK)

This is how it should be? If so - then how can I correct determine in version 1.19 that this is a monochrome image without decoding?

Example of test image if needed can be found [here](https://github.com/bigcat88/pillow_heif/blob/master/tests/images/heif/L_8__29x100.heif)

**Comment by bradh** [comment]
The format in the `pixi` box is a single channel, and the `hvcC` box has `chroma_format_idc` of 0 (which is monochrome), so I think it should not be chroma of 4:2:0.

However that is not what I get when using `heif-info` from current master (which is probably pretty close to 1.19.3)

```
MIME type: image/heic
main brand: heic
compatible brands: mif1, heic, miaf

image: 29x100 (id=1), primary
  tiles: 1x1, tile size: 29x100
  colorspace: monochrome
  bit depth: 8
  color profile: no
  alpha channel: no 
  depth channel: no
metadata:
  none
transformations:
  crop: left=0 top=0 right=35 bottom=0
region annotations:
  none
properties:
```

Can you say where you are getting "Colorspace=0(YCBCR) and Chroma=1(420)" from?

**Comment by farindk** [comment]
I also don't see where "4:2:0" is returned. `heif_decode_image()` with `heif_colorspace_unknown` returns monochrome:

![image](https://github.com/user-attachments/assets/c0780eb0-e3e0-4f54-b953-b4017a628f35)

**Comment by bigcat88** [comment]
Sorry, I incorrectly identified the file with which this happens.

It happens with the same file but in [avif](https://github.com/bigcat88/pillow_heif/blob/master/tests/images/heif/L_8__29x100.avif) format

File was created 9 months ago and with libheif 1.18 version it was detected as monochrome...
*Maybe that was the bug of 1.18 version and file in reality is not a monochrome and I should rebuild "avif" files*

**Comment by bradh** [comment]
Indeed that file should be mono from both the `pixi` box and `av1C`.

**Comment by farindk** [comment]
@bradh Right, that function misses the `monochrome` case. I've added it.

This only affected the output of `heif_image_handle_get_preferred_decoding_colorspace()`. The decoding function `heif_decode_image()` correctly returned the monochrome image.

**Comment by bradh** [comment]
Can this issue be closed?

**Comment by bigcat88** [comment]
Yes. Can a release be published with it please when someone has time?

**Comment by farindk** [comment]
Version 1.19.4 has been released.

**Comment by bigcat88** [comment]
thank you
