### ISSUE TITLE
Linux Packages seem to compile and not include plugins

### ISSUE THREAD

**Issue by phazei** [strukturag/libheif#1392]
It seems that some linux distros are compiling with the default options, but then not including any plugins in the plugin directory, which makes them quite a bit more useless.

Maybe `DENABLE_PLUGIN_LOADING=NO` should be a default to prevent this?

**Comment by farindk** [comment]
Maybe we can tell the distributions to use one of the cmake presets when building (for example `release-noplugins`).
In which distribution did you find this situation?

I'm a bit reluctant to change the defaults as there will for sure be people relying on it. Maybe in an upcoming feature release (v1.20.0).

**Comment by phazei** [comment]
https://pkgs.alpinelinux.org/package/v3.20/community/x86_64/libheif

https://packages.debian.org/bookworm/libheif1

I ended up building it from scratch instead.

**Comment by farindk** [comment]
At least for Debian, you find all the plugins in separate packages.

**Comment by farindk** [comment]
And for Alpine, HEIC and AVIF codecs are built-in. Thus, you don't need any plugins.

https://build.alpinelinux.org/buildlogs/build-edge-x86_64/community/libheif/libheif-1.19.2-r0.log
````
...
Compiling 'x265' as built-in backend
Compiling 'libde265' as built-in backend
Not compiling 'dav1d' backend
Compiling 'aomdec' as built-in backend
Compiling 'aomenc' as built-in backend
...
````

Thus, every looks correct the way it is.

**Comment by fancycode** [comment]
> At least for Debian, you find all the plugins in separate packages.

For Bookworm the plugins are in `bookworm-backports`. Regular `bookworm` is on 1.15.1 without plugin support.
