### ISSUE TITLE
Does heif_image_handle_is_premultiplied_alpha function work in 1.19.3(4) version?

### ISSUE THREAD

**Issue by bigcat88** [strukturag/libheif#1394]
Sorry for the late* test, and I haven't gotten to version 1.19.4 yet, but can someone check if the detection works correctly on version 1.19.4 without decoding the image itself, detection does the "premultiplied alpha" present in the image?

[test_premultiplied.heic.zip](https://github.com/user-attachments/files/17819334/test_premultiplied.heic.zip)

```
heif-info test.heic

alpha channel: yes
```

```
heif-info test.heic --dump-boxes

| Box: iref -----
| size: 40   (header size: 12)
| reference with type 'auxl' from ID: 2 to IDs: 1 
| reference with type 'prem' from ID: 1 to IDs: 2 
```

but looking at the `heir-info` sources:

```
    if (has_alpha) {
      premultiplied_alpha = heif_image_handle_is_premultiplied_alpha(handle);
    }

    printf("  alpha channel: %s %s\n", has_alpha ? "yes" : "no",
           premultiplied_alpha ? "(premultiplied)" : "");
```

Thank you for everyone who will have free time to check

**Comment by farindk** [comment]
I hoped that 1.19.4 would be the last patch version...

**Comment by bigcat88** [comment]
_you can delete the 1.19.4 release, rewrite the tag and  do  a re-release. not much time has passed since 1.19.4_

**Comment by farindk** [comment]
I just did a 1.19.5.

I think I need a better test-suite. But no time for that ...

**Comment by fancycode** [comment]
> will we be able to get version 1.19.5 within a week?

For packagers it would be really nice to not have a new release every week :see_no_evil:

**Comment by Lastique** [comment]
> you can delete the 1.19.4 release, rewrite the tag and do a re-release.

Please, do not rewrite tags, ever. People rely on tags (and sometimes - specific commits) to be stable over time.
