### ISSUE TITLE
small heif-enc bug

### ISSUE THREAD

**Issue by pcdion** [strukturag/libheif#1399]
in examples/heif_enc.cc ln 779, there's this line : `std::string input_filename = tile_generator.filename(0, 0);`

yields a build error with C++20: ` error: conversion from 'std::filesystem::__cxx11::path' to non-scalar type 'std::string' {aka 'std::__cxx11::basic_string<char>'} requested1`

Issue resolved using the filesystem string() method: `std::string input_filename = tile_generator.filename(0, 0).string();`

@farindk

**Comment by bradh** [comment]
@pcdion You know you can do PR, right?

**Comment by pcdion** [comment]
https://github.com/strukturag/libheif/pull/1400
