### ISSUE TITLE
error message in C api.

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libheif#14]
We are using libheif in the @ImageMagick project and I was trying to print the message from the `heif_error` struct to give our users a better error message. But it turns out that we cannot use this in the C api because the error class is freed and then `error.message` points to an invalid memory block. 

```C
struct heif_error heif_decode_image(const struct heif_image_handle* in_handle,
                                    struct heif_image** out_img,
                                    heif_colorspace colorspace,
                                    heif_chroma chroma,
                                    const struct heif_decoding_options* options)
{
  std::shared_ptr<HeifPixelImage> img;

  Error err = in_handle->image->decode_image(img,
                                             colorspace,
                                             chroma,
                                             options);
  if (err.error_code != heif_error_Ok) {
    // After the return `err` gets freed and message points to an invalid block of memory.
    return err.error_struct(in_handle->image.get());
  }

  *out_img = new heif_image();
  (*out_img)->image = std::move(img);

  return Error::Ok.error_struct(in_handle->image.get());
}
```

This can be resolved by making a copy of the string before this is copied to the error message but that means we would need to free the error message after each call. There is a comment that the error message will never be null. But I personally don't care about the error message when the message is `Success` and then we would need to free it every time. I don't know what the best solution is for this issue so I will leave the solution up to you.

**Comment by farindk** [comment]
We took care about this. error.message does never point to an invalid memory area. The error message is not stored in the Error object, but in the heif_context or whatever object has caused the error. The buffer stays valid until that main object is destroyed.

Hence, in your example, the error message returned from the C api is valid until the heif_image_handle is destroyed.

**Comment by dlemstra** [comment]
Aah sorry I missed that part. I did not realize the error message comes from the image object and not the err. We free the handle before we try to get the error. Thanks for your explanation
