### ISSUE TITLE
heif-convert support .jpeg extension

### ISSUE THREAD

**Issue by hcconquer** [strukturag/libheif#144]
JPEG format is has extension `.jpg` and `jpeg`, heif-enc support jpeg but heif-convert not.
e.g. `heif-enc input.jpeg -o output.heic` is ok, but `heif-convert output.heic output.heic.jpeg` will cause `Unknown file type in output.heic.jpeg`.

**Comment by farindk** [comment]
Thanks for spotting this. Changed in 71db9e0.
