### ISSUE TITLE
Some HEIC depth channels can't be extracted

### ISSUE THREAD

**Issue by faxx1080** [strukturag/libheif#145]
It seems there may have been a regression between the current version of libheif in the git repo master and in the Ubuntu repositories -- I've been having trouble extracting the depth map of some images using the Ubuntu version, and yet when I compile from tip of master, there's always a failure in color conversion (something to do with the Dijkstra search in ColorConversionPipeline::construct_pipeline). This is done completely differently in the older version.

I attached a sample file.

[bottle-ios.zip](https://github.com/strukturag/libheif/files/3542508/bottle-ios.zip)

**Comment by farindk** [comment]
Thanks for reporting this. I have fixed this in the master branch.
