### ISSUE TITLE
Integer-overflow (8062)

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libheif#15]
The @ImageMagick project is using https://github.com/google/oss-fuzz to find bugs in our own library and in libraries that we use. The fuzzer found an issue and we think this is an issue that should be resolved in the library that we use. This issue is posted under the url https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8062 that is not publicly visible yet but added as a link for future reference. Below are the details of the issue that can be reproduced using the following technique: https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md

Stacktrace:
```
/usr/local/bin/../include/c++/v1/sstream:599:12: runtime error: signed integer overflow: 16 + 9223372036854775792 cannot be represented in type 'long long'
	#0 0x437982 in std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::seekoff(long long, std::__1::ios_base::seekdir, unsigned int) /usr/local/include/c++/v1/sstream:599:12
	#1 0xf9608c in std::__1::basic_istream<char, std::__1::char_traits<char> >::seekg(long long, std::__1::ios_base::seekdir)
	#2 0x9329d4 in heif::Box::parse(heif::BitstreamRange&) libheif/src/box.cc:291:28
	#3 0x934025 in heif::Box::read(heif::BitstreamRange&, std::__1::shared_ptr<heif::Box>*) libheif/src/box.cc:434:20
	#4 0x96d96b in heif::HeifFile::parse_heif_file(heif::BitstreamRange&) libheif/src/heif_file.cc:165:19
	#5 0x971c78 in heif::HeifFile::read_from_memory(void const*, unsigned long) libheif/src/heif_file.cc:81:17
	#6 0x916524 in heif::HeifContext::read_from_memory(void const*, unsigned long) libheif/src/heif_context.cc:361:28
	#7 0x9029b8 in heif_context_read_from_memory libheif/src/heif.cc:107:29
	#8 0x7add39 in ReadHEICImage imagemagick/coders/heic.c:195:9
	#9 0x53fc60 in ReadImage imagemagick/MagickCore/constitute.c:500:13
```

Links:
https://github.com/strukturag/libheif/blob/b56e683d05e60a8efcbf6eddbd6f22672b407659/src/box.cc#L291

Commit: b56e683d05e60a8efcbf6eddbd6f22672b407659
Testcase file: [clusterfuzz-testcase-minimized-ping_heic_fuzzer-5816072648261632.zip](https://github.com/strukturag/libheif/files/1983645/clusterfuzz-testcase-minimized-ping_heic_fuzzer-5816072648261632.zip)

**Comment by farindk** [comment]
fixed in 6d1f9ca
