### ISSUE TITLE
Increase MAX_IMAGE_WIDTH/HEIGHT limit

### ISSUE THREAD

**Issue by cbig6464** [strukturag/libheif#150]
Please increase the `MAX_IMAGE_WIDTH` and `MAX_IMAGE_HEIGHT` limits in `heif_limits.h`. I work with high-resolution scans and libheif refuses to open such images with the message `Memory allocation error: Security limit exceeded: Image size 18000x12000 exceeds the maximum image size 16384x16384`. As a result, software like GIMP and ImageMagick can save such HEIF images with no problem, but nothing can ever view them again.

**Comment by farindk** [comment]
Yes, right. As long as we were mainly reading iPhone camera images, the limit was ok, but now, since HEIF images can be saved by software, we need a larger limit. Or maybe even the possibility to switch it off through the API.

**Comment by Jehan** [comment]
@farindk  I haven't checked/don't remember how this is implemented in the GIMP plug-in, but doesn't libheif has a streaming-type API, which would allow read the file piece by piece (and not all at once from memory or whatnot)? If so, such a hard-coded limit would be useless.
Any serious implementation would just have to use the streaming API to load images (then how they handle the huge image on their side is their business; on GIMP our backend is able to handle bigger-than-memory images).

**Comment by farindk** [comment]
@Jehan libheif is not reading the whole compressed HEIF file into memory, but it does keep the whole decompressed image in memory. Changing this is quite some work. Even if we assume that images are saved as image tiles, the HEIF container does allow all kinds of transformations and compositions to these images. It would be quite hard to do all of them on-the-fly.

**Comment by farindk** [comment]
I have increased the maximum image size to 32768x32768. That is 2 GB for YUV-4:2:0 or 4 GB for RGB32. There is also a new API function `heif_context_set_maximum_image_size_limit()` to increase this limit to a custom size.

**Comment by 800jkm** [comment]
I am still having this exact same issue in spring of 2026 on a similar size of files using libheif (bigger than 16384x16384 but less than 32768x32768).

Have you heard back from @cbig6464 whether the fix worked or not?

I can open a 200 megpixel photo, but a 240 megapixel photo cannot be opened by libheif, no matter what I try to set the security limits to, even if I disable them completely.

**Comment by farindk** [comment]
What is the error message?

I am regularly working with images MUCH larger (e.g., up to 66 Gigapixel: https://github.com/farindk/tiled-image-viewer).

**Comment by 800jkm** [comment]
Thank you so much for the reply! I am at work now, but I will check the message and let you know!

I do remember the threshhold was mentioned as a data size limit, somewhere around 43 memory units, and the image I was working with was about 42 units, so I was barely exceeding the limit. However, my images could not be opened or processed at all by libheif despite trying every possible way to disable or increase that limit. I got a bunch of other error messages when trying those steps, so I will try to report all of that later today.

If I remember right, this happened when I was trying to load an AVIF image saved by Lightroom from a Sony A7R camera (60 megapixels) but rendered with the Super Resolution option (240 megapixels output).

**Comment by 800jkm** [comment]
@farindk Hello, I am back home from work, and this is the error I get:

time ./vips_scale1 JAH04831-PanoL02-3.AVIF 50 aom 
Starting process (PID: 15106) using AOM 12-bit (Unlimited mode: ON)...

Image A: 10376 x 2767 pixels

(process:15106): VIPS-WARNING **: 14:49:40.430: error in tile 0 x 0
heif: Memory allocation error: Security limit exceeded: Memory usage of 4651643913 bytes for image data exceeds the security limit of 4294967296 bytes of total memory usage (6.1000)
heifload: load error




I get the same error no matter what environment variables or other options I use to disable or increase the security limits. Even in C code specifying no limits does not work.

Nothing works that uses libheif, not imagemagick, not heif-dec, nothing.

Note, the input AVIF file is 31127 × 8301 pixels.

The source code of this test program is attached.

[vips_scale1.c](https://github.com/user-attachments/files/26799366/vips_scale1.c)


I can workaround it by doing this:

time avifdec JAH04831-PanoL02-3.AVIF out1.png

time ./vips_scale1 out1.png 50 aom



For any images that are beyond the 4294967296-byte limit.

Which shows it is not a VIPS issue but a libheif issue.

And that workaround also destroys the whole automation that I need to have for the millions of photos I am working with.

Besides being orders of magnitude slower to use PNG files as an intermediate step, even with compressin turned off.

**Comment by farindk** [comment]
>  limit of 4294967296 bytes

this is the default limit. Thus it appears to me that the environment variable (if you set that) is not picked up.
How did you set that? Like this?
````
LIBHEIF_SECURITY_LIMITS=off ./vips_scale ...
````

**Comment by 800jkm** [comment]
Yes, I have tried that before. Then the error just changes to a different one:

heif: Invalid input: No 'ftyp' box (2.102)

**Comment by 800jkm** [comment]
The security limits are already set to unlimited inside the C code, but this is being ignored by libheif.

And setting the environment variable just causes a false error to be reported.

There is not any issue with the input AVIF file. Preview, avifdec, and other tools can read it, just not libheif.

As mentioned, I can work around it by using a different tool to decode the input image to a temp file then scale that temp file to the output files. But the tools that can decode the image (like avifdec) don't have the scaling functionality available in them, as they are single-purpose tools.

Only programs that use libheif have the capability to scale, from what I can find.

So as of now I have to create a temp image that's decoded before scaling, which slows down the processing of images.

My M5 Max computer can only do 100-200K images per day with the temp image method, while it could possibly do a million per day without the temp image bottleneck.

**Comment by 800jkm** [comment]
What does your program do to allow it to use libheif to open up files that are 60 gigapixels?

Are those files HEIF and/or AVIF files like the ones I am having trouble with?

**Comment by farindk** [comment]
> Yes, I have tried that before. Then the error just changes to a different one:
> heif: Invalid input: No 'ftyp' box (2.102)

That does not really make sense to me. Can you tell exactly which libheif version, which libvips version, and attache the image (or send it as email if you don't want to put it public). Then I'll try to reproduce it.

**Comment by 800jkm** [comment]
Yes, it is libvips 8.18.2 and libheif version: 1.21.2 

I am on the latest macOS and using brew.sh to install those.

Here is a link to an example image:

https://securedownload.us/day/JAH04831-PanoL02-3.AVIF

If you can advise any command line method or option to enable libheif to open files like that, it would amazing!

Or if it can only be done within a computer program context, I am attaching a sample computer program that I wrote today to demonstrate some scaling of images using libvips / libheif, and it shows that same error even when I follow the instructions to open the file with security limits turned off ( "unlimited", TRUE ) within the image opening command.

[vips_scale2.c](https://github.com/user-attachments/files/26807603/vips_scale2.c)

You can compile that on macOS if libvips is installed via brew.sh with this command:

```
gcc -O2 -Wall -o vips_scale2 vips_scale2.c `pkg-config vips --cflags --libs` 
```

**Comment by 800jkm** [comment]
On another note, it used to be possible to use svt-av1 within libheif, from what I've been told by brew.sh, but the current release of libheif is no longer compatible.

Is that right?

Or is there anyway that I could still use svt-av1 as an encoder option? My first vips_scale1.c program had code in it that tried to detect and use it, but after being told by brew.sh that libheif no longer supported svt-av1 at all, I removed that code in the second code file.

**Comment by farindk** [comment]
> v3 support is in the current code for next release

It's even for SVT-AV1 v4.1.x

**Comment by 800jkm** [comment]
Thank you so much for your help!

Would you be willing to see if libheif can open the example image that I attached on your machine? And if you needed to use certain settings or certain lines of code to do that, could you help me figure out what they are? I have tried both environment variables as well as options within the C code to remove limits, and nothing works, not with my program, nor with ImageMagick or other image programs.

On macOS at least I cannot open it / load it with anything that uses libheif, not even open source image viewers. I can see it with Preview, the Finder, and with other image libraries, but not with anything that uses libheif.

**Comment by farindk** [comment]
Yes, I can convert it with `heif-dec` without any issues (on Linux):

````
$ ./examples/heif-dec ~/JAH04831-PanoL02-3.AVIF out.jpg
File contains 1 image
decoding image... 100%
Written to out.jpg

$ ./examples/heif-dec ~/JAH04831-PanoL02-3.AVIF out.png
File contains 1 image
decoding image... 100%
Could not decode image: Memory allocation error: Security limit exceeded: Memory usage of 4651643913 bytes for image data exceeds the security limit of 4294967296 bytes of total memory usage

$ LIBHEIF_SECURITY_LIMITS=off ./examples/heif-dec ~/JAH04831-PanoL02-3.AVIF out.png
File contains 1 image
decoding image... 100%
Written to out.png
````

When converting to JPG, the security limit is not exceeded because the 4:2:0 subsampled data does not exceed the limit. Only when converting to RGB for PNG, we hit the limit. But with setting the environment variable, it works.

I guess this has something to do with how you pass the security limits. Or libvips is overwriting it with its own limits.

You can check whether the environment variable is read correctly here:
https://github.com/strukturag/libheif/blob/f20a88baec0f34825cc076b3dfb2578fb2d5728c/libheif/context.cc#L149

And whether the limits are overwritten, when this function is called:
https://github.com/strukturag/libheif/blob/f20a88baec0f34825cc076b3dfb2578fb2d5728c/libheif/context.cc#L207

**Comment by 800jkm** [comment]
Thank you so, so much!

This was exactly how I was hoping it would work, but for me whenever I set that same environment variable LIBHEIF_SECURITY_LIMITS=off it just causes it to throw some other weird errors. 😭

 Like the no ftyp box error that I showed above.

You're on Linux, which likely works a LOT better than the brew.sh version that I am using on macOS.

I am reaching out to brew.sh as well, and hopefully they can help!

**Comment by 800jkm** [comment]
And also, thank you again and again for your help. You are awesome to help a random stranger for no payback to yourself!!

**Comment by 800jkm** [comment]
I've reinstalled libheif and libvips and so on, but I am still having the same security limit issue no matter what I try.

When I repeat the same steps you did, it just changes the error message, but still does not work.

```
time heif-dec JAH04831-PanoL02-3.AVIF out.jpg
File contains 1 image
decoding image... 100%
Written to out.jpg
heif-dec JAH04831-PanoL02-3.AVIF out.jpg  3.72s user 3.79s system 374% cpu 2.002 total
j@mac14 Desktop % time heif-dec JAH04831-PanoL02-3.AVIF out.png
File contains 1 image
decoding image... 100%
Could not decode image: Memory allocation error: Security limit exceeded: Memory usage of 4651643913 bytes for image data exceeds the security limit of 4294967296 bytes of total memory usage
heif-dec JAH04831-PanoL02-3.AVIF out.png  3.37s user 4.03s system 653% cpu 1.133 total
j@mac14 Desktop % LIBHEIF_SECURITY_LIMITS=off  heif-dec JAH04831-PanoL02-3.AVIF out.png  
Could not read HEIF/AVIF file: Invalid input: No 'ftyp' box

```

Thank you for your help, anyway!
