### ISSUE TITLE
Please create a NuGet Packag for C#

### ISSUE THREAD

**Issue by moutasem1989** [strukturag/libheif#152]
it would be so helpful and useful to access all the features of this library through C#. there is nothing out there similar to the features of this library, and the one close are extremely limited.

**Comment by fancycode** [comment]
We don't have experience with NuGet, so this is something we would be happy to accept pull-requests from the community (if changes are required in libheif for the packaging to work).

**Comment by farindk** [comment]
It should be very easy to generate a C# wrapper for libheif using SWIG (http://www.swig.org/).
If you use this to wrap our C++ API, you should get the C# interface automatically.

**Comment by moutasem1989** [comment]
even though my experience with C++ is almost non existing i have tried to educate myself. SWIG was one of my approaches I just did not know how to apply it even though the steps seem to be very basic.
I am also trying to [create a DLL to be invoked from C#](https://github.com/strukturag/libheif/issues/137) but thats another dead end. I have seen many examples but i just feel bad that i feel lost all the time
Maybe someone can help me and use some free time for it ? i promise i will make it worth your while with the app im trying to make :P

**Comment by 0xC0000054** [comment]
I created .NET bindings for libheif, https://github.com/0xC0000054/libheif-sharp.
This library wraps a large portion of the libheif API and makes it usable from C# and other [CLI languages](https://en.wikipedia.org/wiki/List_of_CLI_languages).

The NuGet package is located at https://www.nuget.org/packages/LibHeifSharp.
Examples of how to use the API can be found in the https://github.com/0xC0000054/libheif-sharp-samples repository.

**Comment by bradh** [comment]
I guess this can be closed, since there is a NuGet package available.

**Comment by 0xC0000054** [comment]
Yes.
