### ISSUE TITLE
How to get Cover image from HEIF container.

### ISSUE THREAD

**Issue by cgilles** [strukturag/libheif#160]
Following spec from Nokia in "Images in HEIF Files" section, HEIF is able to store plenty of image versions.

One interesting is the Cover image which can be used to render a reduced size preview on screen.

Currently, libheif can get "Master" and "thumbnail" image. How i can get the "Cover" version ?

Best

Gilles Caulier

**Comment by fancycode** [comment]
According to the standard, the cover image is defined as
```
6.4.3	Cover image
For a collection of images carried as items in a MetaBox, the primary item of the
MetaBox should be displayed when no other information is available on the
preference to display a collection of images.
```

The primary image can be fetched using `heif_context_get_primary_image_handle`:
https://github.com/strukturag/libheif/blob/7c3241a26e8e92b5fe11f81e7f3233628312b3e4/libheif/heif.h#L423
