### ISSUE TITLE
HEIF container and JPEG image

### ISSUE THREAD

**Issue by cgilles** [strukturag/libheif#162]
In main library header, we can see :  

enum heif_compression_format {
  heif_compression_undefined = 0,
  heif_compression_HEVC = 1,
  heif_compression_AVC = 2,
  heif_compression_JPEG = 3
};

So HEIF container can contain a JPEG image. If libjpeg is available, it's planed to pass this library as an external dependency for a delegate plugin to encode and decode JPEG image data ?

Best

Gilles Caulier

**Comment by farindk** [comment]
Currently not. In my view, this is one part of the standard that will probably never be used as I do not see any reason to do that. Maybe you can convince be at the contrary, but at the moment JPEG and AVC is not planned. But there will be AVIF support (already in 'avif' branch).

**Comment by fancycode** [comment]
Closing as per above comment.
