### ISSUE TITLE
error: `Invalid input: No 'meta' box`

### ISSUE THREAD

**Issue by Gabgab2003** [strukturag/libheif#163]
Newest libheif build (today, about 6 hours ago, will rebuild and update this thread)

with imagemagicks convert command (downloaded and built from https://www.imagemagick.org/download/ImageMagick.tar.gz and built with `--with-heic=yes`)

Im getting a "convert: Invalid input: No 'meta' box `index.heic' @ error/heic.c/IsHeifSuccess/136" for the image available [here (dynamicwallpaperclub)](https://dynamicwallpaper.club/wallpaper/qvvk60oi7v). If anyone finds a fix/if anything is wrong with the image itself, that would be cool

**Comment by farindk** [comment]
What a test image... It contains 96 5k images.
With that huge amount of data, it is exceeding the limits we built into libheif to protect against DoS attacks.
If you increase the `MAX_CHILDREN_PER_BOX` and `MAX_ILOC_ITEMS` in `libheif/heif_limits.h`, it loads fine. E.g.:

    static const size_t MAX_CHILDREN_PER_BOX = 10240;
    static const int MAX_ILOC_ITEMS = 10240;

I guess we either have to increase the limits or handle this differently.

**Comment by Gabgab2003** [comment]
Interesting thank you, will rebuild once I get home. I don't think this should get any different treatment as this image may as well be used for a dos attack (when I right click, it takes 30-40 seconds to open the context menu, so all renames are done in wsl). But maybe a notice in the readme would be nice

**Comment by Gabgab2003** [comment]
UPDATE: Works perfectly with the changed values. Will close this now.
