### ISSUE TITLE
set up a fuzzer test for heif encoder

### ISSUE THREAD

**Issue by farindk** [strukturag/libheif#17]
We should also check the encoding in the fuzzer. Fuzzed parameters could be the image size, color format, encoder parameters and algorithmically generated image content.

**Comment by fancycode** [comment]
I started one here:
https://github.com/strukturag/libheif/blob/master/src/encoder-fuzzer.cc

**Comment by farindk** [comment]
updated link:
https://github.com/strukturag/libheif/blob/master/libheif/encoder_fuzzer.cc
