### ISSUE TITLE
heif-thumbnailer generates preview images from the files without any thumbnails incorectly

### ISSUE THREAD

**Issue by 1div0** [strukturag/libheif#174]
Hallo @farindk und @fancycode!

An example of downscaled images in Caja as well as Nautilus in F31.

![HEIF](https://user-images.githubusercontent.com/3098510/68313354-ba6c6280-00b4-11ea-82c2-6a8e23bd4d4b.png)

Everything was compiled from recent source libheif repository version.

Danke.

**Comment by fancycode** [comment]
Could you please provide an example file we could use to reproduce this behaviour?

**Comment by farindk** [comment]
Seems to happen on basically all images...
I can reproduce it.

**Comment by farindk** [comment]
Thanks for reporting this. I should be fixed now.
I have also fixed thumbnail generation of HEIC files with alpha in 2e442f6 (it failed previously with "unknown colorspace conversion").

**Comment by 1div0** [comment]
Wunderbar. Danke schön.
