### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_heif_context_add_generic_metadata"

### ISSUE THREAD

**Issue by Arthur111** [strukturag/libheif#176]
nm -g libheif.a (in .libs) gives 

0000000000000050 T _heif_check_filetype
0000000000006680 T _heif_context_add_XMP_metadata
0000000000006570 T _heif_context_add_exif_metadata
0000000000006790 T _heif_context_add_generic_metadata
00000000000003c0 T _heif_context_alloc

and nm -g libheif.1.dylib (in .libs or /usr/local/lib after make install ) gives 

000000000002cab0 T _heif_check_filetype
00000000000333e0 T _heif_context_add_XMP_metadata
00000000000332c0 T _heif_context_add_exif_metadata
000000000002ce20 T _heif_context_alloc

So _heif_context_add_generic_metadata  is missing in the dynamic lib with macOS.

**Comment by farindk** [comment]
Thanks. The commit above should fix this.
