### ISSUE TITLE
Undefined symbols for architecture x86_64: "_heif_context_add_generic_metadata" #176

### ISSUE THREAD

**Issue by Arthur111** [strukturag/libheif#178]
This error occurred AFTER the commit #176.

nm -g libheif.a (in .libs) gives

0000000000000050 T _heif_check_filetype
0000000000006680 T _heif_context_add_XMP_metadata
0000000000006570 T _heif_context_add_exif_metadata
0000000000006790 T _heif_context_add_generic_metadata
00000000000003c0 T _heif_context_alloc

and nm -g libheif.1.dylib (in .libs or /usr/local/lib after make install ) gives

000000000002cab0 T _heif_check_filetype
00000000000333e0 T _heif_context_add_XMP_metadata
00000000000332c0 T _heif_context_add_exif_metadata
000000000002ce20 T _heif_context_alloc

So _heif_context_add_generic_metadata is missing in the dynamic lib with macOS.

Note :

(You closed the iptc problem i submitted in April and commit the modification , so i tested and i get this error (after running ./configure;make;make install).)

How _heif_context_add_generic_metadata can be in the libheif.a without your commit ?

**Comment by farindk** [comment]
Are you really sure it is not fixed with 24aae3b1f953a6a49bc0ca05c346bfa1e869adef ?
It is pretty obvious that the reason was the missing `LIBHEIF_API` in the function declaration and when I check it on Linux, it is now ok.

**Comment by Arthur111** [comment]
It was already the case before the commit (when it was in the branch iptc) but i waited to be in master to test and close the issue when it was ok like i said. 
But it is not.

git pull
./configure;make;make install
and in /usr/local/lib by nm -g on libheif.a and libheif.1.dylib show _heif_context_add_exif_metadata is missing in libheif.1.dylib and NOT in libheif.a like i showed  above.

The syntax is ok in the project it can find the definition of heif_context_add_exif_metadata  in /usr/local/include/libheif/heif.h

**Comment by farindk** [comment]
Just tried the latest version (1.6.0) on macOS and it is fine for me. `_heif_context_add_generic_metadata` is in both, the `.a` and the `.dylib`.

:libheif-1.6.0 struktur$ nm -g libheif/.libs/libheif.a |grep metadata
                 U __ZN4heif11HeifContext16add_XMP_metadataENSt3__110shared_ptrINS0_5ImageEEEPKvi
                 U __ZN4heif11HeifContext17add_exif_metadataENSt3__110shared_ptrINS0_5ImageEEEPKvi
                 U __ZN4heif11HeifContext20add_generic_metadataENSt3__110shared_ptrINS0_5ImageEEEPKviPKcS8_
00000000000065a0 T _heif_context_add_XMP_metadata
0000000000006490 T _heif_context_add_exif_metadata
00000000000066b0 T _heif_context_add_generic_metadata
0000000000002a80 T _heif_image_handle_get_list_of_metadata_block_IDs
0000000000003000 T _heif_image_handle_get_metadata
0000000000002d50 T _heif_image_handle_get_metadata_content_type
0000000000002ed0 T _heif_image_handle_get_metadata_size
0000000000002bd0 T _heif_image_handle_get_metadata_type
0000000000002940 T _heif_image_handle_get_number_of_metadata_blocks
000000000000da80 T __ZN4heif11HeifContext16add_XMP_metadataENSt3__110shared_ptrINS0_5ImageEEEPKvi
000000000000d560 T __ZN4heif11HeifContext17add_exif_metadataENSt3__110shared_ptrINS0_5ImageEEEPKvi
000000000000d7b0 T __ZN4heif11HeifContext20add_generic_metadataENSt3__110shared_ptrINS0_5ImageEEEPKviPKcS8_

-------------

:libheif-1.6.0 struktur$ nm -g libheif/.libs/libheif.dylib |grep metadata
0000000000031740 T _heif_context_add_XMP_metadata
0000000000031630 T _heif_context_add_exif_metadata
0000000000031850 T _heif_context_add_generic_metadata
000000000002dc20 T _heif_image_handle_get_list_of_metadata_block_IDs
000000000002e1a0 T _heif_image_handle_get_metadata
000000000002def0 T _heif_image_handle_get_metadata_content_type
000000000002e070 T _heif_image_handle_get_metadata_size
000000000002dd70 T _heif_image_handle_get_metadata_type
000000000002dae0 T _heif_image_handle_get_number_of_metadata_blocks

**Comment by Arthur111** [comment]
Probably a version problem :

clang -v

Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

on macOS 10.13.6

**Comment by Arthur111** [comment]
After the last commit 1.6.0, it compile. Linking problem solved.
Finally after 208 days (April 14 2019) iptc metadata is available reading and writing.
