### ISSUE TITLE
README upgrade request: Instructions for installing Imagemagick with libheif support

### ISSUE THREAD

**Issue by feliperaul** [strukturag/libheif#180]
First of all, I want to congratulate all the contributors os this amazing project.

My use case is very simple: I want to allow HEIC files from iPhones to be processed in my Rails app, which uses Imagemagick.

However, installing Imagemagick with libheif support is not being easy.

I found this tutorial (https://medium.com/@eplt/5-minutes-to-install-imagemagick-with-heic-support-on-ubuntu-18-04-digitalocean-fe2d09dcef1), but it envolves compiling from source directly. Isn't there an easier way just using `apt-get install` ? It would help tremendously. 

I checked https://github.com/strukturag/libheif/issues/21, but I couldn't install it with apt-get. 

Would you guys be kind enough to write some quick instructions for some non-experienced-dev-ops person like me? Thanks a lot in advance.

**Comment by bb** [comment]
@feliperaul `apt install libheif-dev`. This will install libheif1 and possibly others you might need. With the -dev packet you'll be able to compile imagemagick (or vips etc.).

**Comment by feliperaul** [comment]
Thanks @bb, I'll give it a try. Will it include libde265 as well?

**Comment by fancycode** [comment]
This is something that should be added to the ImageMagick documentation.

**Comment by bb** [comment]
@feliperaul AFAIK not, try `apt install libde265-dev`. PPA here: https://launchpad.net/~strukturag/+archive/ubuntu/libde265

**Comment by feliperaul** [comment]
For the ones interested, I wrote an Ansible role that installs imagemagick with HEIC support here: https://github.com/cimon-io/ansible-role-imagemagick/issues/5
