### ISSUE TITLE
Possibly incorrect error message with large resolutions

### ISSUE THREAD

**Issue by lgritz** [strukturag/libheif#181]
When attempting to write a 16384 x 16384 resolution image (just to stress test my software), I get the following error from libheif:

    Memory allocation error: Security limit exceeded: Image size 16384x16384 exceeds the maximum image size 16384x16384

You can see in https://github.com/strukturag/libheif/blob/master/libheif/heif_context.cc#L687  : 

        if (width  >= m_maximum_image_width_limit ||
            height >= m_maximum_image_height_limit) {
          std::stringstream sstr;
          sstr << "Image size " << width << "x" << height << " exceeds the maximum image size "
               << m_maximum_image_width_limit << "x" << m_maximum_image_height_limit << "\n";

I would suggest that perhaps those `>=` should be `>` ?  The wording of the error message implies that 16k is ok, as long as not exceeded, but in fact 16k will be rejected.

**Comment by fancycode** [comment]
Good catch, thanks.
