### ISSUE TITLE
gdk-pixbuf loader fails assertion, image not loaded

### ISSUE THREAD

**Issue by marianrh** [strukturag/libheif#182]
Hi,

thanks for developing this library! I'm trying to use it in Ubuntu 19.10 in order to being able to view HEIF photos taken on an iPhone using the default image viewer eog (Eye of GNOME).

However, trying to open a HEIF file in eog fails with the following messages:
```
$ eog myphoto.heic

** (eog:13857): WARNING **: 11:03:03.445: Unsupported feature: Unsupported color conversion

(eog:13857): GdkPixbuf-CRITICAL **: 11:03:03.445: gdk_pixbuf_animation_is_static_image: assertion 'GDK_IS_PIXBUF_ANIMATION (animation)' failed

(eog:13857): GdkPixbuf-CRITICAL **: 11:03:03.445: gdk_pixbuf_animation_get_iter: assertion 'GDK_IS_PIXBUF_ANIMATION (animation)' failed

(eog:13857): GdkPixbuf-CRITICAL **: 11:03:03.445: gdk_pixbuf_animation_iter_get_pixbuf: assertion 'GDK_IS_PIXBUF_ANIMATION_ITER (iter)' failed

** (eog:13857): WARNING **: 11:03:03.611: Unsupported feature: Unsupported color conversion
```
and eog shows `Image loading failed`.

I also tried using gpicview, which also fails:
```
$ gpicview myphoto.heic

Gtk-Message: 11:10:42.146: Failed to load module "gail"
Gtk-Message: 11:10:42.157: Failed to load module "canberra-gtk-module"

** (gpicview:15691): WARNING **: 11:10:42.157: (../atk-adaptor/bridge.c:997):atk_bridge_adaptor_init: runtime check failed: (root)

** (gpicview:15691): WARNING **: 11:10:42.335: Unsupported feature: Unsupported color conversion

** (gpicview:15691): WARNING **: 11:10:42.482: Unsupported feature: Unsupported color conversion
Segmentation fault (core dumped)
```

I'm using Ubuntu's packages:
libheif1 1.5.0-1build1
heif-gdk-pixbuf 1.5.0-1build1
eog 3.34.1-1
gpicview 0.2.5-3

**Comment by fancycode** [comment]
The version of `libheif` included in the official repository is a bit outdated, you could try the latest version from our PPA (https://launchpad.net/~strukturag/+archive/ubuntu/libheif). If this still doesn't solve the problem, please provide an example file we could use to reproduce.

**Comment by marianrh** [comment]
Thanks for the speedy reply :)

I updated to the versions from the PPA:
```
heif-gdk-pixbuf:
  Installed: 1.6.0-1~ppa1~ubuntu19.10.1
libheif1:
  Installed: 1.6.0-1~ppa1~ubuntu19.10.1
```

Now, eog also crashes (without any messages) and gpicview displays some other messages before crashing as well:
```
$ eog 2019-11-15-11-20-260208.heic
Segmentation fault (core dumped)
```
```
$ gpicview 2019-11-15-11-20-260208.heic
Gtk-Message: 11:24:15.971: Failed to load module "gail"
Gtk-Message: 11:24:15.983: Failed to load module "canberra-gtk-module"

** (gpicview:18953): WARNING **: 11:24:15.983: (../atk-adaptor/bridge.c:997):atk_bridge_adaptor_init: runtime check failed: (root)

(gpicview:18953): GdkPixbuf-CRITICAL **: 11:24:16.278: info_cb: assertion 'width > 0 && height > 0' failed
Segmentation fault (core dumped)
```

I'm attaching the example file in a zip archive: [2019-11-15-11-20-260208.zip](https://github.com/strukturag/libheif/files/3851027/2019-11-15-11-20-260208.zip)
The photo was taken on an iPhone X on the current iOS 13.2.2.

**Comment by farindk** [comment]
Converting your supplied picture works fine with `heif-convert`, so it's either a problem in eog/gpicview, or the gdk-pixbuf plugin. I'll check the plugin.

**Comment by maclomhair** [comment]
I can confirm this issue on Arch Linux with libheif 1.6, eog 3.34.1, gdk-pixbuf2 2.40.0...

**Comment by benmccann** [comment]
I was getting the output from [the original report above](https://github.com/strukturag/libheif/issues/182#issue-523380090) on Ubuntu 19.10. However, I upgraded to the latest from the PPA and am now getting:
```
Segmentation fault (core dumped)
```

**Comment by farindk** [comment]
Should be fixed in 46e7bf2d258a7b744abdc463cb045769c8c0a3fa
Please confirm that this solves it for you.

**Comment by Devristo** [comment]
Fixed it for me!

**Comment by marianrh** [comment]
I'd love to test this. I managed to build libheif and now have libheif.so.1.6.1 in /usr/local/lib. However, I don't know how to build and install the gdk-pixbuf loader.

**Comment by benmccann** [comment]
@marianrh 1.6.1 has been released on github, so hopefully it'll be in the PPA before too long. https://github.com/strukturag/libheif/releases

**Comment by marianrh** [comment]
@benmccann Thank you, hope so!

**Comment by Devristo** [comment]
> I'd love to test this. I managed to build libheif and now have libheif.so.1.6.1 in /usr/local/lib. However, I don't know how to build and install the gdk-pixbuf loader.

On Fedora I only had to run this after `sudo make install` to make Gnome's image viewer handle HEIF photos properly:

```
sudo gdk-pixbuf-query-loaders-32 --update-cache
sudo gdk-pixbuf-query-loaders-64 --update-cache
```

**Comment by marianrh** [comment]
> ```
> sudo gdk-pixbuf-query-loaders-32 --update-cache
> sudo gdk-pixbuf-query-loaders-64 --update-cache
> ```

Thanks! On Ubuntu I had to use ` sudo /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders --update-cache`. However, this results in
```
g_module_open() failed for /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-heif.so: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-heif.so: undefined symbol: heif_context_alloc
```
So I guess I'll just wait until the new version is available in the PPA.

**Comment by fancycode** [comment]
@marianrh / @benmccann 1.6.1 is currently building on launchpad and should be available shortly in the PPA:
https://launchpad.net/~strukturag/+archive/ubuntu/libheif

**Comment by marianrh** [comment]
@fancycode @farindk I upgraded to 1.6.1 and eog now displays the test image correctly! Thanks a lot for your work, much appreciated!
Can I do anything to make sure the new version will be picked up in Ubuntu 20.04 next year?

**Comment by fancycode** [comment]
@marianrh We submitted the new version to Debian where it should get updated over the next couple of days. Ubuntu pulls from Debian, so 20.04 should automatically get the new version.

Closing this issue now that the gdk-pixbuf plugin is working again.

**Comment by benmccann** [comment]
Thank you! I can confirm everything is working on Ubuntu now with the latest version from the PPA!
