### ISSUE TITLE
Out of bounds issue when decoding image.

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libheif#184]
We are using this library in the @ImageMagick project and we ran into an issue reported by one of our users. For the decoding of the image we are using the same method as the one that is used in `encoder_jpeg.cc`. This means that we use the following method to calculate the offset to a pixel for the `Cb` channel:

```c
row_u = heif_image_get_plane_readonly(image, heif_channel_Cb,&stride_u);

cb_offset = ((y / 2) * stride_u) + (x / 2);
```

We are running into an out of bounds issue with the image (https://drive.google.com/open?id=1eqKJG5OZfpbqzDtARZEFRBv-wdMsUfjD) from the following issue: https://github.com/dlemstra/Magick.NET/issues/533.

The image has the following dimensions: `5000x10827` and `stride_u` is `2512`. This means that the maximum offset is: `((10827/ 2) * 2512) + (5000 / 2) = 13599956`. But that value is less than the size that is used to create the `plane.allocated_mem` inside `add_plane`. For the `Cb` channel this is calculated with the following values:

```c
// decode_full_grid_image
const int cw = w/chroma_h_subsampling(tile_chroma);
const int ch = h/chroma_v_subsampling(tile_chroma)

// with values:
const int cw = 5000/2; // 2500
const int ch = 10827/2; // 5413

// these values are passed to add_plane with bpp=8
plane.stride = width * bytes_per_pixel;
plane.stride = (plane.stride+alignment-1) & ~(alignment-1);
plane.allocated_mem = new uint8_t[height * plane.stride + alignment-1];

// with values:
plane.stride = 2500 * 1; // 2500
plane.stride = (2500+16-1) & ~(16-1); // 2512
plane.allocated_mem = new uint8_t[5413 * 2512 + 16-1]; // 13597471
```

And because `13597471` is less than `13599957` we are running into an out of bounds issue. We suspect that this is happening because `const int ch` should be rounded up: `10827 / 2.0 = 5413.5` but we are not sure if that is the best way to resolve this issue.

**Comment by farindk** [comment]
Yes, you are right. Thanks for the detailed analysis :-)
I have fixed this in e496fc2

BTW: this also related to the problem of odd image sizes (#191). It seems that several software packages generate odd-sized images, ignoring the problems that arise with it. So we probably have to deal with it.

**Comment by dlemstra** [comment]
Thanks for fixing this. Do you have an estimate when we can expect a new release?

**Comment by farindk** [comment]
Probably still this week. I just went through all the important issues.

**Comment by fancycode** [comment]
Closing now that 1.6.1 has been released.
