### ISSUE TITLE
Only left side of image renders

### ISSUE THREAD

**Issue by benmccann** [strukturag/libheif#188]
I'm running Ubuntu 19.10. Only the left side of the images are rendering as thumbnails in Nemo. [Here's a sample image that doesn't render properly](https://drive.google.com/open?id=1rYtNJj07ooU-a03xK1ONnXWkR1B_iusg).

Please let me know if this is the wrong repo to have filed this issue in. I'm not 100% sure which library is causing this issue.

![Screenshot from 2019-12-08 13-43-22](https://user-images.githubusercontent.com/322311/70396787-dec3a380-19c0-11ea-9e4e-8938e90a12b3.png)

**Comment by farindk** [comment]
This is probably the same issue as the one we have fixed in #174 (libheif version 1.6.0).
I think Ubuntu 19.10 is currently still at 1.5.0.

**Comment by benmccann** [comment]
Thank you. I've upgraded to the latest version from the PPA and it's working now!
