### ISSUE TITLE
Issue installing/packaging libheif

### ISSUE THREAD

**Issue by efleurant** [strukturag/libheif#190]
No rule seems to be set for `make install`

> No rule to make target `install'

What's the best/official way to deploy libheif?

Thanks in advance

**Comment by fancycode** [comment]
How do you create the makefile? We are using autoconf / automake, so a target `install` should be created automatically.

**Comment by efleurant** [comment]
I was using cmake3(-gui), so I guess the Makefile is generated this way. I guess there no `TARGETS` in the source CMakeLists.txt or *.cmake files in the project, so that's why it's not generating make install this way. Would be nice though :wink: 

I guess I'll use the autoconf way then. Thanks

**Comment by fancycode** [comment]
It's working fine with cmake here:
```bash
$ cd libheif
$ mkdir build
$ cd build
$ cmake --version
cmake version 3.5.1
$ cmake ..
-- The C compiler identification is GNU 4.8.4
..
-- Build files have been written to: /path/to/libheif/build
$ make -j8
Scanning dependencies of target heif
...
[100%] Built target heif-enc
$ make install DESTDIR=$(pwd)/dist
[ 43%] Built target heif
...
-- Installing: /path/to/libheif/build/dist/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-heif.so
```

Please reopen with additional information on how to reproduce.
