### ISSUE TITLE
ImageMagick: identify: Unsupported file-type: Unspecified: File does not support the 'heic' brand.

### ISSUE THREAD

**Issue by shanemcquillan** [strukturag/libheif#199]
Referencing this issue from the ImageMagick repo - https://github.com/ImageMagick/ImageMagick/issues/1841

ImageMagick delegates out to libheif to read and write the HEIC image format, and the message in the subject is being returned for the attached file.

I'm receiving the error message "identify: Unsupported file-type: Unspecified: File does not support the 'heic' brand." when running identify with the attached image (attached as archive because Github doesn't seem to allow directly uploading .heic image). This is working without issue with other .heic files:

I'm seeing this on latest install using Homebrew.

[image.heic.zip](https://github.com/ImageMagick/ImageMagick6/files/4131522/image.heic.zip)

Steps to Reproduce
Execute:

identify image.heic
System Configuration
ImageMagick version: ImageMagick 7.0.9-20
Environment (Operating system, version and so on): macOS 10.14.4
Additional information:

**Comment by farindk** [comment]
Thanks for the example image.
This image in fact only includes a `mif1` brand, no `heic` or `heix`.
When accepting also images with only the `mif1` brand, the image loads fine.
I have made this change in the commit above.

However, I am not completely sure this is valid according to the standard. I'd like to check this in depth before including it into `master`.

Which software/hardware was used to generate this image?

**Comment by shanemcquillan** [comment]
Hi Dirk, thank you for looking into this. I'm afraid I'm not sure how the image was produced, I have a large collection of images I'm using for testing purpose and this one was causing some problems. Will be interested to know if this one is standard compliant.

**Comment by shanemcquillan** [comment]
@farindk did you get a chance to check if it's standard compliant to only include an mif1 brand in a .heic image? Is there anything I could do to help here?

**Comment by revk** [comment]
I am getting the same error for HIF files produced by a Canon 1Dx III. 
[AJKL0035.zip](https://github.com/strukturag/libheif/files/4570156/AJKL0035.zip)

**Comment by farindk** [comment]
@shanemcquillan `mif1` brands seem to be ok, but unusual. It means that it is an image file, but does not give any more information about the encoding used.

@revk That was because of the Canon using the 'heix' type. This is included now.

I also merged the change to accept 'mif1' files into 'master' (v1.7.0).

Thanks for the issue report.
