### ISSUE TITLE
Stack-overflow (8136)

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libheif#20]
The @ImageMagick project is using https://github.com/google/oss-fuzz to find bugs in our own library and in libraries that we use. The fuzzer found an issue and we think this is an issue that should be resolved in the library that we use. This issue is posted under the url https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8136 that is not publicly visible yet but added as a link for future reference. Below are the details of the issue that can be reproduced using the following technique: https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md

Stacktrace:
```
==1==ERROR: AddressSanitizer: stack-overflow on address 0x7ffdcfa72ff8 (pc 0x000000db0f88 bp 0x7ffdcfa73010 sp 0x7ffdcfa73000 T0)
--
  | SCARINESS: 10 (stack-overflow)
  | #0 0xdb0f87 in heif::BitstreamRange::read(unsigned long) libheif/src/bitstream.h:65
  | #1 0xdb1055 in heif::BitstreamRange::read(unsigned long) libheif/src/bitstream.h:68:27
  | #2 0xdb1055 in heif::BitstreamRange::read(unsigned long) libheif/src/bitstream.h:68:27
  | #3 0xdb1055 in heif::BitstreamRange::read(unsigned long) libheif/src/bitstream.h:68:27
  | #4 0xdb1055 in heif::BitstreamRange::read(unsigned long) libheif/src/bitstream.h:68:27
  | #5 0xdb1055 in heif::BitstreamRange::read(unsigned long) libheif/src/bitstream.h:68:27
  | #6 0xdb1055 in heif::BitstreamRange::read(unsigned long) libheif/src/bitstream.h:68:27
  | #7 0xdb1055 in heif::BitstreamRange::read(unsigned long) libheif/src/bitstream.h:68:27
  | #8 0xdb1055 in heif::BitstreamRange::read(unsigned long) libheif/src/bitstream.h:68:27
```

Links:
https://github.com/strukturag/libheif/blob/0a0db99176355c51a7785a7a6442baacac65f854/src/bitstream.h#L65
https://github.com/strukturag/libheif/blob/0a0db99176355c51a7785a7a6442baacac65f854/src/bitstream.h#L68

Commit: 0a0db99176355c51a7785a7a6442baacac65f854
Testcase file: [clusterfuzz-testcase-minimized-ping_heic_fuzzer-4721040704929792.zip](https://github.com/strukturag/libheif/files/1998519/clusterfuzz-testcase-minimized-ping_heic_fuzzer-4721040704929792.zip)

**Comment by farindk** [comment]
fixed in a53a44e
