### ISSUE TITLE
Windows binaries / Windows build process

### ISSUE THREAD

**Issue by VanKurt** [strukturag/libheif#200]
Where can I find the official binaries for this project? Is there also a Windows build?

If no binaries are available:

- I already tried to compile the library myself (using VS2017 and nmake), but without success. Could you provide instructions how to do the build?
- Would it be possible to add prebuilt binaries for the major platforms (Windows, Linux, MacOS) in future releases?

**Comment by masx200** [comment]
https://github.com/pphh77/libheif-Windowsbinary

**Comment by coooooooorey** [comment]
I tried several times to build libheif with VS2017 and failed as well. 
I kept getting the error   
> Unsupported feature: Unsupported codec.

It would be great if there is an instruction to build it on Windows.

**Comment by 06needhamt** [comment]
This really needs to be fixed I hav e several projects which would benefit from this library but it seems it is impossible to build a fully featured version on Windows as the external dependencies are missing from CMake.

**Comment by pke** [comment]
> [pphh77/libheif-Windowsbinary](https://github.com/pphh77/libheif-Windowsbinary)

This is not a static or dynamic lib but rather the compiled versions of the tools to thumbnail or convert files.

I think whats needed are a bunch of VS solution files to build static and dynamic libs from this code.

**Comment by 06needhamt** [comment]
@pke That's exactly right!

**Comment by pphh77** [comment]
@06needhamt [libheif-1.6.2-msvc2019-win64](https://github.com/pphh77/libheif-Windowsbinary/releases/download/v1.6.2/libheif-1.6.2-msvc2019-win64.7z)

**Comment by pke** [comment]
@pphh77 do you have the VS project files for that?
Also why is the DLL 17 MB big? What is in this beast? The H256 decoder?
With the project files we could compile a much smaller version without the encoder.
Thanks!

**Comment by konsnos** [comment]
Although, I've had success building libheif dll for windows, it didn't help much as the code `heif_context_get_encoder_for_format` returns `heif_error_Unsupported_filetype`.

I suspect that the plug ins required for the encoder are not available for Windows. It would be nice if it was supported.

**Comment by mcychan** [comment]
Build successfully in Visual Studio 2019 using CMake.
[(https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019)]
Add x86-Release and x64-Release, then save to CMake.json.
heif.dll just around 651KB and 758KB.

**Comment by mcychan** [comment]
heif_error_Unsupported_feature
Unsupported feature: Unsupported codec
[CMakeLists.txt](https://github.com/strukturag/libheif/files/4795887/CMakeLists.txt)

**Comment by mcychan** [comment]
Aborted using CMake!!
Success in linking decoder only, anyone could help me to link with the x265 encoder?
https://github.com/mcychan/libheif/blob/master/libheif/libheif.vcxproj

**Comment by mcychan** [comment]
CMake with msvc for libheif 1.62 or above.
Extract from the following zip file into inner libheif folder.
[libheif_msvc.zip](https://github.com/strukturag/libheif/files/4817508/libheif_msvc.zip)

**Comment by farindk** [comment]
Libheif is now included in [Vcpkg](https://github.com/Microsoft/vcpkg/). That might be the easiest way to use it on Windows.

**Comment by mcychan** [comment]
Where is the official source or lib for aom, rav1e, dav1d?

**Comment by silverbacknet** [comment]
Aside from aom being primarily hosted at https://aomedia.googlesource.com/aom/ you can just type those names in and their official repositories are the first results.

**Comment by mcychan** [comment]
Resolved [https://github.com/AOMediaCodec/libavif](https://github.com/AOMediaCodec/libavif)
Thanks.

**Comment by EddyParkinsonAllTraders** [comment]
@farindk 
>Libheif is now included in [Vcpkg](https://github.com/Microsoft/vcpkg/).

Looks to install ok.   But how to run it?  
I wanted to use this exe  https://github.com/MaestroError/heif-converter-image/tree/maestro/bin
but looks like the config is not compatible. 
https://github.com/MaestroError/heif-converter-image/blob/maestro/install-libheif-windows.bat



```
Total install time: 4.3 min
libheif provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(libheif CONFIG REQUIRED)
  target_link_libraries(main PRIVATE heif)

libheif provides pkg-config modules:

  # HEIF image codec.
  libheif
  
```

**Comment by bradh** [comment]
> Looks to install ok. But how to run it?
> I wanted to use this exe https://github.com/MaestroError/heif-converter-image/tree/maestro/bin
> but looks like the config is not compatible.
> https://github.com/MaestroError/heif-converter-image/blob/maestro/install-libheif-windows.bat

Perhaps you could ask at that project, rather than on a closed issue?
