### ISSUE TITLE
Usupported feature: Unsupported codec when compiling with CMake

### ISSUE THREAD

**Issue by amyspark** [strukturag/libheif#208]
Hey,
I'm experiencing the same issue as #90 when using CMake 3.16.4 to compile the examples. I've tried:
- MinGW 7.3.0 on Windows 10 1809, building with custom compiled libjpeg-turbo, libde265 and x265
- GCC 9.2.1 on Manjaro, building with system libraries and with custom compiled deps

In Linux, when I use the `./configure` script everything works OK (even with the custom compiled dependencies), so I believe there is something missing from the CMake toolchain.

**Comment by 06needhamt** [comment]
I am also experiencing this issue and therefore I can’t use the library to decode photos from iOS devices on windows. Is there any ETA for a fix
