### ISSUE TITLE
install libheif with apt-get

### ISSUE THREAD

**Issue by ddor254** [strukturag/libheif#21]
i have ubuntu 16.04 , can i install libheif  with apt-get instead of cloning this git repository and run `./configure`, `make` and `make install` ?

**Comment by fancycode** [comment]
Yes, you can use our PPA to install using `apt-get`:
https://launchpad.net/~strukturag/+archive/ubuntu/libheif

**Comment by feliperaul** [comment]
@fancycode Even tough I ran `sudo add-apt-repository ppa:strukturag/libheif` successfully, `sudo apt-get install libheif` return `E: Unable to locate package libheif`

**Comment by bb** [comment]
@feliperaul `apt install libheif-dev`. This will install libheif1 and possibly others you might need. With the -dev packet you'll be able to compile imagemagick (or vips etc.).
