### ISSUE TITLE
What is the future of AVIF support in libheif?

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#217]
libheif project has "_experimental code for an AV1 plugin (for AVIF format support) in the 'avif' branch._"

Is there any plan to include the AVIF support in the main branch so it will be equally supported as HEIC?

Many graphics applications are supporting HEIC via libheif because it is available in distributions. Those applications wish to support AVIF too.

It would be very convenient for those apps to support AVIF via distro-installed libheif.

The app makers need to know **if or when** the AVIF support will be available in libheif releases. If the AVIF is not going to be fully supported by libheif, it would be good to tell the app makers not to wait for libheif and choose some other library for AVIF support.

The answer is needed for http://www.imagemagick.org/discourse-server/viewtopic.php?p=172532&sid=06d02192af870c90be1dc3ce2902b146#p172532 but there are similar questions in other projects too.

**Comment by farindk** [comment]
I'm working on AVIF support this week. It should be possible to have it in master at the end of the week. I just got the AVIF encoder working.

First version will be using libaom since there are Debian packages for it. Shouldn't be too much work to also add dav1d and rav1e as codecs, but since there don't seem to be any pre-built packages for them, packaging will be more difficult with them.

**Comment by novomesk** [comment]
Thank you!

**Comment by 06needhamt** [comment]
Would it not be easier / better to use. https://github.com/AOMediaCodec/libavif as it seems to consolidate all the decoders and encoders in one library?

**Comment by farindk** [comment]
AVIF support is now in libheif master. Decoding should need no code change at all. For encoding, one can choose between HEIF/AVIF with an encoder parameter. All the API stays the same.
If I don't see any issues in the coming days, I'll tag a release.

Will also try to add dav1d and rav1e as optional plugins.
