### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by DomT4** [strukturag/libheif#22]
Apologies, asking for a release/asking for information on when the next release is likely to be always feels like a big of a nag.

Just wondering if it'd be possible to get an estimate on that because the current 1.1.0 release doesn't compile on macOS. Has already been fixed in master with https://github.com/strukturag/libheif/commit/001a93c2, https://github.com/strukturag/libheif/commit/7ac92eb0 & https://github.com/strukturag/libheif/commit/a237e50a. As far as I'm aware those are the only clang/macOS issues present currently; the current master branch here builds fine.

**Comment by farindk** [comment]
I'm looking at the remaining issues and preparing a new release this week.

**Comment by DomT4** [comment]
Great! Thanks for the update.

**Comment by dreampiggy** [comment]
@DomT4 Current latest libheif v1.1.0 & libde265 v1.0.3 seems can succesfully be compiled on macOS & iOS & tvOS.

However, I only compile the static/dynamic library but not the example project. Maybe this is the issue.

**Comment by DomT4** [comment]
@dreampiggy Yeah the example executables are the point of failure with the existing releases, but I think from a packaging standpoint those examples are worthwhile enough to users to not omit.

**Comment by DomT4** [comment]
New release builds without issue, thanks!
