### ISSUE TITLE
Get the metaInfo & imageSize without reading the whole file to memory

### ISSUE THREAD

**Issue by coooooooorey** [strukturag/libheif#224]
Currently, to get meta info and image size, we have to read the whole file. This is not the efficient way in some cases.

Does  heif_reading_options designed to avoid this situation?
How to use this parameter?

**Comment by farindk** [comment]
Actually, the version in the current `master` branch does exactly this. It only requests those parts of the file that are needed.

**Comment by coooooooorey** [comment]
yeah. I realized that. sorry.

Thank you.
