### ISSUE TITLE
heif_context_get_encoder_for_format failed

### ISSUE THREAD

**Issue by diricse** [strukturag/libheif#225]
heif_error err=heif_context_get_encoder_for_format(context, heif_compression_HEVC, &encoder);
qDebug()<<"heif_context_get_encoder_for_format() err:"<<err.message;//this err.message:Success 
err.code :heif_error_Unsupported_filetype (3)

why?

my all codes:

int ret=-1;
    QByteArray rgba;
    int w=0;
    int h=0;
    int y_stride=0;
    heif_image *image=nullptr;
    heif_encoder* encoder = nullptr;
    heif_context *context=heif_context_alloc();
    if(context){
        heif_error err=heif_context_get_encoder_for_format(context, heif_compression_HEVC, &encoder);
        qDebug()<<"heif_context_get_encoder_for_format() err:"<<err.message;
        if(err.code==0)
        {
            QBmpImage::ImageToRGBA(qImage,rgba,w,h);
            heif_image_create(w,h,heif_colorspace_RGB,heif_chroma_interleaved_RGBA,&image);
            if(image){
                heif_image_add_plane(image, heif_channel_Y, w,h, 32);//RGBA格式
                uint8_t* py = heif_image_get_plane(image, heif_channel_Y, &y_stride);
                //复制图片数据到py
                memcpy(py,rgba.constData(),rgba.size());
                if(lossless){
                    heif_encoder_set_lossless(encoder, true);
                }
                else{
                    heif_encoder_set_lossy_quality(encoder, qa);
                    heif_encoder_set_lossless(encoder, false);
                }
                struct heif_encoding_options* options = heif_encoding_options_alloc();
                if(options){
                    options->save_alpha_channel =1;
                    struct heif_image_handle* handle=nullptr;
                    if(handle){
                        heif_context_encode_image(context,
                                                  image,
                                                  encoder,
                                                  options,
                                                  &handle);
                        ret=heif_image_handle_get_raw_color_profile_size(handle);
                        QByteArray enData(ret,0);
                        heif_image_handle_get_raw_color_profile(handle,enData.data());
                        heifData=enData;
                        heif_image_handle_release(handle);
                    }
                    else{
                        ret=-6;
                    }
                    heif_encoding_options_free(options);
                }
                else{
                    ret=-5;
                }
                heif_image_release(image);
                image=nullptr;
            }
            else{
                ret=-4;
            }
            heif_encoder_release(encoder);
        }
        else{
            ret=-2;
        }
        heif_context_free(context);
    }
    return  ret;

**Comment by silverbacknet** [comment]
You need x265 to encode HEIF. It's not being found on your system, so that needs to be fixed first.

**Comment by diricse** [comment]
3ks
