### ISSUE TITLE
Cannot get data from image, crash ( heif_image_get_plane return NULL)

### ISSUE THREAD

**Issue by Arthur111** [strukturag/libheif#228]
Hello,

I updated recently and a program who work without problem crash now.

I cannot get the data from the image. 

        err = heif_decode_image(handle, &img, heif_colorspace_undefined, heif_chroma_undefined, NULL);

        unsigned char *data = heif_image_get_plane(img, heif_channel_Y, &stride);

data is NULL

This works without problem until the update.
I restore some weekly backup of .dylib and its after the 10th of May it no longer work.
Before that date its ok.

Thank you

**Comment by farindk** [comment]
You specify the colorspace as 'undefined', but it seems you are implicitly assuming that the returned colorspace is YCbCr. However, this can also be RGB if you don't specify anything.
Probably you should specify `colorspace_YCbCr` explicitly when decoding the image.

**Comment by Arthur111** [comment]
Yes i use undefined because i want the original colorspace,  from lib.h : 

// If colorspace or chroma is set to heif_colorspace_undefined or heif_chroma_undefined,
// respectively, the original colorspace is taken.

And i don't have any error.

If i put colorspace_YCbCr i get the error : 

Code = heif_error_Unsupported_feature
subcode = heif_suberror_Unsupported_color_conversion

i test before the update and after with the same picture and the same program.

**Comment by Arthur111** [comment]
Not knowing which commit cause this bug , i go back to release [1.6.2](https://github.com/strukturag/libheif/releases/tag/v1.6.2) .

Everything is fine now and when this bug will be fixed i 'll update.

**Comment by farindk** [comment]
It is not a bug. The internal color-space used just changed from YCbCr to RGB.
Using YCbCr with downsamples chroma resulted in a lot of problems (e.g. rotating images with odd sizes), so that the default output format is now RGB. This probably won't change.

**Comment by Arthur111** [comment]
Its not a bug but this change cause a crash. (data is NULL)

So what values i have to put for colorspace, chroma and channel not knowing them ? The data i work with must be lossless.

err = heif_decode_image(handle, &img, x, y, NULL);

unsigned char *data = heif_image_get_plane(img, z, &stride);

x, y, z ?

to replace heif_colorspace_undefined , heif_chroma_undefined , heif_channel_Y who worked well.

Thank you

**Comment by farindk** [comment]
To come close to your old behaviour, use
heif_colorspace_YCbCr, heif_chroma_420, then get heif_channel_Y, Cb, and Cr

**Comment by Arthur111** [comment]
If put heif_colorspace_YCbCr, heif_chroma_420 and get data from heif_channel_Y before the update it works.

But if i put these values with the latest commit it does not work.

The data i get after i modified the image are not the same data i get when i read this new image.

**Comment by Arthur111** [comment]
If i take this picture (recently posted) :  https://www.me.uk/AJKL0637.HIF , rename it in .heic the data from heif_image_get_plane_readonly is NULL (with heif_decode_image(handle, &img, heif_colorspace_undefined, heif_chroma_undefined, NULL); )

But if i open this same picture in Apple preview , export it in heic format and decode it works ( I get the data)

**Comment by farindk** [comment]
Tested current version 1cc07c43c125d6ace0118fd6821bf64813b25e9d (will become v1.9.0) with your image AJKL0637.HIF. Works fine with heif-convert.

**Comment by ryusaeba** [comment]
@Arthur111  
I'm using pyheif and config the colorspace and chroma as below shows.
        colorspace = _constants.heif_colorspace_undefined
        chroma = _constants.heif_chroma_undefined
Then I hit the same issue as yours, the return data is NULL. 
As you mentioned, 1.6.2 version works well. My question is how to make pyheif to use 1.6.2?
As the pyheif page shows, Python 3.6+ interface to libheif library using CFFI.

**Comment by ryusaeba** [comment]
@Arthur111 
If it is possible, coud you share the piece of your code (directly reading yuv420 back) with me?

**Comment by Arthur111** [comment]
> My question is how to make pyheif to use 1.6.2?

I don't know, i used c to do it, and i was stuck with this version. This means i could not upgrade.
As the admin of this project did nothing to allow compatibility with 1.6.2 (watermarking/steganography was impossible after 1.6.2) i stop using heif for the project i had to do. The code i made was near the same as the example in this project.

**Comment by ryusaeba** [comment]
@Arthur111 
Thanks for these useful information. After looking into the c implementation and sticking with the version you mentioned, I am able to do the similat thing as yours. 
Just curious: Which one project you are using now? I afraid I will suffer from similat issue as yours.

**Comment by Arthur111** [comment]
I just made a project about watermarking (decode image, read raw bytes, change it, writes raw bytes, encode) for openexr and heic format. As admins of these apis did nothing to help, so I gave up on these formats. Hope this help. have a nice day.

**Comment by Arthur111** [comment]
I just made a project about watermarking (decode image, read raw bytes, change it, writes raw bytes, encode) for openexr and heic format. As admins of these apis did nothing to help, so I gave up on these formats. Hope this help. have a nice day.
