### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libheif#23]
We got an issue reported for ImageMagick (https://github.com/ImageMagick/ImageMagick/issues/1131) about a crash when reading an heic image multithreaded. Is this a bug in the library or should we make sure that heic images are always read in a single thread?

**Comment by farindk** [comment]
This is a race condition when calling de265_init() multithreaded in quick succession.
I have fixed this in libde265, commit d4ee91618ce7e1eb705b1b7979a36daf11edb608
