### ISSUE TITLE
Can't link Imagemagick 7.0.10-16 with libheif 1.7.0

### ISSUE THREAD

**Issue by dmilith** [strukturag/libheif#230]
http://s.verknowsys.com/9474398ad0b03b65813caa04e951b0c0.png

Looks like not exported symbol?

**Comment by silverbacknet** [comment]
Looks like a typo on ImageMagick's side: It should be `heif_compression_AV1`. I've filed ImageMagick/ImageMagick#1432 on their repo.

**Comment by fancycode** [comment]
Thanks, closing.
