### ISSUE TITLE
1.7.0/Master Fails HEIC Self-Test on Centos 6/7 + MacOS 10.15.4: Unsupported RGB chroma format: 3

### ISSUE THREAD

**Issue by diegomontoya** [strukturag/libheif#231]
Go self test failed on both Centos 6 + 7 and MacOS 10.15.4 via brew.  Mac is using brew 1.7.0 of libheif. 

libde265 is also master/latest version.

Unsupported RGB chroma format: 3

`
Making test in go
make[1]: Entering directory '/root/libheif/go'
ln -sf /root/libheif/go /root/libheif/go/src
GOPATH=/root/libheif/go PKG_CONFIG_PATH=/root/libheif CGO_CFLAGS="-I/root/libheif" CGO_LDFLAGS="-L/root/libheif/libheif/.libs" LD_LIBRARY_PATH=/root/libheif/libheif/.libs /root/go-master/bin/go test -v heif
=== RUN   TestGetVersion
--- PASS: TestGetVersion (0.00s)
=== RUN   TestReadFromFile
--- PASS: TestReadFromFile (0.18s)
=== RUN   TestReadFromMemory
--- PASS: TestReadFromMemory (0.18s)
=== RUN   TestReadImage
    TestReadImage: heif_test.go:145: Could not load image from ../../examples/example.heic: Unsupported RGB chroma format: 3
--- FAIL: TestReadImage (0.18s)
FAIL
FAIL    heif    0.552s
FAIL
make[1]: *** [Makefile:489: test-go] Error 1
make[1]: Leaving directory '/root/libheif/go'
make: *** [Makefile:509: test-recursive] Error 1
`

GCC version 8.3.1 (Centos 6)
GCC version 4.8.5 20150623 (Red Hat 4.8.5-39)  (Centos 7)

`
pkg-config libheif --modversion
1.7.0
pkg-config libde265 --modversion
1.0.5
`

We can also confirm that any library that depends on libheif will fail at HEIC  image file decoding if using any thing newer than version 1.6.2 of the libheif lib.

**Comment by jsmolic** [comment]
I can confirm that tests fail on Gentoo Linux as well on 1.7.0. version. 
See https://github.com/gentoo/gentoo/pull/17122 for reference.

**Comment by jsmolic** [comment]
#285 and #286 resolved the issues

**Comment by fancycode** [comment]
This has been fixed with the mentioned PRs, closing.
