### ISSUE TITLE
cmakelists.txt sets compile definition AOM=1 instead of HAVE_AOM=1

### ISSUE THREAD

**Issue by ikirill** [strukturag/libheif#233]
In cmakelists.txt it sets AOM=1:
https://github.com/strukturag/libheif/blob/82eccc96fc119351a0303357dd281707400cd376/libheif/CMakeLists.txt#L96

In the code it checks for HAVE_AOM=1:
https://github.com/strukturag/libheif/blob/1efe4ad59ab77b3f016425ac2b550768e50dc418/libheif/heif_plugin_registry.cc#L79

A typo?

**Comment by farindk** [comment]
Thanks. Was fixed in 3357f013062a57d5c0e9a09ba094f8df9cf1c780
