### ISSUE TITLE
AVIF with crop operation - Invalid clean-aperture specification

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#236]
Hello,
I get following errors when opening AVIF files:
![invalid_clean_aperture_specification](https://user-images.githubusercontent.com/52529860/84896484-5414dd00-b0a4-11ea-8a2a-675b65324cee.png)
![invalid_clean_aperture_specification2](https://user-images.githubusercontent.com/52529860/84896486-54ad7380-b0a4-11ea-8bd4-004f99b375c7.png)
Can you investigate whether it is a bug in libheif or are these files incorrect please? libavif opens them fine.
https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Microsoft/Chimera_8bit_cropped_480x256.avif
https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.mirror-vertical.rotate270.crop.avif
Regards,
Daniel

**Comment by farindk** [comment]
Thanks. There was a rounding issue bug. It should be fixed now with the above commit.
