### ISSUE TITLE
Feature request: YUV444 and YUV422 support

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#237]
Hello,
I have problem opening this file:
https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Microsoft/Mexico_YUV444.avif
```
heif-info Mexico_YUV444.avif 
MIME type: unknown
image: 960x540 (id=1), primary
  color profile: nclx
  alpha channel: no
  depth channel: no
```
```
heif-convert Mexico_YUV444.avif a.png
File contains 1 images
Could not decode HEIF image: 0: Unsupported feature: Unsupported color conversion
```
Regards,
Daniel

**Comment by silverbacknet** [comment]
Yes, see #40, YUV444 is not yet supported. (Though YUV422 has been added since.) If you want to make this a feature request, you can edit the title.

**Comment by novomesk** [comment]
Thanks for confirmation regarding the YUV444. Sorry, I didn't know about issue 40.

I created an AVIF with YUV422 and I have got different kind of error message:
```
heif-convert 422.avif z.png
File contains 1 images
Could not decode HEIF image: 0: Decoder plugin generated an error: Unsupported image type
```
I definitively want to make this a feature request because AVIF files created via libavif software use 444 and 422 formats.
avifenc utility (from libavif package) use default=444 for output format.
My qt-avif-image-plugin use 422 for high quality and 444 for best quality.
My gimp-avif-plugin (libavif based) allows user to select between 420,422,444 and I would like that libheif based software would be capable to load the files in the future too.

**Comment by farindk** [comment]
I'm adding this today.

**Comment by farindk** [comment]
YUV->RGB should work now for all chroma formats and both 8bit and HDR.

**Comment by novomesk** [comment]
Thanks for the YUV444 - it works for me. Impressive.
But the following AVIF with YUV422 doesn't yet.
[test_422.zip](https://github.com/strukturag/libheif/files/4799245/test_422.zip)

**Comment by farindk** [comment]
Right. Thanks for the 4:2:2. Fortunately, it was only a small thing. Works now.

**Comment by silverbacknet** [comment]
Awesome! This makes it much more useful for me!
