### ISSUE TITLE
Pyheif version 0.4 is not loading HEIC images

### ISSUE THREAD

**Issue by AhmedAldahshoury** [strukturag/libheif#241]
The latest pyheif version (0.4) is not loading the images. It always get an "unsupported codec" error. When I uninstalled the latest version and installed an older version (0.3.3), it worked good.

**Comment by diegomontoya** [comment]
Most likely duplicate issue of https://github.com/strukturag/libheif/issues/231. Libheif 1.7 upgrade broke heif image decoding and fails self test.

**Comment by fancycode** [comment]
Please report upstream to pyheif. Should be fixed if pyheif is compiled against the latest version of libheif.
