### ISSUE TITLE
Manjaro KDE

### ISSUE THREAD

**Issue by kalvish21** [strukturag/libheif#251]
I'm using Manjaro KDE latest and i'm getting all HEIC images from iPhone to appear like the sample image below. I'm using the latest release of libheif (1.7.0). I should add that I did NOT have this issue with prior versions of libheif on the same desktop.

![Screenshot_20200627_121231](https://user-images.githubusercontent.com/2179704/85930234-93df7f80-b86f-11ea-8760-aaa234623860.png)

**Comment by farindk** [comment]
Which image viewer program is that?

**Comment by kalvish21** [comment]
Gnome Image Viewer.

**Comment by farindk** [comment]
Duplicate of #265. Has been fixed in latest 'develop' branch.

**Comment by kalvish21** [comment]
How can I get that version on Manjaro KDE? Is it possible?
