### ISSUE TITLE
Unsupported image type

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#257]
Hello,
I am trying to open [fox.profile2.12bpc.yuv422.odd-width.odd-height.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/fox.profile2.12bpc.yuv422.odd-width.odd-height.avif) test file.
heif-convert return **Could not decode image: 0: Decoder plugin generated an error: Unsupported image type**
Image is 1203x799, 12bit, YUV422, Limited range.

I don't know why this one doesn't work. Other 12bit AVIF samples work for me.

**Comment by farindk** [comment]
Thanks. Fixed in 491c800.
