### ISSUE TITLE
Strange Colorspace Problem

### ISSUE THREAD

**Issue by GrandArth** [strukturag/libheif#260]
This issue was originally posted there: https://github.com/libvips/libvips/issues/1742

> 
> 
> Originally, i use ffmpeg to encode jpeg/png files to hevc frames and then box them with mp4box from GPAC project.
> I have a collection of high resolution photos in heic format, which would be very power consuming on mobile device, so i thought i would use `vips resize` to reduce the resolution.
> 
> However, the resulted images are somehow darken than the original heic image from ffmpeg.
> 
> I ran a few tests with this original png.
> ![o](https://user-images.githubusercontent.com/30680793/88445543-f79c9e80-ce55-11ea-908b-c19ffc5e1284.png)
> 
> And this is the ffmpeg version heic "fffo.heic"(screen shot):
> ![图片](https://user-images.githubusercontent.com/30680793/88445553-0e42f580-ce56-11ea-8711-58055daf5800.png)
> 
> When i use `vips heifsave fffo.heic fffo2.heic` the resulted fffo2.heic is darkened.
> ![图片](https://user-images.githubusercontent.com/30680793/88445595-3df1fd80-ce56-11ea-8edd-fb2cee9d1be7.png)
> 
> However, if i run the above operation with heic converted from vips (filename vfo.heic), everything works fine.
> ![图片](https://user-images.githubusercontent.com/30680793/88445631-64b03400-ce56-11ea-9c19-c4241b6b510f.png)
> 
> I use `magick identify` on heics converted from png (with ffmpeg and vips) and the output show no difference.
> 
> ```
> PS D:\IMAGES\SX\2020-07> magick identify fffo.heic
> fffo.heic HEIC 358x476 358x476+0+0 8-bit YCbCr 0.000u 0:00.000
> PS D:\IMAGES\SX\2020-07> magick identify vfo.heic
> vfo.heic HEIC 358x476 358x476+0+0 8-bit YCbCr 0.000u 0:00.000
> PS D:\IMAGES\SX\2020-07>
> ```
> 
> I upload my images:
> [2020-07.zip](https://github.com/libvips/libvips/files/4974726/2020-07.zip)
> fffo.heic `ffmpeg converted from original png`
> fffo2.heic `vips heifsave on the ffmpeg version heic`
> o.png `origin png file`
> vfo.heic `vips heifsave on the original png`
> vfo2.heic `vips heifsave on the vfo.heic`
> 
> BTW, the command i use to convert files to heic.
> 
> ```
> 		ffmpeg -i "$($FilePath)"  -crf $CRTValue -vf "crop=trunc(iw/2)*2:trunc(ih/2)*2" -pix_fmt yuv420p -sws_flags spline+accurate_rnd+full_chroma_int -color_range 1 -colorspace 5 -color_primaries 5 -color_trc 6   -f hevc "$($FileNoExtensionPath).hvc";
> 		MP4Box -add-image "$($FileNoExtensionPath).hvc:primary" -ab heic -new "$($FileNoExtensionPath).heic";
> ```

With @kleisauke kindly digging further on this subject. It seems that the source this strange behaviour is some commits between  1.3.2 and mster branch.

> 
> 
> I could reproduce this with libheif master ([strukturag/libheif@b296667](https://github.com/strukturag/libheif/commit/b29666747b4be5fcaf3f17a551ed5c2fd596872b)) and libde265 v1.0.5 when doing:
> 
> ```shell
> $ heif-convert fffo.heic x.png
> ```
> 
> However, I could not reproduce this with the online decoder from:
> https://strukturag.github.io/libheif/
> 
> In an attempt to bisect this, I tried libheif v1.3.2 and libde265 v1.0.2 with this Dockerfile:
> Details
> 
> But the gray background is still present. Assuming it's in libheif, a git bisect from [strukturag/libheif@fb60ff7](https://github.com/strukturag/libheif/commit/fb60ff7f50a99bee70e28e9b2d4c1e74f76c3ea6) to https://github.com/strukturag/libheif/tree/v1.3.2 should reveal which commit introduces this behavior (I'm not sure if it's a bug).

> 
> 
> I could reproduce this with libheif master ([strukturag/libheif@b296667](https://github.com/strukturag/libheif/commit/b29666747b4be5fcaf3f17a551ed5c2fd596872b)) and libde265 v1.0.5 when doing:
> 
> ```shell
> $ heif-convert fffo.heic x.png
> ```
> 
> However, I could not reproduce this with the online decoder from:
> https://strukturag.github.io/libheif/
> 
> In an attempt to bisect this, I tried libheif v1.3.2 and libde265 v1.0.2 with this Dockerfile:
> Details
> 
> But the gray background is still present. Assuming it's in libheif, a git bisect from [strukturag/libheif@fb60ff7](https://github.com/strukturag/libheif/commit/fb60ff7f50a99bee70e28e9b2d4c1e74f76c3ea6) to https://github.com/strukturag/libheif/tree/v1.3.2 should reveal which commit introduces this behavior (I'm not sure if it's a bug).

I would be really appreciated it if anyone can take a look.
Thx in advance.

**Comment by novomesk** [comment]
There was rounding error in older RGB<->YUV conversions. That would explain why the image got visually darker when it was opened, saved and opened again.

**Comment by farindk** [comment]
I encoded your image `o.png` with a plain `heif-enc`  and decoded with `heif-convert`.
With v1.8.0, the background changed from pixel value 255 to pixel value 254 because of the rounding issue @novomesk mentioned.
This is fixed now. Current master (pre v1.9.0) also gives 255 on the decoded image.
