### ISSUE TITLE
Missing function definition for  heif_encoder_descriptor_get_compression_format

### ISSUE THREAD

**Issue by Micket** [strukturag/libheif#261]
Declared here
https://github.com/strukturag/libheif/blob/1efe4ad59ab77b3f016425ac2b550768e50dc418/libheif/heif.h#L955-L957

but I can't see any definition of it. A quick glance at the code tells me it should probably have
```c
enum heif_compression_format heif_encoder_descriptor_get_compression_format(const struct heif_encoder_descriptor* descriptor)
{
  return descriptor->plugin->compression_format;
}
```

**Comment by farindk** [comment]
Right. Thanks. I added this in 6889f67.
