### ISSUE TITLE
Pass CICP Matrix Coefficients to conversion pipeline

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#263]
When we have AVIF with NCLX profile, matrix coefficients are correctly extracted from the NCLX and passed to conversion pipeline.
However, when we have AVIF with ICC profile, there is no NCLX and the `aom_matrix_coefficients_t mc;` are in the `aom_image` structure. This value should be passed to conversion pipeline like it is done with NCLX.

I am attaching a testfile (2048x1366, 8bit, YUV444 full range, Matrix Coeffs. : 0, ICC Profile):
[testfile.zip](https://github.com/strukturag/libheif/files/4982043/testfile.zip)
This is how it shouldn't look like:
![converted](https://user-images.githubusercontent.com/52529860/88543239-f9ae5b00-d017-11ea-8f4c-674ef57cb378.png)

**Comment by farindk** [comment]
Thanks.
Implemented in c02e2108075742ae0f02702957768df5be3a7df7.

**Comment by farindk** [comment]
Question: when saving AVIF with ICC, do you think it makes sense to specify ICC and NCLX over the public API or should we just use a default NCLX in that case? Does it matter that much which NCLX parameters are used internally?

**Comment by novomesk** [comment]
Someone wrote that the coefficients slightly influence compression (encoded file size).
I think for majority of people, it is enough to use default (any choice) coefficients.
However, maybe in future someone would like to use true lossless mode (zero quantizers, YUV444 + avoiding RGB->YUV conversion by using the `heif_matrix_coefficients_RGB_GBR = 0`)
