### ISSUE TITLE
Display HEIF incorrectly with gdk-pixbuf

### ISSUE THREAD

**Issue by SheldonZhong** [strukturag/libheif#265]
libheif version: 1.7.0
gdk-pixbuf version: 2.40.0

[example.zip](https://github.com/strukturag/libheif/files/4999053/example.zip)
Due to GitHub's attachment format limit, test file and screenshots are attached in the zip file.

Sometimes it also gets
```bash
$ eog example.heic
Segmentation fault (core dumped)
```
The same for `gpicview`.

The picture shows perfectly if I use `heif-convert` to other formats.

**Comment by silverbacknet** [comment]
The common theme is that both of those applications are incorrectly interpreting the API: They are reading the metadata, seeing 32-bit, and assuming that they're going to get RGBA back, when they're asking for straight RGB. If they want RGBA, they have to ask for that, or handle what they ask for properly. That's a bug in both of them.

**Comment by farindk** [comment]
Since the gdk-pixbuf loader is part of libheif, I'll have a look at it :-)

**Comment by farindk** [comment]
Fixed in a070738a81a253ad13bc63fe4cee805c8833da7b.
Thanks for reporting this.
