### ISSUE TITLE
Add supported values to enum heif_color_primaries

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#267]
Hello,
Maximum value defined in `enum heif_color_primaries` is 7 now.
However, `heif_color_primaries` often contains non-enumerated values (for example 9 - BT2020)

I see in nclx.cc, that other possible values are 8, 9, 10, 11, 12, 22
Can we add them to the enum?

**Comment by farindk** [comment]
Yes, I will do so. Same for transfer characteristics and matrix coefficients.
I've taken the full list out of the h.273 standard.
