### ISSUE TITLE
AVIF with alpha channel

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#268]
[transp.zip](https://github.com/strukturag/libheif/files/5002447/transp.zip)
I have AVIF file with transparency created via libavif but heif-info indicate there is no alpha channel:
```
heif-info transp.avif 
MIME type: image/avif
image: 2048x1366 (id=1), primary
  color profile: nclx
  alpha channel: no
  depth channel: no
```
libavif utility claims there is alpha channel:
```
avifdec --info transp.avif 
Image decoded: transp.avif
 * Resolution     : 2048x1366
 * Bit Depth      : 8
 * Format         : YUV420
 * Alpha          : Present
 * Range          : Full
 * Color Primaries: 2
 * Transfer Char. : 2
 * Matrix Coeffs. : 6
 * ICC Profile    : Absent (0 bytes)
 * XMP Metadata   : Absent (0 bytes)
 * EXIF Metadata  : Absent (0 bytes)
 * Transformations: None
```

**Comment by farindk** [comment]
Added in the commit above. Same for depth images. AVIF uses a different ID for alpha and depth images as HEIF. I have added those IDs.
Now AVIF images with alpha are decoded.

**Comment by farindk** [comment]
I've also added writing AVIF alpha channels (f3077a6).
