### ISSUE TITLE
quality does not seem to be taken into account when encoding an AVIF file

### ISSUE THREAD

**Issue by jaubourg** [strukturag/libheif#274]
I'm using libheif 1.7.0.

While using [libvips](https://github.com/libvips/libvips), I stumbled upon the fact quality does not seem to be taken into account when encoding an AVIF file using libheif.

I reported it here: https://github.com/libvips/libvips/issues/1757

From what we could gather, it might be an issue with how user-supplied options are handled:

> ```shell
> $ heif-enc --avif -q 25 -o out-25.avif input.jpg
> $ heif-enc --avif -q 75 -o out-75.avif input.jpg
> $ ls *.avif
> 123239 out-25.avif
> 123239 out-75.avif
> ```
> 
> My best guess is that `aom_set_default_parameters` is being called too late and overriding user-supplied values, so the "quality" will always be the default value of 50.
> 
> https://github.com/strukturag/libheif/blob/436d1c4078d27a5ff3b31e98a378b328894c1efb/libheif/heif_encoder_aom.cc#L590

**Comment by farindk** [comment]
Right, thanks. Regression introduced during refactoring...
Corrected in above commit.

**Comment by jaubourg** [comment]
Awesome! Any idea when a 1.7.1 will be released?
