### ISSUE TITLE
Possible to use libavif?

### ISSUE THREAD

**Issue by adityapatadia** [strukturag/libheif#275]
There is a library specifically designed to encode and decode AVIF images. Can this project use that instead of libaom?

My motive is to improve encoding speed which is very low for libaom.

https://github.com/AOMediaCodec/libavif

**Comment by farindk** [comment]
The libavif library also uses aom/rav1e for encoding/decoding. It is on the same abstraction level as libheif. Hence, it makes no sense that libheif uses libavif.

**Comment by adityapatadia** [comment]
Whoops. Just read it on their readme after your comment. Anyway, rav1e is way to go. I will be waiting for https://github.com/strukturag/libheif/issues/266
