### ISSUE TITLE
The library should expose nclx_color_profile_free methods

### ISSUE THREAD

**Issue by 0xC0000054** [strukturag/libheif#276]
The `heif_image_handle_get_nclx_color_profile` and `heif_image_get_nclx_color_profile` should have accompanying `heif_image_handle_nclx_color_profile_free` and `heif_image_nclx_color_profile_free` methods.

Currently, callers of `heif_image_handle_get_nclx_color_profile` and `heif_image_get_nclx_color_profile` need to have read the source code to know how to free the allocated `heif_color_profile_nclx` structure.
This is also problematic when libheif is compiled as a Windows DLL, `malloc` and `free` are only guaranteed to work when called from the same DLL.

**Comment by farindk** [comment]
Right, thanks. Function has been added.
