### ISSUE TITLE
Do these logs come from this library?

### ISSUE THREAD

**Issue by adityapatadia** [strukturag/libheif#278]
When I encode AVIF image, I get following logs.
Please note, I use libheif from libvips and not a standalone one.

```
--- construct_pipeline
from: colorspace=RGB chroma=RGBA bpp(R)=8 alpha=yes nclx=no
to: colorspace=YCbCr chroma=420 bpp(R)=8 alpha=yes nclx=yes
> 23Op_RGB24_32_to_YCbCr420
input spec: colorspace=RGB chroma=RGBA bpp(R)=�
```

Is it coming from this library?

**Comment by farindk** [comment]
Yes. I forgot to turn it off after debugging.
Setting is at the top of `heif_colorspace.cc`. I've also just turned it off in `master`.
