### ISSUE TITLE
JPEG_INCLUDE_DIR isn't used in projects

### ISSUE THREAD

**Issue by silverbacknet** [strukturag/libheif#280]
CMake doesn't seem to generate an include folder for JPEG_INCLUDE_DIR in the example projects. I'm not really fluent in CMake so I don't know how to fix it; manually adding the folder to heif-convert and heif-enc projects built correctly.

**Comment by farindk** [comment]
Thanks. Does the above patch fix the problem for you?

**Comment by fancycode** [comment]
Closing, feel free to reopen with more feedback if the problem persists.
