### ISSUE TITLE
Image fails to decode correctly

### ISSUE THREAD

**Issue by swftvsn** [strukturag/libheif#283]
Hi,

the image in question is produced by iphone, ios 13.6.1. It decodes fine on mac, but libheif fails to decode it. Here is what is produced:

![image](https://user-images.githubusercontent.com/25097010/90144185-2c31b500-dd87-11ea-951e-d6f701b47c77.png)

And here is the correct image screen capped from mac:

![image](https://user-images.githubusercontent.com/25097010/90144301-54211880-dd87-11ea-8cf9-7d3494d4e5fd.png)

I can provide sample file via email or similar to aid in testing, but can't add it publicly here.

**Comment by farindk** [comment]
Thanks. Please send the file to `farin@struktur.de`.

**Comment by farindk** [comment]
Tested the file provided by @swftvsn . Decodes fine with current libheif. Probably an old libheif version (more specifically, libheif.js) was used.

Note: provided file had faulty 'pixi' box with just a single BPP entry for a color image.
