### ISSUE TITLE
nclx profile is not passed through the color conversion

### ISSUE THREAD

**Issue by farindk** [strukturag/libheif#288]
We have to pass the NCLX profile through the color conversion so that the encoder plugins can embed the information in the image bitstreams.
See the comments from @wantehchang in #279.

**Comment by novomesk** [comment]
Dirk, do you have some news how this could be solved?

If it is too complicated to change library structure to pass the information automatically, I think there could be an alternative solution: What about adding new parameters to AV1 encoders: full_range, primaries, transfer_characteristics, matrix_coefficients ? (with default values 1-full_range,2-unspecified primaries,2-unspecified trc, 6-BT_601)

Setting those values manually introduce small redundancy on library user's side but only if someone will need to use non-default values. It will solve also problem with saving AVIF with ICC profile, and matrix coefficients will be saved in AV1 stream too. Output file will be color compatible with other AVIF implementations.

**Comment by farindk** [comment]
The information probably can be passed automatically. That's something for the next release, as I just didn't want to delay v1.8.0 any further.
I think the library has to handle this automatically. At least there is also the decoding case where the nclx comes from the AV1 bitstreams and the ICC from the container.

**Comment by wantehchang** [comment]
I just proposed pull request #308 as an interim solution to this issue in the aom encoder. Please take a look. Thank you!

**Comment by novomesk** [comment]
Hard coded full range is better than limited range.

**Comment by farindk** [comment]
The nclx is now preserved through color conversion and passed to the aom/rav1e encoders.
If there is an ICC in the input, it will be stored in the `colr` box of the output. Otherwise the nclx is stored in the `colr` box.

Please check whether it is ok now in current master branch (5221af2).

**Comment by novomesk** [comment]
I think there is a new bug now. Tried to save AVIF with ICC profile but avifdec did not find ICC. heif-info reports `color profile: nclx`

**Comment by farindk** [comment]
@novomesk Are you sure that's the current master version? Sounds like the broken behavior in v1.8.0.
This is what I get now:
````
./heif-enc ~/.../jpeg/with-color-profile/YellowFlower-P3.jpg -o out.avif -A

./heif-info out.avif 
MIME type: image/avif
image: 600x400 (id=1), primary
  color profile: prof
  alpha channel: no
  depth channel: no
````

**Comment by farindk** [comment]
With v1.8.0 it was as you describe:
````
./heif-enc ~/.../jpeg/with-color-profile/YellowFlower-P3.jpg -o out.avif -A

./heif-info out.avif 
MIME type: image/avif
image: 600x400 (id=1), primary
  color profile: nclx                    <<<< overwrites ICC
  alpha channel: no
  depth channel: no
````

**Comment by novomesk** [comment]
I have got that behavior when using my GIMP plug-in.
I will try to rebuild everything again and let you know if I continue to reproduce it or some anomaly on my system.

**Comment by novomesk** [comment]
When I use heif-enc with JPG (with ICC) input, AVIF has ICC saved.
But when I use PNG(with ICC) as input, saved AVIF has nclx.

In my program I use `err = heif_image_set_raw_color_profile (image, "prof", icc_data, icc_length);`
The call is successful but the saved AVIF doesn't have ICC.

Maybe the changes in conversion pipeline are causing problem? ICC gets lost there?
When converting JPG->AVIF, the RGB->YUV conversion pipeline is bypassed (we have YUV data already from JPG) and this scenario is working.

**Comment by farindk** [comment]
Yes, that makes perfect sense. The ICC is lost in the conversion pipeline. I'll fix that.
Thanks for cross testing.

**Comment by wantehchang** [comment]
Dirk: I tested your code carefully. Overall it works well. I suggest a minor improvement in https://github.com/strukturag/libheif/pull/318.

**Comment by farindk** [comment]
Thanks @novomesk and @wantehchang for testing. Closing it since it appears to work correctly now.
