### ISSUE TITLE
heif_test.go not included in the tarball

### ISSUE THREAD

**Issue by jsmolic** [strukturag/libheif#289]
Hello,
https://github.com/strukturag/libheif/blob/master/go/heif/heif_test.go file is not included in release tarballs, making it impossible to run the test by default (see https://github.com/gentoo/gentoo/pull/17122 for reference). Could you include that file as part of future releases?

Thank you,
Jakov

**Comment by farindk** [comment]
Thanks. I have added this.

**Comment by jsmolic** [comment]
@farindk Thanks!
