### ISSUE TITLE
libheif+libde265 static variables initialization order problem

### ISSUE THREAD

**Issue by LibRaw** [strukturag/libheif#297]
libde265 initializer is protected with static mutex:
`static std::mutex de265_init_mutex;`
libheif plugin initializer is also static:
`static class Register_Default_Plugins
{
....
} dummy;
`
This may result in wrong order of calls: when dummy's constructor is called, de265_init_mutex is not yet initialized.

I was **immediately** hit by this when trying to understand libheif API (by running heif-convert under debugger). I'm using static libraries for both libheif and libde265.

With dynamic libraries this may be a non issue because of dynamic libraries initialization order (libde265.so probably ininitalized before libheif.so because libheif depends on libde265).

Possible solution: implement explicit heif_init_plugins() call that will call plugin registration after libde265 initialization (e.g. from main())

**Comment by farindk** [comment]
Thanks.
This has been already tackled in this pull request:
https://github.com/strukturag/libde265/pull/263
