### ISSUE TITLE
AVIF encoding of semitransparent pixels degraded in 1.8.0

### ISSUE THREAD

**Issue by dooman87** [strukturag/libheif#298]
Hi there,

I'm using libheif through ImageMagick. I've updated libheif to the latest release (1.8.0) and noticed an issue when converting PNG to AVIF.

I attached an example of original image and using libheif with aom and rav1e.

## Original

![original](https://user-images.githubusercontent.com/124110/91523893-359f4d80-e941-11ea-94a1-c480e5e08d61.png)

## AOM (screenshot from Chrome 85)
 
<img width="554" alt="aom" src="https://user-images.githubusercontent.com/124110/91506182-d1ff2b00-e914-11ea-9daa-6ea9cf37ae08.png">

## RAV1E (screenshot from Chrome 85)

<img width="554" alt="rav1e" src="https://user-images.githubusercontent.com/124110/91506186-d62b4880-e914-11ea-9157-4be3583c3b78.png">

With version 1.7.0 file sizes were bigger, but there was no visual artifacts as an example above.

**Comment by farindk** [comment]
Images with alpha are now considerably smaller because this bug in v1.7.0 has been fixed:
https://github.com/strukturag/libheif/issues/279

I cannot reproduce the artifacts you get. Could you please attach the original image and the command lines you are using to convert the images?

My guess is that the artifacts come from incorrect rendering of the alpha channel (seems like it is treated like a binary channel). Together with some compression "ringing" artifacts in the alpha plane, this may result in this result.

**Comment by dooman87** [comment]
Argh, I think something was wrong with my tests. I can see the same artifacts on both versions (1.7.0 and 1.8.0). I'm not using libheif directly but through the ImageMagick version 7.0.10-25 and I think the code that encoding the image is here: https://github.com/ImageMagick/ImageMagick/blob/04994e3457a44d699c88e0946b66f63199dcef25/coders/heic.c#L788

The original image is the one attached to the bug (top PNG) and the command I use to convert is:

```
convert test.png test.avif
```

The Chrome version:

```
Google Chrome: 85.0.4183.83 (Official Build) (64-bit)
Revision: 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS: Linux
```

Looks like it's ImageMagick problem and I might need to create an issue there.

Thanks a lot @farindk for your work, quick reply and troubleshooting!

**Comment by dooman87** [comment]
@dlemstra do you think it could be an issue in ImageMagick?

**Comment by dlemstra** [comment]
ImageMagick only support writing images in the `YCbCrColorspace` at the moment.

**Comment by dooman87** [comment]
Thanks @dlemstra for confirming. Sorry, my knowledge of colorspaces is not good and they all show `sRGB` when using `identify`. Am I right thinking that images without transparency (opaque = true) should work fine at this stage? Is there any feature request opened in GH that I could track?

**Comment by dlemstra** [comment]
At this moment we don't have a feature request for that @dooman87. We probably want to have support for both reading and writing images with an alpha channel. It would help us if we would have an input image with an alpha channel.
