### ISSUE TITLE
AVIF image is brighter than original

### ISSUE THREAD

**Issue by dooman87** [strukturag/libheif#304]
Hi,

Thanks a lot for putting this library together.

I'm using `heif-enc` tool to convert JPEGs/PNGs to AVIF and noticed that colors are different on source and result images.

```
dooman@lapata:~$ heif-enc --help
 heif-enc  libheif version: 1.8.0
----------------------------------------
Usage: heif-enc [options] image.jpeg ...
...

dooman@lapata:~$ heif-enc ./test.jpeg -A -o ./test.avif
```

Example images:
![logo](https://user-images.githubusercontent.com/124110/91719421-a6ac6280-ebd8-11ea-92c4-7b410ce03fb7.png)
![test](https://user-images.githubusercontent.com/124110/91719457-b5931500-ebd8-11ea-9f52-1453f08cdca3.jpeg)

If you open source and result images in 2 tabs of the browser then you could notice that AVIF images are lighter.

Web browser:

Google Chrome | 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Linux
JavaScript | V8 8.5.210.20

Libheif 1.8.0 with libaom-2.0.0

**Comment by novomesk** [comment]
What web browser are you using?

Do you use AOM encoder or rav1e in libheif?

There are known issues in libheif to be fixed in next version but problem could be different implementation in the web browser.

**Comment by dooman87** [comment]
> What web browser are you using?
> 
> Do you use AOM encoder or rav1e in libheif?
> 
> There are known issues in libheif to be fixed in next version but problem could be different implementation in the web browser.

My apologies, added browser info and libheif version to the issue.

**Comment by novomesk** [comment]
The bright areas in Chrome are brighter and the dark areas are darker in Chrome. It seems that Chrome consider the image has limited range (instead of full range). Libheif signals full range in NCLX profile only but not in AV1 stream yet.

When the https://github.com/strukturag/libheif/issues/288 is solved, this problem should be gone.

It is also possible that future Chrome will change full range detection, I reported similar situation to libavif https://github.com/AOMediaCodec/libavif/issues/281

**Comment by dooman87** [comment]
Attaching AVIF files from `heif-enc` and `squoosh` app.

`heif-enc` - https://drive.google.com/file/d/1aRXS0cpBjzLoKX6B-HclHblKDo9yk4nm/view?usp=sharing
`squoosh` - https://drive.google.com/file/d/1fjRPUZfiVdN47lmejLWPSdDCtg9qj8v4/view?usp=sharing

Looks like files generated from `squoosh` doesn't have this problem and it seems to be using `libavif`.

**Comment by dooman87** [comment]
I could also confirm that when I open files from previous comment on MacOSX in the same version of Chrome then the colours are fine. 

I raised an issue in Chrome tracker - https://bugs.chromium.org/p/chromium/issues/detail?id=1123866#c3

**Comment by dooman87** [comment]
@novomesk Thanks a lot for helping with troubleshooting this one. Do you think we could close this one in favour of #288. Or there is still a chance the cause is different?

**Comment by novomesk** [comment]
Potentially, there could be other cause too but with very little impact on the problem. Solving https://github.com/strukturag/libheif/issues/288 will improve compatibility between various AVIF implementations.
I think you can close the issues (as being technically duplicate) but I think someone else would post similar issue again as people don't know what is the technical background of the problem, they just see different colors and feel a problem somewhere.
