### ISSUE TITLE
Adobe RGB & Display P3 Support

### ISSUE THREAD

**Issue by imfantuan** [strukturag/libheif#310]
For now: a Adobe RGB & P3 Jpeg will be convert to sRGB.

Before
<img width="401" alt="Xnip2020-09-08_00-15-40" src="https://user-images.githubusercontent.com/16457655/92405583-847e8b80-f168-11ea-9659-1224f604ed9a.png">

After
<img width="395" alt="Xnip2020-09-08_00-16-03" src="https://user-images.githubusercontent.com/16457655/92405599-89433f80-f168-11ea-901d-ce526e458c89.png">

Shall we keep them?

**Comment by imfantuan** [comment]
via: https://images.unsplash.com/photo-1596678117830-567fdc063f56
HEIC from heif-enc:
<img width="589" alt="Xnip2020-09-08_12-04-27" src="https://user-images.githubusercontent.com/16457655/92432449-baedf200-f1cc-11ea-9676-fbfc5af168e9.png">

Better HEIC from Cloudinary (with Adobe RGB):
https://res.cloudinary.com/demo/image/fetch/w_860,q_85,f_heic/https://images.unsplash.com/photo-1596678117830-567fdc063f56
<img width="594" alt="Xnip2020-09-08_12-04-50" src="https://user-images.githubusercontent.com/16457655/92432034-980f0e00-f1cb-11ea-9be9-7b5949c7d2dc.png">

Do you have any idea?

**Comment by dahugi** [comment]
I can confirm this. Same for input PNG files.
Older versions of heif-enc managed color profiles correctly.

**Comment by imfantuan** [comment]
> I can confirm this. Same for input PNG files.
> Older versions of heif-enc managed color profiles correctly.

Thanks for your reply.
May be i should waiting for the next version.

**Comment by farindk** [comment]
Leaving this open as reminder. Problem is that because of the recent changes concerning the nclx profile, the original ICC was replaced with the nclx. I'm changing this now such that an image can hold both nclx and icc.

**Comment by farindk** [comment]
Should be fixed with ee3bb69

**Comment by farindk** [comment]
Please check whether it is ok now in current master branch (5221af2b6e).

**Comment by imfantuan** [comment]
> Please check whether it is ok now in current master branch ([5221af2](https://github.com/strukturag/libheif/commit/5221af2b6e713edd1dba697dbc788dd22045600e)).

So fast and great update! It worked for this issue! 👏

**Comment by farindk** [comment]
Thanks for testing. We found there is still a problem when the input is RGB, but that's easy to fix (#313).

**Comment by imfantuan** [comment]
> #313

OK, i followed that issue, thanks.

**Comment by ValZapod** [comment]
The problem with Display P3 ICC profile it has red Z of XYZ as negative.
