### ISSUE TITLE
PNG converted to AVIF can't be opened in chrome

### ISSUE THREAD

**Issue by adityapatadia** [strukturag/libheif#311]
https://www.unnatisilks.com/pub/static/version1598010421/frontend/Mgs/unnati/en_US/MGS_Mpanel/images/blank.png

If this image is converted to AVIF using rav1e encoder, it can't be opened in Chrome 85.

**Comment by farindk** [comment]
Probably an error with rav1e. It generates no output for this 1x1 image. Encoding with aom and x265 works fine.

**Comment by adityapatadia** [comment]
This is another example: https://www.suppliesshops.com/wp-content/themes/supplies_shops/r2d_images/navigation_sep.png

It's 2 pixel wide and 38 pixel in height.

**Comment by adityapatadia** [comment]
This is a known issue in Rav1e: https://github.com/xiph/rav1e/issues/2518

**Comment by farindk** [comment]
AVIF images with a size <16 pixels are now encoded with 16 pixels minimum and a crop transform is used to reduce it to the final size.

**Comment by adityapatadia** [comment]
This issue is not resolved. Original PNG and processed AVIF look different.

Original: https://www.suppliesshops.com/wp-content/themes/supplies_shops/r2d_images/navigation_sep.png

AVIF: https://suppliesshops.gumlet.io/wp-content/themes/supplies_shops/r2d_images/navigation_sep.png?format=avif
