### ISSUE TITLE
Improve RGB->YUV conversion

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#313]
I have sRGB image in JPG format and identical copy as PNG.
Encoding JPG and PNG via heif-enc gives different results.
YUV values from JPG are used directly. When input is PNG, RGB->YUV conversion in libheif is performed.

The difference is not big, but noticeable sometimes.

I suspect the difference could be a numerical error caused maybe conversions from float to int without rounding.

I wish to look at the conversion math closer with goal to reach more accurate results.

**Comment by novomesk** [comment]
In `Op_RGB24_32_to_YCbCr::convert_colorspace` there is following code:
```
      float yv = r * coeffs.c[0][0] + g * coeffs.c[0][1] + b * coeffs.c[0][2];

      if (full_range_flag) {
        out_y[y * out_y_stride + x] = clip(yv);
```
When float is converted to integer (uint8_t), it is good to add 0.5f to perform rounding. So values like 99.999 will result to 100 and not 99.

When I changed the line to
`out_y[y * out_y_stride + x] = clip(yv + 0.5f);` it helped significantly.

**Comment by farindk** [comment]
Sure. Let me fold this into the clip() functions, so that it'll always do that.

**Comment by novomesk** [comment]
I suggest not to put it to clip() yet, this +0.5f has to be used wisely and I think not everywhere (so that we don't create other problems). I am still continuing with review.

**Comment by farindk** [comment]
I just did it...
Biggest problem is probably that `Op_YCbCr420_to_RRGGBBaa` does not adapt to the nclx yet.
I'll add that too.

**Comment by novomesk** [comment]
I still refer the previous code here.
The rounding is needed also when we open the files and use YUV->RGB. For example in `Op_YCbCr_to_RGB<Pixel>::convert_colorspace` I tried this:
```
out_r[y * out_r_stride + x] = (Pixel) (clip(yv + coeffs.r_cr * cr + 0.5f, fullRange));
out_g[y * out_g_stride + x] = (Pixel) (clip(yv + coeffs.g_cb * cb + coeffs.g_cr * cr + 0.5f, fullRange));
out_b[y * out_b_stride + x] = (Pixel) (clip(yv + coeffs.b_cb * cb + 0.5f, fullRange));
```
because I observed that images were darker than original.


There is still something I don't understand or not sure how it should be:
Then you calculate **out_cb** and **out_cr** values you use `clip(cb + 128)` or `clip(cr + 128)`
Half of 255 is 127.5 and 128 actually looks like 127.5 + 0.5rounding.
But when clip performs another +0.5 I don't know whether or not it is desired there.

**Comment by farindk** [comment]
Output values in H.273 seem to be always float. I find no information how to convert them to integer. Hence, my assumption that the final step (converting float to integer) should simply be rounded. An as the integers are always >=0, there also should be no question about rounding directions.

**Comment by novomesk** [comment]
I think you are right. Zero seems to map to 128 also in libavif.

**Comment by farindk** [comment]
Chroma zero has to map to straight 128. Otherwise it wouldn't be possible to have clean black-and-white images.

**Comment by novomesk** [comment]
Thanks, I will test and let you know if I found some problems.

**Comment by farindk** [comment]
Please also note #287

**Comment by novomesk** [comment]
I thing we have new problem. I used grayscale-looking RGB image with `808080` values.

When I encoded the image heif-enc and converted back with heif-convert, the values were `838083`

When I encoded with libavif first and decoded with heif-convert, the values were `818181`

When I encoded and decoded only via libavif, the result was `817f81`

The worst scenario is to encode via heif-enc and decode via libavif, the result is `837f84`

**Comment by novomesk** [comment]
Maybe this line is causing the problem?
`  long x = lroundf(fx + 0.5f);`
If **lroundf** is performing rounding, maybe we don't need to add 0.5f

**Comment by farindk** [comment]
You are right, that +0.5f is complete nonsense. Old code that I forgot to remove when introducing `lroundf`.
Thanks for spotting this, I've corrected it immediately.

**Comment by novomesk** [comment]
Also this one:
https://github.com/strukturag/libheif/blob/9a1046f891fe8818cb20478a60abf20eba6c6179/libheif/heif_colorconversion.cc#L1885

**Comment by novomesk** [comment]
Thanks, looks good.
