### ISSUE TITLE
Use libheif javascript version on server side

### ISSUE THREAD

**Issue by kishorekpoluri** [strukturag/libheif#328]
Can I use libheif javascript  version on server side using node? I tried, it didn't work.

**Comment by fancycode** [comment]
Our CI tests run the emscripten-compiled libheif in node:
https://github.com/strukturag/libheif/blob/master/scripts/test-javascript.js

The API is based on the C-API of libheif:
https://github.com/strukturag/libheif/blob/master/post.js

Please provide some information what exactly is not working and how you are testing it.

**Comment by kishorekpoluri** [comment]
I am using the script in node environment. decoded image object is empty.

Log below:
Debugger attached.
Running libheif JavaScript tests ...
test-javascript.js:23
Loaded libheif.js 0.0.1
test-javascript.js:26
Loaded images: 2
test-javascript.js:52
Array(2) [HeifImage, HeifImage]
test-javascript.js:53
length:2
__proto__:Array(0) [, …]
0:HeifImage {handle: heif_image_handle, img: null}
1:HeifImage {handle: heif_image_handle, img: null}
