### ISSUE TITLE
Factor out ISOBMFF parser

### ISSUE THREAD

**Issue by ao2** [strukturag/libheif#333]
Hi,

AFAIU libheif has to parse ISOBMFF files to do its job, I was wondering whether it would be worth splitting up the ISOBMFF parsing code into a library.

Ideally this would enable sharing the code with other projects like [libavif](https://github.com/AOMediaCodec/libavif) and possibly even [libexif](https://github.com/libexif/libexif) in case they decided to support extracting EXIF data from ISOBMFF files.

I know that this is easier said that done, but I wanted to at least ask if there any interest.

FWIW there is already [libbmff](https://github.com/frejoel/bmffparse) by @frejoel, which is a small C shared library for parsing ISOBMFF but I don't know in what shape it is.

Feel free to close the issue if this is too far fetched. :sweat_smile:

Thanks,
Antonio

**Comment by ao2** [comment]
Posted related questions to [libavif](https://github.com/AOMediaCodec/libavif/issues/317) and [libexif](https://github.com/libexif/libexif/issues/51)

**Comment by farindk** [comment]
Thanks for the pointer to libbmff, I was not aware of that.

I had a look at libbmff. The code is good quality, but still, I think this would complicate things much more than it helps. It's going to introduce another dependency. Even one for which no packages exist as far as I can see. Moreover, we would need a lot of interface code, e.g., converting error messages. In the end, this will be much more work than simply decoding the box structure ourselves, which is not that difficult anyways (and the code is already there).

**Comment by ao2** [comment]
@farindk thanks for at least taking a look at libbmff.

The dependency issue could be mitigated by using a git submodule, but yeah I figured that the effort to change the current working code in libheif may not really be worth it.

Thanks again for taking the time.

Ciao, Antonio
