### ISSUE TITLE
Non-inline methods in heif_cxx.h causing trouble

### ISSUE THREAD

**Issue by lgritz** [strukturag/libheif#339]
Image::get_nclx_color_profile(), Image::get_color_profile_type(), Image::get_raw_color_profile(), and Image::set_raw_color_profile() are not declared inline, so if heif_cxx.h is included in two different modules, you can end up with link errors like:

```
duplicate symbol 'heif::Image::get_color_profile_type() const' in:
    heifinput.cpp.o
    heifoutput.cpp.o
```

This is a pretty serious build break, and this error just got incorporated into Homebrew's version of libheif, so everybody who builds any packages on Mac using Homebrew will find, as this auto-updates for them, to break their apps if they have more than one module including heif_cxx.h.

**Comment by lgritz** [comment]
Sorry, as an open source org manager myself, I am embarrassed to report this as an issue instead of just submitting the obvious 4-line PR that fixes it. But it would take me at least a week to get my company's lawyers to ok sending PRs to a project we hadn't contributed to before, probably a month for a GPL-licensed project.

**Comment by farindk** [comment]
Right. Stupid mistake. No worries about the PR, I think I can handle this myself :-)
Will do a v1.9.1 today.

**Comment by lgritz** [comment]
Thanks for the rapid fix!
