### ISSUE TITLE
feature request: add detection of dav1d if installed on the system

### ISSUE THREAD

**Issue by vtorri** [strukturag/libheif#340]
do like aom : detect cav1d with its pkg-config file

thank you

**Comment by brad0** [comment]
Yes. Looking at what was commited I'm glad there is now a dav1d decoder but please allow building against an external copy of dav1d.

**Comment by farindk** [comment]
Should be implemented with #341 . Can you please confirm that it works with a global system installation of dav1d?

**Comment by fancycode** [comment]
This will be used (and was tested) for the upcoming libheif Debian packaging update, closing.

Feel free to re-open if you find any issues.
