### ISSUE TITLE
Ubuntu upgrade error

### ISSUE THREAD

**Issue by Filbuntu** [strukturag/libheif#347]
I get updates/upgrades through the [libheif “struktur AG” team PPA on Launchpad](https://launchpad.net/~strukturag/+archive/ubuntu/libheif).
Last week an upgrade was suggested but I get following error when trying to `sudo apt upgrade`:
The following packages have been kept back:
  heif-gdk-pixbuf heif-thumbnailer

$ `sudo apt install heif-thumbnailer`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 heif-thumbnailer : Depends: libheif1 (= 1.9.1-1~ ppa1~ ubuntu20.04.1) but 1.8.0-1 ~ ppa1 ~ ubuntu20.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.

_Same for:_
$ `sudo apt install heif-gdk-pixbuf`

Any tips how to resolve this?
(I could not ask a question on the [PPA Launchpad](https://answers.launchpad.net/~strukturag) that is why I post it here.)

**Comment by farindk** [comment]
@fancycode I tried a fresh install of heif-thumbnailer on Ubuntu 18.04 and everything looked ok:

````
# apt install heif-thumbnailer
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libheif1
The following NEW packages will be installed:
  heif-thumbnailer libheif1
0 upgraded, 2 newly installed, 0 to remove and 8 not upgraded.
Need to get 193 kB of archives.
After this operation, 634 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://ppa.launchpad.net/strukturag/libheif/ubuntu bionic/main amd64 libheif1 amd64 1.9.1-1~ppa1~ubuntu18.04.1 [181 kB]
Get:2 http://ppa.launchpad.net/strukturag/libheif/ubuntu bionic/main amd64 heif-thumbnailer amd64 1.9.1-1~ppa1~ubuntu18.04.1 [12,3 kB]
Fetched 193 kB in 0s (620 kB/s)              
Selecting previously unselected package libheif1:amd64.
(Reading database ... 360969 files and directories currently installed.)
Preparing to unpack .../libheif1_1.9.1-1~ppa1~ubuntu18.04.1_amd64.deb ...
Unpacking libheif1:amd64 (1.9.1-1~ppa1~ubuntu18.04.1) ...
Selecting previously unselected package heif-thumbnailer.
Preparing to unpack .../heif-thumbnailer_1.9.1-1~ppa1~ubuntu18.04.1_amd64.deb ...
Unpacking heif-thumbnailer (1.9.1-1~ppa1~ubuntu18.04.1) ...
Setting up libheif1:amd64 (1.9.1-1~ppa1~ubuntu18.04.1) ...
Setting up heif-thumbnailer (1.9.1-1~ppa1~ubuntu18.04.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for shared-mime-info (1.9-2) ...
Unknown media type in type 'all/all'
Unknown media type in type 'all/allfiles'
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
````
Also works for heif-gdk-pixbuf. But I cannot test on 20.04.

**Comment by Filbuntu** [comment]
Thank you, Farin, for the quick check! Great it works in Ubuntu 18.04. 
Unfortunately I still get the error mentioned above.

**Comment by fancycode** [comment]
You also need to enable the PPA `strukturag/libheif` (https://launchpad.net/~strukturag/+archive/ubuntu/libde265) to get the correct dependencies:
```
# apt install libheif1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libheif1 : Depends: libde265-0 (>= 1.0.7) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

After enabling the PPA:
```
# apt install heif-thumbnailer
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libaom2 libde265-0 libheif1 libx265-179
The following NEW packages will be installed:
  heif-thumbnailer libaom2 libde265-0 libheif1 libx265-179
0 upgraded, 5 newly installed, 0 to remove and 49 not upgraded.
Need to get 3162 kB of archives.
After this operation, 23.1 MB of additional disk space will be used.
```

**Comment by Filbuntu** [comment]
Yes, indeed! 
```
sudo add-apt-repository ppa:strukturag/libde265
sudo apt update
sudo apt upgrade
```
And everything is upgraded fine now! Thanks a lot!

**Comment by ollydixon** [comment]
```
[ 8/24] RUN add-apt-repository ppa:strukturag/libde265:                                                                                                                                                                                                    
#12 0.234 /bin/sh: 1: add-apt-repository: not found  
```

**Comment by fancycode** [comment]
> ```
> [ 8/24] RUN add-apt-repository ppa:strukturag/libde265:                                                                                                                                                                                                    
> #12 0.234 /bin/sh: 1: add-apt-repository: not found  
> ```

Please make sure the package `software-properties-common` is installed.
