### ISSUE TITLE
Compilation failure with recent change in heif.h

### ISSUE THREAD

**Issue by 1div0** [strukturag/libheif#35]
In file included from interface.h:25,
                 from interface.c:28:
/usr/local/include/libheif/heif.h:299:3: error: expected specifier-qualifier-list before ‘heif_reader_grow_status’
   heif_reader_grow_status (*wait_for_file_size)(int64_t target_size, void* userdata);
   ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:422: heif_gimp_plugin-interface.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from interface.h:25,
                 from main.c:30:
/usr/local/include/libheif/heif.h:299:3: error: expected specifier-qualifier-list before ‘heif_reader_grow_status’
   heif_reader_grow_status (*wait_for_file_size)(int64_t target_size, void* userdata);
   ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:436: heif_gimp_plugin-main.o] Error 1
make[2]: Leaving directory '/usr/src/strukturag/heif-gimp-plugin/src'

**Comment by 1div0** [comment]
In file included from /usr/src/1div0/darktable/src/common/imageio_heif.c:32:
/usr/local/include/libheif/heif.h:299:3: error: expected specifier-qualifier-list before ‘heif_reader_grow_status’
   heif_reader_grow_status (*wait_for_file_size)(int64_t target_size, void* userdata);
   ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/lib_darktable.dir/build.make:1403: src/CMakeFiles/lib_darktable.dir/common/imageio_heif.c.o] Error 1

**Comment by farindk** [comment]
Thanks. Should be fixed with a1c591c.

**Comment by fancycode** [comment]
For reference: which compiler did this happen with? We are covering various compilers / OS variants with automated tests, so if possible we should try to prevent this from happening again in the future.

**Comment by farindk** [comment]
It happens as soon as you use a plain C compiler. We compile everything as C++.
Compiling a small test program like this with normal GCC suffices:

    #include "libheif/heif.h"
    int main() { return 0; }

leads to

    $ gcc test.c 
    In file included from test.c:2:0:
    libheif/heif.h:299:3: error: expected specifier-qualifier-list before ‘heif_reader_grow_status’
       heif_reader_grow_status (*wait_for_file_size)(int64_t target_size, void* userdata);
       ^~~~~~~~~~~~~~~~~~~~~~~

**Comment by 1div0** [comment]
GCC 8.1.1,Fedora 28, Linux, x86-64
