### ISSUE TITLE
Trying to use libheif javascript version on server side - decoded object image is empty

### ISSUE THREAD

**Issue by kishorekpoluri** [strukturag/libheif#351]
I am using the script in node environment. decoded image object is empty.

Log below:
Debugger attached.
Running libheif JavaScript tests ...
test-javascript.js:23
Loaded libheif.js 0.0.1
test-javascript.js:26
Loaded images: 2
test-javascript.js:52
Array(2) [HeifImage, HeifImage]
test-javascript.js:53
length:2
proto:Array(0) [, …]
0:HeifImage {handle: heif_image_handle, img: null}
1:HeifImage {handle: heif_image_handle, img: null}

**Comment by fancycode** [comment]
The image is decoded lazily when it's being displayed. See https://github.com/strukturag/libheif/blob/master/examples/demo.html for an example how to use it.
