### ISSUE TITLE
Library throws error when converting certain PNG to AVIF

### ISSUE THREAD

**Issue by adityapatadia** [strukturag/libheif#352]
When I try to convert attached PNG to AVIF, this error is thrown.

`heif: Unsupported feature: Unsupported codec (4.3000)`

![Blank-Featured-Image](https://user-images.githubusercontent.com/1086617/94769488-c9948700-03cf-11eb-9934-5abe9553dc65.png)

**Comment by farindk** [comment]
You get "unsupported codec" when you use a compression method that is not supported. Maybe you set the compression method to heif_compression_AVC or heif_compression_JPEG. I see no other way how to get this error. It has nothing to do with the input image.
