### ISSUE TITLE
Question: is there interest in making the hdlr box name optional?

### ISSUE THREAD

**Issue by lovell** [strukturag/libheif#356]
Hello, since commit https://github.com/strukturag/libheif/commit/f231c7a941d64cb3528f373ae9f0580c61dbb80b included in libheif v1.8.0, the `hdlr` box in output images now always has a name that includes the libheif version and encoder plugin details.

Would you be amenable to making this feature configurable? The current behaviour would remain the default, with the addition of an optional to allow someone to revert to the previous `hdlr` box behaviour without a name.

I'm happy to work on and submit a PR with this change, but would prefer to know beforehand if this is something that the maintainers and/or others would be willing to support.

Thanks, as always, for continuing to improve this very useful library.

**Comment by farindk** [comment]
Right. That should be optional or it should even be possible to pass a software version string that should be written.

Apart from that, when I look at it now, it even seems that the hdlr box is the wrong place for this kind of information.
However, I could not find any documentation about a standard box type in which to write comments. Any ideas if there is a standard box for general comments?

**Comment by lovell** [comment]
To record the software used to create an image, existing metadata schemas often support this e.g. EXIF provides `Exif.Image.Software` and XMP has `xmp:CreatorTool`. It's usually the responsibility of downstream software to set this so I wouldn't expect libheif to have to deal with setting these.

**Comment by farindk** [comment]
Yes, if that information is to be stored in Exif/XMP, it's out of scope for libheif.
