### ISSUE TITLE
lossless encoding, not exactly the sources

### ISSUE THREAD

**Issue by LoveStep** [strukturag/libheif#36]
PNG -> HEIC lossless -> PNG = does not equal original image.

**Comment by farindk** [comment]
Two reasons:
1) the exact layout and compression technique used in PNG can be different, hence even with exactly the same image content, the file might be different
2) PNG uses RGB while HEIC uses YUV. Hence, there is a color space conversion involved.

HEIC can be used in lossless when saving YUV data. I'll still have to check whether we can put RGB data into HEIC directly and whether this will be widely supported.
