### ISSUE TITLE
symbol binding failed on macos10.8

### ISSUE THREAD

**Issue by zhzhl1993** [strukturag/libheif#364]
I have used cmake maked it, It can operate **normally on macos10.9** and above, but when I run 
`./heif-convert IMG_3132.HEIC testimg.jpg`
 on command line of **macos10.8**, It show logs as blow:

```
File contains 1 images
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/phonepro/Desktop/deployment10.8 2/./libheif.1.9.1.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/phonepro/Desktop/deployment10.8 2/./libheif.1.9.1.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
```

**Comment by fancycode** [comment]
Where did you build libheif, on the macos10.9 system or the macos10.8?

**Comment by zhzhl1993** [comment]
macos10.9 system.

**Comment by zhzhl1993** [comment]
> Where did you build libheif, on the macos10.9 system or the macos10.8?

I am sorry so long time has gone, I build libheif on macos10.9.

**Comment by fancycode** [comment]
Ok, so that's most likely the problem then. You should always build on the minimun version you still want to support, e.g. on macos10.8 if it should still run there. macos10.9 might have introduced new OS APIs that are not available in earlier versions.
