### ISSUE TITLE
Converting animated heif to jpeg - Which frame ?

### ISSUE THREAD

**Issue by ccheneson** [strukturag/libheif#37]
Hi all,
Sorry if it's the wrong channel to ask this question.
I m using Imagemagick + libheif to convert heif to jpeg.

When converting an animated heif, which frame is used to convert the animated image to jpeg ?
Is it something you compute, a fix frame number or something else ?

Thank you

**Comment by farindk** [comment]
It's returning the "primary item" of the file. This is an ID specified in the file itself.
Files with only video sequences (without identified still images) cannot be decoded yet, but I did not come across any of these yet apart from some demo streams.

If you have any information where animated heifs could be found (except the 5 nokia demos), I'd be glad to hear about it.

**Comment by cchphotobox** [comment]
Thanks for your quick answer. I have indeed tested only with the examples from the nokia demos http://nokiatech.github.io/heif/comparison.html (the star and candle animations)
