### ISSUE TITLE
heif-thumbnailer generates output files size large than original file.

### ISSUE THREAD

**Issue by eterrao** [strukturag/libheif#372]
Hi, thanks for authors who wrote this lib.
When I'm using `heif-thumbnailer -s [same as original dimension] src_file.heic output_file.heic` in CL, output thumbnail file size large than original file.

- My original file resolution:              2160 × 2880, size: 145KB
- Output thumbnail file resolution:   2160 × 2880, size: 3MB

Is that right？ :)

**Comment by fancycode** [comment]
The thumbnailer creates a PNG, so it's expected that this is larger than the original HEIF file:
https://github.com/strukturag/libheif/blob/5b3c8dd984b110d2921378609ce27e98afe9bda5/examples/heif_thumbnailer.cc#L135

**Comment by eterrao** [comment]
Thank you so much !
