### ISSUE TITLE
CI: Test compiling with plain C compiler

### ISSUE THREAD

**Issue by fancycode** [strukturag/libheif#38]
To prevent future regressions of problems like the error in #35 we should compile a small C application that is using the header files.

**Comment by farindk** [comment]
Already did so: 8e20f1c

**Comment by fancycode** [comment]
Great, thanks! Could you also include the other public headers (like `heif_plugin.h`) from that app?

**Comment by farindk** [comment]
Good idea, did that (94f7137). Found out that 'bool' was used in that file.
