### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by bmclean2** [strukturag/libheif#382]
I hate to waste people's time here, but I have searched for a solution and experimented for many hours in vain. The issue: libheif will not compile. I have compiled and installed libde256 and installed the x256 package. Autogen.sh and configure work fine, but when I `sudo make`, I get the following:

make[2]: *** [Makefile:1171: libheif_la-heif.lo] Error 1
make[2]: Leaving directory '/usr/src/libheif/libheif'
make[1]: *** [Makefile:536: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/libheif'
make: *** [Makefile:445: all] Error 2

Further, when I run `sudo make --debug`, I get the following:

Updating goal targets....
 File 'all' does not exist.
   File 'all-am' does not exist.
     File 'libheif.la' does not exist.
       File 'libheif_la-heif.lo' does not exist.
      Must remake target 'libheif_la-heif.lo'.

There are other such similar "errors" output prior to the above. I say "errors" because I'm not sure they qualify as such. Thank you in advanced for any help. I just hope I haven't foolishly overlooked something trivial detail.

EDIT: I'm running Ubuntu 20.10

**Comment by farindk** [comment]
Please try (in a new clean unpacked directory) `make` without `sudo`.
If it still fails, send the first error, not the end of the output. I cannot see anything from the last lines.

**Comment by bmclean2** [comment]
It worked. Many thanks!
