### ISSUE TITLE
Cannot extract auxl and depth_image_handle crashes.

### ISSUE THREAD

**Issue by hackerfactor** [strukturag/libheif#386]
I have a HEIC from an iPhone 12.  No special processing for features enabled.

The iref lists 5 IDs:

ID=49 is 'dimg' and is dependent on lots of IDs. (Typical.) This is the main image and it decodes without a problem.

ID=50 is 'thmb' and it decodes properly as a thumbnail image.

ID=51 is 'auxl'. It appears to be an image, but I cannot find any decoders in libheif that can extract his image.

- If I pass ID=51 into heif_image_handle_get_thumbnail, it returns heif_error_Usage_error. (Okay, so it isn't a thumbnail.)

- If I pass ID=51 into heif_image_handle_get_depth_image_handle, then heif_image_handle_get_depth_image_handle crashes (segfault).

ID=52 and ID=53 are 'cdsc' (content descriptors). 52 is the cdsc for 51, and 53 is the cdsc for 49 (and it works properly).

How do I extract the image from ID=51 'auxl'?

Running heif-info does not identify auxl as a depth map or thumbnail.
```
MIME type: image/heic
image: 3024x4032 (id=49), primary
  thumbnail: 240x320
  color profile: prof
  alpha channel: no
  depth channel: no
```

**Comment by hackerfactor** [comment]
According to the ispe, auxl in ID=51 should be 2016x1512.

**Comment by farindk** [comment]
Could you please attach such an image that I can have a look what it might be?

**Comment by hackerfactor** [comment]
It's a crappy photo, but I wanted to run a quick test. (Don't criticize the content.)

How ironic that github won't let me attach a HEIC file.  I've uploaded it to: https://fotoforensics.com/analysis.php?id=d3adc789289e7e102975100dcd4abe41ca90d6b1.1973852&fmt=orig
NOTE: I block wget and curl by default. Use firefox or chrome to download it.

**Comment by farindk** [comment]
heif-info says that it is an aux image of type
`aux type: urn:com:apple:photo:2020:aux:hdrgainmap`

Never seen this before. The image itself is not HDR, so my guess is that it shows the per-pixel factors that were used when converting the original HDR image down to 8 bit.

libheif ignores this image because it does not know the type. Probably, I should extend the API such that all auxiliary images can still be accessed even if they have a proprietary type.

With some very wild hacking in a hex-editor, I could decode the aux image as this (looks somewhat similar to the color image, but it is not the same):
![aux-gain](https://user-images.githubusercontent.com/968944/100131398-44d06180-2e84-11eb-8ec6-824ae8387747.jpg)

**Comment by hackerfactor** [comment]
Whoa! That's the area that I selected for the focal depth!

**Comment by farindk** [comment]
I'm not sure I understand? The image region is the same as the color image.

I still think it's some 8bit vs. HDR gain factors. Would be interesting to see this for an image from inside a room with backlight from a window. E.g. high contrast between room and window that has to be equalized.

BTW: there are a few extra bytes attached to the aux image. Probably some factors defining the value range or similar attributes.

**Comment by hackerfactor** [comment]
I'll try to make a test picture with a high-contrast backlight later today.

Is there any special magic I can do to extract this image? (E.g., easy alteration of the HEIC pointers/values, simple tweak to libheif source.) Or should I just wait for a patch?

**Comment by farindk** [comment]
I used a hex editor to replace the aux type with "urn:mpeg:hevc:2015:auxid:2" (also add a null byte after that).
Then it decodes as a depth image.

**Comment by hackerfactor** [comment]
I have a patch:

1. Edit libheif/heif_context.cc
2. Jump down to the depth channel processing (search for "// depth channel")
3. Add in a check for Apple's new urn:

```
          if (auxC_property->get_aux_type() == "urn:mpeg:hevc:2015:auxid:2" || // HEIF
              auxC_property->get_aux_type() == "urn:com:apple:photo:2020:aux:hdrgainmap" || // New: Apple
              auxC_property->get_aux_type() == "urn:mpeg:mpegB:cicp:systems:auxiliary:depth") { // AVIF
            image->set_is_depth_channel_of(refs[0]);
```
This doesn't fix the crash, when a bad ID is passed to heif_image_handle_get_depth_image_handle.  But this does permit extracting the new aux type.

**Comment by farindk** [comment]
API for accessing auxiliary images has been added.
Closing this. For further discussion, use issue #389.
