### ISSUE TITLE
libheif unable to extract multiple auxC images

### ISSUE THREAD

**Issue by hackerfactor** [strukturag/libheif#389]
Related to issue 386:

I have a few instances of HEIC images with unsupported auxC types.
The types I have observed so far:
```
urn:com:apple:photo:2020:aux:hdrgainmap
urn:com:apple:photo:2020:aux:semanticglassesmatte
urn:com:apple:photo:2019:aux:semanticchairmatte
urn:com:apple:photo:2019:aux:semanticskinmatte
urn:com:apple:photo:2019:aux:semanticteethmatte
urn:com:apple:photo:2018:aux:portraiteffectsmatte
```

I modified libheif/heif_context.cc function HeifContext::interpret_heif_file() to recognize these types as depth maps.
```
          // depth channel
          if ((auxC_property->get_aux_type() == "urn:mpeg:hevc:2015:auxid:2") || // HEIF
              (auxC_property->get_aux_type() == "urn:com:apple:photo:2020:aux:hdrgainmap") || // Apple
              (auxC_property->get_aux_type() == "urn:com:apple:photo:2020:aux:semanticglassesmatte") || // Apple
              (auxC_property->get_aux_type() == "urn:com:apple:photo:2019:aux:semanticchairmatte") || // Apple
              (auxC_property->get_aux_type() == "urn:com:apple:photo:2019:aux:semanticskinmatte") || // Apple
              (auxC_property->get_aux_type() == "urn:com:apple:photo:2019:aux:semanticteethmatte") || // Apple
              (auxC_property->get_aux_type() == "urn:com:apple:photo:2018:aux:portraiteffectsmatte") || // Apple
              (auxC_property->get_aux_type() == "urn:mpeg:mpegB:cicp:systems:auxiliary:depth")) { // AVIF
```

I have some examples that list multiple HEIC "auxC" images. However, heif_image_handle_get_number_of_depth_images() only returns "1", even if there is one or more present. Moreover, heif_image_handle_get_list_of_depth_image_IDs() only returns the ID of the last one listed.

Since the two example images that I have show people's faces (and I don't known them or have permission), I'm hesitant to post the pictures here. However, I am attaching the "heif-info -d" listing for one of the pictures.

What I want/hope/expect:

- A function to list all of these auxC images, and not just the last one. (There are functions for thumbs and functions for depth maps. We need functions for generic aux images.)
- Probably should be cause 'aux' rather than 'depth', since most of these do not appear to be depth maps.
- If there are multiple depth maps, the the get_number_of_depth_images() function should return all of them, not just the last one.
- The aux list should probably be generic since Apple appears to revise the auxC type.  Either "starts with urn:com\:\apple\:photo:" or "if it's not a top level and not a thumb, then it's an aux."

[8ad6bb96.txt](https://github.com/strukturag/libheif/files/5611316/8ad6bb96.txt)

**Comment by hackerfactor** [comment]
Find a viable workaround:

lib/heif/heif_context.cc:
Find the line that says "if ((auxC_property->get_aux_type() == "urn:mpeg:hevc:2015:auxid:2") || // HEIF".
Change it to an "else if"
And right before it, add:
```
        // Apple thumbnails
        else if (auxC_property->get_aux_type().rfind("urn:com:apple:photo:")==0) // Apple
#if 0
                // Specific strings
              (auxC_property->get_aux_type() == "urn:com:apple:photo:2020:aux:hdrgainmap") || // Apple
              (auxC_property->get_aux_type() == "urn:com:apple:photo:2020:aux:semanticglassesmatte") || // Apple
              (auxC_property->get_aux_type() == "urn:com:apple:photo:2019:aux:semanticchairmatte") || // Apple
              (auxC_property->get_aux_type() == "urn:com:apple:photo:2019:aux:semanticskinmatte") || // Apple
              (auxC_property->get_aux_type() == "urn:com:apple:photo:2019:aux:semanticteethmatte") || // Apple
              (auxC_property->get_aux_type() == "urn:com:apple:photo:2018:aux:portraiteffectsmatte") || // Apple
#endif
          {
          image->set_is_thumbnail_of(refs[0]);
          auto master_iter = m_all_images.find(refs[0]);
          if (master_iter == m_all_images.end()) {
              return Error(heif_error_Invalid_input,
                         heif_suberror_Nonexisting_item_referenced,
                         "Apple Thumbnail references a non-existing image");
            }

          if (master_iter->second->is_thumbnail()) {
              return Error(heif_error_Invalid_input,
                         heif_suberror_Nonexisting_item_referenced,
                         "Apple Thumbnail references another thumbnail");
            }

          if (image.get() == master_iter->second.get()) {
              return Error(heif_error_Invalid_input,
                         heif_suberror_Nonexisting_item_referenced,
                         "Apple Recursive thumbnail image detected");
            }
          master_iter->second->add_thumbnail(image);
          remove_top_level_image(image);
          } // if Apple
```
What this code does:
Rather than treating all auxC as a depth map (and only supporting one depth map), treat any auxC that starts with "com:\apple:photo:" as a thumbnail. The current libheif library supports multiple thumbnails, so the pictures can be retrieved that way.

**Comment by farindk** [comment]
I have implemented a proper API to access the auxiliary images (95f116a).
When using `heif-convert`, it should now output a separate image for each auxiliary image. E.g.:
````
$ ./heif-convert input.heic out.png
File contains 1 images
Written to out.png
Auxiliary image written to out-urn:com:apple:photo:2020:aux:hdrgainmap.png
````

Could you please check whether this works for you?
It also would be great if you could send me a couple of images with the other aux image types. I am in particular interested to see if they have some "subtypes" data associated in their `auxC` box. If that is the case, I might have to add a function to read this data.

@hackerfactor Send me an email if you need a place where to upload the images.

**Comment by hackerfactor** [comment]
Tested. Confirmed -- works great! Thank you.

**Comment by farindk** [comment]
Thanks for testing. Merged to master.
