### ISSUE TITLE
Cannot load from non-ANSI paths on Windows

### ISSUE THREAD

**Issue by tomalakgeretkal** [strukturag/libheif#398]
`HeifFile::read_from_file` is going to need to pass UTF-16 in a `wchar_t*` into Microsoft's non-standard `ifstream` constructor, otherwise all you can use is ANSI paths.

I propose we treat the input `const char*` as UTF-8 and add a conversion.

The whole thing can be wrapped in a macro so as not to affect other platforms at all.

**Comment by farindk** [comment]
Fixed in #399.
