### ISSUE TITLE
heic write broken in latest release

### ISSUE THREAD

**Issue by lgritz** [strukturag/libheif#405]
Hi, I'm the leader of OpenImageIO, a downstream consumer of libheif.

My tests started failing when Homebrew bumped to the new 1.10.0 release. When writing heic files, I end up with a corrupted or possibly truncated file that can't be read properly by either my software or by MacOS's Preview.app.

I was able to narrow down the specific commit: 1449f182e0, dated Nov 13, which has the comment "only wrap heif image in grid if it has an odd size". Building at that commit fails, whereas the immediately prior commit (45f708220c) works for me.

I thought maybe some of the APIs changed or that just some code paths broke in a very specific way. I happen to use the C++ API and thought maybe that was the problem, so tonight I recoded my heic writer using only your C API. That did not help.

I also suspected that perhaps my use of interleaved channels (heif_channel_interleaved, etc.) was the culprit, so I changed that to have non-interleaved, separately heif_image_add_plane for each channel, but that also did not solve the problem.

I don't have a lot of heic images to test with, so I can't give you a comprehensive rundown of all parameters that break, or if it's only a subset of files that have problems. But if it helps, the image I'm writing when it corrupts the file is 8 bits per channel, RGB. I don't get any exceptions (when using the C++ API), nor any non-OK error return codes (when using the C API). All calls appear to succeed, but the resulting file is invalid somehow. It's not just that the pixels are messed up... it seems to result in an invalid heic file entirely -- Apple Preview.app opens a dialog saying that it couldn't read and "It may be damaged or use a file format that Preview doesn’t recognize", and my reading software as I said does not detect any errors returned from libheif but nonetheless ends up with a nonsensical header data (0 pixels wide, and other fields missing or obviously wrong). And in both cases, the failure is 100% reproducible, it does not appear to be sporadic, like you might see for an uninitialized variable or other undefined behavior.

I'm afraid I don't know anything about libheif internals, so this is about as far as I've been able to trace things. But perhaps knowing on which commit things started to break and with the other breadcrumbs I've left, somebody on your dev team can look at the diffs for that checkin and spot the likely culprit.

I haven't tried on platforms other than Mac, but I can also build for Linux and try there if that would help you narrow things down. Also, if it helps you, I can send you one of the corrupted files. Just let me know if there's more I can do to point you in the right direction.

**Comment by ecc521** [comment]
Can confirm that the current build does not work with MacOS Preview. example.heif is working with libheif and the browser demos, but is not opening in Preview.

**Comment by sofire** [comment]
I use version 1.9.1,  heif-info get:
image: 1242x1242 (id=1), primary

version 1.10.0, heif-info get:
image: 0x0 (id=1), primary

**Comment by jcupitt** [comment]
I see this problem too (I think it's the same one) with git master libheif on linux:

```
john@yingna ~/pics $ heif-enc sample.jpg -o x.heic
john@yingna ~/pics $ heif-info x.heic
MIME type: image/heic
image: 0x0 (id=1), primary
  color profile: prof
  alpha channel: no
  depth channel: no
```

The `(0x0)` is the size reported by `heif_image_handle_get_width()` and `heif_image_handle_get_height()` on the primary image handle. You can decode `x.heic` with `heif-convert`, but no other program I have can read it (since the size has not been set correctly).

If you `git checkout v1.9.1` in the libheif repo and build that, you see:

```
john@yingna ~/pics $ heif-enc sample.jpg -o x.heic
john@yingna ~/pics $ heif-info x.heic
MIME type: image/heic
image: 290x442 (id=1), primary
  color profile: prof
  alpha channel: no
  depth channel: no
```

And I can read it everywhere, so it seems to be a problem introduced since perhaps October.

**Comment by jcupitt** [comment]
I tried the two commits @lgritz identified and I can confirm that https://github.com/strukturag/libheif/commit/1449f182e0bdee574ca98aa9b06defd38a94dea9 seems to be the one that causes this.

**Comment by ndurner** [comment]
Yes, 1.9.1 is not affected. So workaround with homebrew:

1. brew unlink libheif
2. wget https://raw.githubusercontent.com/Homebrew/homebrew-core/11b57fac1637eccffdefb1d44140a1325ef0234e/Formula/libheif.rb -O /tmp/libheif.rb
2. brew install /tmp/libheif.rb

**Comment by zhutq** [comment]
Thanks a lot for @ndurner 's workaround
For those who see
```
Warning: libheif 1.9.1 is already installed, it's just not linked
You can use `brew link libheif` to link this version.
```
but ` brew link libheif` links back to 1.10.0, remove 1.10.0 first:
```
rm -rf /usr/local/Cellar/libheif/1.10.0
brew link libheif 
```
I also pinned `libheif` to avoid it being upgraded:
```
brew pin libheif
```

**Comment by hjmallon** [comment]
There is very little in that change. Removing non functional changes gets

```diff
diff --git a/libheif/heif_context.cc b/libheif/heif_context.cc
index aac8170..b74fb4a 100644
--- a/libheif/heif_context.cc
+++ b/libheif/heif_context.cc
@@ -1946,9 +1946,9 @@ Error HeifContext::encode_image_as_hevc(std::shared_ptr<HeifPixelImage> image,
   // if image size was rounded up to even size, add a 'clap' box to crop the
   // padding border away
 
-  if (options->macOS_compatibility_workaround == false) {
   if (out_image->get_width() != encoded_width ||
       out_image->get_height() != encoded_height) {
+    if (options->macOS_compatibility_workaround == false) {
       m_heif_file->add_clap_property(image_id,
                                      out_image->get_width(),
                                      out_image->get_height(),
@@ -1957,7 +1957,6 @@ Error HeifContext::encode_image_as_hevc(std::shared_ptr<HeifPixelImage> image,
 
       m_heif_file->add_ispe_property(image_id, out_image->get_width(), out_image->get_height());
     }
-  }
     else {
       // --- wrap the encoded image in a grid image just to apply the cropping
 
@@ -1990,6 +1989,7 @@ Error HeifContext::encode_image_as_hevc(std::shared_ptr<HeifPixelImage> image,
       // now use the grid image for all further property output
       image_id = grid_image_id;
     }
+  }
 
 
   // --- choose which color profile to put into 'colr' box
```

**Comment by lgritz** [comment]
It's very possible that this is just the commit that made the problem symptomatic (because of the slightly changed conditionals here), and that the ultimate culprit for why exactly the written files are showing 0x0 resolution lies elsewhere.

**Comment by farindk** [comment]
Please try the new version above and let me know whether that fixed it.

**Comment by lgritz** [comment]
@farindk YES, appears to fix!

**Comment by ndurner** [comment]
Confirmed.

**Comment by jcupitt** [comment]
Working here too! With git master libheif I see:

```
john@yingna ~/pics $ heif-enc k2.jpg -o x.heic
john@yingna ~/pics $ heif-info x.heic 
MIME type: image/heic
image: 1450x2048 (id=1), primary
  color profile: nclx
  alpha channel: no
  depth channel: no
```

Thank you very much @farindk !

**Comment by farindk** [comment]
Thanks for confirming this.

**Comment by lgritz** [comment]
If 1.11 is not coming fairly soon, is there any chance of incorporating this fix into a 1.10.1 release? The version of libheif installed by Homebrew is the broken one.

**Comment by farindk** [comment]
I plan to finish the 1.11 this weekend.

**Comment by sethify** [comment]
I had an image where `heif-info` reported the size correctly, but it also could not be displayed (generated with libvips), reverting to 1.9.1 also corrected the issue.
