### ISSUE TITLE
heif_image_handle_get_auxiliary_type needs a free method

### ISSUE THREAD

**Issue by 0xC0000054** [strukturag/libheif#406]
The `heif_image_handle_get_auxiliary_type` method should have accompanying `heif_auxiliary_type_free` method.

Currently, callers of `heif_image_handle_get_auxiliary_type` must use the C runtime `free` method.
This is problematic when libheif is compiled as a Windows DLL, `malloc` and `free` are only guaranteed to work when called from the same DLL.

**Comment by farindk** [comment]
Right. Thanks for noting that. Has been added in the commit above.
