### ISSUE TITLE
Cannot download x265

### ISSUE THREAD

**Issue by RosenZhu** [strukturag/libheif#410]
Any idea why  `hg clone --branch stable http://hg.videolan.org/x265 x265` results in a timeout?
The server of x265 is down?

**Comment by hackerfactor** [comment]
It's been offline since Dec 18th.
https://mailman.videolan.org/pipermail/x265-devel/2020-December/013204.html

When I previously asked videolan about it, they said "soon".  But that was over a week ago. No ETA and nothing about where to get it right now.

**Comment by RosenZhu** [comment]
Thanks!
