### ISSUE TITLE
Cannot convert HEIC image

### ISSUE THREAD

**Issue by anddam** [strukturag/libheif#412]
Trying to convert an iPhone 12 Pro HEIC image using 1.10.0 `heif-convert` built-in tool results in

```
$ heif-convert IMG_3005.HEIC  IMG_3005.png
File contains 1 images
Could not decode image: 0: Unsupported feature: Unsupported codec
```

while `heif-info` shows:

```
$ heif-info IMG_3005.HEIC
MIME type: image/heic
image: 3024x4032 (id=49), primary
  color profile: prof
  alpha channel: no
  depth channel: yes
 (576x768)
    z-near: undefined
    z-far:  undefined
    d-min:  0.167725
    d-max:  2.292969
    representation: uniform disparity
    disparity_reference_view: 0
```

Is this due to some oddity in Apple saved images or is there a problem on my setup?

I built libheif from 1.10.0 tag using libjpeg-turbo 2.0.6 and libpng 1.6.37 on a Void Linux (glibc) system.

**Comment by farindk** [comment]
Have you built libheif with the libde265 dependency? Please check the
configure output.


anddam <notifications@github.com> schrieb am Mo., 28. Dez. 2020, 23:39:

**Comment by anddam** [comment]
Seems I was not, I added `libde265`. I saw a sherlock feature that was not going to build examples so I added `libswscale` and `SDL2_gfx` as well for good measure (my OS does not offer a packaged `libvideogfx`).

I am able to convert HEIC files now, thanks.
