### ISSUE TITLE
LNK2019 libde265_free_decoder(void *)

### ISSUE THREAD

**Issue by pol2095** [strukturag/libheif#413]
Hello,

I have this message error when I add "libde265.lib" in CMAKE

`Error	LNK2019	unresolved external symbol __imp_de265_free_decoder referenced in function "void __cdecl libde265_free_decoder(void *)" `

Thanks

**Comment by 0xC0000054** [comment]
You need to define `LIBDE265_STATIC_BUILD` in the preprocessor section of the project properties.
By default, libde265 assumes that you are linking to a DLL.

**Comment by pol2095** [comment]
I added `set(CMAKE_CXX_EXTENSIONS OFF)` in "CMakeLists.txt", CMake create a static library I think but I have this message error when I try to generate the dll.

**Comment by 0xC0000054** [comment]
> I think but I have this message error when I try to generate the libheif.dll.

You need to define LIBDE265_STATIC_BUILD in the preprocessor section of the `heif` project properties.
Or add `-DLIBDE265_STATIC_BUILD=1` to the CMake options when generating the Visual Studio project for libheif.

**Comment by pol2095** [comment]
I think it's the same property if you define `set(BUILD_SHARED_LIBS OFF)`
```
option(BUILD_SHARED_LIBS "Build shared library" ON)
if(NOT BUILD_SHARED_LIBS)
  add_definitions(-DLIBDE265_STATIC_BUILD)
endif()
```

**Comment by pol2095** [comment]
You're right it's necessary to add `add_definitions(-DLIBDE265_STATIC_BUILD)` in heif "CMakeLists.txt" too.
