### ISSUE TITLE
How to run heif_enc?

### ISSUE THREAD

**Issue by aaaaeerr** [strukturag/libheif#42]
I have install X265 and turn on HAVE_X265 ,but i can't find heif_encoder_x265.h . should I rename x265.h to heif_encoder_x265.h.

**Comment by farindk** [comment]
I don't quite understand the question. The file "heif_encoder_x265.h" is not installed as public header file. It is only used internally. When you compile libheif with support for x265 and then query the list of encoders (heif_context_get_encoder_descriptors(), or heif_context_get_encoder_for_format(..., heif_compression_HEVC) ), it will return the x265 encoder plugin as an option.

**Comment by aaaaeerr** [comment]
OK！ Thank you！ I made a mistake ！
