### ISSUE TITLE
Where can user find jpeg2000 compatible with heif container?

### ISSUE THREAD

**Issue by Jamaika1** [strukturag/libheif#420]
https://jpeg.org/jpeg2000/index.html
_Part 16 specifies the carriage of JPEG 2000 codestreams in ISO/IEC 23008-12, commonly referred to as HEIF. A revision is underway to support more flexible wrapping of all JPEG 2000 codestreams, including HTJ2K._

**Comment by bradh** [comment]
libheif can now write this. So you can create whatever you need.

**Comment by Jamaika1** [comment]
Thanks for the info. It's been while since I created libheif.
As far as I know openjpeg doesn't create htj2k. Is libheif compatible with htj2k? I don't know. Give examples of commands.

**Comment by bradh** [comment]
OpenJPEG supports HT (part 15) for decoding as of 2.5.0. There is a discussion topic about the proposed part 16 update in #1054.

Also, your response comes across as demanding, and will point out I was only trying to help with the original question about jpeg2000 source data.

**Comment by bradh** [comment]
You can also test with https://github.com/bradh/libheif/tree/openjph which implements the Part 16 encoding using OpenJPH.

**Comment by Jamaika1** [comment]
Super. I just created a libheif encoder with openjph in C++11. heif(j2c) is created, but I am missing the function j2c/j2k -> heif(j2c/j2k) -> j2c/j2k.
