### ISSUE TITLE
Libheif fails to build on Ubuntu 20.04.1

### ISSUE THREAD

**Issue by dansloane** [strukturag/libheif#428]
I'm trying to add HEIC support to Imagemagick using the steps shown [here](https://askubuntu.com/a/1142317) and in other places. 

After autogen and configuring, make fails with the following libtool error:

```
libtool: link: ar cr .libs/libpixbufloader-heif.a  libpixbufloader_heif_la-pixbufloader-heif.o
libtool: link: ranlib .libs/libpixbufloader-heif.a
/usr/bin/sed: can't read Gallery/libheif/libheif/libheif.la: No such file or directory
libtool:   error: 'Gallery/libheif/libheif/libheif.la' is not a valid libtool archive
make[2]: *** [Makefile:471: libpixbufloader-heif.la] Error 1
```

I can't see a Gallery directory and `find . libpixbufloader-heif*` yields no results.

I've Googled this error, but can't find any similar issues.  Any clues? 

Thanks in advance

**Comment by mcaptk** [comment]
I had the same issue as you.  Maybe this is too late or you've already figured it out, but I ended up seeing that my parent directory had a space in the name.  I removed the space, and repeated the steps and then it built clean.  Here's to hoping you have the same simple problem.

**Comment by dansloane** [comment]
Thanks - weirdly, having given up on this and moved onto more interesting problems, I've just tried again using the same steps and everything complied and installed correctly.  Maybe something else changed. 

` % convert -version
Version: ImageMagick 7.0.10-59 Q16 x86_64 2021-01-24 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5)
Delegates (built-in): bzlib djvu fontconfig freetype **heic** jbig jng jpeg lcms lqr lzma openexr png tiff x xml zlib`
