### ISSUE TITLE
How can I use VS to compile libheif?

### ISSUE THREAD

**Issue by aaaaeerr** [strukturag/libheif#43]
Sorry to bother you 。Can I use VS to compile libheif?

**Comment by farindk** [comment]
There is a config file for CMake that you can use to compile with VS.
We are continuously testing with VS-2015 to make sure it compiles correctly. See here: https://ci.appveyor.com/project/strukturag/libheif

**Comment by aaaaeerr** [comment]
where can I get the config file ?

**Comment by fancycode** [comment]
The files are in the repository.

CMake configuration:
https://github.com/strukturag/libheif/blob/master/CMakeLists.txt

AppVeyor configuration:
https://github.com/strukturag/libheif/blob/master/appveyor.yml
