### ISSUE TITLE
compiling as a dependency with cmake help for newbie

### ISSUE THREAD

**Issue by CharStiles** [strukturag/libheif#430]
Hi,
I am looking to compile the libheif as an external dependency in a cpp project using just cmake. I know vcpkg has it, but Im working on a team w people who dont have vcpkg, also I need it to build for OSX.

So far I have tried exporting pre-compiled binaries from vcpkg, I ran into many problems, also I dont think it will build for mac this way. 

I am now trying to use find_package and then target_link_libraries, first I add libheif sourcecode to my project:

`git submodule add [https://github.com/strukturag/libheif.git](https://github.com/strukturag/libheif.git) external/libheif`
I see a lot of other projects that use libheif as a dependency will have a Findlibheif.cmake file. So that is what I am trying. I use this [findlibheif.cmake](https://raw.githubusercontent.com/zzag/heifthumbnailer/5f3e8380728751cafd8f0da78eae1b7da2b0d9ff/cmake/Modules/Findlibheif.cmake) file

So, inside of CMakeLists.txt for my_project I have:
```
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_SOURCE_DIR}/cmake/Modules/)`

find_package(libheif)
target_link_libraries(hop_studio_api libheif::libheif)
target_link_libraries(hop_studio_cli libheif::libheif)
```

but I got stuck at these errors
`-- Could NOT find libheif (missing: libheif_LIBRARY libheif_INCLUDE_DIR)
`
and then later on

```
  Target "my_project" links to target "libheif::libheif" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```
So when building with the source do I need to compile the library first by using add_library and then use find_package so it can find the .lib files? What search terms should I use to look up this problem? I have tried “writing a find module to build from source” among others, but I cant find useful information.

Thank you for your time.

**Comment by CharStiles** [comment]
with the help of the _Professional CMake_ book, this is the solution:
```
include(FetchContent)

FetchContent_Declare(libheif
    GIT_REPOSITORY https://github.com/strukturag/libheif.git
    GIT_TAG 7976e1858a857e33200cd33d01689fd040de6d3d  # master
)
FetchContent_MakeAvailable(libheif)

# Add things that libheif neglects to add
target_include_directories(heif INTERFACE
    $<BUILD_INTERFACE:${libheif_BINARY_DIR}>
    $<BUILD_INTERFACE:${libheif_SOURCE_DIR}>
)

# Work around libheif mishandling how to link to gdk-pixbuf-2.0
if(UNIX AND TARGET pixbufloader-heif)
    find_package(PkgConfig)
    pkg_check_modules(GDKPIXBUF2 gdk-pixbuf-2.0)
    # We shouldn't need to do this, but libheif adds the wrong library variable and that requires
    # us to add the library directory so that the library is found at link time
    target_link_directories(pixbufloader-heif PRIVATE ${GDKPIXBUF2_LIBRARY_DIRS})
endif()
# libheif dependencies
include_directories(external/libjpeg)
add_subdirectory(external/libjpeg)
target_link_libraries(my_project libjpeg)
target_link_libraries(my_project libjpeg)

include_directories(external/libheifExtra)
```
Im sure there is a smarter way to include the examples, but what i did is that i took just the files I needed and put it into libheifExtra folder (I mostly just needed the encoder files). Then I also had to compile libjpeg, for some reason when I got it to compile and included in the project (Thanks to this repo https://github.com/stohrendorf/libjpeg-cmake) it did set the HAVE_LIBJPEG macro, so in the convert app I just added #define HAVE_LIBJPEG true
again, sure that there would be a better way of doing this, but this works and if anyone else runs into this challenge hopefully this can  help them out.

**Comment by silverbacknet** [comment]
FWIW, mainline libjpeg is widely Considered Harmful in the development community due to newer versions using a variety of untested and breaking changes. https://github.com/libjpeg-turbo/libjpeg-turbo is arguably the best place to get your jpeg from.
