### ISSUE TITLE
Possible Error in ImageGrid::write in heif_context.cc

### ISSUE THREAD

**Issue by chris0e3** [strukturag/libheif#432]
This is based on the v1.10.0 sources.

In the function `ImageGrid::write` in file heif_context.cc, line 225 you have:
```
  uint8_t flags = 0;
  if (field_size == 32) {
    flags |= 1;
  }
```
But you don’t use `flags` anywhere else.
Should there not be a line following the above such as:
```
  data[1] = flags;
```
Otherwise `data[1]` appears not to be set.

Or simply replace the whole thing with:
```
  data[1] = (field_size == 32) ? 1 : 0;
```

**Comment by farindk** [comment]
Yes, you are right. That line was missing. I have added it.
Thank you.
