### ISSUE TITLE
cmake CMakelist.txt -> libde265: not found, x265: not found

### ISSUE THREAD

**Issue by eubean7** [strukturag/libheif#436]
OS is windows10. 
vcpkg install libheif, then git clone libheif.
excute autogen.sh and build-emscripten.sh

![image](https://user-images.githubusercontent.com/75243276/106718863-f5a56a80-6644-11eb-96e5-44e0dbdf3e02.png)

i have libde265-1.0.2 !
cmake Cmakelist.txt in libheif folder but 
![image](https://user-images.githubusercontent.com/75243276/106718988-1a99dd80-6645-11eb-96ee-c956550668e4.png)
i don't know... 
change folder name libde265-1.0.2 -> libde265 but same result...

CMakeCache.txt result
![image](https://user-images.githubusercontent.com/75243276/106730618-eb3d9d80-6651-11eb-906c-54a15270232a.png)

how can i do? 
please help me

**Comment by silverbacknet** [comment]
On Windows, you have to either create an environment variable or manually specify a path in that directive that points to the right folder. Linux package managers take care of that for you if you use them, but if you build from git, you have to manually fix the path there too.

**Comment by eubean7** [comment]
Thanks to that, I can made an executable file!! Changed makefie manually.
I ran the following the readme.md file.
	./heif-convert example.heic example.jpeg
	./heif-enc example-1.jpeg -o example.heif

first result: Procedure entry point heif_image_handle_free_auxiliary_types could not located in the dynamic link library ....../heif-convert.exe
![image](https://user-images.githubusercontent.com/75243276/106870436-75e6d100-6714-11eb-987c-13b9c4aa6955.png)

second result:
![image](https://user-images.githubusercontent.com/75243276/106870560-957df980-6714-11eb-8664-b52e9f8f91ae.png)
The program crashes at the debugging point. 
An image file is created when annotation is processed. However, it is not a valid file.

Below is the log file when using cmake. 
cmake -G "Visual Studio 15 2017" -A x64 CMakeLists.txt -DCMAKE_TOOLCHAIN_FILE=C:\Dev\vcpkg\scripts\buildsystems\vcpkg.cmake
The dll and header files were taken from vcpkg's include.

C:\Work\libheif\build>cmake -G "Visual Studio 15 2017" -A x64 ../CMakeLists.txt -DCMAKE_TOOLCHAIN_FILE=C:\Dev\vcpkg\scripts\buildsystems\vcpkg.cmake
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19041.
-- The C compiler identification is MSVC 19.16.27045.0
-- The CXX compiler identification is MSVC 19.16.27045.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Performing Test has_potentially_evaluated_expression
-- Performing Test has_potentially_evaluated_expression - Failed
-- Found LIBDE265
-- Found Libde265: C:/Dev/vcpkg/installed/x64-windows/include (found version "1.0.8")
-- Found X265
-- Found X265: C:/Dev/vcpkg/installed/x64-windows/include (found version "192")
CMake Warning at cmake/modules/LibFindMacros.cmake:267 (message):
  WARNING: MISSING PACKAGE

  We could not find development headers for AOM.  Do you have the necessary
  dev package installed? This package is NOT REQUIRED and you may ignore this
  warning but by doing so you may miss some functionality of libheif.

  Relevant CMake configuration variables:

    AOM_INCLUDE_DIR=<not found>
    AOM_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/modules/FindLibAOM.cmake:30 (libfind_process)
  C:/Dev/vcpkg/scripts/buildsystems/vcpkg.cmake:650 (_find_package)
  CMakeLists.txt:68 (find_package)


CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:424 (message):
  The package name passed to `find_package_handle_standard_args` (AOM) does
  not match the name of the calling package (LibAOM).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindLibAOM.cmake:33 (find_package_handle_standard_args)
  C:/Dev/vcpkg/scripts/buildsystems/vcpkg.cmake:650 (_find_package)
  CMakeLists.txt:68 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find AOM (missing: AOM_INCLUDE_DIR AOM_LIBRARIES)
CMake Warning at cmake/modules/LibFindMacros.cmake:267 (message):
  WARNING: MISSING PACKAGE

  We could not find development headers for RAV1E.  Do you have the necessary
  dev package installed? This package is NOT REQUIRED and you may ignore this
  warning but by doing so you may miss some functionality of libheif.

  Relevant CMake configuration variables:

    RAV1E_INCLUDE_DIR=<not found>
    RAV1E_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/modules/FindRav1e.cmake:17 (libfind_process)
  C:/Dev/vcpkg/scripts/buildsystems/vcpkg.cmake:650 (_find_package)
  CMakeLists.txt:73 (find_package)


CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:424 (message):
  The package name passed to `find_package_handle_standard_args` (RAV1E) does
  not match the name of the calling package (Rav1e).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindRav1e.cmake:20 (find_package_handle_standard_args)
  C:/Dev/vcpkg/scripts/buildsystems/vcpkg.cmake:650 (_find_package)
  CMakeLists.txt:73 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find RAV1E (missing: RAV1E_INCLUDE_DIR RAV1E_LIBRARIES)
CMake Warning at cmake/modules/LibFindMacros.cmake:267 (message):
  WARNING: MISSING PACKAGE

  We could not find development headers for DAV1D.  Do you have the necessary
  dev package installed? This package is NOT REQUIRED and you may ignore this
  warning but by doing so you may miss some functionality of libheif.

  Relevant CMake configuration variables:

    DAV1D_INCLUDE_DIR=<not found>
    DAV1D_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/modules/FindDav1d.cmake:17 (libfind_process)
  C:/Dev/vcpkg/scripts/buildsystems/vcpkg.cmake:650 (_find_package)
  CMakeLists.txt:78 (find_package)


CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:424 (message):
  The package name passed to `find_package_handle_standard_args` (DAV1D) does
  not match the name of the calling package (Dav1d).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindDav1d.cmake:20 (find_package_handle_standard_args)
  C:/Dev/vcpkg/scripts/buildsystems/vcpkg.cmake:650 (_find_package)
  CMakeLists.txt:78 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find DAV1D (missing: DAV1D_INCLUDE_DIR DAV1D_LIBRARIES)
HEIF decoder, libde265: found
HEIF encoder, x265: found
AVIF encoder, aom: not found
AVIF decoder, aom: not found
AVIF encoder, rav1e: not found
AVIF decoder, dav1d: not found
-- Found JPEG: optimized;C:/Dev/vcpkg/installed/x64-windows/lib/jpeg.lib;debug;C:/Dev/vcpkg/installed/x64-windows/debug/lib/jpegd.lib (found version "62")
-- Performing Test HAVE_JPEG_WRITE_ICC_PROFILE
-- Performing Test HAVE_JPEG_WRITE_ICC_PROFILE - Success
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Work/libheif

I don't know what's the problem. Could you help me a little more?

**Comment by eubean7** [comment]
heif.dll is old.
build heif project and then outfile heif.dll update.
Works well.

Thanks to silverbacknet you can solve the problem.

**Comment by silverbacknet** [comment]
I've forgotten to run clean and scratched my head at the weird errors many times. Nothing to be ashamed of. 😅

**Comment by CharStiles** [comment]
> On Windows, you have to either create an environment variable or manually specify a path in that directive that points to the right folder. Linux package managers take care of that for you if you use them, but if you build from git, you have to manually fix the path there too.

Hi, How do you do this? I have tried 
```
set(LIBDE265_INCLUDE_DIR 
${CMAKE_SOURCE_DIR}/external/libde265/libde265
)

set(LIBDE265_LIBRARY ${CMAKE_SOURCE_DIR}/build/external/libde265/libde265/Release/libde265.lib)
```
This felt really wrong plus I run into linker errors like this:
```
heif.lib(heif_decoder_libde265.obj) : error LNK2019: unresolved external symbol __imp_de265_get_version referenced in function "char const * __cdecl 
 libde265_plugin_name(void)" (?libde265_plugin_name@@YAPEBDXZ) [C:\Users\me\Desktop\my_project\my_project_api\build\my_project_cli.vcx 
proj]
```
What variable do I set?
Thank you!
