### ISSUE TITLE
Speed up heif encoding

### ISSUE THREAD

**Issue by eubean7** [strukturag/libheif#437]
Excute heif-enc project

    error = heif_context_encode_image(context.get(),
                                      image.get(),
                                      encoder,
                                      options,
                                      &handle);

when measuring the speed, it came out about 9-10 seconds.

I want convert time is 200msec. 
if i bitmap->heic or rawdata->heic, is it possible?

am i missing something? or have a good idea?

**Comment by farindk** [comment]
10 seconds sound like much. What is the image resolution, what are the encoder settings? The easiest way to reduce computation complexity is to set the x265 'preset' parameter when encoding, e.g. to 'veryfast'. See `heif-enc` how to pass through x265 parameters.

**Comment by farindk** [comment]
Closing as this is obviously an x265 encoder "issue".
