### ISSUE TITLE
Use-of-uninitialized-value (8158)

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libheif#44]
The @ImageMagick project is using https://github.com/google/oss-fuzz to find bugs in our own library and in libraries that we use. The fuzzer found an issue and we think this is an issue that should be resolved in the library that we use. This issue is posted under the url https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8158 that is not publicly visible yet but added as a link for future reference. Below are the details of the issue that can be reproduced using the following technique: https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md

Stacktrace:
```
#0 0x15b8c88 in heif::HeifContext::decode_full_grid_image(unsigned int, std::__1::shared_ptr<heif::HeifPixelImage>&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&) const libheif/libheif/heif_context.cc:987:28
--
  | #1 0x15b2765 in heif::HeifContext::decode_image(unsigned int, std::__1::shared_ptr<heif::HeifPixelImage>&, heif_decoding_options const*) const libheif/libheif/heif_context.cc:822:13
  | #2 0x15b07d2 in heif::HeifContext::Image::decode_image(std::__1::shared_ptr<heif::HeifPixelImage>&, heif_colorspace, heif_chroma, heif_decoding_options const*) const libheif/libheif/heif_context.cc:728:31
  | #3 0x158e433 in heif_decode_image libheif/libheif/heif.cc:458:33
  | #4 0x109acd2 in ReadHEICImage imagemagick/coders/heic.c:267:9
  | #5 0x7d3ce9 in ReadImage imagemagick/MagickCore/constitute.c:500:13
  | #6 0x6fd87a in BlobToImage imagemagick/MagickCore/blob.c:473:13
  | #7 0x593661 in Magick::Image::read(Magick::Blob const&) imagemagick/Magick++/lib/Image.cpp:4029:12
  | #8 0x4a4f5c in LLVMFuzzerTestOneInput imagemagick/Magick++/fuzz/encoder_fuzzer.cc:46:11
  | #9 0x4ec19c in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:526:13


```
Links: https://github.com/strukturag/libheif/blob/2706077d0fe4019e4555bebb46e98ff57b850e63/libheif/heif_context.cc#L987

Commit: 2706077d0fe4019e4555bebb46e98ff57b850e63
Testcase file: [clusterfuzz-testcase-minimized-encoder_heic_fuzzer-5362068734607360.zip](https://github.com/strukturag/libheif/files/2138888/clusterfuzz-testcase-minimized-encoder_heic_fuzzer-5362068734607360.zip)

**Comment by farindk** [comment]
Thanks for reporting this. Fixed in 01fe0a8.
