### ISSUE TITLE
heif-enc -A -P segfault

### ISSUE THREAD

**Issue by dbquarrel** [strukturag/libheif#441]
Platform macOS big sur

```
% uname -A

Darwin tome.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
```

Simple crash trying to get parameter help.

```
% heif-enc -A -P

Parameters for encoder `AOMedia Project AV1 Encoder 2.0.2`:
  realtime, default=false
  speed, default=5, [0;8]
  threads, default=4, [1;16]
  quality, default=50, [0;100]
  lossless, default=false
  chroma, default=420, { 420,422,444 }
  tune, default=ssim, { psnr,ssim,Segmentation fault
```

```
% brew info libheif

libheif: stable 1.11.0 (bottled)
ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
https://www.libde265.org/
/usr/local/Cellar/libheif/1.11.0 (25 files, 2.8MB) *
  Poured from bottle on 2021-02-11 at 19:45:06
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libheif.rb
License: LGPL-3.0-only
==> Dependencies
Build: pkg-config ✔
Required: aom ✔, jpeg ✔, libde265 ✔, libpng ✔, shared-mime-info ✔, x265 ✔
```

**Comment by farindk** [comment]
Probably fixed with 2d3139152c68dec7deb2d87aa3832a80f3322b19. Can you please confirm?

**Comment by dbquarrel** [comment]
Confirmed fixed.

My machine has changed to an M1 Mac from an Intel Mac.

Build with go failed out of the box so I had to configure with --disable-go ... not a go user so the intricacies of why are beyond me.

Built in /tmp as I have libheif installed with homebrew.

ln -sf /private/tmp/libheif/examples/../go /private/tmp/libheif/examples/src/github.com/strukturag/libheif/
GOPATH=/private/tmp/libheif/examples PKG_CONFIG_PATH=:/tmp/libheif:/tmp/libheif/libde265/dist/lib/pkgconfig/ CGO_CFLAGS="-I/tmp/libheif" CGO_LDFLAGS="-L/tmp/libheif/libheif/.libs" LD_LIBRARY_PATH=/tmp/libheif/libheif/.libs /opt/homebrew/bin/go build -o heif-test-go heif-test.go
heif-test.go:39:2: no required module provides package github.com/strukturag/libheif/go/heif: go.mod file not found in current directory or any parent directory; see 'go help modules'

Non-issue for me as I don't need go functionality but thought I'd note it.

**Comment by bradh** [comment]
Ticket can probably be closed as resolved.

**Comment by farindk** [comment]
Thanks.
