### ISSUE TITLE
including libde265 help

### ISSUE THREAD

**Issue by CharStiles** [strukturag/libheif#446]
I can not figure out how to include libde265 in my cmake project. I am using git submodules to include both libde265 and libheif. I get `unsupported codec` whenever I try to decode a heic file. I looked an confirmed this is because libheif doesnt recognize the libde265 library. I am using windows.

this is the relevant parts of cmakelists.txt

```
# libde265
add_subdirectory(external/libde265)
include_directories(
${CMAKE_SOURCE_DIR}/external/libde265/libde265
${CMAKE_SOURCE_DIR}/build/external/libde265/libde265
${CMAKE_SOURCE_DIR}/build/external/libde265
${CMAKE_SOURCE_DIR}/external/libde265
)
target_link_libraries(my_project libde265)

# libheif

add_subdirectory(external/libheif)
include_directories(
${CMAKE_SOURCE_DIR}/external/libheif
${CMAKE_SOURCE_DIR}/build/external/libheif
)
target_link_libraries(my_project heif)
```

I see [here](https://github.com/strukturag/libheif/issues/436#issuecomment-772750763) @silverbacknet said if youre on windows you need to set an environment variable, the question is what environment variable. I have tried 
```
set(LIBDE265_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/external/libde265/libde265)
set(LIBDE265_LIBRARY external/libde265)
```
It is found when compiling, but I still get the `unsupported codec` error

I have also tried adding add_definitions(-DLIBDE265_STATIC_BUILD) in libheif "CMakeLists.txt" [like this issue](https://github.com/strukturag/libheif/issues/413#issuecomment-753485750) suggests.
I still get `HEIF decoder, libde265: not found`  when running `cmake ..`
How can I make sure the find_package call in libheif
s cmakelists.txt file can find the installed libde265? What environment variable do I need to set? is that the only thing I need to do?

Any help appreciated. Thank you.

**Comment by CharStiles** [comment]
I have tried
```
set(LIBDE265_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/external/libde265")
set(LIBDE265_LIBRARY ${CMAKE_SOURCE_DIR}/build/external/libde265/libde265/Release/libde265.lib)
```
I get ,ultiple errors like this when building
```
heif.lib(heif_decoder_libde265.obj) : error LNK2019: u 
nresolved external symbol __imp_de265_decode reference 
d in function "struct heif_error __cdecl libde265_v1_d 
ecode_image(void *,struct heif_image * *)" (?libde265_ 
v1_decode_image@@YA?AUheif_error@@PEAXPEAPEAUheif_imag 
e@@@Z) [C:\Users\me\Desktop\myproject\my_project_api\build\external\libheif\example 
s\heif-test.vcxproj]
```
leading me to believe that the functions are declared but there is no body to them. So that means that Im setting the library path wrong? Please help! I feel like its such a simple solution I am not seeing!

**Comment by farindk** [comment]
Theoretically, a "cmake -DWITH_LIBDE265=OFF -DWITH_X265=OFF ..." should work.
