### ISSUE TITLE
Crash in Op_RGB_HDR_to_RRGGBBaa_BE::convert_colorspace

### ISSUE THREAD

**Issue by chris0e3** [strukturag/libheif#449]
I experienced a 100% reproducible crash in `Op_RGB_HDR_to_RRGGBBaa_BE::convert_colorspace` when
`input->has_channel(heif_channel_Alpha)` returns true but `target_state.has_alpha` is false.

File: heif_colorconversion.cc, line: 1069
```
Op_RGB_HDR_to_RRGGBBaa_BE::convert_colorspace(const std::shared_ptr<const HeifPixelImage>& input, …
…
  bool has_alpha = input->has_channel(heif_channel_Alpha);    // ← has_alpha is true
  outimg->create(width, height, heif_colorspace_RGB,
                 target_state.has_alpha ? heif_chroma_interleaved_RRGGBBAA_BE : heif_chroma_interleaved_RRGGBB_BE);
```

This results in `outimg` being created with chroma = interleaved_RRGGBB_BE i.e. no alpha, but then having alpha values written to it as that is decided by `has_alpha` and `target_state.has_alpha` is ignored.

I stopped the crash by changing it to:
```
  outimg->create(width, height, heif_colorspace_RGB,
                 /*target_state.*/has_alpha ? heif_chroma_interleaved_RRGGBBAA_BE : heif_chroma_interleaved_RRGGBB_BE);
```

I don’t know if that is fully correct or whether the output generation needs an alternate case for `if (!has_alpha && target_state.has_alpha) …` instead.

Similarly, `Op_RGB_to_RRGGBBaa_BE::convert_colorspace` appears to contain the same logic, so probably requires a similar fix.
However, `Op_RGB_to_RRGGBBaa_BE::convert_colorspace` also appears to be using the wrong bytes-per-pixel when `!has_alpha`.  I think it should be 6 (rather than 8).

lines: 1286 .. 1291
```
        out_p[y * out_p_stride + 8 * x + 0] = 0;
        out_p[y * out_p_stride + 8 * x + 1] = in_r[x + y * in_r_stride];
        out_p[y * out_p_stride + 8 * x + 2] = 0;
        out_p[y * out_p_stride + 8 * x + 3] = in_g[x + y * in_g_stride];
        out_p[y * out_p_stride + 8 * x + 4] = 0;
        out_p[y * out_p_stride + 8 * x + 5] = in_b[x + y * in_b_stride];
```
Should be:
```
        out_p[y * out_p_stride + 6 * x + 0] = 0;
        out_p[y * out_p_stride + 6 * x + 1] = in_r[x + y * in_r_stride];
        out_p[y * out_p_stride + 6 * x + 2] = 0;
        out_p[y * out_p_stride + 6 * x + 3] = in_g[x + y * in_g_stride];
        out_p[y * out_p_stride + 6 * x + 4] = 0;
        out_p[y * out_p_stride + 6 * x + 5] = in_b[x + y * in_b_stride];
```
Or even better :-):
```
      auto dst = &out_p[y * out_p_stride];
      for (int x = 0; x < width; ++x, dst += 6) {
        dst[0] = 0;
        dst[1] = in_r[x];
        dst[2] = 0;
        dst[3] = in_g[x];
        dst[4] = 0;
        dst[5] = in_b[x];
      }
      in_r += in_r_stride;
      in_g += in_g_stride;
      in_b += in_b_stride;
```

**Comment by farindk** [comment]
Thanks, @chris0e3 .
The fix should actually be a bit different. The color-conversion stage promises that is may add an alpha channel, but it announces that it will never remove an alpha channel, but that is what happened in your case.

I have changed it in the way I think is correct, but I cannot confirm this as I didn't have a case to reproduce this.
Could you please check if it works now?
The main point I am worried about is whether you will get the output image that you expect (i.e. without alpha channel).
If the output is wrong, could you please enable `DEBUG_PIPELINE_CREATION` at the top of the file and send me the output?

**Comment by chris0e3** [comment]
@farindk,
> I have changed it in the way I think is correct, but I cannot confirm this as I didn't have a case to reproduce this.
> Could you please check if it works now?

The output is now byte-for-byte identical to what I was getting with my change as `input_has_alpha` implies `output_has_alpha` in your change, as `has_alpha` did in my change.  I too don’t have a test case that exercises the new RGB → RGBA support in this function.  I’m not clear under what circumstances it would be triggered.

> The main point I am worried about is whether you will get the output image that you expect (i.e. without alpha channel).
> If the output is wrong, could you please enable `DEBUG_PIPELINE_CREATION` at the top of the file and send me the output?

Output is as expected now.

I think your change to `Op_RGB_to_RRGGBBaa_BE::convert_colorspace` line 1305 should be:
```
        if (output_has_alpha) {
          out_p[y * out_p_stride + pixelsize * x + 6] = 0;
          out_p[y * out_p_stride + pixelsize * x + 7] = 0xFF;
        }
```
Where you are currently setting both bytes to `0xFF`.

**Comment by farindk** [comment]
Thanks for spotting the error. I have corrected that.
