### ISSUE TITLE
Unnecessary copying of child-boxes vector

### ISSUE THREAD

**Issue by chris0e3** [strukturag/libheif#450]
A small optimisation :-).

Functions `Box_ipco::get_properties_for_item_ID` & `Box_ipco::get_property_for_item_ID` make unnecessary copies of `m_children` vector.

File box.cc, line 1947:
```
  auto allProperties = get_all_child_boxes();
```
Should be:
```
  auto& allProperties = get_all_child_boxes();
```

The above occurs again at line 1981.

**Comment by farindk** [comment]
changed it.
