### ISSUE TITLE
Problem with convert heic to jpg

### ISSUE THREAD

**Issue by msly** [strukturag/libheif#458]
[test.zip](https://github.com/strukturag/libheif/files/6059479/test.zip)

heif-convert  test.heic  test.jpg
![test.jpg](https://user-images.githubusercontent.com/3837731/109458885-a8c48080-7a98-11eb-8c79-ae9eee635b56.jpg)

libheif 1.11.0

test.heic HEIC 3072x4096 3072x4096+0+0 10-bit YCbCr
exif:Make: OPPO
exif:Model: PEEM00

**Comment by msly** [comment]
fixed  #https://github.com/strukturag/libheif/commit/115c96a96a583dfa72d12eeb9b24506016dafe5d

**Comment by farindk** [comment]
Thank you for checking this.
