### ISSUE TITLE
saving nclx/cicp values works for avif but not heif

### ISSUE THREAD

**Issue by therahedwig** [strukturag/libheif#462]
When writing unittests, I noticed that saving and loading NCLX/CICP values doesn't work for heif, but it does work for avif.

[heif_avif_cicp_rec2020.zip](https://github.com/strukturag/libheif/files/6063457/heif_avif_cicp_rec2020.zip)

**Comment by novomesk** [comment]
Try to set heif_encoding_options.macOS_compatibility_workaround_no_nclx_profile to false

**Comment by therahedwig** [comment]
Yeah, works. This is kinda annoying.

**Comment by farindk** [comment]
Note that iOS 12 cannot load HEIF files when they have an nclx profile. #397

**Comment by therahedwig** [comment]
> Note that iOS 12 cannot load HEIF files when they have an nclx profile. #397

Yeah, I'm going to discuss this with my colleagues. In theory, we only need the nclx profile when the image is hdr (so the transfer function is PQ or HLG ... or st 428) because none of those can be stored inside ICC profiles, so maybe we only save nclx for hdr images then...
