### ISSUE TITLE
Load some heic file error

### ISSUE THREAD

**Issue by KngStr** [strukturag/libheif#465]
Hi,

I'm using image magick and found a heic file can not be loaded.
Then I tried to https://strukturag.github.io/libheif/ , it did not work well.

Here is my test file: [IMG20210103002456.zip](https://github.com/ImageMagick/ImageMagick/files/6122741/IMG20210103002456.zip)
Here is the issue: https://github.com/ImageMagick/ImageMagick/issues/3386

Thanks.

**Comment by farindk** [comment]
Hi,
thank you for the example image.
The issue has already been resolved. The image doesn't work with v1.11.0, but works fine with current master (dd993f3d5465de5215e24cde36b18f92d7d6d0c6).

**Comment by KngStr** [comment]
OK. Thanks.
