### ISSUE TITLE
How to use without libx265 nor libde265

### ISSUE THREAD

**Issue by CharStiles** [strukturag/libheif#469]
I am working on using the libav HEVC decoder (ffmpeg) to decode depth images in the meta data of HEIC iphone photos. So I am not using libx265 nor libde265. When I build with neither of them because I am not using them I get an error when running:
`The code execution could not proceed because libx265.dll was not found`
I tried setting 
```
set(LIBDE265_FOUND, NOTFOUND)
set(X265_FOUND, NOTFOUND)
```
to let the cmake process know that it shouldnt be included. Is this impossible? should I make my own fork and take any references to libde265 and libx265?
Any help appriciated!!

**Comment by farindk** [comment]
You will have to write a libav decoder plugin to libheif. You can have a look at the existing plugins as an example.
However, I don't see yet why that would be needed. Using libav instead of libde265 will give the exactly same output.

BTW: libheif is available in vcpkg.

**Comment by CharStiles** [comment]
Thank you for your answer. I have tried to use libde265 but I was unsuccessful https://github.com/strukturag/libheif/issues/446
I cant use vcpkg because this is a project where we will have to build on mac too, so its just using CMake 
I'm not sure libheif was intended to be used the way i need it to be used. Alas!

**Comment by CharStiles** [comment]
Thank  you for your comment in the other issue- I added 
```
set(DWITH_LIBDE265, OFF)
set(DWITH_X265, OFF)
``` at the top of the CMakeLists.txt in libheif folder
and turned off BUILD_SHARED_LIBS:
```
option(BUILD_SHARED_LIBS "Build shared libraries" OFF)
```
I also turned off all the other libraries, and it worked!
Thank you again.
