### ISSUE TITLE
 Abrt (9175)

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libheif#47]
The @ImageMagick project is using https://github.com/google/oss-fuzz to find bugs in our own library and in libraries that we use. The fuzzer found an issue and we think this is an issue that should be resolved in the library that we use. This issue is posted under the url https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8922 that is not publicly visible yet but added as a link for future reference. Below are the details of the issue that can be reproduced using the following technique: https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md

Stacktrace:
```
SCARINESS: 10 (signal)
--
  | #0 0x7f35ed949427 in gsignal /build/glibc-Cl5G7W/glibc-2.23/sysdeps/unix/sysv/linux/raise.c:54
  | #1 0x7f35ed94b029 in abort /build/glibc-Cl5G7W/glibc-2.23/stdlib/abort.c:89
  | #2 0x7f35ed941bd6 in __assert_fail_base /build/glibc-Cl5G7W/glibc-2.23/assert/assert.c:92
  | #3 0x7f35ed941c81 in __assert_fail /build/glibc-Cl5G7W/glibc-2.23/assert/assert.c:101
  | #4 0xdc8aef in heif::BitstreamRange::prepare_read(long) libheif/libheif/bitstream.cc:274:5
  | #5 0xdce843 in heif::Box::parse(heif::BitstreamRange&) libheif/libheif/box.cc:312:15
  | #6 0xdd0d84 in heif::Box::read(heif::BitstreamRange&, std::__1::shared_ptr<heif::Box>*) libheif/libheif/box.cc:476:20
  | #7 0xe05df5 in heif::HeifFile::parse_heif_file(heif::BitstreamRange&) libheif/libheif/heif_file.cc:166:19
  | #8 0xe05368 in heif::HeifFile::read(std::__1::shared_ptr<heif::StreamReader>) libheif/libheif/heif_file.cc:82:17
  | #9 0xe056d8 in heif::HeifFile::read_from_memory(void const*, unsigned long, bool) libheif/libheif/heif_file.cc:71:10
  | #10 0xda0796 in heif::HeifContext::read_from_memory(void const*, unsigned long, bool) libheif/libheif/heif_context.cc:357:28
  | #11 0xd8812d in heif_context_read_from_memory libheif/libheif/heif.cc:107:29
  | #12 0xae518e in ReadHEICImage imagemagick/coders/heic.c:195:9
```

Links: https://github.com/strukturag/libheif/blob/2706077d0fe4019e4555bebb46e98ff57b850e63/libheif/bitstream.cc#L274

Commit: 2706077d0fe4019e4555bebb46e98ff57b850e63
Testcase file: [clusterfuzz-testcase-minimized-ping_heic_fuzzer-5723660210929664.zip](https://github.com/strukturag/libheif/files/2152793/clusterfuzz-testcase-minimized-ping_heic_fuzzer-5723660210929664.zip)

**Comment by farindk** [comment]
Thanks for reporting this. Fixed in b196c9deb.
