### ISSUE TITLE
programmatically accessing the images in an heif sequence file

### ISSUE THREAD

**Issue by vtorri** [strukturag/libheif#475]
Hello

I would like to add the support of heif sequence files in our toolkit. SO I have several questions : 
1) is libheif supporting heif sequence files
2) if yes, what are the API to get the number of images, and how to access each image of the file

thank you

Vincent Torri

**Comment by farindk** [comment]
Hello Vincent,

no, there is no support for sequences and I also have no short-term plans to add this. I'm even not aware that anyone is using heif sequences. If you know of any applications, please let me know.

Dirk

**Comment by vtorri** [comment]
at least, i have seen some examples of heif sequences here : 

https://nokiatech.github.io/heif/examples.html

(a bit below the middle of the page)

about applications, well, that could be a high quality replacement of animated gif :-)

regards

Vincent Torri

**Comment by farindk** [comment]
Yes, those examples are the only sign of life there appears to be for it :-)
I don't really see the benefit of another container format for video sequences. One can already store HEVC in mp4, so why HEIF sequences? Maybe I am missing the point, but so far, I see no advantage.

**Comment by vtorri** [comment]
thank you for your answer !

i'm closing this issue, then

Vincent
