### ISSUE TITLE
AVIF requirement: The values of the fields in the AV1CodecConfigurationBox shall match those of the Sequence Header OBU in the AV1 Image Item Data.

### ISSUE THREAD

**Issue by wantehchang** [strukturag/libheif#477]
The [AVIF specification, Section 2.2.1 _AV1 Item Configuration Property_](https://aomediacodec.github.io/av1-avif/#av1-configuration-item-property) says:

> The syntax and semantics of the **_AV1 Item Configuration Property_** are identical to those of the AV1CodecConfigurationBox defined in [AV1-ISOBMFF], with the following constraints:
> 
> - ...
> - The values of the fields in the AV1CodecConfigurationBox shall match those of the Sequence Header OBU in the AV1 Image Item Data.
> - ...

This requirement is not guaranteed by the `heif::fill_av1C_configuration()` method in libheif/libheif/heif_avif.cc because it determines the values of the fields in the AV1CodecConfigurationBox independently, without coordinating with the AV1 encoder.

A reliable way to satisfy this requirement is to parse the AV1 sequence header OBU encoded by the AV1 encoder and set the fields in the AV1CodecConfigurationBox to the parsed values.

Note: I noticed this issue when running the [AVIF Validator](https://gpac.github.io/ComplianceWarden-wasm/avif.html ) on two AVIF images encoded by libheif. See https://bugs.chromium.org/p/chromium/issues/detail?id=1198455#c4.

**Comment by farindk** [comment]
I'm now parsing the AV1 sequence header OBU. I tried with a couple of images and the AVIF Validator now seems satisfied. I still could not test all code paths in the OBU parser.

**Comment by wantehchang** [comment]
Dirk,

Thank you for fixing this issue. I think the most practical way to ensure the correctness of heif::fill_av1C_configuration_from_stream() is by code review. I will try to review it.

A quick look shows that heif::fill_av1C_configuration_from_stream() does not seem to do error checking. This is fine if the function is only called on a successful output of an AV1 encoder.

**Comment by farindk** [comment]
@wantehchang Yes, there is no error checking, but I'm not even sure what to check when parsing the binary data except maybe some consistency check for the image size. Let's just assume that the input data is correct because when we get invalid data from the encoder, we are in bigger trouble anyway.

**Comment by adityapatadia** [comment]
I hope this is released in `1.12.0`?

**Comment by farindk** [comment]
@adityapatadia Yes, it is.
