### ISSUE TITLE
major_brand is unnecessarily repeated in compatible_brands

### ISSUE THREAD

**Issue by baumanj** [strukturag/libheif#478]
Is this an intentional choice? I haven't seen this behavior in other AVIF writers. It's only 4 bytes, but I know many would prefer to keep files as small as possible while maintaining compliance

**Comment by farindk** [comment]
This is what I found:
* The examples in the HEIF standard repeat the main brand in the list of compatible brands.
* 14496-12 says that `compatible brands` list other brands that the file is compatible with, which sounds like we can omit it.
* all MP4 video files I checked repeat the major brand in the compatible brands.

Hence, to be on the safe side, I would prefer for now to repeat the major brand in the compatible brands until I become aware of a standard document that says that it can be omitted.

**Comment by baumanj** [comment]
I take it back, I see other AVIF writers doing this as well. It still seems unnecessary, but it's hardly uncommon.

**Comment by farindk** [comment]
Thanks for the feedback. Yes, it seems it is safer to keep it.

**Comment by baumanj** [comment]
As a result of some further investigation (and thanks to @wantehchang), it appears this repetition may actually required. Per ISOBMFF (ISO/IEC 14496-12:2020) § K.4:
> NOTE This document requires that the major brand be repeated in the compatible-brands, but this requirement is relaxed in the 'profiles' parameter for compactness.

It seems odd that is never stated clearly in § 4.3 (File-type box), but it does indeed seem the existing behavior is best.

**Comment by farindk** [comment]
Thanks for the reference. I only have ISO 14496-12:2004 and that note is not included in that version...
