### ISSUE TITLE
10 bits HEIF convert problem

### ISSUE THREAD

**Issue by GeorgeCh2** [strukturag/libheif#480]
I have a heif file by OPPO Find X3
![image](https://user-images.githubusercontent.com/22410736/115534018-ed66de00-a2c9-11eb-8014-94f03543c812.png)

use heif-convet input.heic out.jpg,  the result is
![out2](https://user-images.githubusercontent.com/22410736/115534111-066f8f00-a2ca-11eb-8e15-e15a677200f2.jpg)

**Comment by GeorgeCh2** [comment]
HEIF file url: https://drive.google.com/file/d/1WEXqaKsNAn34bBXUvfyQuvSE3_sRfBU7/view?usp=sharing

**Comment by farindk** [comment]
Works for me with current master c1674b500c62f59f10af10c29eccfb79fd3b1faf:
![outr](https://user-images.githubusercontent.com/968944/115537590-40756c80-a29b-11eb-8b0d-59036bec8eaf.jpg)

**Comment by GeorgeCh2** [comment]
thx,is work for me
