### ISSUE TITLE
Integer-overflow (9244)

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libheif#49]
The @ImageMagick project is using https://github.com/google/oss-fuzz to find bugs in our own library and in libraries that we use. The fuzzer found an issue and we think this is an issue that should be resolved in the library that we use. This issue is posted under the url https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9244 that is not publicly visible yet but added as a link for future reference. Below are the details of the issue that can be reproduced using the following technique: https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md

Stacktrace:
```
bitstream.cc:301:48: runtime error: signed integer overflow: 16 + 9223372036854775797 cannot be represented in type 'long'
--
  | #0 0x93c48d in heif::BitstreamRange::wait_for_available_bytes(long) libheif/libheif/bitstream.cc:301:48
  | #1 0x943af7 in heif::Box::read(heif::BitstreamRange&, std::__1::shared_ptr<heif::Box>*) libheif/libheif/box.cc:465:23
  | #2 0x97df7b in heif::HeifFile::parse_heif_file(heif::BitstreamRange&) libheif/libheif/heif_file.cc:166:19
  | #3 0x97db94 in heif::HeifFile::read(std::__1::shared_ptr<heif::StreamReader>) libheif/libheif/heif_file.cc:82:17
  | #4 0x97de51 in heif::HeifFile::read_from_memory(void const*, unsigned long, bool) libheif/libheif/heif_file.cc:71:10
  | #5 0x91f77c in heif::HeifContext::read_from_memory(void const*, unsigned long, bool) libheif/libheif/heif_context.cc:357:28
  | #6 0x90910e in heif_context_read_from_memory libheif/libheif/heif.cc:107:29
  | #7 0x7b3f29 in ReadHEICImage imagemagick/coders/heic.c:195:9
  | #8 0x544570 in ReadImage imagemagick/MagickCore/constitute.c:500:13
  | #9 0x6724cb in ReadStream imagemagick/MagickCore/stream.c:1043:9
```

Links:
https://github.com/strukturag/libheif/blob/01fe0a821d5feefb5e8cdefbf2310a07b25b04a8/libheif/bitstream.cc#L301

Commit: 1fe0a821d5feefb5e8cdefbf2310a07b25b04a8
Testcase file: [clusterfuzz-testcase-minimized-ping_heic_fuzzer-5764869918818304.zip](https://github.com/strukturag/libheif/files/2194792/clusterfuzz-testcase-minimized-ping_heic_fuzzer-5764869918818304.zip)

**Comment by farindk** [comment]
fixed in 71ba895
