### ISSUE TITLE
[BUG] decode_image_user is not passing the heif_decoding_options to decode_image_planar

### ISSUE THREAD

**Issue by Ziriax** [strukturag/libheif#498]
I'm not sure if this is by design, but the line

```
 if (!options || options->ignore_transformations == false) {
 ```
 
 is not controllable because the options are not passed down from `decode_image_user` to `decode_image_planar`...

I'm having troubles with the conversion from HEIC to JPEG, the orientation is sometimes wrong, no matter what I set `ignore_transformations` to. This might explain this.

**Comment by Ziriax** [comment]
Thanks for the fast reply and fix! 

> However, you should not need to use ignore_transformation. This options was only added for a very specific use-case.

I see

> The confusion about the image rotation may come from this: in JPEG, the image rotation is specified in the EXIF data and applied by the viewer. In HEIF, there may also be a rotation value in the EXIF data, but it is NOT applied to the image. It is only for information. Hence, when converting the HEIF to JPEG, you have to remove the rotation entry from the EXIF data. Otherwise the rotation is applied twice.

I was running code based on your `heif-convert` example, and it [has code like](https://github.com/strukturag/libheif/blob/31d44edbb237182e8a0f5fee586011e7aa821c66/examples/encoder_jpeg.cc#L48):

```

void JpegEncoder::UpdateDecodingOptions(const struct heif_image_handle* handle,
                                        struct heif_decoding_options* options) const
{
  if (HasExifMetaData(handle)) {
    options->ignore_transformations = 1;
  }

  options->convert_hdr_to_8bit = 1;
}
```

The idea being that when copying all the EXIF data, HEIC transformations should be ignored, because of the reason you gave; since the code does not seem to reset the EXIF orientation, it just copies the metadata blocks as-is.

I'm not even sure if that is right thing to do, since HEIC might do other transformations that JPEG can't handle?

Can you recommend a C/C++ EXIF metadata modifier? The main one I found is exiv2, but that one is GPL. Or should I just apply DIY? 😉

**Comment by farindk** [comment]
Actually, 'ignore_transformations' currently works in practice, but it a hack since the EXIF information is not required in the HEIF. In that case, you would get a wrong orientation.

I have done the EXIF transformation myself using `libexif`. This code is not included in libheif because I did not want to add the dependency to another library.

**Comment by ByteYIFFF** [comment]
> 是的，选项在传递时丢失了。我已经纠正了这一点。
> 
> 但是，您应该不需要使用`ignore_transformation`. 此选项仅针对非常特定的用例添加。
> 
> 关于图像旋转的混淆可能来自于此：在 JPEG 中，图像旋转在 EXIF 数据中指定并由查看器应用。在 HEIF 中，EXIF 数据中也可能有一个旋转值，但它不会应用于图像。它仅用于信息。因此，在将 HEIF 转换为 JPEG 时，您必须从 EXIF 数据中删除旋转条目。否则旋转应用两次。

this error will lead to the crash of hdr_to_8bit.?
