### ISSUE TITLE
undefined symbol de265_get_image_full_range_flag when heif-convert running on Linux

### ISSUE THREAD

**Issue by Enoch-Liu** [strukturag/libheif#538]
Firstly, I build the libde265. 
If I build using cmake, I get a liblibde265.so in /usr/local/lib/.
If I build using ./autogen.sh && ./configure && sudo make && sudo make install, I get a libde265.so.0.1.1.
Is that correct above ?
Then, I build the libheif.
I run ./autogen.sh && ./configure && sudo make && sudo make install, and there is no error occurred when building.
But when I run the bin heif-convert in examples, it crashed with error "/home/liuyike/Codes/libheif/examples/.libs/heif-convert: symbol lookup error: /home/liuyike/Codes/libheif/libheif/.libs/libheif.so.1: undefined symbol: de265_get_image_full_range_flag
"

I want to know why and how to fix it ?

Environment: Linux version 5.4.0-74-generic (buildd@lcy01-amd64-023) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021

**Comment by farindk** [comment]
Sounds like you have installed libde265 twice. Once in /usr/local and once (probably from your distribution) maybe in /usr.
During compilation it seems to find the header with the version information in /usr/local and when running, the library in /usr
seems to have higher priority.

**Comment by Enoch-Liu** [comment]
> Sounds like you have installed libde265 twice. Once in /usr/local and once (probably from your distribution) maybe in /usr.
> During compilation it seems to find the header with the version information in /usr/local and when running, the library in /usr
> seems to have higher priority.

Although I built libde265 twice, but there is only one libde265.so.0.1.1 and one liblibde265.so in /usr/local/lib/. And the second one, liblibde265.so is not a executable binary. It is weird that, the repo of libde265 is on 8aed74 "increase version number to v1.0.8", but the version of lib built is 0.0.1 ...

**Comment by silverbacknet** [comment]
That usually means that CMake's configure step couldn't determine the version. If it's the repo version, the repo maintainer might need to be notified to check that out.

Meanwhile, if you're building it, might be a good idea to uninstall the repo's copy unless you need something dependent on that. It can be a bit of a slog fixing it otherwise.

**Comment by Enoch-Liu** [comment]
I don't know why, but it fixed when I rebuilt the libde265.
Thanks for the hints above.
