### ISSUE TITLE
Thread safe in decoding hevc image

### ISSUE THREAD

**Issue by giantpoplar** [strukturag/libheif#55]
ImageMagick has used libheif to support HEVC format. Note that it sets hevc encoder is thread support, but decoder is not. I’m here to confirm whether this assumption is correct. Libheif doc does’t  mention anything about it.

**Comment by farindk** [comment]
Libheif in general is probably not thread safe. As long as each thread works on its own heif_context, you should be safe. You also should be safe when one thread has read an image and multiple threads get the data from it. The encoder (adding images, thumbnails, ...) to a single heif file is most likely not thread safe. Encoding several images with separate heif_contexts should be safe.

**Comment by fancycode** [comment]
Closing as answered, feel free to open another issue if you have further questions.
