### ISSUE TITLE
heif_context_write_to memory

### ISSUE THREAD

**Issue by pol2095** [strukturag/libheif#560]
Hello,

using `heif_context_write_to_file(ctx, ofile.toStringz);` a heic file is created,
is-it possible to get a byte array instead of create a file ?

Thanks

**Comment by silverbacknet** [comment]
Of course, but you have to define a callback first. You just use
```
uint8_t* databytes;
heif_writer writer;
writer.writer_api_version = 1;
writer.write = writer_callback;
heif_context_write(ctx, &writer, &databytes);
```
and the file as it would be on disk will be in databytes.

You can see an example of a complete in-memory callback at the end of encoder_fuzzer.cc, and if you want pure C it would be trivial to translate MemoryWriter.

**Comment by pol2095** [comment]
It work, thanks.
