### ISSUE TITLE
如何提高HEIC转JPG速度？

### ISSUE THREAD

**Issue by 205418367** [strukturag/libheif#564]
[IMG_20211106_180819.zip](https://github.com/strukturag/libheif/files/7517710/IMG_20211106_180819.zip)
台式机ubuntu系统，HEIC转JPG需要7秒钟

**Comment by ByteYIFFF** [comment]
> [IMG_20211106_180819.zip](https://github.com/strukturag/libheif/files/7517710/IMG_20211106_180819.zip) 台式机ubuntu系统，HEIC转JPG需要7秒钟

https://github.com/strukturag/libheif/issues/552

**Comment by ccfriend** [comment]
so do you have resolved this issue? which decoder do you use, libde265 or other?
when I decode the heic on Q888, it takes 12seconds to decode, not  acceptable.
