### ISSUE TITLE
how to get NCLX profile from heif taked by iphone 12

### ISSUE THREAD

**Issue by ByteYIFFF** [strukturag/libheif#566]
i can not get NCLX by heif_image_handle_get_nclx_color_profile

my code: 
                    heif_color_profile_nclx *heif_nclx = heif_nclx_color_profile_alloc();
                    heif_error err = heif_image_handle_get_nclx_color_profile(handle, &heif_nclx);
                    //err is heif_error_Color_profile_does_not_exist

**Comment by farindk** [comment]
Can you please attach the image so that I can reproduce the issue?

**Comment by kmilos** [comment]
Maybe it has ICC instead?

**Comment by ByteYIFFF** [comment]
> Can you please attach the image so that I can reproduce the issue?
[IMG_6465.HEIC.zip](https://github.com/strukturag/libheif/files/7553742/IMG_6465.HEIC.zip)
@farindk

**Comment by kmilos** [comment]
Yep: "prof" (ICC) instead of "nclx" in the "colr" box.

**Comment by farindk** [comment]
Yes, it is an unrestricted ICC profile "prof":
````
| | | Box: colr -----
| | | size: 560   (header size: 8)
| | | colour_type: prof
| | | profile size: 548
````

You need to use `heif_image_handle_get_raw_color_profile()" to read it.

**Comment by ByteYIFFF** [comment]
> Yes, it is an unrestricted ICC profile "prof":
> 
> ```
> | | | Box: colr -----
> | | | size: 560   (header size: 8)
> | | | colour_type: prof
> | | | profile size: 548
> ```
> 
> You need to use `heif_image_handle_get_raw_color_profile()" to read it.

ok, thanks~

**Comment by ByteYIFFF** [comment]
@farindk
so how to read the out_data, it is not a stuct.
i want to know the color_profile of heif

**Comment by farindk** [comment]
It's a raw ICC profile. Reading this is not in the scope of libheif. You can use a library like lcms2 for this.

**Comment by ValZapod** [comment]
All iphones use P3-D65 woth sRGB curve... ICC profile.
