### ISSUE TITLE
heif-convert to jpeg failed for some HEIC-files => "Bogus marker length" error

### ISSUE THREAD

**Issue by dtgeorge** [strukturag/libheif#575]
Ubuntu 16.04
Compiled with libjpeg8-dev, libjpeg9-dev, libjpeg-turbo8-dev, not luck...

heif-convert -q \<any\> source.HEIC target.jpg
Bogus marker length
Could not write image

Example image: (https://kalendari.fastprint.ua/o_1fmnncgr8j0q1kt6uad1qjf1vkdsa.HEIC)

demo.html (libheif.js) works OK for that file

**Comment by farindk** [comment]
Confirmed. Conversion to JPEG does not work. Conversion to PNG is fine and also heif-info does not show any error. Probably some issue with the EXIF data. I'll have a closer look at that.

**Comment by xiehuc** [comment]
also found this error

**Comment by xiehuc** [comment]
test compile master code with libde265 and libjpeg80 every thing goes well

**Comment by srett** [comment]
This issue seems to be resolved in the current 1.13 release. I tested this on Debian 12 and Ubuntu 22.10; they both ship 1.13 and affected HEIC files that failed on Ubuntu 22.04 convert fine. (Debian is using `libjpeg62-turbo` while Ubuntu has `libjpeg8`.)
