### ISSUE TITLE
heif-convert: orientation wront /  does not rotate the pictures?

### ISSUE THREAD

**Issue by hfst1** [strukturag/libheif#584]
I converted some HEIF to jpg but it seems using gwenview that there is something wrong with orientation. :-(

**Comment by hfst1** [comment]
Thanks. 
I got `heif-convert  libheif version: 1.13.0` from github and compiled it. But I got `JPEG support has not been compiled in.` I built it using
`./autogen.sh `
`./configure`
`make`
I am using a linux. config.log says:
`uname -m = x86_64`
`uname -r = 5.14.21-150400.24.21-default`
`uname -s = Linux`
`uname -v = #1 SMP PREEMPT_DYNAMIC Wed Sep 7 06:51:18 UTC 2022 (974d0aa)`
`/usr/bin/uname -p = x86_64`
`/bin/uname -X     = unknown`
`configure:18086: checking jpeglib.h usability`
`configure:18086: gcc -c -g -O2  conftest.c >&5`
`conftest.c:63:10: fatal error: jpeglib.h: No such file or directory`

**Comment by silverbacknet** [comment]
Depending on the exact system you have, you'll need to install something like libjpeg-turbo-dev or libjpeg-dev for jpeg, you can probably search *jpeg* in your package manager to see what your distro calls it.

Other dependencies if you're building from source are any of: aom, svt-av1, dav1d, rav1e, x265, libde265 (depending on if you want av1 and/or hevc support).

**Comment by hfst1** [comment]
`libjpeg8-devel` changes to an other error `Could not decode image: 0: Unsupported feature: Unsupported codec`
Now I do not know which codec I need.

**Comment by hfst1** [comment]
@farindk Thanks, now the orientation is correct.
