### ISSUE TITLE
Example for metadata in C

### ISSUE THREAD

**Issue by lanthale** [strukturag/libheif#592]
I have searched but have not found anything. Concrete I am searching for an example to print just all metadata of a file on the console.

The problem I have seen is that in the header file all API request is needing a metadata ID. But I have nothing found to get that ID.

How can I access e.g. the exif data ?

Thank you in advance.
Clemens

**Comment by farindk** [comment]
Use `heif_image_handle_get_list_of_metadata_block_IDs()` to get the list of metadata IDs. You can pass "Exif" as filter to only get the Exif metadata.
https://github.com/strukturag/libheif/blob/d2b412553346c8cb057a9fe8a966a2471e732474/libheif/heif.h#L676

**Comment by lanthale** [comment]
Thanks. Now I have used the method and it seems to work.
But what is left how the data structure looks like what is copied into the void* ?

**Comment by lanthale** [comment]
Thank you for the information. If have now done it directly in Java. Was easier to do for me and I had a lib which can read heic metadata already.
