### ISSUE TITLE
libde265 decode and patents

### ISSUE THREAD

**Issue by torakiki** [strukturag/libheif#601]
Hello,
I added a functionality to our non open source application to convert .heic to jpg using libheif. I later fell into the rabbit hole that is the HEVC patent topic and I'm having a very hard time finding information so I was hoping maybe you can shed some light. I only need the decoder (no encoder), as far as I understand I don't need the MulticoreWare encoder license but I can't figure if I still need something to be in compliance with patents, can you give me some information or pointing to the right direction?
Thanks

**Comment by silverbacknet** [comment]
Contact MPEG-LA and Access Advance directly. There are exemptions for tiny operators, but not nearly as broad as H.264's terms.

**Comment by torakiki** [comment]
Ok, so I contacted both 
1.  MPEG-LA, they were very helpful and indeed there is a 100.000/year limit under which there is no royalty. You still need to go through the 26 pages license, get a lawyer advise and eventually sign it and this will make your product compliant regarding MPEG-LA claims (but not other patent holders).
2. Access Advance, contacted twice and didn't get any answer.

In the end, for small/micro companies as mine is too complicated to try to be compliant. I spent days trying to understand who are all the patents holders and how to obtain a license, all this just to support users taking pictures with an iPhone.
My case is an additional little step towards the non-adoption of a patent encumbered format. 
Side note, all this lead me to add avif support to our application.

**Comment by farindk** [comment]
Thanks @torakiki for sharing the responses. That's approximately what I expected.

What is this 100.000/year limit? 100.000 sold units? Images? Revenue?

**Comment by torakiki** [comment]
That chapter clarifies all sorts of cases to cover all possible means of HEVC inclusion but in general it's distributed units containing HEVC decoder and/or encoder. Commercial or free doesn't matter.. in may case would be 100.000 downloads per year
