### ISSUE TITLE
Heif-enc 1.12.0 not using all physical processors (sockets), cores, logical processors

### ISSUE THREAD

**Issue by YupoWert** [strukturag/libheif#602]
Hi,
I have a dual CPU Xeon E5530 based Dell workstation (aka 2 sockets, 8 cores, 16 logical processors) on Win10.
All sockets, cores, and logical processors are visible, and all 16 logical processors can be used for video encoding by apps such as Handbrake.
 
Running a HEIF-ENC test conversion of 500,000+ JPG images, Task Manager indicates only the 1st 8 logical processors are being used (at ~100%) - the last 8 being completely idle). Each CPU socket is a 4 core / 8 logical processor unit.

Is Heif-enc only 'binding' to the 1st physical CPU?
Can this be altered to use all available CPU's ?
Many thanks

**Comment by farindk** [comment]
Are you encoding to HEIC or to AVIF?
libheif forwards the actual encoding task to x265 or one of the av1 encoders. Thus, this appears to be an issue of the encoder.

Could you send the output of `heif-enc --list-encoders`, or `heif-enc --list-encoders -A` in case you use AVIF?

**Comment by YupoWert** [comment]
By adding -v into the heif-enc encoder params I got this back... on a jpg-heic encode

x265 [info]: HEVC encoder version 3.5+10-82786fccc
x265 [info]: build info [Windows][GCC 10.3.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
x265 [info]: Main Still Picture profile, Level-6 (Main tier)
x265 [debug]: detected NUMA node 0 with 8 logical cores
x265 [debug]: detected NUMA node 1 with 8 logical cores
x265 [debug]: NUMA node 0 may use 8 logical cores
x265 [debug]: NUMA node 1 may use 8 logical cores
x265 [debug]: NUMA node 2 may use 0 logical cores
x265 [info]: Thread pool 0 using 8 threads on numa nodes 0
x265 [info]: Thread pool 1 using 8 threads on numa nodes 1
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 4 / wpp(45 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 2 intra
x265 [info]: ME / range / subpel / merge         : star / 57 / 3 / 3
x265 [info]: Lookahead / bframes / badapt        : 0 / 0 / 0
x265 [info]: b-pyramid / weightp / weightb       : 0 / 0 / 0
x265 [info]: References / ref-limit  cu / depth  : 1 / off / off
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 1 / 1.0 / 32 / 0
x265 [info]: Rate Control / qCompress            : CRF-25.0 / 0.60
x265 [info]: tools: rect amp rd=4 psy-rd=1.00 rdoq=2 psy-rdoq=1.00 signhide
x265 [info]: tools: tmvp strong-intra-smoothing lslices=4 deblock sao
x265 [info]: frame I:      1, Avg QP:21.16  kb/s: 5033.25
x265 [info]: consecutive B-frames: 100.0%

so it does (?) seem x265 recognises both pools and both groups of 8 threads

Can you point me to a Windows app / command line util which will enable me to encode a video using your x265 library, so that I can get test data back to you.

Unfortunately, as I'm not a developer, recompiling etc is not in my capabilities.
Many thanks

**Comment by YupoWert** [comment]
OK, so after much trial and error, I have results from 'pool' parameters passed through ffmpeg to x265
example: ffmpeg -i input.mp4 -c:v libx265 -an -x265-params pools=8,8:crf=28 output.x265.mp4

the relevant pools values affect the CPU binding are:
8,8 = use both CPUs, creating 2 pools with 8 logical processors/hyperthreads per CPU per pool
-,+ = Don't use the first CPU, Create 1 pool for the second CPU, use all threads
+,- = The reverse of the previous setting (the default behaviour of x265)
-,- = Use only the first CPU and turn off "WPP" and "lookahead slices"

BTW: +,+ = "Thread pool 0 using 16 threads on numa nodes 0,1" - but still only invoked CPU 0 in reality
The more CPUs/cores you have, you can add more value combinations (e.g. 8,8,8,8 -,-,+,+ etc)

So, the big question..
How do I pass the pools parameters through HEIF-ENC to x265?

I am going to test both scenarios of a single batchfile encode using both CPUs, vs 2 batchfiles - each tying the encoder affinity to a separate CPU

Many thanks

**Comment by MimoKar** [comment]
you can add x265 params via

-p x265:<param_name> 

line param so possibly yours will be x265:pools=8,8

**Comment by YupoWert** [comment]
Tested, both scenarios working great!
Thanks !
