### ISSUE TITLE
Protocol error when using heif-convert

### ISSUE THREAD

**Issue by bobhavlin** [strukturag/libheif#620]
When trying to use heif-convert I get "Protocol error" as follows:

```
# heif-convert 2021/12/IMG_4661.HEIC JPG/2021/12/IMG_4661.HEIC.jpg
File contains 1 images
Written to JPG/2021/12/IMG_4661.HEIC.jpg
Can't open JPG/2021/12/IMG_4661-urn:com:apple:photo:2020:aux:hdrgainmap.HEIC.jpg: Protocol error
could not write auxiliary image
```
The heif-convert does produce the .jpg image, but throws the above error.
Probably related to hdrgainmap being processed as an image....

```
# heif-info 2021/12/IMG_4661.HEIC
MIME type: image/heic
main brand: heic
compatible brands: mif1, MiHE, MiPr, miaf, MiHB, heic

image: 3024x4032 (id=49), primary
  thumbnail: 240x320
  color profile: prof
  alpha channel: no 
  depth channel: no
```

**Comment by farindk** [comment]
Maybe the ':' in the filename are interpreted as some internet protocol instead of an ordinary file?
Is this on Linux?
Can you attach the image?

**Comment by bobhavlin** [comment]
This is ubuntu 20.04, the input filename does not have a ":" in it, so the string "-urn:com:apple:photo:2020:aux:hdrgainmap" is somehow extracted from the file.  

https://share.icloud.com/photos/024FrW2Q4CE69NjFZv1p4MfWQ

**Comment by farindk** [comment]
When I get the file from your icloud link, I just get a JPEG:
````
$ unzip iCloud\ Photos\ from\ Robert\ Havlin.zip 
Archive:  iCloud Photos from Robert Havlin.zip
  inflating: iCloud Photos from Robert Havlin/IMG_4814.JPEG  
  inflating: iCloud Photos from Robert Havlin/IMG_4814.MOV  
````

**Comment by bobhavlin** [comment]
Try this and rename to heic:

![IMG_4814 HEIC fake](https://user-images.githubusercontent.com/1026345/159125478-37020cac-55a2-4691-9edc-2cbaa2f3f3c7.JPG)

**Comment by farindk** [comment]
Hm, works for me (Ubuntu 21.10, ext4 filesystem).
Latest libheif (ad4f9a5794282626178feb4f2219372c5fe535d3).
````
$ ./examples/heif-convert ~/data/images/heif/issues/issue-620/IMG_4814.heic out.jpg
File contains 1 images
Written to out.jpg
Auxiliary image written to out-urn:com:apple:photo:2020:aux:hdrgainmap.jpg
````

**Comment by bobhavlin** [comment]
Ok, thanks for the help!  I am on latest releast of 1.12.0.  I guess I need to compile the latest lib.

```
# dpkg --list |grep heif
ii  libheif-examples                                            1.12.0-1~ppa1~ubuntu20.04.1                          amd64        ISO/IEC 23008-12:2017 HEIF file format decoder - examples
ii  libheif1:amd64                                              1.12.0-1~ppa1~ubuntu20.04.1                          amd64        ISO/IEC 23008-12:2017 HEIF file format decoder - shared library
```

**Comment by farindk** [comment]
I tried with v1.12.0. Also works for me.
I guess that it has something to do with your system. Probably the filesystem.

You could try to change the code so that it generates an output filename without ':' in it. Change it here:
https://github.com/strukturag/libheif/blob/ad4f9a5794282626178feb4f2219372c5fe535d3/examples/heif_convert.cc#L382

Please let me know what you find out.

**Comment by bobhavlin** [comment]
Awesome! Thank you!!

**Comment by bobhavlin** [comment]
I think you nailed it.  I forgot that this was a "vboxsf" mounted sub-folder not an ext4 as I was thinking...  So probably unexpected filename issues.

**Comment by farindk** [comment]
I'm reopening this as a reminder to add an option to replace ':' in the output filename with something else (maybe '-').

**Comment by bobhavlin** [comment]
Confirmed that release 1.12.0 works when on a proper filesystem such as ext4:
```
# heif-convert IMG_4814.heic out.jpg
File contains 1 images
Written to out.jpg
Auxiliary image written to out-urn:com:apple:photo:2020:aux:hdrgainmap.jpg
```

**Comment by bobhavlin** [comment]
Confirmed that release 1.12.0 works when on a proper filesystem such as ext4:
```
# heif-convert IMG_4814.heic out.jpg
File contains 1 images
Written to out.jpg
Auxiliary image written to out-urn:com:apple:photo:2020:aux:hdrgainmap.jpg
```

**Comment by farindk** [comment]
There is now a heif-convert option `--no-colons` that will replace the colons in the filename with a safe character.
