### ISSUE TITLE
How to check if a heif file has been lossless encoded

### ISSUE THREAD

**Issue by jfcalvo** [strukturag/libheif#621]
I'm looking for a way to check if a heif still image (not sequence) has been encoded as lossless. I have used `heif-info` tool without any success.

For the following file that I know has been lossless encoded using AV1 compression this is what I get:

```
$ heif-info example.avif
MIME type: image/avif
main brand: avif
compatible brands: avif, mif1, miaf

image: 500x334 (id=1), primary
  color profile: rICC
  alpha channel: no
  depth channel: no
```

I have tried with `-d` option but I don't identify anything that can help me to check that the image has been lossless encoded.

If `heif-info` don't show that information do we have any other way to check for this?

I'm using libheif 1.12.0.

**Comment by Jamaika1** [comment]
This cann't be verified.
heifenc.exe image_21447_24bit.png -v -q 90 --avif --no-alpha -p chroma=420 -p speed=1 --matrix_coefficients=6 --full_range_flag=0 -o image_21447_24bit.avif
avifenc.exe -c aom -l -d 8 -y 420 -r full -s 1 -j 4 image_21447_24bit.png image_21447_24bita.avif
av1enc.exe -avif -q 190 -420 -size 1563x1558 -effort 1 -thread 4 image_21447_24bit.png -d image_21447_24bitw.avif

You can only have approximate info.
avifdec.exe -d 8 -c dav1d image_21447_24bit.avif 111.png
```
Decoding with AV1 codec 'dav1d' (1 worker thread), please wait...
Image decoded: image_21447_24bit.avif
Image details:
 * Resolution     : 1563x1558
 * Bit Depth      : 8
 * Format         : YUV420
 * Chroma Sam. Pos: 0
 * Alpha          : Absent
 * Range          : Full <-- false
 * Color Primaries: 2
 * Transfer Char. : 2
 * Matrix Coeffs. : 6
 * ICC Profile    : Absent (0 bytes)
 * XMP Metadata   : Absent (0 bytes)
 * EXIF Metadata  : Absent (0 bytes)
 * Transformations: None
 * Progressive    : Unavailable
Wrote PNG: 111.png
```

**Comment by silverbacknet** [comment]
That's not something kept in the metadata at all. Maybe it'd be a useful extension to the Exif, IPTC, or XMP, but no one's ever bothered before. Lossless can only be inferred by seeing that all decoded blocks are transform skip, and that's the decompressor's job, a lower level than libheif operates. If Dav1d or ffmpeg gave that info, libheif could.

You can get it now with ffmpeg's debugging mode switches, but it'd be hell to parse all of that.

**Comment by jfcalvo** [comment]
Looks like I don't have too much options 😃.  thanks @Jamaika1 and @silverbacknet for the help.
