### ISSUE TITLE
Error with Debian Bullseye

### ISSUE THREAD

**Issue by jdlail** [strukturag/libheif#629]
I recently upgraded from Debian Buster to Bullseye. 

I have uninstalled and installed the libheif-examples (from the Bullseye repos) but I cannot get it to execute. I get this error

`heif-enc: error while loading shared libraries: libx265.so.165: cannot open shared object file: No such file or directory`

I have these Libx265 files:

./lib/x86_64-linux-gnu/libx265.so.192
./lib/x86_64-linux-gnu/libx265.a
./lib/x86_64-linux-gnu/libx265.so

I'm not sure what I should do to resolve the issue? The "165" version does not see to be available for Bullseye?

**Comment by bradh** [comment]
This seems like you may have a local version (e.g. in /usr/local/bin). Can you check what versions of libheif.so and heif-enc you have installed?

**Comment by jdlail** [comment]
I think this is resolved. Closing.
