### ISSUE TITLE
Broken with dav1d 1.0.0

### ISSUE THREAD

**Issue by installgentoo** [strukturag/libheif#630]
On gentoo here, everything using libheif breaks when you update dav1d to 1.0.0
libheif is also compiled with libaom-3.3.0

**Comment by farindk** [comment]
What exactly is the problem with dav1d 1.0.0 ?

**Comment by installgentoo** [comment]
I don't know. Both imagemagic and geeqie fail to open avif files with libheif 1.12 and dav1d 1.0.0. I've rebuilt the dependencies, naturally.

**Comment by installgentoo** [comment]
Specific error for imagemagic is

```display: Decoder plugin generated an error: Unspecified `zl6xfnhzsbj41.avif' @ error/heic.c/IsHeifSuccess/135.```

**Comment by farindk** [comment]
Are you sure that you include the latest libheif commit in your checked out code:
````
commit 0f8496f22d284e1a69df12fe0b72f375aed31315
fix dav1d decoding: input stream must be flushed with dav1d 1.0.0
````

If yes, please attach the image that does not decode correctly.

**Comment by installgentoo** [comment]
No, i tested on 1.12 release

**Comment by installgentoo** [comment]
master works, the commit should probably be in a new release, it's kinda important.
