### ISSUE TITLE
How to decode raw metadata returned by heif_image_handle_get_metadata

### ISSUE THREAD

**Issue by AydinyanNarek** [strukturag/libheif#639]
Currently, the libheif (C API) has the following functionality to extract the metadata
* heif_image_handle_get_number_of_metadata_blocks
* heif_image_handle_get_list_of_metadata_block_IDs
* heif_image_handle_get_metadata_type
* heif_image_handle_get_metadata_content_type
* heif_image_handle_get_metadata_size
* heif_image_handle_get_metadata

The question is how to decode the byte array returned by  `heif_image_handle_get_metadata` ?.
Are you going to add that functionality or do the users have to deal with the parsing of metadata ?.
For example, the `MacOS` (CoreImage) framework provides the full functionality to decode the metadata.

**Comment by bigcat88** [comment]
[python pillow-heif metadata parse](https://github.com/bigcat88/pillow_heif/blob/03c42f9e0a6d2a2f38a8a88835ebed73cc379a79/pillow_heif/private.py#L166
)
and in that file also see `retrieve_xmp` and `retrieve_xmp` functions above that line.

Explanation:
1. Call `heif_image_handle_get_number_of_metadata_blocks`
2. Alloc memory (number of blocks * sizeof(int32))
3. Call `heif_image_handle_get_list_of_metadata_block_IDs`

After that for each metadata block id:
1. Call `heif_image_handle_get_metadata_type` + `heif_image_handle_get_metadata_content_type` + `heif_image_handle_get_metadata_size`
2. Call `heif_image_handle_get_metadata`

If returned `type` from `heif_image_handle_get_metadata_type` is `mime` then it is XMP data.
if type is `Exif` then it is `EXIF` data.
All other types probably will be `IPTC` data.

For parsing EXIF look at: [C EXIF library](https://libexif.github.io)
or look at [Exiv2 C++ metadata library](https://exiv2.org).

**Comment by AydinyanNarek** [comment]
Thanks, I have done everything like you told me, and it seems that libheif returns only raw data , and for parsing it I'll need to use another metadata parser library for getting it in user readable form. Do I understand it correctly?

**Comment by bigcat88** [comment]
yes, libheif returns only `raw` meta data.

**Comment by AydinyanNarek** [comment]
Thanks, I am closing this issue

**Comment by AydinyanNarek** [comment]
Hello again

I have tried to decode the raw metadata through [Exiv2 C++ metadata library](https://exiv2.org/). but it doesn't work.
This is a small example that I have created for decoding the metadata[ ](https://github.com/AydinyanNarek/heif)

Do you have a working example of decoding the metadata returned by libHEIF ?

NOTES:
I have used the latest version of Exif lib.
I have tried to skip the first 4 bytes of Exif raw data before passing it to libExif, but without result.

**Comment by 0xC0000054** [comment]
> Do you have a working example of decoding the metadata returned by libHEIF ?

I have written two programs that use libheif and read EXIF metadata, one in C# and the other in C++.

C#:  https://github.com/0xC0000054/pdn-heicfiletype-plus/blob/740d74fcfcc22900184273bb9b98b5492f89ec16/src/HeicFile.cs#L347

C++: https://github.com/0xC0000054/avif-format/blob/e6b61b56f8bbbfcc466554565dab2c27466ca18b/src/common/ReadMetadata.cpp#L111

The first 4 bytes of the EXIF block that libheif returns is a header, consisting of an unsigned 32-bit integer in big-endian byte order representing the number of bytes that need to be skipped before the TIFF header that contains the EXIF data.
The EXIF header format is defined in ISO/IEC 23008-12 section A.2.1.

**Comment by AydinyanNarek** [comment]
Thanks, this helps.
Seem libExif isn't doing this stuff internally and it is needed to skip the bytes before passing it to the library.
Closing this issue.
