### ISSUE TITLE
heif_image_set_raw_color_profile doesn't set the color profile data

### ISSUE THREAD

**Issue by AydinyanNarek** [strukturag/libheif#646]
Using libheif API I can successfully write an RGB image data to .heic file.

Trying to write ICC color profile data to an image using 
```
heif_image_set_raw_color_profile(image, "rICC", input.data(),  input.size())
```
and then write that image to the file I am not having any failures.

The problem is that after creating the .heic file (which must also contain the color profile data), I am not able to read the color profile data from that file. I have used the function `heif_image_handle_get_raw_color_profile` and int returns 0.

I have some test samples containing color profile data and I am sure that the getter function `heif_image_handle_get_raw_color_profile` working properly because I can successfully extract that data from the images.

It seems that `heif_image_set_raw_color_profile`  function doesn't work at all.

**Comment by bigcat88** [comment]
Provide a full example. I have tests in my python project for `heif_image_set_raw_color_profile` and it works  as expected for me.

Note: tests uses `prof` profile, i was not able to find any image with `rICC` profile to test it. But they must be the same.

**Comment by AydinyanNarek** [comment]
I have uploaded a simple example here (https://github.com/AydinyanNarek/heif).
In that example, I am decoding an image and storing it in memory, and then exporting it to the file.

Note:
I have also uploaded an image that contains ICC color_profile_data.

**Comment by bigcat88** [comment]
hm... did you try first set color profile and then encode image?

`heif_image_set_raw_color_profile` and after that `heif_context_encode_image`

**Comment by AydinyanNarek** [comment]
excellent, it fixed the issue, thanks.
I am closing this. 
Could you pl also take a look at this issue?
https://github.com/strukturag/libheif/issues/639
