### ISSUE TITLE
handle missing image conversion DLL's

### ISSUE THREAD

**Issue by rrepka10** [strukturag/libheif#65]
I built the heif_covert sample code and ran a simple test to convert an heif file to jpeg, there was no error AND no file.  I had forgotten to download and install a jpeg conversion DLL.  

I recommend adding the following to help others that might forget to include the conversion DLLs

file:   heif_convert.cc        after line 106     - insert the following

#if !(HAVE_LIBJPEG || HAVE_LIBPNG)
    fprintf(stderr, "Your build does not include a PNG or JPG encoder, no conversion possible\n");
    return 1;
#endif

**Comment by farindk** [comment]
Hm, if neither HAVE_LIBJPEG nor HAVE_LIBPNG is set, the variable `encoder` should stay `NULL` and the warning "Unknown file type in ..." should be printed. On Linux, it does. Any idea why it doesn't on Windows for you?

**Comment by rrepka10** [comment]
I build the app under Ubuntu running under Windows 10.  I DID receive the "unknown file type" error but I didn't immediately understand why .jpg was "unknown".   I just assumed that JPEG and PNG libraries were on my system, they were not.  I had to install them.   Just trying to help the next guy.

**Comment by farindk** [comment]
Yes, right. I added better error messages in 9e626fb83c864a4f48684c38637dacd785865ab2.
Thanks.
