### ISSUE TITLE
suggesting to improve reading example in readme

### ISSUE THREAD

**Issue by vaifrax** [strukturag/libheif#651]
I started from the example in the readme. Unfortunately, error handling is not part of the example, this would be useful.
But I consider it essential to include the clean up part, e.g. like this:
```
// done, clean up
heif_image_handle_release(handle);
heif_context_free(ctx);
```
At least this would have saved me a lot of debugging.

Thanks for your effort!

**Comment by vaifrax** [comment]
plus
```
heif_image_release(img);
```

**Comment by quiian** [comment]
Yes, please. Glad I found this :)
