### ISSUE TITLE
Input file is not a HEIF file

### ISSUE THREAD

**Issue by haphaeu** [strukturag/libheif#655]
Hi,
I'm having issues of `heif-convert` not recognizing some pictures from an iPhone. The majority of the images work ok, for some some I get:

```
$ heif-convert file.HEIC file.jpg
Input file is not an HEIF file.
```

The same file is successfully opened in GIMP. 

```
$ uname -a
Linux ryzen7 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ apt version libheif-examples
1.6.1-1build1
```

**Comment by haphaeu** [comment]
Duplicate of [111](https://github.com/strukturag/libheif/issues/111)

**Comment by farindk** [comment]
Please check whether the file is in fact a JPEG with a wrong suffix. If yes, close this issue. If no, please attach an example file or send it to me to check.

**Comment by haphaeu** [comment]
Sure, thought I had closed it. 

Indeed the file was a misnamed jpeg file. Some weird bug in iPhone or one of its apps. 

Closing.

**Comment by tarjei** [comment]
I just thought I'd mention that this errormessage can also show up if you are trying to open a file which you do not have permissions to.
