### ISSUE TITLE
Cannot load PNG because libpng support was not compiled.

### ISSUE THREAD

**Issue by gitlabspy** [strukturag/libheif#657]
Apple M1 Pro. Follow the installation instructions, and try to run examples `./heif-enc` to convert png to heif and get error `Cannot load PNG because libpng support was not compiled.` pkg-config can locate libpng.

**Comment by bigcat88** [comment]
`brew install libpng` or install libheif itself with homebrew will do the job.

**Comment by gitlabspy** [comment]
Errors pop after `brew install libpng`, it seems to be m1 version of brew 's problem? libpng installed properly.
```
$ pkg-config --list-all 
libde265     libde265 - H.265/HEVC video decoder.
libpng       libpng - Loads and saves PNG files
libpng16     libpng - Loads and saves PNG files
```

**Comment by bigcat88** [comment]
> Errors pop after `brew install libpng`, it seems to be m1 version of brew 's problem? libpng installed properly.

Try `brew reinstall libheif`  then. Are  you using Monterey? I didn't test it on Big Sur, but for me on Monterey it works fine.

**Comment by farindk** [comment]
Is this solved? Can we close it?
