### ISSUE TITLE
Query: libheif installation through vcpkg on MACOS-Arm64 

### ISSUE THREAD

**Issue by AydinyanNarek** [strukturag/libheif#659]
Do you know why it is not possible to install libheif through vcpkg on MACOS-Arm64 ?.
Seems the vcpkg having problem installing the x265 library for Latest MacOS having M1 chip-set.
Is it going to be resolved ?
Are there any package manager by which libheif binaries could be installed on machines having the following architectures ? 
Windows-x86-64
Windows-arm
Windows-arm64
Linux-x86-64
Linux-arm
Linux-arm64
MacOS-x86-64
MacOS-arm
MacOS-arm64

**Comment by bigcat88** [comment]
For Windows better to use [MSYS2](https://github.com/msys2)

I do not know what is `MacOS-arm`, never seen macOS working on armhfv7 CPU...

If you are asking for universal package manager for all OS and CPU's - answer is no, there is no such.

**Comment by AydinyanNarek** [comment]
Thanks, I am closeing this issue
