### ISSUE TITLE
Automatic color profile determination is broken

### ISSUE THREAD

**Issue by leonklingele-work** [strukturag/libheif#66]
Revision 943361a456fcb8a609deddf06dbea8b7294b704b breaks automatic color profile determination:

```sh
./examples/heif-enc ~/Desktop/rndimg.png 
Assertion failed: (m_color_profile), function write, file box.cc, line 1693.
Abort trap: 6
```

Conversion works fine without the patch.

**Comment by farindk** [comment]
Fixed saving images without any color profile in 472d9e2.
