### ISSUE TITLE
chroma=444 makes wrong images with some dimensions

### ISSUE THREAD

**Issue by bigcat88** [strukturag/libheif#661]
Version: 1.12

[img example](http://fnordware.com/superpng/pnggrad16rgb.png)

`heif-enc pnggrad16rgb.png -p chroma=444`

<img width="703" alt="image" src="https://user-images.githubusercontent.com/13381981/185197980-409ce5c0-e11b-4fd4-bf1d-088d48580c95.png">
<img width="644" alt="image" src="https://user-images.githubusercontent.com/13381981/185198295-43596c72-9ef7-4552-a306-d262f1a353a0.png">
<img width="603" alt="image" src="https://user-images.githubusercontent.com/13381981/185214822-494b5bde-a567-4d65-8b8d-501577a0e8bc.png">

With dimensions 128x128, 64x64, 32x32 and 15x15 images is ok.
The same applies for 8 bit images.

Also tried the same on `master` version today from this repository and the same problem occurred.

P.S: Encoded files was opened by macOS viewer, when they opened by libheif itself they looks fine.

**Comment by farindk** [comment]
Sounds more like a macOS problem. Is there a way that you could save to heic on macOS with another software such that the images with these dimensions look ok? I could then compare the differences between the files.

**Comment by bigcat88** [comment]
Seems yes, maybe it is macOS viewer program problem. I'll close issue, until find more info/software to check it.

**Comment by farindk** [comment]
Does it work with 512x512 ? Apple uses 512x512 sized tiles internally, so that might be an indication to where the error is.

**Comment by bigcat88** [comment]
It works for all sizes till 255x255.(254x254 is OK)
255x255 and more are looks like I posted.

**Comment by bigcat88** [comment]
@farindk Did a simple test: airdropped an image to an iphone - everything was fine there.
Transfer to the computer - it does not show well.

So it is 99% error in macOS viewer.

**Comment by farindk** [comment]
Thanks for trying doing this experiments!
