### ISSUE TITLE
Plugins not registered by default after introduction of heif_init()

### ISSUE THREAD

**Issue by farindk** [strukturag/libheif#668]
`heif_init()` and `heif_deinit()` were introduced to properly clean up allocated memory when the program ends.
It was implemented such that it should still be backward compatible (i.e. plugins are still initialized at program start by default).
The dummy-class for initialization has been moved to https://github.com/strukturag/libheif/blob/626b6203f1d033f9e8bcacd610baf7cbe775ce82/libheif/heif_init.cc#L80-L87

Still, people report that plugins are not automatically registered at start anymore (https://github.com/strukturag/libheif/issues/554#issuecomment-1232771115).

**Comment by farindk** [comment]
Plugins are still initialized at start even without `heif_init()` on Linux, but maybe it is a Windows-only problem? Maybe because of undefined static class initialization execution order?

**Comment by farindk** [comment]
@kleisauke Could you please try if plugins are now registered again even without `heif_init()` on Windows?

**Comment by kleisauke** [comment]
Commit https://github.com/strukturag/libheif/commit/e995017a20d862e1d61a36cb5cfc7371231cdb2d fixes this for me on Windows without doing `heif_init()`, the plugins are now registered at startup. Thanks!

**Comment by farindk** [comment]
@kleisauke Thank you for testing this.
