### ISSUE TITLE
heif_init/heif_deinit

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#674]
Should the pixbufloader-heif.c use heif_init/heif_deinit calls too?

I am somehow worried about thread safety when heif_init/heif_deinit would be called from different threads.

I am thinking, would it be possible to use a mutex in heif_init/heif_deinit avoid potential concurrency problems?

**Comment by farindk** [comment]
The easiest way to ensure thread safety might be to use `std::atomic<int>` for `heif_library_initialization_count`.

**Comment by farindk** [comment]
How about this change to make it thread safe?

**Comment by novomesk** [comment]
What happens if is unregistering plugins in heif_deinit and other thread calls heif_init ?

I think the new thread will think that the plugins are still registered.

First thread will finish unregistering and the new thread remains without plugins.

I think std:atomic<int> helps only partially.

Or what happens if plugins are unregistered but suddenly multiple threads call heif_init ?
Other threads may return sooner than the first one which is still registering the plugins.

**Comment by farindk** [comment]
Right. I'll copy over the solution from libde265...

**Comment by farindk** [comment]
Better now. Note, the mutex has to be returned from a static function because a mutex as a global variable gives problems in Windows code.

**Comment by novomesk** [comment]
Thanks, I think it is OK now.

**Comment by farindk** [comment]
I've added `heif_init()` / `heif_deinit()` to pixbufloader-heif.c.
