### ISSUE TITLE
Input file is not an HEIF/AVIF file

### ISSUE THREAD

**Issue by t3kg33k** [strukturag/libheif#675]
I'm coming across some HEIC files the are not converting when I issue the following command:

heif-convert IMG.HEIC IMG.jpg

I get the following output:

Input file is not an HEIF/AVIF file

**Comment by silverbacknet** [comment]
Can't do anything about it if you don't attach one.

**Comment by t3kg33k** [comment]
Download from my cloud storage a sample:

https://mega.nz/file/pGM2RJaR#ifoqAX6GejHEm-x5GBcCgiv5UTYHEk96IR7mm67UeZU

I tried the command from a Fedora 36 install.

**Comment by farindk** [comment]
I had a look at your file. This is not an HEIC file. It is a JPEG file with the wrong suffix in the filename.

**Comment by t3kg33k** [comment]
Well that is bizarre. Especially since it was a photo taken from my wife's iPhone. Even the metadata states that.

![Screenshot_20220924_064054](https://user-images.githubusercontent.com/4992046/192093596-d7741f72-928e-43f5-ab0f-a43963804f98.png)

**Comment by farindk** [comment]
That's a common issue. I have answered the same issue numerous times :-)
Apple's HEIC images are automatically converted to JPEG when exported from the phone. I think there is an option on the phone to turn the conversion off.

**Comment by t3kg33k** [comment]
Ah. Wow. So annoying.
It's even more bizarre that I was able to convert some of her photos successfully with the command. It was erroring out only on a few.

**Comment by farindk** [comment]
Since this is such a common problem, I've added a utility function to check for JPEG inputs. `heif-convert` now shows a more specific warning:
````
$ heif-convert IMG_6079.HEIC out.png
Input file 'IMG_6079.HEIC' is a JPEG image
````

**Comment by t3kg33k** [comment]
> Since this is such a common problem, I've added a utility function to check for JPEG inputs. `heif-convert` now shows a more specific warning:
> 
> ```
> $ heif-convert IMG_6079.HEIC out.png
> Input file 'IMG_6079.HEIC' is a JPEG image
> ```

I guess I need to install the latest version then since I did not receive that output.

**Comment by farindk** [comment]
I added it 10 minutes ago...
