### ISSUE TITLE
extra compatible brand "miaf" make MacOS cannot recognize Exif orientation

### ISSUE THREAD

**Issue by japheth-sh** [strukturag/libheif#677]
I am use ImageMagick which is using libheif to handle heic files. However, when I convert photos to heic, their exif orientations are always recognized as 1 (no rotate) while Exif orientation is not 1. Here's the example:
[43.txt](https://github.com/strukturag/libheif/files/9662539/43.txt)
![image](https://user-images.githubusercontent.com/43056596/192721375-6471ef93-8870-48d0-a248-39e8bde06141.png)
![image](https://user-images.githubusercontent.com/43056596/192721524-9c6b929a-6d30-4ef5-a435-a14cb2a8483a.png)
See blow 43.heic is not placed correctly. (43ae...ff27.heic is the original photo, I used "convert -define heic:preserve-orientation=true 43ae6f68-7f55-4228-bff3-61c2b383ff27.heic 43.heic")
<img width="427" alt="image" src="https://user-images.githubusercontent.com/43056596/192733260-a22557eb-156c-4b50-8d15-f83c4c92bb76.png">

And Preview App says orientation is 1:
![image](https://user-images.githubusercontent.com/43056596/192721845-01791906-dc38-4eaf-99f8-ce02f20b0a9b.png)

Looks like the m_miaf_compatible is set to true by default and only set to false in some cases. Thus most of heic files will have the "miaf" appended. Is this a bug or Apple's fault?
![image](https://user-images.githubusercontent.com/43056596/192725572-b4494266-8333-47f5-923e-7e9c8ffaf105.png)

![image](https://user-images.githubusercontent.com/43056596/192724611-aaa2d084-0677-4df4-9632-46108e92ba08.png)
![image](https://user-images.githubusercontent.com/43056596/192723319-123f5e3d-5134-4595-b126-b928c347e0a5.png)

**Comment by bigcat88** [comment]
It is Apple "feature"

**Comment by japheth-sh** [comment]
Oh...glad to have a light speed response. I will have a look.

**Comment by japheth-sh** [comment]
See:
![image](https://user-images.githubusercontent.com/43056596/192728482-b5dcaf56-a86c-416a-a0ac-0ef494a39bf5.png)
then:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/43056596/192728577-c2078d22-dd19-4c1f-9777-ecabc6d9b8e9.png">

**Comment by japheth-sh** [comment]
Is it possible that the photo must be "grided" when "miaf" appears in compatible brands? I see the original photo does.

**Comment by farindk** [comment]
MIAF only puts some further restrictions on HEIF. It does not change the interpretation.
Hence, if the orientation that macOS displays depends on the MIAF compatibility, it looks like a macOS bug to me.

There was a lot of confusion about the fact that unlike JPEG, the EXIF rotation value has no effect for HEIF and many implementations did it wrong. Thus, maybe macOS uses the MIAF in some heuristics on how they interpret the EXIF data instead of strictly following the standard.

**Comment by bigcat88** [comment]
I can say more: when a file contains multiple images, the Apple Preview app (on macOS Monterey) doesn't account Exif orientation (tested this June). Exactly the opposite as with one.

**Comment by japheth-sh** [comment]
Mine contains only one still image. Maybe "miaf" misguided MacOS? Is it possible we have an official patch with no "miaf" when there is only one image?

**Comment by farindk** [comment]
I don't think it's a good idea to introduce "bugs" into libheif just to compensate bugs in some other software. There may be a set of programs that only accept MIAF images because of their stricter specification.

**Comment by japheth-sh** [comment]
Ok...so my 43.heic is a correct heic file and we can ignore Mac incorrect orientation, right?

**Comment by farindk** [comment]
You can attach the two images (43.heic and the original) to here and I'll check whether the file is correct. If it is, it's on Apple to fix their bug.
