### ISSUE TITLE
Build fails with: ./configure CXXFLAGS="-DNDEBUG -Wall"

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libheif#686]
With the following configure options the build fails:  `./configure CXXFLAGS="-DNDEBUG -Wall"`. I am getting the following error message:

```
g++ -DHAVE_CONFIG_H -I. -I..     -DNDEBUG -Wall -Wall -Werror -Wsign-compare -Wconversion -Wno-sign-conversion -Wno-error=conversion -Wno-error=unused-parameter -Wno-error=deprecated-declarations -Wno-error=tautological-compare -MT file_fuzzer.o -MD -MP -MF $depbase.Tpo -c -o file_fuzzer.o file_fuzzer.cc &&\
mv -f $depbase.Tpo $depbase.Po
file_fuzzer.cc: In function ‘void TestDecodeImage(heif_context*, const heif_image_handle*, size_t)’:
file_fuzzer.cc:38:7: error: unused variable ‘width’ [-Werror=unused-variable]
   38 |   int width = heif_image_handle_get_width(handle);
      |       ^~~~~
file_fuzzer.cc:39:7: error: unused variable ‘height’ [-Werror=unused-variable]
   39 |   int height = heif_image_handle_get_height(handle);
      |       ^~~~~~
file_fuzzer.cc:47:7: error: unused variable ‘metadata_ids_count’ [-Werror=unused-variable]
   47 |   int metadata_ids_count = heif_image_handle_get_list_of_metadata_block_IDs(handle, nullptr, metadata_ids,
      |       ^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

Also a bit strange that these files get build when I did not use `--enable-fuzzing`. I solved this locale with some `ifndef NDEBUG` checks but that is probably not the best way.

**Comment by farindk** [comment]
@fancycode Can you tell me what `libfuzzer.a` is for? I don't see it being linked to any executable.
Any why is it only built if `ENABLE_LIBFUZZER` is disabled?
Can we remove the whole else-block?
https://github.com/strukturag/libheif/blob/886a74436e5d57a2c8e17d130721f0b3f374178c/libheif/Makefile.am#L146-L153

**Comment by bradh** [comment]
This may be able to be closed with the removal of the old build system.

**Comment by farindk** [comment]
Yes, that seems obsolete now.
