### ISSUE TITLE
Auxiliary image written to lumpi-urn:com:apple:photo:2020:aux:hdrgainmap.jpg - what's that

### ISSUE THREAD

**Issue by hfst1** [strukturag/libheif#699]
Hello, I use `heif-convert 1.13.0`
I use the parameter `--with-aux` which sometimes seems to produce extra files like `lumpi-urn:com:apple:photo:2020:aux:hdrgainmap.jpg`. When are this files produces and what do they mean?

**Comment by farindk** [comment]
These are the auxiliary files assigned to the main image. Vendor specific content.

Here is some random link to explain the HDR gain map:
https://www.researchgate.net/publication/4288952_Display_HDR_Image_using_a_Gain_Map
