### ISSUE TITLE
strange black offset for 10 and 12 bit AVIF decode

### ISSUE THREAD

**Issue by jcupitt** [strukturag/libheif#706]
Hello, thank you again for this nice library.

Eight bit AVIFs images are fine, but I'm seeing a curious black offset when decoding 10 and 12 bit AVIF. For example with these test images:

https://github.com/link-u/avif-sample-images

I run:

```
$ heif-convert fox.profile2.12bpc.yuv422.avif heif-convert-12.png
```

`fox.png` in that directory is the correct result:

https://raw.githubusercontent.com/link-u/avif-sample-images/master/fox.png

Here's the 12 bit AVIF to see how your browser decodes it:

https://raw.githubusercontent.com/link-u/avif-sample-images/master/fox.profile2.12bpc.yuv422.avif

And here's the result from `heif-convert` in master:

![heif-convert-12](https://user-images.githubusercontent.com/580843/199722085-983b92c8-7fce-44b8-80e4-d3897bc0dfed.png)

If you put them in separate tabs and flip you can hopefully see the issue.

Looking at the histograms shows the problem:

![image](https://user-images.githubusercontent.com/580843/199722870-b6f30fd2-dc63-4460-8ade-3ebe77470e51.png)

The 12 bit version has been shifted right by about 17, using 8-bit units. Ten bit AVIF images have the same problem, but the shift is smaller, perhaps 14.

I can work around this, sort-of, with:

https://github.com/libvips/libvips/commit/7bff57bcd969464dc61370f55ad9d4c52538fd8a

But that's obviously not a great solution since the white will now be off by that amount.

Ubuntu 22.04 with git master libheif, libaom 3.3.0, libdav1d 0.9.2, though earlier versions seem to have the issue as well. 

Downstream issue: https://github.com/libvips/libvips/issues/3123

**Comment by kmilos** [comment]
Full vs narrow/limited/studio range YCbCr<->RGB conversion related perhaps?

**Comment by jcupitt** [comment]
Maybe, though the matching 8 bit AVIF in that test set seems to give the expected result:

https://raw.githubusercontent.com/link-u/avif-sample-images/master/fox.profile2.8bpc.yuv422.avif

(I edited the OP to add this info, thanks for pointing it out)

**Comment by kmilos** [comment]
Also the files don't seem to have any `colr` information attached, so perhaps different implementations assume different defaults...

**Comment by jcupitt** [comment]
True. I was also thinking it could be a simple rounding issue -- this looks a bit like the offset you might add before integer division to get round to nearest. Though I don't know where a rounding offset of approx. 17.5 might come from haha.

**Comment by jcupitt** [comment]
More info (from the reporting issue, thanks kmilos):

```
$ avifdec fox.profile2.12bpc.yuv422.avif avifdec-12.png
```

Gives a good result.

**Comment by farindk** [comment]
Yes, @kmilos is right, it was a wrong offset for the limited-range color conversion.
@jcupitt, could you please confirm that this now gives the correct result? Visually, it looks ok for me, but I haven't compared the histograms.

**Comment by jcupitt** [comment]
Hi Dirk, thanks for fixing this!

I built git master libheif and tried:

```
$ heif-convert fox.profile2.12bpc.yuv422.avif heif-convert-12.png
```

Then converted the result to 8 bit mono and compared to the reference image:

![image](https://user-images.githubusercontent.com/580843/201893929-ace82d7a-f254-4560-a64f-bb35c650e1a5.png)

And get an identical result. So I think it's all good.

**Comment by farindk** [comment]
Thank you @jcupitt for cross checking this and the clear bug report.
