### ISSUE TITLE
heif-convert Windows versus maOS

### ISSUE THREAD

**Issue by vicodark** [strukturag/libheif#71]
The attached file (and others) convert fine using the sample heif-convert program (to png) on macOS (10.12.6
[IMG_4453.HEIC.zip](https://github.com/strukturag/libheif/files/2324200/IMG_4453.HEIC.zip)), but give "Could not read HEIF file: Invalid input: No 'meta' box" on Windows (7 and 10).  I can clearly see the "meta" box tag in a hex editor:

bbmbp081:~ vico$ xxd -l 128 projects/apple_formats/media/Archive_from_MikeH/Archive/IMG_4453.HEIC
00000000: 0000 0018 6674 7970 6865 6963 0000 0000  ....ftypheic....
00000010: 6d69 6631 6865 6963 0000 0f74 6d65 7461  mif1heic...tmeta
00000020: 0000 0000 0000 0022 6864 6c72 0000 0000  ......."hdlr....

Any ideas? (I had to zip the file to attach it.)

**Comment by farindk** [comment]
I did a quick check on Linux and looked at the file structure. Cannot see anything special so far.
Can you send me the exact command lines you used for building libheif under Windows?

**Comment by vicodark** [comment]
I've attached a file with the build commands since it retains formatting.
[build_heif.txt](https://github.com/strukturag/libheif/files/2324344/build_heif.txt)

**Comment by vicodark** [comment]
Please let me know what else I can provide or test to try to figure this out. I lost on why it might not see the box tag on Windows versus Linux and macOS.

**Comment by jluben-on1** [comment]
I can replicate vicodark's problem using a heic file taken on an Apple iPhone.
[IMG_1403.zip](https://github.com/strukturag/libheif/files/2337688/IMG_1403.zip)

**Comment by farindk** [comment]
Confirmed, running in `wine64`. Will look into this.

**Comment by farindk** [comment]
Should be fixed with commit 4c989e5abd1dc1f58037d0aee1e6331e2308d409.
Can you please confirm?

**Comment by mikebbt** [comment]
On behalf of vicodark I have confirmed that the change seems to resolve the issue, thanks for the quick resolution.

**Comment by fancycode** [comment]
Thanks for confirming the fix, closing.
