### ISSUE TITLE
Memory allocation failed

### ISSUE THREAD

**Issue by jtmathew** [strukturag/libheif#710]
If image size is above 1MB I am getting `Memory allocation failed` error. Smaller images works fine.
I am on `Ubuntu 20.04.2 LTS`
libheif version is `1.6.1` installed with `sudo apt -y install libheif-dev` command.

Is it possible to install latest libheif in Ubuntu?
Can I increase max memory by editing `heif_suberror_Security_limit_exceeded` variable inside `/usr/include/libheif/heif.h` file?

Thanks.

**Comment by fancycode** [comment]
We provide a PPA for Ubuntu containing newer versions:
https://launchpad.net/~strukturag/+archive/ubuntu/libheif

The memory limit doesn't depend on the filesize, but resolution of the image or other objects that get allocated dynamically.

**Comment by jtmathew** [comment]
Hi @fancycode ,

Thanks for the reply.

Tried to install provided PPA `sudo add-apt-repository ppa:strukturag/libheif` and getting following error:-

> Get:1 http://ppa.launchpad.net/strukturag/libheif/ubuntu focal InRelease [23.8 kB]
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:4 http://ppa.launchpad.net/strukturag/libheif/ubuntu focal/main amd64 Packages [1840 B]
Get:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:6 http://ppa.launchpad.net/strukturag/libheif/ubuntu focal/main Translation-en [1160 B]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2197 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Hit:10 https://deb.nodesource.com/node_14.x focal InRelease
Ign:11 https://github.com/strukturag/libheif focal InRelease
Get:9 https://git.launchpad.net/ubuntu/+source/libheif focal InRelease [26 B]
Err:9 https://git.launchpad.net/ubuntu/+source/libheif focal InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Err:12 https://github.com/strukturag/libheif focal Release
  404  Not Found [IP: 140.82.121.4 443]
Reading package lists... Done
E: Failed to fetch https://git.launchpad.net/ubuntu/+source/libheif/dists/focal/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://git.launchpad.net/ubuntu/+source/libheif focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://github.com/strukturag/libheif focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by fancycode** [comment]
> Err:9 https://git.launchpad.net/ubuntu/+source/libheif focal InRelease
...
> Err:12 https://github.com/strukturag/libheif focal Release

You somehow got some git source repositories added to your apt sources? This will not work.

**Comment by jtmathew** [comment]
Hi @fancycode,

Removed git repositories and getting this now:-

> Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 https://deb.nodesource.com/node_14.x focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://ppa.launchpad.net/strukturag/libheif/ubuntu focal InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:6 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Ign:8 https://github.com/strukturag/libheif focal InRelease
Err:9 https://github.com/strukturag/libheif focal Release
  404  Not Found [IP: 140.82.121.3 443]
Get:7 https://git.launchpad.net/ubuntu/+source/libheif focal InRelease [26 B]
Err:7 https://git.launchpad.net/ubuntu/+source/libheif focal InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done
E: The repository 'https://github.com/strukturag/libheif focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://git.launchpad.net/ubuntu/+source/libheif/dists/focal/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://git.launchpad.net/ubuntu/+source/libheif focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by jtmathew** [comment]
Hi @fancycode ,

You are right there was still git repositories present, removed them and successfully added PPA. However original problem still persists `Memory allocation failed`.

If I download sample `HEIF` files from internet it works, but files from Samsung and Apple fails with this error.

[Non working ios image](https://drive.google.com/file/d/1yfyowVcG73Xb3hSqPf_XVzjyLGZIxi9M/view?usp=sharing)

Thanks.

**Comment by fancycode** [comment]
Thanks for the sample.

@farindk could you please check what the problem of this image is?

**Comment by farindk** [comment]
I tried both images with the current master (50a9a907917d9e719ff6e2ac552c74db55039f30) and v1.6.1, and they worked fine for me (Ubuntu 22.04.1 LTS). I didn't try the PPAs yet.

**Comment by jtmathew** [comment]
Hi @fancycode @farindk 

Thanks for the quick reply.

I am using libheif with GM ` gm identify file-path`

Could you share the command to run libheif directly please.

**Comment by farindk** [comment]
I simply used `heif-convert ios.heif output.png`.

I just tried `gm convert ios.heif output.png` and also get the error. Hence, I assume the bug is in graphicsmagick.
Could you please submit a bug report there and cross link with this issue so that we can keep track of this?

**Comment by farindk** [comment]
BTW: imagemagick (`convert ios.heif output.png`) works and also uses libheif.

**Comment by jtmathew** [comment]
Hi Both @fancycode @farindk ,

Thanks for checking the images. Created a bug report in [GM](https://sourceforge.net/p/graphicsmagick/bugs/677/)

Will update here with more details once this is resolved.

**Comment by jtmathew** [comment]
Hi @fancycode @farindk ,

GM released a fix to this issue `1.4.020221119`

From GM:
> What appears to be happening is that the code which retrieves the attached EXIF profile (via libheif) is failing and thus the EXIF profile is claimed to be "0 bytes". Subsequent to that, it is decided that the memory can not be allocated because the allocation size is only 0 bytes.

Any ideas why `libheif` returns 0 for the EXIF profile size?

Thanks.

**Comment by farindk** [comment]
I had a look into the file. It points to Exif data which has in fact zero size. Hence, libheif is correct to return a zero size. The input images seem to be wrong.
I just find it strange that you say that one image comes from iOS and the other one from Samsung.

Have they been processed in some way?

**Comment by jtmathew** [comment]
Hi @farindk ,

Images are directly from respective devices, took them for testing this issue. They are not processed in anyway as far as I can say.

If you have access to either Android or iOS devices please take pictures in `HEIC` and give it a try.

First faced this issue with images from other iOS devices.

Thanks for looking in to this.

**Comment by farindk** [comment]
I've got many images from iOS and never saw this so far. Unfortunately, I only have older iOS devices that don't write HEIC.
Could it be that this is related to some settings, e.g. when GPS coordinates are suppressed?

**Comment by jtmathew** [comment]
Hi @farindk ,

Tried to read EXIF data with [ExifTool](https://exiftool.org/) and both images appears to have EXIF data.

iOS image EXIF info:-

![image](https://user-images.githubusercontent.com/32495952/202919550-de1026b8-0160-4fa8-a2ee-63ef20a959dc.png)

Thanks.

**Comment by farindk** [comment]
This is not really EXIF data. This data is taken from the h265 headers and the included color profile, for example.

Here is the relevant part of the `ios.heic` file:
EXIF is item number 51:
````
| | Box: infe -----
| | size: 21   (header size: 12)
| | version: 2
| | flags: 1
| | item_ID: 51
| | item_protection_index: 0
| | item_type: Exif
| | item_name: 
| | content_type: 
| | content_encoding: 
| | item uri type: 
| | hidden item: true
````

But `iloc` for item 51 says that is has size 0:
````
| item ID: 51
|   construction method: 0
|   data_reference_index: 0
|   base_offset: 0
|   extents: 8666,0 
````

There cannot be any Exif data because real image data starts at the same position 8666:
````
| item ID: 1
|   construction method: 0
|   data_reference_index: 0
|   base_offset: 0
|   extents: 8666,75162 
````

**Comment by farindk** [comment]
PS: `Rotation` is taken from the `irot` box.

**Comment by jtmathew** [comment]
Hi @farindk ,

May be there is no EXIF data and/or because `iloc for item 51 says that is has size 0` , `libheif` is returning `0` for the EXIF profile size.

Thanks.
