### ISSUE TITLE
libheif-1.14.0 does not compile with --disable-multithreading

### ISSUE THREAD

**Issue by freakout42** [strukturag/libheif#715]
without this patch compiling fails with `configure --disable-multithreading` on no threadsupporting platform
[heif_init_disable_multithreading.patch.zip](https://github.com/strukturag/libheif/files/10020678/heif_init_disable_multithreading.patch.zip)

**Comment by farindk** [comment]
Please check whether it now works for you with the above change.

**Comment by freakout42** [comment]
works fine for me - thanks
