### ISSUE TITLE
Error in Cmake

### ISSUE THREAD

**Issue by yongjiea** [strukturag/libheif#720]
/opt/libheif/libheif/plugins/heif_encoder_aom.cc: In function ‘heif_error aom_encode_image(void*, const heif_image*, heif_image_input_class)’:
/opt/libheif/libheif/plugins/heif_encoder_aom.cc:846:27: error: ‘AOM_USAGE_GOOD_QUALITY’ was not declared in this scope
  846 |   unsigned int aomUsage = AOM_USAGE_GOOD_QUALITY;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
/opt/libheif/libheif/plugins/heif_encoder_aom.cc:849:16: error: ‘AOM_USAGE_REALTIME’ was not declared in this scope
  849 |     aomUsage = AOM_USAGE_REALTIME;
      |                ^~~~~~~~~~~~~~~~~~
make[2]: *** [libheif/CMakeFiles/heif.dir/build.make:284: libheif/CMakeFiles/heif.dir/plugins/heif_encoder_aom.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:320: libheif/CMakeFiles/heif.dir/all] Error 2
make: *** [Makefile:152: all] Error

it happened when i make code, does anyone know what this is about？

**Comment by farindk** [comment]
What AOM version do you use?
Looks like it is a v1.x version, which is no longer supported.

**Comment by kmilos** [comment]
@farindk Might be an idea to do stricter checking and fail early during configure when the user has a clearer feedback message?

https://github.com/strukturag/libheif/issues/707
https://github.com/strukturag/libheif/issues/716
