### ISSUE TITLE
Add read/write support for the Content Light Level Information box

### ISSUE THREAD

**Issue by 0xC0000054** [strukturag/libheif#721]
This metadata is important for correctly rendering many AVIF HDR images that use a PQ transfer curve.
The Content Light Level Information box is described in MIAF section 7.4.4.2 and AVIF section 2.2.3.

Related to https://github.com/AOMediaCodec/libavif/pull/1194

**Comment by farindk** [comment]
For testing: CLLI information is shown in `heif-info` output.

**Comment by farindk** [comment]
I have also added support for MDCV (Mastering display colour volume).
