### ISSUE TITLE
SVT-AV1: Quality parameter (1-100) mapping

### ISSUE THREAD

**Issue by dloebl** [strukturag/libheif#729]
We tried to get encoding with SVT-AV1 working and noticed that the quality parameter (range: 1-100) isn't exposed yet:
```
$ heif-enc -A -e aom -q 1 -o aom_1.avif test.jpg
$ heif-enc -A -e aom -q 100 -o aom_100.avif test.jpg
$ heif-enc -A -e svt -q 1 -o svt_1.avif test.jpg
$ heif-enc -A -e svt -q 100 -o svt_100.avif test.jpg

$ du -h svt_* aom_*
104K	svt_1.avif
104K	svt_100.avif
 16K	aom_1.avif
3.1M	aom_100.avif
```
As you can see, an AVIF encoded with SVT-AV1 with quality 1 is of the exact same file size as one with quality 100.

Is there anything we could help with to get a 1-100 quality mapping with SVT-AV1?
https://github.com/strukturag/libheif/blob/f43a3a1fba99e603aeabb38dc631493c69432a18/libheif/plugins/heif_encoder_svt.cc#L44

**Comment by farindk** [comment]
Implemented as described above.
If also 'qp' parameter is set, 'qp' has higher priority.

**Comment by dloebl** [comment]
@farindk Thanks! That's great.
