### ISSUE TITLE
Unnecessary copying of std::vector<Error>

### ISSUE THREAD

**Issue by chris0e3** [strukturag/libheif#738]
The referenced line makes an unnecessary copy of ``HeifPixelImage::m_warnings`` (potentially multiple times).

https://github.com/strukturag/libheif/blob/e5ab2ede435e7cc13b7db9dfd66f9d12f7fa48ed/libheif/heif_colorconversion.cc#L3277

The above line & the line that follows it can be simplified/optimised to:
```
    for (const auto& warning : in->get_warnings()) {
```

BTW Is it possible to create a permalink for multiple lines of code?

**Comment by farindk** [comment]
Doesn't look like a bottleneck, and the vector is empty most of the time anyways. But I've changed it.

PS: at least, you can edit the perma-link manually to "... #L123-132". I also found no way to do it directly in the UI.

**Comment by farindk** [comment]
@kleisauke Thank you for enlighting us :-)
