### ISSUE TITLE
Race condition in HeifContext::decode_and_paste_tile_image

### ISSUE THREAD

**Issue by chris0e3** [strukturag/libheif#740]
The function ``HeifContext::decode_and_paste_tile_image`` has a potential race condition when run in parallel from here:

https://github.com/strukturag/libheif/blob/e886cb55a2296f527a9364549d66de5b559e0c0d/libheif/heif_context.cc#L1615-L1617

The problem code is this:

https://github.com/strukturag/libheif/blob/e886cb55a2296f527a9364549d66de5b559e0c0d/libheif/heif_context.cc#L1668-L1675

Which could end up with multiple threads each trying to add an alpha channel to the same image at the same time.
Also the calls to ``HeifPixelImage::has_alpha`` return true for interleaved RGBA type images, which I believe is not the desired requirement.

These can be fixed with something like:

```C++
  if (tile_img->has_channel(heif_channel_Alpha) && !img->has_channel(heif_channel_Alpha)) {
#if ENABLE_PARALLEL_TILE_DECODING
    static std::mutex m;
    std::lock_guard<std::mutex> lock(m);
    if (!img->has_channel(heif_channel_Alpha))	// check again, after locking
#endif
    {
      int alpha_bpp = tile_img->get_bits_per_pixel(heif_channel_Alpha);
      assert(alpha_bpp <= 16);
      uint16_t alpha_default_value = static_cast<uint16_t>((1u << alpha_bpp) - 1u);
      img->fill_new_plane(heif_channel_Alpha, alpha_default_value, w, h, alpha_bpp);
    }
  }
```

[Also I changed the ``1UL``s to ``1u``, as it doesn’t need to be 64-bit.]
[BTW ``HeifPixelImage::fill_new_plane`` should probably assert (or correctly handle) when called with an interleaved channel.]

**Comment by farindk** [comment]
Thanks, I have fixed it according to your proposal.

Concerning the `1ul` vs `1u`, I think `1ul` enforces 32bit, not 64bit, and 32bit is required for the case that `alpha_bpp==16`.
I guess that there was a compiler warning before that said I should add `UL` to be safe.
