### ISSUE TITLE
Image damaged grey bar

### ISSUE THREAD

**Issue by francescovezzi** [strukturag/libheif#741]
I used the command ` heif-convert -q 100 ` to convert a HEIC image to jpg format.
However, the final image is mostly grey:
![IMG_8012](https://user-images.githubusercontent.com/95044968/207034612-03c23cc0-2818-47d3-ac18-d4d6931afa78.jpg)

Unfortunately, I have deleted the HEIC image for space issues.. is there a way to recover the original image?

Thank you!

**Comment by farindk** [comment]
> Unfortunately, I have deleted the HEIC image for space issues.. is there a way to recover the original image?

No, of course not.
Sorry, I have no idea what I should do with this question...
