### ISSUE TITLE
Spelling error with set_color_primaties?

### ISSUE THREAD

**Issue by stumbles** [strukturag/libheif#753]
I might be mistaken but there might be a spelling error with "set_color_primaties", should it be "set_color_primaries"?

I bring this up after filing a bug report with the krita folks because it failed the compile with;

`[ 78%] Built target kritaheifimport
[ 78%] Automatic MOC for target kritaheifexport
[ 78%] Built target kritaheifexport_autogen
Consolidate compiler generated dependencies of target kritaheifexport
[ 78%] Building CXX object plugins/impex/heif/CMakeFiles/kritaheifexport.dir/HeifExport.cpp.o
/usr/src/krita-5.1.5/plugins/impex/heif/HeifExport.cpp: In member function 'virtual KisImportExportErrorCode HeifExport::convert(KisDocument*, QIODevice*, KisPropertiesConfigurationSP)'
/usr/src/krita-5.1.5/plugins/impex/heif/HeifExport.cpp:477:32: error: 'class heif::ColorProfile_nclx' has no member named 'set_color_primaties'; did you mean 'set_color_primaries'?
  477 |                nclxDescription.set_color_primaties(heif_color_primaries_ITU_R_BT_2020_2_and_2100_0);
      |                                ^~~~~~~~~~~~~~~~~~~
      |                                set_color_primaries
/usr/src/krita-5.1.5/plugins/impex/heif/HeifExport.cpp:487:32: error: 'class heif::ColorProfile_nclx' has no member named 'set_color_primaties'; did you mean 'set_color_primaries'?
  487 |                nclxDescription.set_color_primaties(heif_color_primaries(primaries));
      |                                ^~~~~~~~~~~~~~~~~~~
      |                                set_color_primaries
make[2]: *** [plugins/impex/heif/CMakeFiles/kritaheifexport.dir/build.make:113: plugins/impex/heif/CMakeFiles/kritaheifexport.dir/HeifExport.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:37975: plugins/impex/heif/CMakeFiles/kritaheifexport.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
`

And the krita folks seems to think spelling is the issue.

**Comment by q234rty** [comment]
It was a spelling issue, then it got fixed by https://github.com/strukturag/libheif/commit/d9dedde4d860cb13c233001826a4a7fc4230b154 but the fix broke krita since the fix simply removed the old api instead of deprecating it...

**Comment by farindk** [comment]
Old name is restored in the just released v1.14.2.
