### ISSUE TITLE
Parsing file path to create output filename might be problematic

### ISSUE THREAD

**Issue by mikebbt** [strukturag/libheif#76]
When extracting multiple images from a HEIC file the code that creates the output filename is using find() to search out the period in the file extension from the path (see heif-convert.cc).  This is a problem if the path itself has a period somewhere in it prior to the actual file, 
ie; /users/username/somedirname.version/filename.ext

In the example above the '.' in "somedirname.version" will be found and changed as if it's the output file when the last period is desired.  Using output_filename.find_last_of('.') would be a better solution.

**Comment by farindk** [comment]
Thank you for reporting this.
I fixed it in ba3ee81.
