### ISSUE TITLE
@CMAKE_INSTALL_PREFIX@/lib: No such file or directory

### ISSUE THREAD

**Issue by bengivre** [strukturag/libheif#771]
Operating system : MacOS
Docker container 

I'm not able to compile and get this error : 

```
#0 64.86 mv -f plugins/.deps/libheif_la-heif_decoder_libde265.Tpo plugins/.deps/libheif_la-heif_decoder_libde265.Plo
#0 64.86 /bin/bash ../libtool  --tag=CXX   --mode=link g++ -fvisibility=hidden  -I@CMAKE_INSTALL_PREFIX@/include     -DLIBHEIF_EXPORTS -I.. -DHAVE_VISIBILITY -g -O2 -Wall -Werror -Wsign-compare -Wconversion -Wno-sign-conversion -Wno-error=conversion -Wno-error=unused-parameter -Wno-error=deprecated-declarations -Wno-error=tautological-compare -version-info 15:2:14  -L/usr/local/lib/ -o libheif.la -rpath /usr/local/lib libheif_la-bitstream.lo libheif_la-box.lo libheif_la-error.lo libheif_la-heif_file.lo libheif_la-heif_image.lo libheif_la-heif.lo libheif_la-heif_context.lo libheif_la-heif_hevc.lo libheif_la-heif_init.lo libheif_la-heif_avif.lo libheif_la-heif_plugin_registry.lo libheif_la-heif_plugin.lo libheif_la-heif_colorconversion.lo libheif_la-metadata_compression.lo libheif_la-nclx.lo   plugins/libheif_la-heif_decoder_libde265.lo      -L@CMAKE_INSTALL_PREFIX@/lib -lde265     -lpthread 
#0 64.92 ../libtool: line 7577: cd: @CMAKE_INSTALL_PREFIX@/lib: No such file or directory
#0 64.93 libtool:   error: cannot determine absolute directory name of '@CMAKE_INSTALL_PREFIX@/lib'
#0 64.93 make[2]: *** [Makefile:1048: libheif.la] Error 1
#0 64.93 make[2] : on quitte le répertoire « /usr/src/libheif/libheif »
#0 64.93 make[1]: *** [Makefile:541: all-recursive] Error 1
#0 64.93 make[1] : on quitte le répertoire « /usr/src/libheif »
#0 64.93 make: *** [Makefile:450: all] Error 2
```

This is my docker-compose file : 
```
RUN cd /usr/src/ && \
  git clone --depth 1 --branch v1.14.2 https://github.com/strukturag/libheif.git && \
  cd libheif/ && \
  ./autogen.sh && \
  ./configure --prefix=/usr/local && \
  make -j$(nproc) && \
  make install && \
  ldconfig /usr/local/lib 
```

I don't understand why it does not work on Docker with MacOS , but it works well on a docker host with Linux 

Thanks!

**Comment by LeSuisse** [comment]
It is possible this issue is caused by the broken pc file of libde265 1.0.10, see https://github.com/strukturag/libde265/issues/387

**Comment by dhnyny** [comment]
I get the same error when trying to upgrade with homebrew.

**Comment by bengivre** [comment]
@LeSuisse you were right. thanks a lot. 

I just used the previous release and it works as expected. I will wait they release a new one. 

Good day

**Comment by farindk** [comment]
@bengivre Could you please confirm that the current master version a0508534e92901b9fbbeed55c01d66f78287ce94 works again? I have revoked the broken change so that I believe it should work the same as before again.

**Comment by bengivre** [comment]
> @bengivre Could you please confirm that the current master version of libde265 [a0508534e](https://github.com/strukturag/libde265/commit/a0508534e92901b9fbbeed55c01d66f78287ce94) works again? I have revoked the broken change so that I believe it should work the same as before again.

I confirm, it works with the current master too [a0508534e](https://github.com/strukturag/libde265/commit/a0508534e92901b9fbbeed55c01d66f78287ce94)

Thanks for the temporary fix.

**Comment by farindk** [comment]
@bengivre Thank you for checking this on macOS. I'll probably do a new libde265 release tomorrow.
