### ISSUE TITLE
Issue while builiding libheif

### ISSUE THREAD

**Issue by harshitbhardwaj19** [strukturag/libheif#774]
Getting this error when trying to build libheif

encoder_png.cc:124:63: error: ‘png_set_eXIf_1’ was not declared in this scope
       png_set_eXIf_1(png_ptr, info_ptr, (png_uint_32)size, ptr);

**Comment by farindk** [comment]
You seem to have an old libpng installed.
Could you please check if it compiles with the above change?

**Comment by kmilos** [comment]
Yep, libpng 1.6.32 or later is needed for this to work.

**Comment by harshitbhardwaj19** [comment]
Thank you so much, installing the latest libpng version worked for me and libheif successfully compiled and installed after this.
However, after running configure for ImageMagick (./configure --with-heic=yes), I am facing this issue : 

checking for libheif >= 1.4.0... no
