### ISSUE TITLE
Why GPL license is present in copying folder of libheif?

### ISSUE THREAD

**Issue by MT2017090** [strukturag/libheif#778]
'libheif' is distributed under the terms of the LGPL license but I am wondering about the GPL license (version 3) which is present in the COPYING folder. Example programs used to be under GPL license but after this https://github.com/strukturag/libheif/issues/87 issue, they all were changed into MIT license. I am guessing that GPL-licensed text in copying.txt is redundant and no code in 'libheif' comes under this now. I am looking forward to the confirmation about this.

**Comment by farindk** [comment]
I'm not sure where you found this.
The `COPYING` in the main directory is LGPL and `examples/COPYING` is MIT.
Where did you find this?

**Comment by kmilos** [comment]
@farindk Indeed, the file https://github.com/strukturag/libheif/blob/master/COPYING contains multiple licenses in it.

**Comment by farindk** [comment]
Yes, but I think that's correct, because the LGPL is written as a modification of the GPL.
Thus, the COPYING file should contain both.

**Comment by kmilos** [comment]
You're right, both need to be present, and [FSF even recommends as separate](https://www.gnu.org/licenses/gpl-howto.en.html) files, but this is overkill maybe...

**Comment by farindk** [comment]
Ok, then we keep it like it is. Separating this into separate files is definitely more confusing as one place with the explanation at the top.
