### ISSUE TITLE
'DT_REG' and 'DT_LNK' was not declared

### ISSUE THREAD

**Issue by joutvhu** [strukturag/libheif#782]
CMake
```ruby
FetchContent_Declare(libheif
  GIT_REPOSITORY https://github.com/strukturag/libheif.git
  GIT_TAG 67739b6c2d060ba276dcffc9b3975c7eb4aca416  # master
)
FetchContent_MakeAvailable(libheif)
```

Error log:
```
/cygdrive/d/Documents/Library/C/libheif_test/cmake-build-debug/_deps/libheif-src/libheif/plugins_unix.cc: In function 'std::vector<std::basic_string<char> > list_all_potential_plugins_in_directory_unix(const char*)':
/cygdrive/d/Documents/Library/C/libheif_test/cmake-build-debug/_deps/libheif-src/libheif/plugins_unix.cc:67:23: error: 'DT_REG' was not declared in this scope
   67 |     if ((d->d_type == DT_REG || d->d_type == DT_LNK) && strlen(d->d_name) > 3 &&
      |                       ^~~~~~
/cygdrive/d/Documents/Library/C/libheif_test/cmake-build-debug/_deps/libheif-src/libheif/plugins_unix.cc:67:46: error: 'DT_LNK' was not declared in this scope
   67 |     if ((d->d_type == DT_REG || d->d_type == DT_LNK) && strlen(d->d_name) > 3 &&
      |                                              ^~~~~~
make[3]: *** [_deps/libheif-build/libheif/CMakeFiles/heif.dir/build.make:280: _deps/libheif-build/libheif/CMakeFiles/heif.dir/plugins_unix.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:322: _deps/libheif-build/libheif/CMakeFiles/heif.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:199: CMakeFiles/libheif_test.dir/rule] Error 2
make: *** [Makefile:189: libheif_test] Error 2
```

**Comment by fancycode** [comment]
A quick search found this:
https://stackoverflow.com/a/69691361

> You can use [feature macros](https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html) to enable additional extensions. As [readdir manual](https://man7.org/linux/man-pages/man3/readdir.3.html) mentions, you need _DEFAULT_SOURCE macro to enable file type constants.
> 
> You can do this in the source code before including dirent.h
>
>```C++
> #define _DEFAULT_SOURCE
> #include <dirent.h>
>```

**Comment by farindk** [comment]
@joutvhu Can you please try whether it compiles with the above change?

**Comment by joutvhu** [comment]
I tried but it didn't solve the issue

![image](https://user-images.githubusercontent.com/9401202/218736117-7ca6b1ab-b6a1-4877-b625-cebb844dfe62.png)
![image](https://user-images.githubusercontent.com/9401202/218736056-4527012f-11af-4fa6-ae93-f605df7b0b5e.png)

**Comment by farindk** [comment]
As it seems that we must not set `__BSD_VISIBLE` from application code (see: https://lists.freebsd.org/pipermail/freebsd-standards/2004-March/000474.html), this could mean that file types are not supported on your system.
Hence, we now only check the file type if these macros are available.

@joutvhu Please check again with the above change.

**Comment by farindk** [comment]
Thanks for checking.
