### ISSUE TITLE
Unsupported feature: Unsupported codec" error when using heif-convert on HEIC image

### ISSUE THREAD

**Issue by harshitbhardwaj19** [strukturag/libheif#800]
I'm trying to convert a HEIC image file to JPEG format using the heif-convert command, but I'm getting an error "Unsupported feature: Unsupported codec (4.3000)" and the conversion fails. I've also tried using the convert command from ImageMagick to convert the HEIC file to JPEG, but I'm getting a similar error.

Here are the commands I'm running:

**heif-convert sample1.heic abc.jpg**
and
**/usr/local/ImageMagick/bin/convert sample1.heic abc.jpg**

And here are the error messages I'm seeing:

For heif-convert:
**Could not decode image: 0: Unsupported feature: Unsupported codec**

For convert:
**convert: Unsupported feature: Unsupported codec (4.3000) `sample1.heic' @ error/heic.c/IsHEIFSuccess/139.
convert: no images defined `abc.jpg' @ error/convert.c/ConvertImageCommand/3342**

I've already tried updating to the latest version of libheif, but the issue still persists. I've also checked the HEIC file for corruption and tried converting it to other formats, but the issue remains.

Is there anything else I can do to troubleshoot this issue? Are there any additional dependencies or libraries that libheif requires to handle HEIC files with this particular codec?

Any help or guidance on this issue would be greatly appreciated.

Environment:

ImageMagick version
7.1.1-4 Q16-HDRI x86_64 20976

Operating system
centOS

Operating system, version and so on
CentOS Linux release 7.6.1810 (Core)

**Comment by silverbacknet** [comment]
The OS version of the package won't include a number of non-free libraries, but as you have 7.1 I assume you built it yourself or brought it from another repo. (6.9 is Centos 7's, iirc.) I remember that --enable-heic was required for configure a few years ago, if you built it yourself, try that. If you downloaded it, it probably didn't even include support, and you'll have to build locally.

**Comment by harshitbhardwaj19** [comment]
Thank you for your response!

I did indeed build ImageMagick with HEIC support from source, as the OS version did not include the necessary libraries. I used the "--with-heic=yes" option during configuration, which is the current method for enabling HEIC support. Your suggestion to use "--enable-heic" is outdated now. 

I'm facing these errors after going through these steps.

Thanks again for your feedback, and please let me know if you have any further suggestions or questions!

**Comment by farindk** [comment]
You can list which decoders/encoders are installed as so:
````
$ heif-convert --list-decoders
HEIC decoders:
- libde265 = libde265 HEVC decoder, version 1.0.11
AVIF decoders:
- dav1d = dav1d v6.6.0
- aom = AOMedia Project AV1 Decoder v3.3.0

$ heif-enc --list-encoders
HEIC encoders:
- x265 = x265 HEVC encoder (3.5+1-f0c1022b6) [default]
AVIF encoders:
- aom = AOMedia Project AV1 Encoder v3.3.0 [default]
- svt = SVT-AV1 encoder v1.2.1
- rav1e = Rav1e encoder
````

**Comment by harshitbhardwaj19** [comment]
Thank you for your response! It helped me identify that the issue was with the decoder. Specifically, the problem was with PKG_CONFIG_PATH. By adding the path of the .pc files for libde265 to PKG_CONFIG_PATH and then reinstalling libheif, I was able to resolve the issue.

I appreciate your assistance and guidance in troubleshooting this problem. Thank you again!

**Comment by tuananhzippy** [comment]
> 

I am also facing this problem after translating from source. This is the process I do

```
cd /root
wget https://github.com/strukturag/libde265/releases/download/v1.0.8/libde265-1.0.8.tar.gz
tar xf libde265-1.0.8.tar.gz
cd libde265-1.0.8
./autogen.sh
./configure
make
sudo make install
```

```
cd ..
wget https://github.com/strukturag/libheif/releases/download/v1.12.0/libheif-1.12.0.tar.gz
tar xf libheif-1.12.0.tar.gz
cd libheif-1.12.0
./autogen.sh
./configure
make
sudo make install
```

```
heif-enc --list-encoders
Encoders (first is default):
```


How did you fix this problem, can you share it with me?

**Comment by silverbacknet** [comment]
de265 isn't an encoder. You need some set of: aom, x265, svt-av1, rav1e
