### ISSUE TITLE
heif-thumbnailer unable to proces HEVC-encoded HEIF file

### ISSUE THREAD

**Issue by rathann** [strukturag/libheif#825]
With libheif-1.15.2, I'm getting this error:
```
$ file image1.heic 
image1.heic: ISO Media, HEIF Image HEVC Main or Main Still Picture Profile
$ heif-convert --list-decoders
HEIC decoders:
- libde265 = libde265 HEVC decoder, version 1.0.9
AVIF decoders:
- dav1d = dav1d v6.6.0
- aom = AOMedia Project AV1 Decoder v3.6.0
$ heif-convert image1.heic image1.jpeg
File contains 1 image
Written to image1.jpeg
$ heif-thumbnailer -s 128x128 image1.heic image1-t.heic
Could not decode HEIF image : Unsupported feature: Unsupported codec
```
Sample image attached (gzipped, otherwise github rejects upload).
[image1.heic.gz](https://github.com/strukturag/libheif/files/11295000/image1.heic.gz)

**Comment by farindk** [comment]
Right. There is a bug when you use libheif with the codecs compiled as independent plugins, the `heif-thumbnailer` will not load the plugins.
I have fixed this in c086da0f73579947e460750aee0e308adae8326d. Please try with the current version in master branch.
