### ISSUE TITLE
Viewing HEIF/HEIC photos in Ubuntu 23.04/lunar does not work anymore

### ISSUE THREAD

**Issue by marianrh** [strukturag/libheif#827]
In previous Ubuntu versions, including 22.10, I was able to open HEIF/HEIC files by installing libheif1 and heif-gdk-pixbuf. This does not work anymore in 23.04.

I created an Ubuntu bug report for this at https://bugs.launchpad.net/ubuntu/+source/libheif/+bug/2017420, but also wanted to create one here to be sure. If you feel that this is inappropriate, feel free to close.

Running eog in a terminal displays:
```
$ eog IMG_9996.HEIC

** (eog:44492): WARNING **: 14:29:17.537: Cannot read plugin directory.

(eog:44492): GdkPixbuf-CRITICAL **: 14:29:17.537: gdk_pixbuf_animation_is_static_image: assertion 'GDK_IS_PIXBUF_ANIMATION (animation)' failed

(eog:44492): GdkPixbuf-CRITICAL **: 14:29:17.538: gdk_pixbuf_animation_get_iter: assertion 'GDK_IS_PIXBUF_ANIMATION (animation)' failed

(eog:44492): GdkPixbuf-CRITICAL **: 14:29:17.538: gdk_pixbuf_animation_iter_get_pixbuf: assertion 'GDK_IS_PIXBUF_ANIMATION_ITER (iter)' failed

** (eog:44492): WARNING **: 14:29:17.543: Cannot read plugin directory.

(eog:44492): GdkPixbuf-CRITICAL **: 14:29:17.543: gdk_pixbuf_animation_is_static_image: assertion 'GDK_IS_PIXBUF_ANIMATION (animation)' failed

(eog:44492): GdkPixbuf-CRITICAL **: 14:29:17.543: gdk_pixbuf_animation_get_iter: assertion 'GDK_IS_PIXBUF_ANIMATION (animation)' failed

(eog:44492): GdkPixbuf-CRITICAL **: 14:29:17.543: gdk_pixbuf_animation_iter_get_pixbuf: assertion 'GDK_IS_PIXBUF_ANIMATION_ITER (iter)' failed
```

eog then shows `Could not load image “IMG_9996.HEIC”. Image loading failed.`

gpicview even crashes immediately:
```
$ gpicview IMG_9996.HEIC
Gtk-Message: 14:30:30.216: Failed to load module "canberra-gtk-module"

** (gpicview:44624): WARNING **: 14:30:30.260: Cannot read plugin directory.

** (gpicview:44624): WARNING **: 14:30:30.265: Cannot read plugin directory.
Segmentation fault (core dumped)
```

The problem concerns all HEIF/HEIC images I tested.

The installed versions of the (possibly) relevant packages are:
libheif1: 1.14.2-1
heif-gdk-pixbuf: 1.14.2-1
libgdk-pixbuf-2.0-0: 2.42.10+dfsg-1build1
eog: 44.0-1
gpicview: 0.2.5-3build1

**Comment by farindk** [comment]
The "Cannot read plugin directory" error apparently comes from libheif. It tries to find additional codecs in its plugin directory but cannot open that directory.
The plugin directory is specified by the `LIBHEIF_PLUGIN_PATH` environment variable and a standard path has been compiled into libheif itself (configurable, defaults to a subdirectory `libheif` in the library install path).

Can you check which directory is set as plugin path? If the environment variable is not set, you may use `strace` to see what directory it tries to open.

As far as I know, the Ubuntu packages do not use the plugins currently. So just having an empty directory at that place would be sufficient.

**Comment by farindk** [comment]
Note: later versions of libheif do not output this error anymore. They ignore it when the plugin directory does not exist.

**Comment by marianrh** [comment]
Thank you for the extremely fast reply (on a Sunday!), Dirk, you're spot on! The path that's being tried to open is `/usr/lib/x86_64-linux-gnu/libheif/plugins`. `libheif` doesn't exist. After creating `libheif/plugins`, eog and gpicview start working :)

I'll add this workaround to the Ubuntu bug report!

So Ubuntu (or Debian) could fix it either by creating the path when installing the package, or by upgrading libheif to a newer version (which one?), correct?

**Comment by farindk** [comment]
> So Ubuntu (or Debian) could fix it either by creating the path when installing the package, or by upgrading libheif to a newer version (which one?), correct?

Yes. The behavior is changed in v1.15.0, but you'll probably want to get the latest patch version v1.15.2

**Comment by marianrh** [comment]
Thanks again!

**Comment by tuxaddict** [comment]
> The "Cannot read plugin directory" error apparently comes from libheif. It tries to find additional codecs in its plugin directory but cannot open that directory. The plugin directory is specified by the `LIBHEIF_PLUGIN_PATH` environment variable and a standard path has been compiled into libheif itself (configurable, defaults to a subdirectory `libheif` in the library install path).
> 
> Can you check which directory is set as plugin path? If the environment variable is not set, you may use `strace` to see what directory it tries to open.
> 
> As far as I know, the Ubuntu packages do not use the plugins currently. So just having an empty directory at that place would be sufficient.

Just to confirm that the solution creating the folders `libheif/plugins` is working here as well! Thank you guys very much! (-: 
Ubuntu 23.04 6.2.0-20-generic, libheif 1.14.2-1
