### ISSUE TITLE
What is HEIF/HEIC magic number?

### ISSUE THREAD

**Issue by Jehan** [strukturag/libheif#83]
Hi!

At GIMP's we had a report about a file wrongly interpreted as HEIC because of the wrong extension. Normally we are able to avoid this kind of error if we add magic number detection.

I couldn't get clear details about what can be considered as HEIC/HEIF magic number. Looking at a few sample images, I found that the string "ftyp" at the 5th bytes seems like a constant in every HEIC/HEIF file. Yet since I understand that HEIC/HEIF is a subformat of ISOBMFF, it looks like this magic number would also detect non-HEIC files which are ISOBMFF, right? At least it also worked with a `.mov` file (unfortunately!).

In the various HEIC files I could find, the longer string was either `ftypmif1` or `ftypheic`. Would both these strings qualify as good magic numbers? Can there be other variants?
All the files I had in my possession also had the string `mif1heic` at the 16th byte. Is it also a confirmed constant? Can I use this as magic keyword instead?

Thanks! :-)

**Comment by Jehan** [comment]
> 'mif1' should not be a valid major brand

A major brand is when it is the 4-byte code after 'ftyp'? So 'ftypmif1' files should not be valid HEIC files according to you?
I actually have a few samples on my disk with this sequence, and they actually opens fine (as far as I can see) with GIMP, which uses libheif. I have no idea where I got them though (probably somewhere on the web, when searching for test samples).
For instance (I appended a .txt so that github accepts it; obviously remove this extension): 
[season_collection_1440x960.heic.txt](https://github.com/strukturag/libheif/files/2384368/season_collection_1440x960.heic.txt)

I would be a bit sad to reject these files if they work.

> Note that this is not a string. It is not null-terminated.

Yeah I was saying "string" in the meaning of "sequence of bytes". Our code does not assume magic numbers to be null-terminated (or even readable text). ;-)

**Comment by farindk** [comment]
I have attached the relevant parts of the MP4 and HEIF standards below.
The file starts with a box header, which is its size (including the box header) and its type ('ftyp').
The header can be tricky to read if one wants to do it 100% correct (largesize), but I've never seen a box with 'largesize' in the ftyp box. So you can probably assume a fixed byte offset for ftyp.

This is followed by the major brand and a version, then a list of compatible brands. The number of compatible brands in the list must be derived from the box size. As far as I understand, 'heic' should be the major brand, or at least appear in the compatible brands list. The Nokia example you attached (season collection) puts 'mif1' into the major brand, which seems unusual, but might be still conforming to the standard as 'heic' appears in the list of compatible brands.

Would it help if libheif provided a method for quickly checking the file-type? That might be useful for other projects too, I guess.

---

Syntax of box header:
![screenshot from 2018-09-16 14-48-58](https://user-images.githubusercontent.com/968944/45596699-3b076580-b9c0-11e8-8fb4-f2f25ca03eb8.png)

Syntax of ftyp box:
![screenshot from 2018-09-16 14-49-18](https://user-images.githubusercontent.com/968944/45596691-1ad7a680-b9c0-11e8-863c-056b4a261488.png)

**Comment by Jehan** [comment]
> I have attached the relevant parts of the MP4 and HEIF standards below.

Thanks! Looking at this, it is confirmed the compatible brands are actually at fixed offset (well unless the box uses a largesize, but as you note, that probably nearly never happens), but it doesn't give any order for the brands. I imagine then that the fact that all the files in my possession had `mif1heic` in the list cannot therefore be considered as a constant, just chance.

> Would it help if libheif provided a method for quickly checking the file-type? That might be useful for other projects too, I guess.

Not really. Or to be accurate, we are already checking the file type before we even get to the file plug-in. Basically for this, every file plug-in register oneself with file name extensions and magic bytes (the magic takes precedence over the extension of course, as it is much more reliable).
This algorithm has the merit to be both simple and efficient.

Anyway I think I will just use `ftyp(heic|heix|…|mif1)` as magic (basically "ftyp" + the list you gave me including "mif1" since I actually encountered this one). I think this should be both generic and accurate enough to detect a HEIF file.

Thanks for all the help. Unless you want to leave this opened (for any file type detection API or anything), I guess you can close.

**Comment by Jehan** [comment]
For the record, this was the bug report at GIMP: https://gitlab.gnome.org/GNOME/gimp/issues/2209

And my commits:
https://gitlab.gnome.org/GNOME/gimp/commit/d738d2f645abe16457311389b8827ecd80ca71da
https://gitlab.gnome.org/GNOME/gimp/commit/4ad3993eca935854ef2f5664fb77a75c128bbf4d

Thanks again!

**Comment by farindk** [comment]
I had another look into the specs. The brand 'mif1' seems to be actually allowed as the major brand. In that case, the file extension and MIME type defined in the file (requires deep parsing) should be considered.
Some parts of the spec seem to be much more complicated than necessary to me...

And btw. you might also check for 'msf1', which is the equivalent case for image sequences.

**Comment by fancycode** [comment]
@farindk maybe it would be a good idea to provide a function in libheif to check if some data looks like a heif file?

**Comment by farindk** [comment]
Yes, that's what I proposed a few posts above. As Jehan said, it will not work for GIMP, because they'd like to check the format before even accessing the plugin, but we should still add such a function.

**Comment by farindk** [comment]
merged the file-type detection into `master`
