### ISSUE TITLE
Package name libheif-1.16.0-Source

### ISSUE THREAD

**Issue by arjendekorte** [strukturag/libheif#838]
Is it intentional that the package is now named `libheif-1.16.0-Source` (compared to the previous version that was named `libheif-1.15.2`?

**Comment by farindk** [comment]
This is because the packages are now generated with CPack instead of the autotools "make dist".
Is this a problem?

**Comment by arjendekorte** [comment]
No, not really. Just wondering if this was a glitch or intentional.
