### ISSUE TITLE
can't untar libheif 1.16.1 with msys2

### ISSUE THREAD

**Issue by vtorri** [strukturag/libheif#843]
error:

```
tar zxvf libheif-1.16.1.tar.gz
...
...
tar: libheif-1.16.1/tests/src/github.com/strukturag/libheif/go: Cannot create symlink to ‘/home/farindk/Projects/libheif/libheif/tests/../go’: No such file or directory
```

**Comment by farindk** [comment]
Thank you. Those files should not be in the tar archive.
I have replaced the file with a corrected one.

**Comment by fancycode** [comment]
Updating release tarballs should be avoided if possible. Packagers usually use the "official" release tarball as source tarball and keep checksums of that. If the upstream tarball changes, the checksums of the packaged release tarballs are no longer valid when compared against upstream.

So unfortunately the right way to handle such cases would be to do a new release.

The old `make dist` handled creating the tarball correctly by only including files mentioned in the makefiles, is this different with cmake? You could also keep a "clean" checkout from which you do the releases to prevent including additional files.

**Comment by kmilos** [comment]
> The old `make dist` handled creating the tarball correctly by only including files mentioned in the makefiles, is this different with cmake?

One can use [CPack](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Packaging%20With%20CPack.html) as replacement.

Or, if no special steps are needed, just let GitHub generate those from a clean tree of the tag.
