### ISSUE TITLE
User annotations do not work for region items

### ISSUE THREAD

**Issue by 0xC0000054** [strukturag/libheif#858]
The `heif_item_add_property_user_description(ctx, region_item_id, desc, NULL)` call succeeds and the user annotation appears to have been written to the file.
But `heif_item_get_properties_of_type(ctx, region_item_id, heif_item_property_type_user_description, properties, count)` returns 0 items.

This is due to [get_properties](https://github.com/strukturag/libheif/blob/e411241b9afd0ac96e78045cb5fb815e906f09ff/libheif/heif.cc#L1835) returning an error with the message "Item (ID=2) has no properties assigned to it in ipma box".

The following zip file contains a HEIF image that demonstrates this issue: [test.zip](https://github.com/strukturag/libheif/files/11417748/test.zip)

**Comment by bradh** [comment]
Indeed the `ipma` entry in that file for the rgan item is not pointing to the correct item id - it is pointing to item_id = 0, instead of item_id = 2.

Can you show more code, or the command line tool + options you used to create it?

**Comment by 0xC0000054** [comment]
> Indeed the ipma entry in that file for the rgan item is not pointing to the correct item id - it is pointing to item_id = 0, instead of item_id = 2.

Thanks for looking into this.

The code is part of an upcoming update to my LibHeifSharp library that adds support for the version 1.16.0 APIs.

I had forgotten to call `heif_region_item_get_id` after creating the region item, which caused the region item id to always be zero.
I overlooked that when debugging my encoding code.
