### ISSUE TITLE
heic to PNG cannot retain the alpha channel

### ISSUE THREAD

**Issue by eliassama** [strukturag/libheif#867]
like this: https://static.elias.ink/resource/Elasticsearch-Logo-Color-V.heic

**Comment by farindk** [comment]
Works perfectly.
````
heif-convert Elasticsearch-Logo-Color-V.heic out.png
````
and the PNG has an alpha channel.
Here is the PNG: 
![out](https://github.com/strukturag/libheif/assets/968944/aa900bef-4ade-462d-936b-efe00011d72a)
