### ISSUE TITLE
Build Error with Brew on macOS

### ISSUE THREAD

**Issue by ywwn** [strukturag/libheif#871]
Please pardon my disturbance, I couldn't compile libheif since v1.16.0.

I uses brew [formula](https://github.com/Homebrew/homebrew-core/blob/7a34021a6c0f0ad45d38c463d33435574713a1a1/Formula/libheif.rb) to compile, and get two errors:

```
/tmp/libheif-20230523-31616-1nzbo7y/libheif-1.16.2/libheif/plugins/encoder_rav1e.cc:38:10: fatal error: 
      'rav1e.h' file not found
#include "rav1e.h"
         ^~~~~~~~~
1 error generated.
make[2]: *** [libheif/plugins/CMakeFiles/heif-rav1e.dir/encoder_rav1e.cc.o] Error 1
make[1]: *** [libheif/plugins/CMakeFiles/heif-rav1e.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

```
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -bundle -Wl,-headerpad_max_install_names -compatibility_version 1.0.0 -current_version 1.16.2 -o libheif-svtenc.so "CMakeFiles/heif-svtenc.dir/encoder_svt.cc.o" "CMakeFiles/heif-svtenc.dir/__/heif_plugin.cc.o"  -Wl,-rpath,/tmp/libheif-20230523-31616-1nzbo7y/libheif-1.16.2/build/libheif /usr/local/lib/libSvtAv1Enc.dylib ../libheif.1.16.2.dylib 
clang: error: invalid argument '-compatibility_version 1.0.0' only allowed with '-dynamiclib'
make[2]: *** [libheif/plugins/libheif-svtenc.so] Error 1
make[1]: *** [libheif/plugins/CMakeFiles/heif-svtenc.dir/all] Error 2
...
make: *** [all] Error 2
```

Environment:

```
HOMEBREW_VERSION: 4.0.19-9-g8aaf99e
CPU: octa-core 64-bit haswell
Clang: 12.0.0 build 1200
macOS: 10.15.7-x86_64
Xcode: 12.4

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
```

Related issue (maybe):

#290 

If anyone can help me it would be greatly appreciated!

**Comment by bigcat88** [comment]
```brew install rav1e```

_but brew builds libheif without rav1e or dav1d, as far as I know_

**Comment by ywwn** [comment]
> `brew install rav1e`
> 
> _but brew builds libheif without rav1e or dav1d, as far as I know_

Thanks for replying, I have installed rav1e but the same result.

**Comment by bigcat88** [comment]
Tried myself to built formula from source:

```
...
Compiling 'x265' as built-in backend
Compiling 'libde265' as built-in backend
Compiling 'dav1d' as built-in backend
Compiling 'aomdec' as built-in backend
Compiling 'aomenc' as built-in backend
Compiling 'svtenc' as dynamic plugin
...
```

I think this should be reported as an issue in brew repositories, not here.

They forgot to include dav1d, svtenc as dependencies in their formula or if not and they wany to compile libheif without this as in previous versions, then they should do something like this:
```
      -DWITH_RAV1E=OFF \
      -DWITH_DAV1D=OFF \
      -DWITH_SvtEnc=OFF \
```

**Comment by bigcat88** [comment]
@ywwn try add that three options like this(it helps me to build from source on Ventura)

```
system "cmake", "-S", ".", "-B", "build", *std_cmake_args, "-DCMAKE_INSTALL_RPATH=#{rpath}", "-DWITH_RAV1E=OFF", "-DWITH_DAV1D=OFF",
"-DWITH_SvtEnc=OFF"
```

as an option you probably can disable plugin system with additional `-DENABLE_PLUGIN_LOADING=OFF` (I did not disabling it in 1.16.2 yet)

**Comment by bradh** [comment]
Does it definitely work in 1.16.0 and break in 1.16.1?

I am concerned I might have busted something in https://github.com/strukturag/libheif/commit/8da2ece185d12b70a4db53ead83fd671d42650e7

However that should only be in 1.16.2, so this mostly feels like an incomplete RAV1E install - where is `rav1e.h` on your system?

**Comment by bigcat88** [comment]
> Does it definitely work in 1.16.0 and break in 1.16.1?
> 
> I am concerned I might have busted something in [8da2ece](https://github.com/strukturag/libheif/commit/8da2ece185d12b70a4db53ead83fd671d42650e7)
> 
> However that should only be in 1.16.2, so this mostly feels like an incomplete RAV1E install - where is `rav1e.h` on your system?

`brew` switched from automake(1.15.2) to cmake(1.16.1), they have no `1.16.0` version, next after `1.15.2` formula is `1.16.2`

**Comment by ywwn** [comment]
> @ywwn try add that three options like this(it helps me to build from source on Ventura)
> 
> ```
> system "cmake", "-S", ".", "-B", "build", *std_cmake_args, "-DCMAKE_INSTALL_RPATH=#{rpath}", "-DWITH_RAV1E=OFF", "-DWITH_DAV1D=OFF",
> "-DWITH_SvtEnc=OFF"
> ```
> 
> as an option you probably can disable plugin system with additional `-DENABLE_PLUGIN_LOADING=OFF` (I did not disabling it in 1.16.2 yet)

Thanks, it just works.

I don't open issue there for they (brew) don't like old macOS which is not continued... (Although it's a brew bug)

I'll open a pull request there. Thanks again!
