### ISSUE TITLE
Dependency issues updating on Arch

### ISSUE THREAD

**Issue by jpretori** [strukturag/libheif#876]
When trying to update my Arch installation today, I got this error message: 

> $  yay -Syu
> :: Synchronizing package databases...
>  core                       134.1 KiB   272 KiB/s 00:00 [##############################] 100%
>  extra                        8.3 MiB  6.90 MiB/s 00:01 [##############################] 100%
>  community is up to date
>  multilib is up to date
> :: Starting full system upgrade...
> resolving dependencies...
> looking for conflicting packages...
> error: failed to prepare transaction (could not satisfy dependencies)
> :: installing libheif (1.16.2-1) breaks dependency 'libheif=1.16.1' required by lib32-libheif
> :: installing rav1e (0.6.6-1) breaks dependency 'rav1e=0.6.3' required by lib32-rav1e
>  -> error refreshing databases - exit status 1

Telling pacman to ignore the two packages for upgrading makes the system upgrade work:

`$  yay -Syu --ignore libheif,rav1e`

**Comment by silverbacknet** [comment]
I think you'd want to report that to Arch, that's all on their side.
