### ISSUE TITLE
New Release Request

### ISSUE THREAD

**Issue by ikerr** [strukturag/libheif#88]
Apologies if this is not the right place to request a new release, but it would be great to have one that includes fixes related to ImageMagick. For example:

- https://github.com/strukturag/libheif/issues/47
- https://github.com/strukturag/libheif/issues/48
- https://github.com/strukturag/libheif/issues/49
- https://github.com/strukturag/libheif/issues/50

**Comment by dustymabe** [comment]
yes please. thanks!

**Comment by tonycoz** [comment]
Getting:

6f5658898e46cf51be5a80fa60cdd4503037615d

and

0a03d6fc2b4e26c3fbb0b541f70f83e45a56bd5f

into a release would be useful.

Non-zero m_reserved in Box_hdlr and non-zero m_item_protection_index in Box_infe both seem to prevent Preview.app on OS X from loading heif images.

For simple cases like heif-enc this isn't a problem, but if new() re-uses freed memory, the lack of initialisers breaks the images.

**Comment by farindk** [comment]
Finally released v1.4.0 :-)
Debian package will follow soon.

**Comment by davidcantrelluk2** [comment]
any news on a debian-testing package?

**Comment by fancycode** [comment]
The Debian packaging is ready but unfortunately still waiting for the sponsor to be added to the repository:
https://mentors.debian.net/package/libheif
https://alioth-lists.debian.net/pipermail/pkg-multimedia-maintainers/2019-March/065516.html

**Comment by tonycoz** [comment]
Unfortunately debian testing is now in freeze (though it wasn't on 2019-02-27.)
https://lists.debian.org/debian-devel-announce/2019/03/msg00003.html

**Comment by fancycode** [comment]
The package is now available in `experimental`:
https://packages.debian.org/source/experimental/libheif

After the freeze (i.e. when Debial "buster" is released) we will upload to `unstable` again.

Closing this issue for now.

**Comment by davidcantrelluk2** [comment]
Thanks, 1.4.0 from 'experimental' works for me.
