### ISSUE TITLE
How do I obtain binary data of encoded images

### ISSUE THREAD

**Issue by liudian** [strukturag/libheif#892]
How do I obtain binary data of encoded images

For example: obtain the complete binary data of HEIC through the context object after encoding HEVC

I tried using the following code:
```
StreamWriter swriter;
context_->context->write(swriter);
std::vector<uint8_t> data = swriter.get_data();
```

But there was an error during compilation: 
**undefined reference to ` HeifContext:: write (StreamWriter&) '**

**Comment by dukesook** [comment]
Your program can't call HeifContext::write() because that function is internal to the library. Refer to "heif.h" which lists all the api functions that you should be using.

There's a function called heif_image_get_plane() which returns the a pointer to the image pixel data. Here's an example:

 ```C
//Heif Error - Check to see if a function was successful
static void he (struct heif_error error) {
  if (error.code) {
    printf("ERROR! - %s\n", error.message);
    exit(error.code);
  }
}

static void get_pixel_data(const char* filename) {
  //Create New Context
  heif_context* ctx = heif_context_alloc();
  
  //Read HEIF from file
  he (heif_context_read_from_file(ctx, filename, nullptr) );

  //Get Primary Image Handle
  heif_image_handle* handle; //The heif_image_handle acts as a wrapper around the heif_image
  he (heif_context_get_primary_image_handle(ctx, &handle) );

  //Decode Image
  heif_image* img; //The pixel data is compressed when stored in a file.
  heif_colorspace colorspace = heif_colorspace_RGB; //Assuming the image is RGB
  heif_chroma chroma = heif_chroma_interleaved_RGB; //Assuming the image is Interleaved
  he (heif_decode_image(handle, &img, colorspace, chroma, nullptr) ); 

  //Get Pixel Data
  heif_channel channel = heif_channel_interleaved; //Assuming the image is Interleaved
  int stride; //Number of bytes in a row (not pixels)
  uint8_t* pixel_data = heif_image_get_plane(img, channel, &stride);

  //Print the first 5 pixels
  uint8_t r, g, b;
  int channel_count = 3;
  for (int i = 0; i < channel_count * 5; i = i + channel_count) {
    r = pixel_data[i + 0];  //Red
    g = pixel_data[i + 1];  //Green
    b = pixel_data[i + 2];  //Blue
    printf("r=%u g=%u b=%u\n", r, g, b);
  }

  //Get Width & Height
  int height = heif_image_get_height(img, channel);
  int width = heif_image_get_width(img, channel);
  printf("width: %d   height: %d\n", width, height);

}

 ```

**Comment by bradh** [comment]
@liudian Are you looking for a byte array after encoding?

**Comment by liudian** [comment]
> 

Thank you for your answer

I don't just need pixel data, I also need the header data of the Heic, just like the complete data obtained from a Heic file.

Of course, I can also read a Heic file to obtain complete data, but I want to directly obtain the complete data after encoding, without the need to persist the image to disk and reread it, which is too inefficient

**Comment by liudian** [comment]
> Your program can't call HeifContext::write() because that function is internal to the library. Refer to "heif.h" which lists all the api functions that you should be using.
> 
> There's a function called heif_image_get_plane() which returns the a pointer to the image pixel data. Here's an example:
> 
> ```c
> //Heif Error - Check to see if a function was successful
> static void he (struct heif_error error) {
>  if (error.code) {
>    printf("ERROR! - %s\n", error.message);
>    exit(error.code);
>  }
> }
> 
> static void get_pixel_data(const char* filename) {
>  //Create New Context
>  heif_context* ctx = heif_context_alloc();
>  
>  //Read HEIF from file
>  he (heif_context_read_from_file(ctx, filename, nullptr) );
> 
>  //Get Primary Image Handle
>  heif_image_handle* handle; //The heif_image_handle acts as a wrapper around the heif_image
>  he (heif_context_get_primary_image_handle(ctx, &handle) );
> 
>  //Decode Image
>  heif_image* img; //The pixel data is compressed when stored in a file.
>  heif_colorspace colorspace = heif_colorspace_RGB; //Assuming the image is RGB
>  heif_chroma chroma = heif_chroma_interleaved_RGB; //Assuming the image is Interleaved
>  he (heif_decode_image(handle, &img, colorspace, chroma, nullptr) ); 
> 
>  //Get Pixel Data
>  heif_channel channel = heif_channel_interleaved; //Assuming the image is Interleaved
>  int stride; //Number of bytes in a row (not pixels)
>  uint8_t* pixel_data = heif_image_get_plane(img, channel, &stride);
> 
>  //Print the first 5 pixels
>  uint8_t r, g, b;
>  int channel_count = 3;
>  for (int i = 0; i < channel_count * 5; i = i + channel_count) {
>    r = pixel_data[i + 0];  //Red
>    g = pixel_data[i + 1];  //Green
>    b = pixel_data[i + 2];  //Blue
>    printf("r=%u g=%u b=%u\n", r, g, b);
>  }
> 
>  //Get Width & Height
>  int height = heif_image_get_height(img, channel);
>  int width = heif_image_get_width(img, channel);
>  printf("width: %d   height: %d\n", width, height);
> 
> }
> ```

Thank you for your answer

I don't just need pixel data, I also need the header data of the Heic, just like the complete data obtained from a Heic file.

Of course, I can also read a Heic file to obtain complete data, but I want to directly obtain the complete data after encoding, without the need to persist the image to disk and reread it, which is too inefficient

**Comment by liudian** [comment]
> @liudian Are you looking for a byte array after encoding?


Yes, I want to obtain a byte array similar to a Heic file from memory after the encoding operation is completed. But I couldn't find a similar method in the libheif interface.

**Comment by bradh** [comment]
> > @liudian Are you looking for a byte array after encoding?
> 
> Yes, I want to obtain a byte array similar to a Heic file from memory after the encoding operation is completed. But I couldn't find a similar method in the libheif interface.

The options are to write it to a file (using `heif_context_write_to_file()`), or to make yourself a `heif_writer` implementation and write to that using `heif_context_write()`. See https://github.com/strukturag/libheif/blob/252c2228225d1836f50f3f80d9dd27909ae75f4c/libheif/heif.h#L1547-L1570

If you are looking for an example of the first, see https://github.com/strukturag/libheif/blob/252c2228225d1836f50f3f80d9dd27909ae75f4c/examples/heif_enc.cc#L900

What you do for the second is a bit more application specific, but you can always see how `heif_context_write_to_file()` is implemented at https://github.com/strukturag/libheif/blob/252c2228225d1836f50f3f80d9dd27909ae75f4c/libheif/heif.cc#L2154-L2161 and https://github.com/strukturag/libheif/blob/252c2228225d1836f50f3f80d9dd27909ae75f4c/libheif/heif.cc#L2154-L2161

That said, consider evaluating your design to make sure you really need an in-memory representation. HEIF is, after all, a file format. It's obviously your call though.

**Comment by liudian** [comment]
> > > @liudian Are you looking for a byte array after encoding?
> > 
> > 
> > Yes, I want to obtain a byte array similar to a Heic file from memory after the encoding operation is completed. But I couldn't find a similar method in the libheif interface.
> 
> The options are to write it to a file (using `heif_context_write_to_file()`), or to make yourself a `heif_writer` implementation and write to that using `heif_context_write()`. See
> 
> https://github.com/strukturag/libheif/blob/252c2228225d1836f50f3f80d9dd27909ae75f4c/libheif/heif.h#L1547-L1570
> 
> If you are looking for an example of the first, see
> 
> https://github.com/strukturag/libheif/blob/252c2228225d1836f50f3f80d9dd27909ae75f4c/examples/heif_enc.cc#L900
> 
> What you do for the second is a bit more application specific, but you can always see how `heif_context_write_to_file()` is implemented at
> 
> https://github.com/strukturag/libheif/blob/252c2228225d1836f50f3f80d9dd27909ae75f4c/libheif/heif.cc#L2154-L2161
> and
> 
> https://github.com/strukturag/libheif/blob/252c2228225d1836f50f3f80d9dd27909ae75f4c/libheif/heif.cc#L2138-L2151
> 
> That said, consider evaluating your design to make sure you really need an in-memory representation. HEIF is, after all, a file format. It's obviously your call though.

Thank you for your answer.

``` 
  MemoryWriter writer;
  struct heif_writer w;
  w.writer_api_version = 1;
  w.write = writer_write;
  heif_context_write(context.get(), &w, &writer);
  assert(writer.size() > 0);
```

Can I also refer to the code in the fuzzing path fuzzer.cc?
Can I obtain binary data of the image in the writer object?

**Comment by bradh** [comment]
You can refer to whatever code you like - this is a key part of open source. I don't think the fuzzer is a great example for learning from though - it is designed to do something else.

> Can I obtain binary data of the image in the writer object?

I'm an unsure what you mean by "the image" here.  Do you mean the encoded byte array (i.e. HEIF format wrapping the HEVC bit streams and metadata), or the image planes? You can use the `heif_context` you get passed in various parts of the libheif API - see heif.h.

**Comment by liudian** [comment]
> 

The image means HEIF format wrapping the HEVC bit streams and metadata.

The libheif does not provide a method for obtaining complete HEIF format wrapping metadata and the HEVC bit data, So I can only obtain it by merge these two parts of data.

**Comment by liudian** [comment]
> I'm an unsure what you mean by "the image" here. Do you mean the encoded byte array (i.e. HEIF format wrapping the HEVC bit streams and metadata), or the image planes? You can use the `heif_context` you get passed in various parts of the libheif API - see heif.h.

The image means HEIF format wrapping the HEVC bit streams and metadata.

The libheif does not provide a method for obtaining complete HEIF format wrapping metadata and the HEVC bit data, So I can only obtain it by merge these two parts of data.

**Comment by bradh** [comment]
libheif will give you back a byte array containing the exact bits that would be written to a file - that is what `heif_context_write()` does - see previous links. All you need to do is to implement the callback function (i.e. `writer_write` in your sample) to process it in whatever way your application needs.

**Comment by liudian** [comment]
> libheif will give you back a byte array containing the exact bits that would be written to a file - that is what `heif_context_write()` does - see previous links. All you need to do is to implement the callback function (i.e. `writer_write` in your sample) to process it in whatever way your application needs.

I implemented a callback function
```
    static struct heif_error writer_write(struct heif_context* ctx,
            const void* data,size_t size,void* userdata){
        MemoryWriter* writer = static_cast<MemoryWriter*>(userdata);
        writer->write(data,size);
        struct heif_error err{heif_error_Ok,heif_suberror_Unspecified,nullptr};
        return err;
    }
```

Called and returned complete HEVC byte data and metadata data in function getImageData
```
    const uint8_t* HEICEncoder::readImageData(size_t &size) {
        MemoryWriter writer;
        struct heif_writer w;
        w.writer_api_version = 1;
        w.write = writer_write;
        heif_context_write(context_,&w,&writer);

        size = writer.size();
        return writer.data();
    }
```

But after I write the data to a heif file, occasionally there may be incorrect heif header data.
The error data is as follows
![heif_data_error](https://github.com/strukturag/libheif/assets/661422/678387a6-850e-4af5-a423-1fbcad83a997)

**Comment by bradh** [comment]
You have a race condition - you need to copy the data (malloc, memcpy or some equivalent in C++) if you want it to be valid after you return the data.

**Comment by silverbacknet** [comment]
Yes, `writer` is going out of scope, destructed, and its data could be overwritten at any point after returning. It's pure luck that the data sometimes stays entirely valid, but shows up so often since the runtime will reuse just-freed memory for new variables to minimize kernel allocations. This could mean that your `writer` should be part of the class itself, or if this is meant to be a static method, a MemoryWriter will have to be allocated outside and passed in as a parameter to leave it in scope.

**Comment by liudian** [comment]
> You have a race condition - you need to copy the data (malloc, memcpy or some equivalent in C++) if you want it to be valid after you return the data.

After I copied the data, I resolved this error

Now everything is correct, I have obtained the complete metadata and HEVC data.

Thank you very much for all your help

**Comment by liudian** [comment]
> Yes, `writer` is going out of scope, destructed, and its data could be overwritten at any point after returning. It's pure luck that the data sometimes stays entirely valid, but shows up so often since the runtime will reuse just-freed memory for new variables to minimize kernel allocations. This could mean that your `writer` should be part of the class itself, or if this is meant to be a static method, a MemoryWriter will have to be allocated outside and passed in as a parameter to leave it in scope.

Thank you very much for your help. I have already solved this problem

**Comment by liudian** [comment]
The solution is as follows:
Defined a MemoryWriter class in my project (this class can be copied from libheif/buzzing/encoder_fuzzer.cc):
```
    class MemoryWriter
    {
    public:
        MemoryWriter() : data_(nullptr), size_(0), capacity_(0)
        {}

        ~MemoryWriter()
        {
            free(data_);
        }

        const uint8_t* data() const
        { return data_; }

        size_t size() const
        { return size_; }

        void write(const void* data, size_t size)
        {
            if (capacity_ - size_ < size) {
                size_t new_capacity = capacity_ + size;
                uint8_t* new_data = static_cast<uint8_t*>(malloc(new_capacity));
                if (data_) {
                    memcpy(new_data, data_, size_);
                    free(data_);
                }
                data_ = new_data;
                capacity_ = new_capacity;
            }
            memcpy(&data_[size_], data, size);
            size_ += size;
        }

    public:
        uint8_t* data_;
        size_t size_;
        size_t capacity_;
    };
```

Define a callback function writer_ Write:
```
    static struct heif_error writer_write(struct heif_context* ctx,
            const void* data,size_t size,void* userdata){
        MemoryWriter* writer = static_cast<MemoryWriter*>(userdata);
        writer->write(data,size);
        struct heif_error err{heif_error_Ok,heif_suberror_Unspecified,nullptr};
        return err;
    }
```

Using the callback function writer in executing code_ Write:
```
    const uint8_t* HEICEncoder::readImageData(size_t &size) {
        MemoryWriter writer;
        struct heif_writer w;
        w.writer_api_version = 1;
        w.write = writer_write;
        heif_context_write(context_,&w,&writer);

        size = writer.size();
        if(size==0) return nullptr;

        const uint8_t* sdata = writer.data();
        uint8_t* data = static_cast<uint8_t*>(malloc(size));
        memcpy(data,sdata,size);

        return data;
    }
```

**Comment by bradh** [comment]
Are you able to close this issue? Thanks.
