### ISSUE TITLE
PPA update policy

### ISSUE THREAD

**Issue by jerbob92** [strukturag/libheif#899]
First, thank you for creating this library! I have created a Go library around it (https://github.com/klippa-app/go-libheif) to do the processing in a separate process since I don't trust CGO too much :smile: 

My question is what the update policy is regarding the PPA, also with possible security issues, like #794. I see that the latest version in the PPA is v1.14.2, I would like to update to the latest version. If the major release strategy is specific per Ubuntu release, would it be possible to backport security fixes to patch version, for example in a v1.14.3?

**Comment by farindk** [comment]
In the past, we have tried to keep the PPA always up-to-date.

@fancycode (PPA maintainer) would it be possible to release a new PPA? We're now at v1.16.2. If you are short on time, we can also postpone this to v1.17.0, which should be ready soon.

**Comment by jerbob92** [comment]
Nice, thanks! Can we also do libde265 in that case? There were quite some security fixes there.

**Comment by farindk** [comment]
@fancycode Great, thank you.

**Comment by fancycode** [comment]
Updates have also been submitted to Debian and hopefully will be accepted soon.

https://mentors.debian.net/package/libde265/
https://mentors.debian.net/package/libheif/

**Comment by jerbob92** [comment]
Would be nice if a version could be pushed again, since HEIC files from newer iPhones are broken now.

https://github.com/strukturag/libheif/issues/1190

**Comment by jerbob92** [comment]
I have made a repository to do some automated builds for Ubuntu 20.04, 22.04 and 24.04, due to the lack of PPA updates, you can find it here:
https://github.com/jerbob92/libheif-packaging

A deb file can be downloaded in the release.

Please note that it's not the same as the packages in the PPA, it doesn't contain all plugins and it's not separated out per component.

**Comment by jerbob92** [comment]
@fancycode is there some way this could be automated? Last update in PPA is almost 1 year old now.
