### ISSUE TITLE
Unsupported feature: Unsupported codec

### ISSUE THREAD

**Issue by alexbilbie** [strukturag/libheif#90]
Hello,

I've managed to successfully compile libde265 and libheif however every HEIC photo I throw at the library I get the error `Unsupported feature: Unsupported codec`.

The following Docker script will compile libde265 and libheif under Debian and then run the example `heif-convert` from this repository but fail with the message above:

```dockerfile
FROM buildpack-deps:stretch-scm

ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

RUN apt-get update -y && \
    apt-get install -y libtool autotools-dev automake libx265-95 libx265-dev cmake libpng-dev libpng++-dev \
    libjpeg-dev g++ gcc libc6-dev make pkg-config

RUN cd /tmp && \
    git clone https://github.com/strukturag/libde265 && \
    git clone https://github.com/strukturag/libheif

RUN cd /tmp/libde265 && \
    git checkout frame-parallel && \
    mkdir build && \
    cd build && \
    cmake .. && make

RUN cd /tmp/libheif && \
    ./autogen.sh && \
    ./configure && \
    make

RUN cd /tmp/libheif && \
    make install

RUN cd /tmp/libheif/examples && \
    curl -LO https://github.com/strukturag/libheif/raw/gh-pages/example.heic && \
    ./heif-convert example.heic example.jpg
```

Please could you advise on how I can overcome this error?

Thanks

**Comment by farindk** [comment]
Your script is compiling libde265, but it is not installing it, hence libheif cannot find it in the configure step.
You might want to compile it like this:
- checkout libde265
- ./configure --prefix=SOMEWHERE.WHERE.IT.WILL.FOUND
- make install

**Comment by Citycorner** [comment]
Hi , I got the same problem.
I am using cmake-gui.exe in window 7 to generate the code.

..\libheif-master\build\examples\Release>heif-convert IMG_0004.HEIC testing.jpg
3
3
1
File contains 1 images
Could not decode HEIF image: 0: Unsupported feature: Unsupported codec


In \libde265-master\build\libde265\Release
I got
libde265.dll
libde265.lib

I think I should link the library to libheif
So in the cmake
I try to set
CMAKE_CONFIGURATION_TYPES  Release;
CMAKE_INSTALL_PREFIX C:/John/libde265-master/build/libde265

I try many different path for
CMAKE_INSTALL_PREFIX

But doesn't work, I still got same error.

Can someone help me.

THX.

**Comment by meonkeys** [comment]
Folks experiencing this issue: when you `./configure` libheif, it must say `checking for libde265... yes` or it won't be able to decode HEIC files.

**Comment by phanirithvij** [comment]
I did install `libde265` by cloning `https://github.com/strukturag/libde265` and `./autogen.sh`, `./configure`, `make` then `sudo make install` but I still get this error for libheif
```shell
checking for libde265... no
configure: libde265 decoder: no
```

**Comment by Yuchen-Wang-SH** [comment]
> I did install `libde265` by cloning `https://github.com/strukturag/libde265` and `./autogen.sh`, `./configure`, `make` then `sudo make install` but I still get this error for libheif
> 
> ```shell
> checking for libde265... no
> configure: libde265 decoder: no
> ```
> 
> > alexbilbie, I got the same issue, but i solved it by the steps below:
> > 
> > 1. check if libde265 is supported during ./configure in libheif project
> > 2. if no, then export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/ , in where libde265 install the pkgconfig file
> > 3. check with item 1 again, it should be libde265 supported
> 
> This worked. Thanks

For anyone who is reading this, the Dockerfile @alexbilbie posted actually missed some steps. Following the steps mentioned by @phanirithvij I finally get this to work.
