### ISSUE TITLE
heif-enc always reads jpeg files as 420

### ISSUE THREAD

**Issue by maryla-uc** [strukturag/libheif#906]
The code in decoder_jpeg.cc [always produces 420 images](https://github.com/strukturag/libheif/blob/ab524d2d47ac7c39055113d99197afbee6c96144/libheif/plugins/decoder_jpeg.cc#L220) even if the source is 444 or 422. Moreover, it doesn't do downsampling by averaging 4 chroma values, but simply discards every other chroma value!

Even when reading 420 files, it produces slightly wrong results, because libjpeg outputs upsampled values using bilinear upsampling (called "fancy upsampling" in the api). Keeping every other upsampled value is therefore different from using the original 420 samples.

There are several ways around this. One is to check the jpeg's sampling factor (`cinfo.comp_info[i].h_samp_factor` and `cinfo.comp_info[i].v_samp_factor for` i in 0..2). If it's 444, read all the samples. If it's 420, you can set `cinfo.do_fancy_upsampling` to false after the call to `jpeg_read_header()` and then keep every other sample as is done currently. 422 would be similar.

Another way would be to request RGB from the API (`cinfo.out_color_space = JCS_RGB`) instead of reading it as YCbCr.

Yet another way is to use the raw sample reading api which does not do any transform or upsampling, using `cinfo->raw_data_out = TRUE;` and `jpeg_read_raw_data()` as is done [in libavif here](https://github.com/AOMediaCodec/libavif/blob/430ea2df584dcb95ff1632c17643ebbbb2f3bc81/apps/shared/avifjpeg.c#L47).

What do you think? My preference would go for the first or second option.

**Comment by farindk** [comment]
Good catch.

> What do you think? My preference would go for the first or second option.

I would vote for the third option ;-)

Going through RGB seems unnecessary work and generating inevitable quality loss.
We also don't really need the upsampling of option 1 when we don't use it.
Option 3 gives us the data exactly as we need it without loss. It's not even interleaved, so even the copying is faster.

I can do the change.

**Comment by farindk** [comment]
I have implemented this.
For 4:2:2 JPEGs, I get a wrong output image (after heif-enc, heif_convert), but I don't think it's the JPEG reader.
That might just have uncovered a bug somewhere else.

**Comment by maryla-uc** [comment]
That was quick! Thank you!

**Comment by maryla-uc** [comment]
I'm getting a compile error: `decoder_jpeg.cc:394:55: error: ‘struct jpeg_component_info’ has no member named ‘DCT_v_scaled_size’; did you mean ‘DCT_scaled_size’?`

I'm afraid you have to use `#if JPEG_LIB_VERSION >= 70` to use the correct version.

**Comment by farindk** [comment]
Ok. I hoped that these were deprecated already (7.0 is from 2009)...

**Comment by farindk** [comment]
Does that patch work?

**Comment by maryla-uc** [comment]
Yup that works!
And I can confirm that reading 444 and 420 works well now. Still some distortion on 422 but as you said it's probably caused by something else.
