### ISSUE TITLE
HEIC are JPG?

### ISSUE THREAD

**Issue by wills721** [strukturag/libheif#907]
I have HEIC files that when I use heif-convert to convert them to JPG show up already as JPG?

will@ubuntu-server:/mnt/photos-gsync/photos/test$ $HOME/heif-convert --list-decoders
HEIC decoders:
- libde265 = libde265 HEVC decoder, version 1.0.12
AVIF decoders:
JPEG decoders:
- jpeg = libjpeg-turbo 2.1.2 (libjpeg 8.0)
uncompressed: yes
will@ubuntu-server:/mnt/photos-gsync/photos/test$ $HOME/heif-convert IMG_1033.heic IMG_1033.jpg
Input file 'IMG_1033.heic' is a JPEG image
will@ubuntu-server:/mnt/photos-gsync/photos/test$

**Comment by farindk** [comment]
This is a known problem that seems to happen somewhere when transferring images from Apple systems where they are auto-converted to JPEG. If you search through the issues reported here, you will find similar reports from other users.
It's not related to libheif, just the wrong file suffix.

**Comment by wills721** [comment]
Ah.  I use Google Photos to sync my phone and then pull from Google Photos.  I suppose Google is doing this.  Thank you for your quick response!
