### ISSUE TITLE
ppa:strukturag/libheif build is broken?

### ISSUE THREAD

**Issue by lgritz** [strukturag/libheif#912]
My project (OpenImageIO) uses libheif, and my CI jobs pull from your pre-built apt repo like this:

    sudo add-apt-repository ppa:strukturag/libde265
    sudo add-apt-repository ppa:strukturag/libheif
    sudo apt-get -q install -y libheif-dev

Starting two days ago, my hief-related tests started failing with "unsupported codec" errors when I try to read avif files. Looking at my CI records, it seems the failures correspond to the point a couple days ago when grabbing ppa:strukturag/libheif transitioned from getting me 1.14.2 to 1.16.2.

My MacOS CI case uses 1.16.2, but from Homebrew, and it works fine, so I think that the problem is not that there's anything wrong with 1.16.2 per se, but that the new build you are hosting on ppa:strukturag is broken.

**Comment by farindk** [comment]
The codecs are now packaged separately. You might have to also install, for example
````
apt get libheif-plugin-aomdec libheif-plugin-aomenc libheif-plugin-libde265 libheif-plugin-x265
````
to get AVIF and HEIC support.

**Comment by lgritz** [comment]
Ah, ok, thanks. Is there anything on the app side I need to do from an API standpoint to enable these codecs? Or is merely installing those packages sufficient?

**Comment by bigcat88** [comment]
> Ah, ok, thanks. Is there anything on the app side I need to do from an API standpoint to enable these codecs? Or is merely installing those packages sufficient?

https://github.com/strukturag/libheif/issues/909

**Comment by lgritz** [comment]
Thanks, @farindk and @bigcat88, that was crucial missing information I needed. All working again now.

**Comment by fancycode** [comment]
> The codecs are now packaged separately. You might have to also install, for example
> 
> ```
> apt get libheif-plugin-aomdec libheif-plugin-aomenc libheif-plugin-libde265 libheif-plugin-x265
> ```
> 
> to get AVIF and HEIC support.

These packages are pulled through `Recommends`  from the `libheif1` package, so unless you are installing with `--no-install-recommends`, everything should be working as before after the upgrade.
