### ISSUE TITLE
A bunch of PNG that heif-enc isn't able to read correctly

### ISSUE THREAD

**Issue by arobase-che** [strukturag/libheif#937]
Hello \o

I don't know if it's known already but here are some examples of PNG pictures that heif-enc isn't able to read correctly.

 - https://ache.one/datasets_test_imgs_ache/xkcd/1416.png
 - https://ache.one/datasets_test_imgs_ache/png_random/computer-icons-space-shuttle-font-keer-imgbin.png
 - https://ache.one/datasets_test_imgs_ache/png_random/statue_of_liberty_pngwing.png
 - https://ache.one/datasets_test_imgs_ache/png_random/fox_random_pngegg.png
 - https://ache.one/datasets_test_imgs_ache/png_random/fox_screaming_pngwing.png
 - https://ache.one/datasets_test_imgs_ache/png_random/pizza_sticker_pngwing.png
 - https://ache.one/datasets_test_imgs_ache/png_random/coffe_cup_energy_pngwing.png
 - https://ache.one/datasets_test_imgs_ache/png_random/mister_avocado_pngwing.png
 - https://ache.one/datasets_test_imgs_ache/png_random/pastafarism_monster_pngwing.png
 
 To have  an example. Let's convert `mister_avocado` to AVIF and back to PNG again because GH doesn't support AVIF.
 
![mister_avocado](https://github.com/strukturag/libheif/assets/2202307/8043de43-2fac-44a3-b922-e31cf1ab1901)

I think maybe, the palette chunk of the PNGs isn't correctly interpreted. But it will hardly explains why the image is deformed.
 
 PS: I won't host the images forever so here is a magnet link to download the datasets they are part of:
 magnet:?xt=urn:btih:3217ff465d9c13cdbb2f7b1d776ee0f2a152ba54&dn=datasets_test_imgs_ache&tr=udp://tracker.opentrackr.org:1337/announce&tr=https://tracker1.520.jp/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=http://bt.endpot.com/announce

**Comment by farindk** [comment]
Thank you. I have fixed reading palette color images.
