### ISSUE TITLE
heif_context_encode_image has a memory leak for heic encoder

### ISSUE THREAD

**Issue by ljdsina** [strukturag/libheif#940]
![image](https://github.com/strukturag/libheif/assets/32031371/adb15dd2-8075-4d26-8441-e626259302aa)

**Comment by farindk** [comment]
Looks like a leak in `libx265` and not in libheif.

**Comment by bradh** [comment]
This is the same issue as #960.

**Comment by farindk** [comment]
Resolved in https://github.com/strukturag/libheif/pull/1061
