### ISSUE TITLE
[bug] filipped pictures. please update the code base.

### ISSUE THREAD

**Issue by zedd-0** [strukturag/libheif#966]
can you update your codebase to v1.16.2 ?(https://github.com/strukturag/libheif/releases/)
there is a bug in v1.14: all my pictures are flipped.
this was fixed in v1.14.1 .

sadly, there is no new update or artifact. :(

thx 4 your help

**Comment by bradh** [comment]
I'm not sure I follow. You've filed this issue against libheif, and libheif definitely has a 1.16.2 release.

Are you using some other application to view your pictures? Should this request be against that application?

**Comment by zedd-0** [comment]
the bug is documented on the release note v1.14.1 (https://github.com/strukturag/libheif/releases/tag/v1.14.1) .
sadly there is no newer windows binary out there. :(

**Comment by bradh** [comment]
I don't think libheif comes with windows binaries (not in 1.14.1, or 1.16.2). You build from source.

**Comment by zedd-0** [comment]
i do not know how to build it by myself ?
last time i tried this, it doesn't work.

**Comment by bradh** [comment]
So how did you do it for 1.14.1?

**Comment by zedd-0** [comment]
i have still 1.14(.0)

**Comment by zedd-0** [comment]
why i didn't see it in the first place.
this is not https://github.com/pphh77/libheif-Windowsbinary
f... shame on me... :D

**Comment by bradh** [comment]
I was trying to point that out in the first response.  Given that this is resolved in libheif, can you close the ticket?

**Comment by silverbacknet** [comment]
FWIW, just dropping 1.16 to replace 1.14 may result in crashes and other unexpected behavior. You have to stay within the same X.Y version to guarantee compatibility, but it can be any of 1.14.x.
