### ISSUE TITLE
no heif-enc was found.

### ISSUE THREAD

**Issue by zedd-0** [strukturag/libheif#967]
Hello,
since I have no idea about compiling
and got lost in a rabbit hole trying to sift through a gigabyte-sized toolset,
I asked a colleague if he could do it for me.
We then realized that the actual encoder (heif-enc.exe) is missing.
My question is: are we overlooking something, or what's going on?

I used this version before:
https://github.com/pphh77/libheif-Windowsbinary
but this project has been dead since the summer of 2022.
And it's stuck at version v1.14.0.
It still has the PNG bug that flipped the images upside down.

So, where can you get fresh binaries for Windows these days?

Thanks in advance for your help.

**Comment by bigcat88** [comment]
Will you be satisfied to build them with [MSYS2](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libheif/PKGBUILD) ?

It is not so hard, and they works fine, MSYS repo has a very good maintainers.

**Comment by zedd-0** [comment]
i fond there are compiled exe files.
some ddl files are missing, but i will test it later, if the binarys will work.
now i have to go to the work. ;)

but do you know why the offical sources on this page do not create a heif-enc.exe ?
just for knowing.

bye.

**Comment by bigcat88** [comment]
`libheif` can be build with many various encoders & decoders.

All of them has different Licenses, pros and cons, there are no "universal/best build type"

On Mac you can easy build libheif with `brew`(even for custom builds just need to modify formula), on Windows it's MSYS2(there are others of course, but I just like it), on Linux here are build scripts in this repo to build what is desired or just add libheif's repo and install with `apt`.

**Comment by silverbacknet** [comment]
> but do you know why the offical sources on this page do not create a heif-enc.exe ?
> just for knowing.

You want to enable the "WITH_EXAMPLES" CMake option if you want the built-in sample encoder, decoder, and info executables. Otherwise, you'll only get the library that you can call from your own software.

**Comment by bradh** [comment]
The build works, so I think this issue can be closed.
