### ISSUE TITLE
Use CMake imported targets

### ISSUE THREAD

**Issue by farindk** [strukturag/libheif#975]
Moving @kmilos comment from #973 into a issue of its own.

> maybe it's time to bump CMake minimum required version and simplifyby using imported targets ZLIB::ZLIB and PNG::PNG...

Do you know what minimum cmake version is required for that? I think the current upper limit might be cmake v3.16.3 (Ubuntu 20.04).

> 3.1 for ZLIB, 3.5 for PNG

**Comment by kmilos** [comment]
And JPEG::JPEG is available since 3.12

**Comment by farindk** [comment]
This was also proposed in PR #754.
@fancycode Which minimum CMake version is required for packaging? Can we switch to v3.12 ?

**Comment by fancycode** [comment]
Ubuntu Focal (20.04) ships cmake 3.16.3, so 3.12 should be ok. We can probably drop support for older versions of Ubuntu for new releases anyway.
