### ISSUE TITLE
Go doesn't make or go build. heif_suberror_Unknown_color_profile_type

### ISSUE THREAD

**Issue by MrBri** [strukturag/libheif#98]
Attempting to use the Golang part of this project.
Wether using make or the different go commands my colleague and I are getting the same error has shown below. He's tried it in Amazon Linux, I've tried on my local Mac. Also tried go versions 1.9.7 and 1.11.4.
 
src/github.com/strukturag/libheif/go/heif/heif.go:219:36: could not determine kind of name for C.heif_suberror_Unknown_color_profile_type

**Comment by bciceron** [comment]
same problem here when i try to build under examples/ : 
`go build heif-test.go
could not determine kind of name for C.heif_suberror_Unknown_color_profile_type`
fails with go 1.8 , 1.9, 1.10, 1.11 .

also tried the go source under go/heif:
`go build heif.go
could not determine kind of name for C.heif_suberror_Unknown_color_profile_type`

as well as running the test:
`PKG_CONFIG_PATH=/usr/local/lib go test -v
could not determine kind of name for C.heif_suberror_Unknown_color_profile_type`

**Comment by bciceron** [comment]
FYI the [documented](https://github.com/strukturag/libheif#compiling) branch `frame-parallel` does not exist anymore.

it works now after fetching the latest and switching back to master.

thanks
